-- ============================================================
-- BATCH: e_anat_sto_2025/1  ·  subject_id=anatomia  ·  SHARED (oba kierunki, tracks=NULL)
-- Źródło: Egzamin anatomia STOMA SUM 2025 (ANATSTO e2025-1), 52 pytań (egzaminy STOMATOLOGII)
-- tracks NULL (anatomia wspólna) · source_code = oryginalne ANATSTO-NNN
-- Self-numbering id per dział = max seq z bazy + 1
--
-- Wersja po dedup (2026-05-28): 24 pytania — wycięte duplikaty w batchu + stemy już w bazie.
-- Audyt: exports/anatomia-batch-sto-2025-dedup-audit.md
-- ============================================================

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
  (1, 'ANA-TRZ',
   'Początkowy przyczep krezki znajduje się:',
   '[{"id": "a", "text": "Na wysokości L2 po lewej stronie kręgosłupa"}, {"id": "b", "text": "Na wysokości L2 po prawej stronie kręgosłupa"}, {"id": "c", "text": "Na wysokości L2 w linii środkowej"}, {"id": "d", "text": "Na wysokości L3 po lewej stronie kręgosłupa"}, {"id": "e", "text": "Na wysokości L3 po prawej stronie kręgosłupa"}]'::jsonb,
   'b',
   $E$Korzeń krezki (**radix mesenterii**) biegnie skośnie od **zgięcia dwunastniczo-czczego** (na wysokości **L2 po stronie lewej**) do **prawego dołu biodrowego** (staw krzyżowo-biodrowy prawy). Pytanie dotyczy **przyczepu początkowego**, czyli punktu górnego przy zgięciu dwunastniczo-czczym. Choć samo zgięcie leży po lewej, klasyczny opis topograficzny lokalizuje początek korzenia na **wysokości L2**; długość korzenia ok. **15 cm**. Mylące jest mieszanie strony lewej (początek) z prawą (koniec w okolicy krętniczo-kątniczej).$E$,
   'krezka jelita', 'ANATSTO-357'),
  (9, 'ANA-OBW',
   'Uszkodzenie którego nerwu spowoduje przede wszystkim utrudnienie przywodzenia w stawie biodrowym',
   '[{"id": "a", "text": "zasłonowy"}, {"id": "b", "text": "Udowy"}, {"id": "c", "text": "Płciowo-udowy"}, {"id": "d", "text": "Kulszowy"}, {"id": "e", "text": "Sromowy"}]'::jsonb,
   'a',
   $E$**Nerw zasłonowy** (L2–L4) unerwia **grupę przywodzicieli uda**: m. przywodziciel długi, krótki, wielki (część), smukły i grzebieniowy (częściowo). Jego uszkodzenie znosi **przywodzenie** w stawie biodrowym i osłabia stabilizację kończyny przy chodzie (noga odwodzi się). Daje też czucie skórne przyśrodkowej powierzchni uda. Nerw udowy odpowiada za prostowanie kolana (m. czworogłowy) i zginanie biodra, nie za przywodzenie.$E$,
   'nerw zasłonowy', 'ANATSTO-365'),
  (11, 'ANA-TUL',
   'Łuk aorty rozpoczyna się:',
   '[{"id": "a", "text": "górny brzeg na wysokości II stawu mostkowo-żebrowego po stronie lewej"}, {"id": "b", "text": "górny brzeg na wysokości II stawu mostkowo-żebrowego po stronie prawej"}, {"id": "c", "text": "górny brzeg na wysokości III stawu mostkowo-żebrowego po stronie lewej"}, {"id": "d", "text": "górny brzeg na wysokości III stawu mostkowo-żebrowego po stronie prawej"}, {"id": "e", "text": "na wysokości kąta mostka"}]'::jsonb,
   'b',
   $E$**Łuk aorty** rozpoczyna się jako przedłużenie aorty wstępującej na wysokości **II prawego stawu mostkowo-żebrowego** (górny brzeg). Biegnie ku tyłowi i w lewo, kończy się na wysokości **Th4** przy **kącie mostka (Ludwiga)** po stronie lewej, przechodząc w aortę zstępującą. Płaszczyzna kąta mostka (linia Th4/Th5) wyznacza początek i koniec łuku. Odejścia: pień ramienno-głowowy, t. szyjna wspólna lewa, t. podobojczykowa lewa.$E$,
   'aorta piersiowa', 'ANATSTO-367'),
  (14, 'ANA-KON',
   'Gdzie najczęściej odpływa żyła odłokciowa:',
   '[{"id": "a", "text": "Żyła promieniowa"}, {"id": "b", "text": "żyła łokciowa"}, {"id": "c", "text": "żyła ramienna"}, {"id": "d", "text": "żyła pośrodkowa łokcia"}, {"id": "e", "text": "żyła pachowa"}]'::jsonb,
   'c',
   $E$**Żyła odłokciowa** (v. basilica) biegnie po stronie przyśrodkowej przedramienia i ramienia, przebija powięź w połowie ramienia (rozwór) i uchodzi do **żył ramiennych** lub bezpośrednio przechodzi w **żyłę pachową**. Klasycznie podaje się, że łączy się z żyłami ramiennymi tworząc ż. pachową. Żyła odpromieniowa (v. cephalica) z kolei uchodzi do ż. pachowej w trójkącie naramienno-piersiowym. Pośrodkowa łokcia łączy obie żyły powierzchowne.$E$,
   'żyły powierzchowne kończyny górnej', 'ANATSTO-370'),
  (17, 'ANA-OUN',
   'Guz popielaty jest elementem:',
   '[{"id": "a", "text": "wzgórza"}, {"id": "b", "text": "podwzgórza"}, {"id": "c", "text": "niskowzgórza"}, {"id": "d", "text": "nadwzgórza"}, {"id": "e", "text": "zawzgórza"}]'::jsonb,
   'b',
   $E$**Guz popielaty** (tuber cinereum) należy do **podwzgórza** (hypothalamus). Leży na podstawie międzymózgowia między ciałami suteczkowatymi (z tyłu) a skrzyżowaniem wzrokowym (z przodu); ku dołowi przechodzi w **lejek** i **przysadkę**. Zawiera jądra (m.in. jądro łukowate) uczestniczące w regulacji wydzielania hormonów przysadki. Nadwzgórze to szyszynka i uzdeczki, zawzgórze — ciała kolankowe, niskowzgórze — j. niskowzgórzowe.$E$,
   'podwzgórze', 'ANATSTO-373'),
  (18, 'ANA-OUN',
   'Konar środkowy móżdżku łączy móżdżek z:',
   '[{"id": "a", "text": "rdzeniem kręgowym"}, {"id": "b", "text": "rdzeniem przedłużonym"}, {"id": "c", "text": "mostem"}, {"id": "d", "text": "międzymózgowiem"}, {"id": "e", "text": "wzgórzem"}]'::jsonb,
   'c',
   $E$**Konar środkowy móżdżku** (najgrubszy) łączy móżdżek z **mostem** — przewodzi włókna mostowo-móżdżkowe (po przełączeniu drogi korowo-mostowej), część układu czołowo-mostowo-móżdżkowego koordynującego ruch. Konar **górny** łączy z śródmózgowiem (głównie drogi z móżdżku, np. do j. czerwiennego/wzgórza), konar **dolny** z rdzeniem przedłużonym (m.in. droga rdzeniowo-móżdżkowa tylna, włókna oliwkowo-móżdżkowe).$E$,
   'móżdżek', 'ANATSTO-374'),
  (19, 'ANA-OUN',
   'Sierp mózgu:',
   '[{"id": "a", "text": "jest tworem opony twardej"}, {"id": "b", "text": "jest tworem opony miękkiej"}, {"id": "c", "text": "oddziela mózg od móżdżku"}, {"id": "d", "text": "A + B"}, {"id": "e", "text": "A + C"}]'::jsonb,
   'a',
   $E$**Sierp mózgu** (falx cerebri) jest wpukleniem **opony twardej** w szczelinę podłużną mózgu, oddzielającym oba **półkule**. W jego brzegu górnym biegnie **zatoka strzałkowa górna**, w dolnym — **zatoka strzałkowa dolna**, a u tylnego połączenia z namiotem móżdżku — **zatoka prosta**. Strukturą oddzielającą mózg od móżdżku jest **namiot móżdżku** (tentorium cerebelli), nie sierp — stąd odpowiedź C błędna. Dolny wolny brzeg sierpu nie sięga ciała modzelowatego. Sierp stabilizuje mózg w jamie czaszki i ogranicza jego ruchy boczne przy urazach.$E$,
   'opony mózgowia', 'ANATSTO-375'),
  (20, 'ANA-OUN',
   'Jądra uzdeczki to elementy:',
   '[{"id": "a", "text": "wzgórza"}, {"id": "b", "text": "podwzgórza"}, {"id": "c", "text": "niskowzgórza"}, {"id": "d", "text": "zawzgórza"}, {"id": "e", "text": "nadwzgórza"}]'::jsonb,
   'e',
   $E$**Jądra uzdeczki** (nuclei habenulares) należą do **nadwzgórza** (epithalamus), które obejmuje też **szyszynkę**, **uzdeczki**, **spoidło uzdeczek** i **trójkąt uzdeczki**. Jądra uzdeczki są stacją przekaźnikową układu limbicznego — łączą struktury węchowo-limbiczne (przez prążek rdzenny wzgórza) z pniem mózgu, uczestnicząc w regulacji nastroju i reakcji na nagrodę/awersję. Zawzgórze to ciała kolankowe (słuch i wzrok).$E$,
   'nadwzgórze', 'ANATSTO-376'),
  (21, 'ANA-KON',
   'Szczyt trójkąta udowego znajduje się w:',
   '[{"id": "a", "text": "Kanale pachwinowym"}, {"id": "b", "text": "Kanale udowym"}, {"id": "c", "text": "Dole podkolanowym"}, {"id": "d", "text": "Kanale przywodzicieli"}, {"id": "e", "text": "Rozworze odpiszczelowym"}]'::jsonb,
   'd',
   $E$**Trójkąt udowy** (Scarpy) ograniczają: u góry **więzadło pachwinowe**, bocznie **m. krawiecki**, przyśrodkowo **m. przywodziciel długi**. Jego **szczyt** (dolny kąt) leży tam, gdzie krzyżują się m. krawiecki i przywodziciel długi i **przechodzi w kanał przywodzicieli** (Huntera). Tym kanałem t. i ż. udowa biegną dalej do dołu podkolanowego. Dnem trójkąta są mm. biodrowo-lędźwiowy i grzebieniowy.$E$,
   'trójkąt udowy', 'ANATSTO-377'),
  (22, 'ANA-KON',
   'Mięsień dłoniowy długi należy do:',
   '[{"id": "a", "text": "Warstwy powierzchownej grupy przedniej mięśni przedramienia"}, {"id": "b", "text": "Warstwy głębokiej grupy przedniej mięśni przedramienia"}, {"id": "c", "text": "Warstwy powierzchownej grupy tylnej mięśni przedramienia"}, {"id": "d", "text": "Warstwy głębokiej grupy tylnej mięśni przedramienia"}, {"id": "e", "text": "Grupy bocznej mięśni przedramienia"}]'::jsonb,
   'a',
   $E$**Mięsień dłoniowy długi** (m. palmaris longus) leży w **warstwie powierzchownej grupy przedniej** przedramienia, obok m. nawrotnego obłego, zginacza promieniowego nadgarstka i zginacza łokciowego nadgarstka. Przechodzi w **rozcięgno dłoniowe**. Unerwiony przez **nerw pośrodkowy**. U ok. **10–15%** osób jest nieobecny (wykorzystywany jako przeszczep ścięgnisty). Napina rozcięgno dłoniowe i wspomaga zginanie nadgarstka.$E$,
   'mięśnie przedramienia', 'ANATSTO-378'),
  (26, 'ANA-OBW',
   'Nerw pachowy odchodzi od:',
   '[{"id": "a", "text": "Pęczka tylnego"}, {"id": "b", "text": "Pęczka przyśrodkowego"}, {"id": "c", "text": "Pęczka bocznego"}, {"id": "d", "text": "A+B"}, {"id": "e", "text": "A+C"}]'::jsonb,
   'a',
   $E$**Nerw pachowy** (C5–C6) odchodzi od **pęczka tylnego** splotu ramiennego, podobnie jak nerw promieniowy. Owija się wokół **szyjki chirurgicznej kości ramiennej** (przez otwór czworoboczny), unerwiając **m. naramienny** i **m. obły mniejszy** oraz skórę nad naramiennym. Złamanie szyjki chirurgicznej lub zwichnięcie barku grozi jego uszkodzeniem — osłabienie odwodzenia ramienia i zaburzenia czucia „naramiennika". Pęczek tylny daje też n. promieniowy.$E$,
   'splot ramienny', 'ANATSTO-382'),
  (28, 'ANA-JAM',
   'Ściana szyjno-żylna to:',
   '[{"id": "a", "text": "Ściana górna jamy bębenkowej"}, {"id": "b", "text": "Ściana dolna jamy bębenkowej"}, {"id": "c", "text": "Ściana przyśrodkowa jamy bębenkowej"}, {"id": "d", "text": "Ściana boczna jamy bębenkowej"}, {"id": "e", "text": "Ściana tylna jamy bębenkowej"}]'::jsonb,
   'b',
   $E$**Ściana dolna** jamy bębenkowej to **ściana szyjno-żylna** (paries jugularis) — oddziela jamę bębenkową od **opuszki żyły szyjnej wewnętrznej**. Ściana górna to **stropowa** (oddziela od dołu środkowego czaszki), przyśrodkowa **błędnikowa** (z wzgórkiem i okienkami), boczna **błoniasta** (błona bębenkowa), przednia **tętniczo-szyjna** (sąsiaduje z t. szyjną wewnętrzną), tylna **sutkowa** (z wejściem do jaskini sutkowej).$E$,
   'jama bębenkowa', 'ANATSTO-384'),
  (29, 'ANA-TRZ',
   'Otwór sieciowy ograniczony jest od tyłu przez:',
   '[{"id": "a", "text": "Żyłę główną dolną"}, {"id": "b", "text": "Więzadło wątrobowo-dwunastnicze"}, {"id": "c", "text": "Część górną dwunastnicy"}, {"id": "d", "text": "Tętnicę wątrobową właściwą"}, {"id": "e", "text": "Wyrostek ogoniasty wątroby"}]'::jsonb,
   'a',
   $E$**Otwór sieciowy** (Winslowa) ograniczają: **od przodu** więzadło wątrobowo-dwunastnicze (z triadą wrotną: ż. wrotna, t. wątrobowa właściwa, przewód żółciowy wspólny), **od tyłu** **żyła główna dolna**, **od góry** wyrostek ogoniasty wątroby, **od dołu** część górna dwunastnicy. Łączy torbę sieciową (kaletkę) z jamą otrzewnej większej. Manewr Pringle'a — zaciśnięcie więzadła w otworze hamuje krwawienie z wątroby.$E$,
   'otwór sieciowy', 'ANATSTO-385'),
  (30, 'ANA-CZA',
   'Ścianę przyśrodkową oczodołu nie buduje część kości:',
   '[{"id": "a", "text": "szczęki"}, {"id": "b", "text": "łzowej"}, {"id": "c", "text": "klinowej"}, {"id": "d", "text": "podniebiennej"}, {"id": "e", "text": "sitowej"}]'::jsonb,
   'd',
   $E$**Ścianę przyśrodkową oczodołu** budują (od przodu ku tyłowi): wyrostek czołowy **szczęki**, kość **łzowa**, blaszka oczodołowa kości **sitowej** (lamina papyracea) oraz część kości **klinowej** (trzon). Kość **podniebienna** nie wchodzi w jej skład — jej wyrostek oczodołowy uczestniczy jedynie w drobnym fragmencie dna/tylnej części oczodołu. Cienka blaszka sitowa to częste miejsce szerzenia się zakażeń z zatok sitowych do oczodołu.$E$,
   'oczodół', 'ANATSTO-386'),
  (33, 'ANA-NAC',
   'W dole zażuchwowym tętnica szyjna zewnętrzna oddaje gałęzie:',
   '[{"id": "a", "text": "twarzową, szczękową, uszną tylną"}, {"id": "b", "text": "twarzową, uszną tylną, skroniową powierzchowną"}, {"id": "c", "text": "uszną tylną, skroniową powierzchowną, szczękową"}, {"id": "d", "text": "twarzową, skroniową powierzchowną, uszną tylną"}, {"id": "e", "text": "szczękową, twarzową, skroniową powierzchowną"}]'::jsonb,
   'c',
   $E$W **dole zażuchwowym** (w obrębie ślinianki przyusznej) **t. szyjna zewnętrzna** oddaje gałąź **uszną tylną**, a następnie dzieli się na dwie gałęzie końcowe: **t. szczękową** i **t. skroniową powierzchowną**. T. twarzowa odchodzi wcześniej, w trójkącie tętnicy językowej/poniżej żuchwy, więc nie jest gałęzią z dołu zażuchwowego. Stąd zestaw: uszna tylna + skroniowa powierzchowna + szczękowa. T. szczękowa zaopatruje głębokie struktury twarzy.$E$,
   'tętnica szyjna zewnętrzna', 'ANATSTO-389'),
  (34, 'ANA-MIE',
   'Przyczep końcowy mięśnia skrzydłowego przyśrodkowego:',
   '[{"id": "a", "text": "przyśrodkowa strona kąta żuchwy (guzowatość skrzydłowa)"}, {"id": "b", "text": "boczna strona kąta żuchwy"}, {"id": "c", "text": "wyrostek dziobiasty żuchwy"}, {"id": "d", "text": "dołek skrzydłowy żuchwy"}, {"id": "e", "text": "głowa żuchwy"}]'::jsonb,
   'a',
   $E$**Mięsień skrzydłowy przyśrodkowy** rozpoczyna się w **dole skrzydłowym** (głównie blaszka boczna wyrostka skrzydłowatego) i kończy na **przyśrodkowej powierzchni kąta żuchwy** (guzowatość skrzydłowa). Wraz z m. żwaczem tworzy „pętlę żwaczowo-skrzydłową" obejmującą kąt żuchwy. **Unosi i wysuwa** żuchwę, jednostronnie powoduje ruch w stronę przeciwną (żucie). Unerwiony przez **n. żuchwowy (V3)**.$E$,
   'mięsień skrzydłowy przyśrodkowy', 'ANATSTO-390'),
  (35, 'ANA-NAC',
   'Trójkąt tętnicy językowej (Pirogowa) — ograniczenie tylne stanowi:',
   '[{"id": "a", "text": "tylny brzeg mięśnia żuchwowo-gnykowego"}, {"id": "b", "text": "ścięgno pośrednie mięśnia dwubrzuścowego"}, {"id": "c", "text": "brzuziec tylny mięśnia dwubrzuścowego"}, {"id": "d", "text": "mięsień gnykowo-językowy"}, {"id": "e", "text": "brzusiec przedni mięśnia dwubrzuścowego"}]'::jsonb,
   'b',
   $E$**Trójkąt Pirogowa** ograniczają: **z przodu** tylny brzeg **m. żuchwowo-gnykowego**, **z tyłu/dołu** **ścięgno pośrednie m. dwubrzuścowego**, **z góry** **n. podjęzykowy (XII)**. Dnem jest **m. gnykowo-językowy**, pod którym przebiega **t. językowa** — stąd trójkąt to punkt orientacyjny do jej podwiązania. Ograniczenie tylne klasycznie opisuje się jako ścięgno pośrednie m. dwubrzuścowego.$E$,
   'trójkąt Pirogowa', 'ANATSTO-391'),
  (36, 'ANA-NAC',
   'Trójkąt tętnicy językowej nie zawiera:',
   '[{"id": "a", "text": "nerwu podjęzykowego"}, {"id": "b", "text": "pętli szyjnej"}, {"id": "c", "text": "tętnicy językowej"}, {"id": "d", "text": "żyły językowej"}, {"id": "e", "text": "mięśnia gnykowo-językowego"}]'::jsonb,
   'b',
   $E$Trójkąt Pirogowa zawiera **m. gnykowo-językowy** (dno), pod którym leży **t. językowa**, oraz **ż. językową** i **n. podjęzykowy (XII)** wyznaczający górną granicę. **Pętla szyjna** (ansa cervicalis) **nie** wchodzi w jego skład — leży na powięzi pochewki naczyniowej szyi, unerwiając mm. podgnykowe. Trójkąt służy do chirurgicznego dostępu do t. językowej. N. podjęzykowy biegnie powierzchownie względem m. gnykowo-językowego.$E$,
   'trójkąt Pirogowa', 'ANATSTO-392'),
  (38, 'ANA-KON',
   'Wykonywanie jakich ruchów jest możliwe w stawie łokciowym:',
   '[{"id": "a", "text": "Nawracania, odwracania"}, {"id": "b", "text": "Zginania, prostowania"}, {"id": "c", "text": "Przywodzenia, odwodzenia"}, {"id": "d", "text": "A i B"}, {"id": "e", "text": "A, B i C"}]'::jsonb,
   'd',
   $E$**Staw łokciowy** to staw złożony z trzech stawów we wspólnej torebce: **ramienno-łokciowy** i **ramienno-promieniowy** (zginanie/prostowanie) oraz **promieniowo-łokciowy bliższy** (nawracanie/odwracanie przedramienia). Stąd możliwe są ruchy **zginania/prostowania** ORAZ **nawracania/odwracania** (A i B). Przywodzenie i odwodzenie **nie zachodzą** w łokciu — to ruchy nadgarstka/barku. Odpowiedź E błędna z powodu dołączenia przywodzenia/odwodzenia.$E$,
   'staw łokciowy', 'ANATSTO-394'),
  (40, 'ANA-NER',
   'Nerw językowo-gardłowy opuszcza mózgowie w:',
   '[{"id": "a", "text": "Między piramidą a mostem"}, {"id": "b", "text": "Kącie móżdżkowo-mostowym"}, {"id": "c", "text": "W bruździe bocznej tylnej rdzenia przedłużonego"}, {"id": "d", "text": "Między konarem górnym móżdżku a mostem"}, {"id": "e", "text": "Między konarem dolnym móżdżku a rdzeniem przedłużonym"}]'::jsonb,
   'c',
   $E$**Nerw językowo-gardłowy (IX)** opuszcza mózgowie w **bruździe bocznej tylnej rdzenia przedłużonego** (zabruzdzie tylnobocznej), powyżej nerwów **X** i **XI**, które wychodzą tą samą bruzdą niżej. Następnie wszystkie trzy opuszczają czaszkę przez **otwór szyjny**. N. IX prowadzi czucie smaku i ogólne z 1/3 tylnej języka, unerwia m. rylcowo-gardłowy i ślinianke przyuszną (przywspółczulnie). Kąt móżdżkowo-mostowy to okolica wyjścia VII i VIII.$E$,
   'nerw językowo-gardłowy', 'ANATSTO-396'),
  (41, 'ANA-OUN',
   'Hipokamp należy do:',
   '[{"id": "a", "text": "Kresomózgowia"}, {"id": "b", "text": "Układu piramidowego"}, {"id": "c", "text": "Układu limbicznego"}, {"id": "d", "text": "A i B"}, {"id": "e", "text": "A i C"}]'::jsonb,
   'e',
   $E$**Hipokamp** to struktura **kresomózgowia** (część kory starej — archicortex, na przyśrodkowej powierzchni płata skroniowego) i zarazem kluczowy element **układu limbicznego**. Odpowiada za **konsolidację pamięci** (przekształcanie pamięci krótko- w długotrwałą) oraz orientację przestrzenną. Jest częścią **obwodu Papeza**. Nie ma związku z układem **piramidowym** (drogi ruchowe), stąd odpowiedź D błędna. Uszkodzenie obustronne → niemożność tworzenia nowych wspomnień (amnezja następcza).$E$,
   'układ limbiczny', 'ANATSTO-397'),
  (42, 'ANA-NAC',
   'Płaty boczne tarczycy przykryte są przez:',
   '[{"id": "a", "text": "Mięśnie nadgnykowe"}, {"id": "b", "text": "Mięśnie podgnykowe"}, {"id": "c", "text": "Blaszkę przedkręgową powięzi szyi"}, {"id": "d", "text": "A i C"}, {"id": "e", "text": "B i C"}]'::jsonb,
   'b',
   $E$Płaty boczne tarczycy od przodu pokrywają **mięśnie podgnykowe** (mostkowo-gnykowy, mostkowo-tarczowy, tarczowo-gnykowy, łopatkowo-gnykowy) wraz z blaszką przedtchawiczą powięzi szyi. **Blaszka przedkręgowa** leży **z tyłu**, na mięśniach przedkręgowych — nie pokrywa tarczycy od przodu. Mięśnie nadgnykowe leżą powyżej kości gnykowej. Stąd poprawna sama odpowiedź B. Tarczyca ma własną torebkę i jest objęta blaszką przedtchawiczą (pochewka tarczycy).$E$,
   'tarczyca i powięzie szyi', 'ANATSTO-398'),
  (44, 'ANA-OBW',
   'Mięśnie prostujące w stawie promieniowo-nadgarstkowym unerwione są przez nerw:',
   '[{"id": "a", "text": "pachowy"}, {"id": "b", "text": "Skórno-mięśniowy"}, {"id": "c", "text": "Łokciowy"}, {"id": "d", "text": "Pośrodkowy"}, {"id": "e", "text": "Promieniowy"}]'::jsonb,
   'e',
   $E$**Mięśnie prostowniki nadgarstka** (prostownik promieniowy długi i krótki, prostownik łokciowy nadgarstka) leżą w **grupie tylnej przedramienia** i są unerwione przez **nerw promieniowy** (gałąź głęboką / n. międzykostny tylny). Uszkodzenie n. promieniowego daje **„rękę opadającą"** (drop hand) — brak prostowania nadgarstka i palców. N. pośrodkowy i łokciowy unerwiają zginacze (grupa przednia). N. skórno-mięśniowy — mięśnie zginacze ramienia (dwugłowy, ramienny).$E$,
   'nerw promieniowy', 'ANATSTO-400'),
  (46, 'ANA-NAC',
   'Tętnica poprzeczna szyi odchodzi od:',
   '[{"id": "a", "text": "tętnicy podobojczykowej bezpośrednio"}, {"id": "b", "text": "tętnicy szyjnej wspólnej"}, {"id": "c", "text": "tętnicy szyjnej zewnętrznej"}, {"id": "d", "text": "pnia tarczowo-szyjnego"}, {"id": "e", "text": "pnia żebrowo-szyjnego"}]'::jsonb,
   'd',
   $E$**Tętnica poprzeczna szyi** klasycznie odchodzi od **pnia tarczowo-szyjnego** (gałąź t. podobojczykowej). Mnemonik gałęzi pnia tarczowo-szyjnego: **STAS** — t. **S**utkowa? nie — właściwie: t. **tarczowa dolna**, t. **nadłopatkowa**, t. **poprzeczna szyi** (oraz t. szyjna wstępująca). Pień **żebrowo-szyjny** daje t. międzyżebrową najwyższą i szyjną głęboką. Wariantowo t. poprzeczna szyi może odchodzić bezpośrednio od t. podobojczykowej (a. cervicalis superficialis).$E$,
   'pień tarczowo-szyjny', 'ANATSTO-402')
),
maxes AS (
  SELECT topic_id, COALESCE(MAX( (regexp_match(id, '([0-9]+)$'))[1]::int ), 0) AS mx
    FROM public.questions WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') GROUP BY topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam)
SELECT
  LOWER(n.topic_id) || '-' || LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_anat_sto_2025/1', 'Egzamin anatomia STOMA SUM 2025 (ANATSTO e2025-1)'
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (SELECT topic_id, COUNT(*) AS cnt FROM public.questions
         WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') AND COALESCE(is_active,true)=true GROUP BY topic_id) sub
 WHERE t.id = sub.topic_id;
