-- ============================================================
-- BATCH: e_anat_sto_2024/1  ·  subject_id=anatomia  ·  SHARED (oba kierunki, tracks=NULL)
-- Źródło: Egzamin anatomia STOMA SUM 2024 (ANATSTO e2024-1), 100 pytań (egzaminy STOMATOLOGII)
-- tracks NULL (anatomia wspólna) · source_code = oryginalne ANATSTO-NNN
-- Self-numbering id per dział = max seq z bazy + 1
--
-- Wersja po dedup (2026-05-28): 27 pytań — wycięte 73 duplikaty (batch + baza).
-- Audyt: exports/anatomia-batch-sto-2024-dedup-audit.md
-- ============================================================

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
(1, 'ANA-KON',
   'Łuk dłoniowy powierzchowny oddaje:',
   '[{"id": "a", "text": "tętnice palców wspólne"}, {"id": "b", "text": "tętnice palców właściwe"}, {"id": "c", "text": "tętnice palców głębokie"}, {"id": "d", "text": "tętnice grzbietowe śródręcza"}, {"id": "e", "text": "tętnice dłoniowe śródręcza"}]'::jsonb,
   'a',
   $E$**Łuk dłoniowy powierzchowny** (*arcus palmaris superficialis*) oddaje **tętnice dłoniowe palców wspólne** (*aa. digitales palmares communes*), które następnie dzielą się na **tt. palców właściwe**. Łuk leży powierzchownie względem ścięgien zginaczy. Natomiast **tt. dłoniowe śródręcza** są gałęziami łuku **głębokiego** — stąd dystraktor E. Łuk powierzchowny zaopatruje głównie palce.$E$,
   'łuk dłoniowy powierzchowny', 'ANATSTO-512'),
(2, 'ANA-KON',
   'Łuk dłoniowy powierzchowny powstaje z połączenia:',
   '[{"id": "a", "text": "końcowej gałęzi t. promieniowej i gałęzi dłoniowej głębokiej t. łokciowej"}, {"id": "b", "text": "końcowej gałęzi t. promieniowej i gałęzi dłoniowej powierzchownej t. łokciowej"}, {"id": "c", "text": "końcowej gałęzi t. łokciowej i gałęzi dłoniowej głębokiej t. promieniowej"}, {"id": "d", "text": "końcowej gałęzi t. łokciowej i gałęzi dłoniowej powierzchownej t. promieniowej"}, {"id": "e", "text": "końcowych gałęzi t. łokciowej i t. promieniowej"}]'::jsonb,
   'd',
   $E$**Łuk dłoniowy powierzchowny** tworzy głównie **końcowa gałąź t. łokciowej**, uzupełniona **gałęzią dłoniową powierzchowną t. promieniowej**. Odwrotnie jest z łukiem **głębokim**: dominuje w nim t. promieniowa, a uzupełnia gałąź głęboka t. łokciowej. Zasada: **powierzchowny = łokciowa, głęboki = promieniowa**. To ułatwia zapamiętanie dominującego naczynia każdego łuku.$E$,
   'łuk dłoniowy powierzchowny', 'ANATSTO-513'),
(3, 'ANA-KON',
   'Żyła odłokciowa odprowadza krew do żyły:',
   '[{"id": "a", "text": "pośrodkowej łokcia"}, {"id": "b", "text": "ramiennej"}, {"id": "c", "text": "podobojczykowej"}, {"id": "d", "text": "piersiowo-nabrzusznej"}, {"id": "e", "text": "piersiowej wewnętrznej"}]'::jsonb,
   'b',
   $E$**Żyła odłokciowa** (*v. basilica*) biegnie po przyśrodkowej stronie przedramienia i ramienia, a następnie przebija powięź, łącząc się z żyłami ramiennymi i dając początek (lub uchodząc do) **żyle ramiennej**. Żyła **odpromieniowa** (*v. cephalica*) uchodzi natomiast do żyły pachowej. Żyła pośrodkowa łokcia łączy obie żyły powierzchowne — to częste miejsce pobrań krwi.$E$,
   'żyła odłokciowa', 'ANATSTO-516'),
(4, 'ANA-TRZ',
   'Płat dolny płuca prawego zawiera:',
   '[{"id": "a", "text": "2 segmenty"}, {"id": "b", "text": "3 segmenty"}, {"id": "c", "text": "5 segmentów"}, {"id": "d", "text": "6 segmentów"}, {"id": "e", "text": "7 segmentów"}]'::jsonb,
   'c',
   $E$**Płat dolny płuca prawego** zawiera **5 segmentów**: szczytowy (górny), podstawny przyśrodkowy, podstawny przedni, podstawny boczny i podstawny tylny. Płuco prawe ma łącznie 10 segmentów (płat górny 3, środkowy 2, dolny 5). Płat dolny **lewego** płuca również ma zwykle 5, lecz całe lewe płuco ma 8–9 segmentów wskutek zlewania się segmentów. Schemat segmentów jest klasykiem anatomii płuc.$E$,
   'segmenty płuca', 'ANATSTO-528'),
(5, 'ANA-CZA',
   'Okienko ślimaka znajduje się:',
   '[{"id": "a", "text": "w ścianie górnej jamy bębenkowej"}, {"id": "b", "text": "w ścianie dolnej jamy bębenkowej"}, {"id": "c", "text": "w ścianie bocznej jamy bębenkowej"}, {"id": "d", "text": "w ścianie przyśrodkowej jamy bębenkowej"}, {"id": "e", "text": "w ścianie tylnej jamy bębenkowej"}]'::jsonb,
   'd',
   $E$**Okienko ślimaka** (okrągłe) leży w **ścianie przyśrodkowej (błędnikowej)** jamy bębenkowej, podobnie jak okienko przedsionka (owalne) i wyniosłość wzgórka (*promontorium*). Ściana przyśrodkowa oddziela ucho środkowe od wewnętrznego. Ściana **boczna** to błona bębenkowa, **górna** (stropowa) graniczy z dołem środkowym czaszki, **dolna** z żyłą szyjną wewnętrzną. Topografia ścian jamy bębenkowej.$E$,
   'jama bębenkowa', 'ANATSTO-530'),
(6, 'ANA-TUL',
   'W śródpiersiu tylnym dolnym nie znajdują się:',
   '[{"id": "a", "text": "przełyk"}, {"id": "b", "text": "nerwy błędne"}, {"id": "c", "text": "nerwy przeponowe"}, {"id": "d", "text": "żyła nieparzysta"}, {"id": "e", "text": "przewód piersiowy"}]'::jsonb,
   'c',
   $E$W **śródpiersiu tylnym** biegną: przełyk, nerwy błędne (X), żyła nieparzysta i nieparzysta krótka, przewód piersiowy oraz aorta zstępująca. **Nerwy przeponowe** przebiegają natomiast w śródpiersiu **środkowym**, po bokach worka osierdziowego (wraz z naczyniami osierdziowo-przeponowymi) — dlatego nie należą do śródpiersia tylnego. Topografia zawartości śródpiersia to częsty temat egzaminacyjny.$E$,
   'śródpiersie', 'ANATSTO-533'),
(7, 'ANA-NER',
   'Nerw okoruchowy nie unerwia mięśnia:',
   '[{"id": "a", "text": "prostego bocznego"}, {"id": "b", "text": "skośnego górnego"}, {"id": "c", "text": "skośnego dolnego"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A i C"}]'::jsonb,
   'd',
   $E$**Nerw okoruchowy (III)** unerwia większość mięśni gałkoruchowych, ale **nie** mięsień **prosty boczny** (CN VI) ani **skośny górny** (CN IV) — stąd poprawna D. Mnemonik: **SO4LR6** — Superior Oblique = IV, Lateral Rectus = VI, reszta (prosty górny, dolny, przyśrodkowy, skośny dolny, dźwigacz powieki) = III. Nerw III niesie też włókna przywspółczulne do zwieracza źrenicy.$E$,
   'nerw okoruchowy', 'ANATSTO-534'),
(8, 'ANA-CZA',
   'Kość łzowa jest jednym z elementów budujących:',
   '[{"id": "a", "text": "ścianę dolną oczodołu i ścianę górną jamy nosowej"}, {"id": "b", "text": "ścianę przyśrodkową oczodołu i ścianę boczną jamy nosowej"}, {"id": "c", "text": "ścianę przyśrodkową oczodołu i ścianę przyśrodkową jamy nosowej"}, {"id": "d", "text": "ścianę boczną oczodołu i ścianę boczną jamy nosowej"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'b',
   $E$**Kość łzowa** (*os lacrimale*) współtworzy **ścianę przyśrodkową oczodołu** (z dołem dla woreczka łzowego) oraz **ścianę boczną jamy nosowej**. Jest najmniejszą kością twarzoczaszki. Ścianę przyśrodkową oczodołu budują też: wyrostek czołowy szczęki, blaszka oczodołowa kości sitowej i trzon kości klinowej. Dół łzowy przechodzi w przewód nosowo-łzowy uchodzący do przewodu nosowego dolnego.$E$,
   'kość łzowa', 'ANATSTO-536'),
(9, 'ANA-TUL',
   'Więzadła żółte łączą:',
   '[{"id": "a", "text": "zwrócone ku sobie powierzchnie sąsiadujących ze sobą łuków kręgów"}, {"id": "b", "text": "zwrócone ku sobie powierzchnie sąsiadujących ze sobą trzonów kręgów"}, {"id": "c", "text": "wyrostki poprzeczne"}, {"id": "d", "text": "wyrostki kolczyste"}, {"id": "e", "text": "wyrostki stawowe"}]'::jsonb,
   'a',
   $E$**Więzadła żółte** (*ligamenta flava*) łączą **sąsiadujące łuki kręgów** (blaszki łuków), zwrócone ku sobie powierzchniami. Zawdzięczają barwę dużej zawartości **włókien sprężystych (elastyny)**, co pomaga w powrocie kręgosłupa do wyprostu. Wyrostki kolczyste łączą więzadła międzykolcowe i nadkolcowe, poprzeczne — międzypoprzeczne. Przerost więzadeł żółtych może powodować stenozę kanału kręgowego.$E$,
   'połączenia kręgosłupa', 'ANATSTO-539'),
(10, 'ANA-TUL',
   'Żebra rzekome to żebra:',
   '[{"id": "a", "text": "VI, VII i VIII"}, {"id": "b", "text": "VII, VIII i IX"}, {"id": "c", "text": "VIII, IX i X"}, {"id": "d", "text": "VIII, IX, X i XI"}, {"id": "e", "text": "IX, X, XI i XII"}]'::jsonb,
   'c',
   $E$**Żebra rzekome** to żebra **VIII, IX i X** — ich chrząstki nie łączą się bezpośrednio z mostkiem, lecz z chrząstką żebra wyżej leżącego, tworząc **łuk żebrowy**. Żebra **I–VII** to żebra prawdziwe (łączą się wprost z mostkiem), a **XI i XII** to żebra wolne (wahadłowe), zakończone w mięśniach. Łącznie 12 par żeber. Podział na prawdziwe/rzekome/wolne to klasyka anatomii klatki piersiowej.$E$,
   'żebra', 'ANATSTO-541'),
(11, 'ANA-KON',
   'W stawie kolanowym więzadła wewnątrzstawowe to:',
   '[{"id": "a", "text": "więzadła krzyżowe"}, {"id": "b", "text": "więzadła poboczne"}, {"id": "c", "text": "więzadło rzepki"}, {"id": "d", "text": "więzadło podkolanowe i skośne"}, {"id": "e", "text": "troczki rzepki"}]'::jsonb,
   'a',
   $E$**Więzadła wewnątrzstawowe** stawu kolanowego to **więzadła krzyżowe** — przednie (ACL) i tylne (PCL), leżące wewnątrz torby, lecz zewnątrzmaziówkowo. Krzyżują się, stabilizując staw w płaszczyznie strzałkowej (ACL zapobiega przesunięciu piszczeli do przodu, PCL do tyłu). Więzadła **poboczne** i rzepki są zewnątrzstawowe. Do wewnątrzstawowych należą też więzadła i łąkotki oraz więzadło poprzeczne kolana.$E$,
   'staw kolanowy', 'ANATSTO-546'),
(12, 'ANA-OUN',
   'Piramidy leżą do boku od:',
   '[{"id": "a", "text": "bruzdy pośrodkowej przedniej rdzenia przedłużonego"}, {"id": "b", "text": "bruzdy pośrodkowej przedniej mostu"}, {"id": "c", "text": "bruzdy pośrodkowej tylnej rdzenia przedłużonego"}, {"id": "d", "text": "bruzdy pośrodkowej tylnej mostu"}, {"id": "e", "text": "bruzdy pośrodkowej tylnej rdzenia kręgowego"}]'::jsonb,
   'a',
   $E$**Piramidy** (*pyramides*) to dwa podłużne wały na **przedniej** powierzchni **rdzenia przedłużonego**, leżące po bokach **bruzdy pośrodkowej przedniej**. Zawierają drogi korowo-rdzeniowe (piramidowe), które w dolnej części krzyżują się (skrzyżowanie piramid). Bocznie od piramidy leży **oliwka**. Między piramidą a oliwką wychodzą korzenie nerwu **podjęzykowego (XII)**. Klasyczna topografia powierzchni przedniej opuszki.$E$,
   'rdzeń przedłużony', 'ANATSTO-550'),
(13, 'ANA-OUN',
   'Wzgórki dolne blaszki pokrywy to:',
   '[{"id": "a", "text": "podkorowe ośrodki wzroku, a ich ramiona dochodzą do ciała kolankowego bocznego"}, {"id": "b", "text": "podkorowe ośrodki wzroku, a ich ramiona dochodzą do ciała kolankowego przyśrodkowego"}, {"id": "c", "text": "podkorowe ośrodki słuchu, a ich ramiona dochodzą do ciała kolankowego bocznego"}, {"id": "d", "text": "podkorowe ośrodki słuchu, a ich ramiona dochodzą do ciała kolankowego przyśrodkowego"}, {"id": "e", "text": "podkorowe ośrodki wzroku i słuchu, a ich ramiona dochodzą do ciała kolankowego przyśrodkowego"}]'::jsonb,
   'd',
   $E$**Wzgórki dolne** blaszki pokrywy (czworaczej) to **podkorowe ośrodki słuchu**; ich **ramiona** biegną do **ciała kolankowego przyśrodkowego** wzgórza, a stąd droga słuchowa idzie do kory skroniowej. **Wzgórki górne** to ośrodki **wzroku**, połączone ramionami z ciałem kolankowym **bocznym**. Mnemonik: słuch–przyśrodkowe (Medial–Music/Auditory), wzrok–boczne (Lateral–Light). Klasyczne rozróżnienie ciał kolankowatych.$E$,
   'blaszka pokrywy śródmózgowia', 'ANATSTO-555'),
(14, 'ANA-TRZ',
   'Przewód wątrobowy wspólny powstaje z połączenia:',
   '[{"id": "a", "text": "przewodu wątrobowego prawego z przewodem pęcherzykowym"}, {"id": "b", "text": "przewodu wątrobowego lewego z przewodem pęcherzykowym"}, {"id": "c", "text": "prawego i lewego przewodu wątrobowego"}, {"id": "d", "text": "przewodu wątrobowego wspólnego z przewodem pęcherzykowym"}, {"id": "e", "text": "przewodu wątrobowego wspólnego z przewodem trzustkowym"}]'::jsonb,
   'c',
   $E$**Przewód wątrobowy wspólny** (*ductus hepaticus communis*) powstaje z połączenia **prawego i lewego przewodu wątrobowego** we wnęce wątroby. Po połączeniu z **przewodem pęcherzykowym** (od pęcherzyka) tworzy **przewód żółciowy wspólny** (*ductus choledochus*) — to treść dystraktora D. Choledochus łączy się następnie z przewodem trzustkowym tworząc bańkę wątrobowo-trzustkową (Vatera). Hierarchia dróg żółciowych.$E$,
   'drogi żółciowe', 'ANATSTO-561'),
(15, 'ANA-JAM',
   'Do przewodu nosowego dolnego uchodzą:',
   '[{"id": "a", "text": "zatoka czołowa, klinowa i szczękowa"}, {"id": "b", "text": "zatoka czołowa, szczękowa i komórki sitowe przednie"}, {"id": "c", "text": "zatoka czołowa, szczękowa i komórki sitowe tylne"}, {"id": "d", "text": "zatoka szczękowa, klinowa i komórki sitowe przednie"}, {"id": "e", "text": "żadne z wyżej wymienionych"}]'::jsonb,
   'e',
   $E$Do **przewodu nosowego dolnego** uchodzi wyłącznie **przewód nosowo-łzowy** — żadna zatoka przynosowa tam nie drenuje, stąd poprawna E. Przypomnienie drenażu: zatoka **szczękowa, czołowa** oraz komórki sitowe **przednie i środkowe** → przewód **środkowy**; komórki sitowe **tylne** → przewód **górny**; zatoka **klinowa** → zachyłek klinowo-sitowy. Dolny przewód obsługuje tylko odpływ łez.$E$,
   'przewody nosowe', 'ANATSTO-565'),
(16, 'ANA-TUL',
   'Rozwór aorty znajduje się w:',
   '[{"id": "a", "text": "części żebrowej przepony"}, {"id": "b", "text": "części lędźwiowej przepony"}, {"id": "c", "text": "części ścięgnistej przepony"}, {"id": "d", "text": "w górnej części blaszki tylnej pochewki m. prostego brzucha"}, {"id": "e", "text": "w dolnej części blaszki tylnej pochewki m. prostego brzucha"}]'::jsonb,
   'b',
   $E$**Rozwór aorty** (*hiatus aorticus*) leży w **części lędźwiowej** przepony, na wysokości **Th12**, między odnogami przepony — to najniżej i najbardziej z tyłu położony otwór. Przechodzą przezeń **aorta** i **przewód piersiowy**. Wyżej leżą: rozwór przełykowy (Th10, z n. błędnymi) i otwór ż. głównej dolnej (Th8, w części ścięgnistej). Mnemonik wysokości: "**8-10-12** = IVC–przełyk–aorta".$E$,
   'przepona', 'ANATSTO-570'),
(17, 'ANA-MIE',
   'Jednostronny skurcz mm. skrzydłowych bocznych:',
   '[{"id": "a", "text": "obniża żuchwę"}, {"id": "b", "text": "cofa wysuniętą żuchwę"}, {"id": "c", "text": "wysuwa żuchwę do przodu"}, {"id": "d", "text": "skręca żuchwę w stronę przeciwną"}, {"id": "e", "text": "skręca żuchwę prawy w stronę prawą, lewy w stronę lewą"}]'::jsonb,
   'd',
   $E$**Jednostronny skurcz mięśnia skrzydłowego bocznego** przesuwa żuchwę **w stronę przeciwną** — np. skurcz prawego kieruje bródkę w lewo (ruchy żucia, mielenia). Skurcz **obustronny** wysuwa żuchwę do przodu i pomaga ją obniżać. To jedyny mięsień żucia czynnie **opuszczający** żuchwę (wspólnie z mm. nadgnykowymi). Unerwiony przez V3. Naprzemienne ruchy boczne tworzą charakterystyczny ruch żucia.$E$,
   'mięsień skrzydłowy boczny', 'ANATSTO-576'),
(18, 'ANA-KON',
   'Mięsień kruczo-ramienny:',
   '[{"id": "a", "text": "tylko prostuje w stawie ramiennym"}, {"id": "b", "text": "prostuje i przywodzi w stawie ramiennym"}, {"id": "c", "text": "prostuje i odwodzi w stawie ramiennym"}, {"id": "d", "text": "zgina i odwodzi w stawie ramiennym"}, {"id": "e", "text": "zgina i przywodzi w stawie ramiennym"}]'::jsonb,
   'e',
   $E$**Mięsień kruczo-ramienny** (*m. coracobrachialis*) **zgina i przywodzi** ramię w stawie ramiennym. Biegnie od wyrostka kruczego łopatki do przyśrodkowej powierzchni trzonu kości ramiennej. Jest **przebijany przez nerw mięśniowo-skórny** (C5–C7), który go unerwia — to charakterystyczna cecha topograficzna. Należy do przedziału przedniego (zginaczy) ramienia wraz z m. dwugłowym i ramiennym.$E$,
   'mięsień kruczo-ramienny', 'ANATSTO-578'),
(19, 'ANA-TRZ',
   'Kolejne odcinki jajowodu, licząc od końca macicznego, to:',
   '[{"id": "a", "text": "bańka, cieśń, lejek"}, {"id": "b", "text": "bańka, lejek, cieśń"}, {"id": "c", "text": "lejek, cieśń, bańka"}, {"id": "d", "text": "lejek, bańka, cieśń"}, {"id": "e", "text": "cieśń, bańka, lejek"}]'::jsonb,
   'e',
   $E$Odcinki jajowodu **od strony macicy ku jajnikowi**: część **maciczna** (śródścienna) → **cieśń** (wąska) → **bańka** (najszersza, miejsce zapłodnienia) → **lejek** z **strzępkami** (wychwytuje komórkę jajową). Stąd kolejność cieśń–bańka–lejek (E). Bańka to typowa lokalizacja **ciąży ektopowej**. Jajowód biegnie w wolnym brzegu więzadła szerokiego macicy (krezka jajowodu).$E$,
   'jajowód', 'ANATSTO-584'),
(20, 'ANA-TRZ',
   'Po lewej stronie mostka osłuchujemy:',
   '[{"id": "a", "text": "zastawkę mitralną i trójdzielną"}, {"id": "b", "text": "zastawkę mitralną i pnia płucnego"}, {"id": "c", "text": "zastawkę trójdzielną i pnia płucnego"}, {"id": "d", "text": "zastawkę aortalną i trójdzielną"}, {"id": "e", "text": "zastawkę pnia płucnego i trójdzielną"}]'::jsonb,
   'b',
   $E$Po **lewej stronie mostka** osłuchujemy zastawkę **pnia płucnego** (II międzyżebrze lewe) oraz punkt osłuchiwania zastawki **mitralnej/dwudzielnej** (koniuszek serca, V międzyżebrze w linii środkowo-obojczykowej lewej). Po **prawej** stronie: aortalna (II mż prawe). Trójdzielna — przy dolnym lewym brzegu mostka. Mnemonik kolejności od góry: "**APTM**" (Aorta–Płucna–Trójdzielna–Mitralna). Punkty osłuchowe nie pokrywają się z anatomicznym położeniem zastawek.$E$,
   'osłuchiwanie zastawek serca', 'ANATSTO-587'),
(21, 'ANA-CZA',
   'Otwór szyjny ograniczony jest przez:',
   '[{"id": "a", "text": "część bębenkową kości skroniowej i część boczną kości klinowej"}, {"id": "b", "text": "część skalistą kości skroniowej i część boczną kości klinowej"}, {"id": "c", "text": "część sutkową kości skroniowej i część boczną kości potylicznej"}, {"id": "d", "text": "część bębenkową kości skroniowej i część boczną kości potylicznej"}, {"id": "e", "text": "część skalistą kości skroniowej i część boczną kości potylicznej"}]'::jsonb,
   'e',
   $E$**Otwór szyjny** (*foramen jugulare*) leży między **częścią skalistą kości skroniowej** a **częścią boczną kości potylicznej**. Przechodzą przezeń: **ż. szyjna wewnętrzna** (zatoka esowata) oraz nerwy **IX, X, XI**. Mnemonik zawartości: "**900, 1000, 1100**" (IX, X, XI). Uszkodzenie okolicy daje zespół otworu szyjnego (Vernet). Z przodu sąsiaduje z kanałem t. szyjnej wewnętrznej.$E$,
   'otwory podstawy czaszki', 'ANATSTO-589'),
(22, 'ANA-CZA',
   'Wyniosłość łukowata piramidy kości skroniowej jest utworzona przez:',
   '[{"id": "a", "text": "kanał półkolisty przedni"}, {"id": "b", "text": "kanał półkolisty tylny"}, {"id": "c", "text": "kanał półkolisty boczny"}, {"id": "d", "text": "podstawę ślimaka"}, {"id": "e", "text": "szczyt ślimaka"}]'::jsonb,
   'a',
   $E$**Wyniosłość łukowata** (*eminentia arcuata*) na przedniej powierzchni piramidy kości skroniowej jest uniesieniem utworzonym przez **kanał półkolisty przedni** (górny) błędnika kostnego. Stanowi ważny punkt orientacyjny w chirurgii podstawy czaszki i dołu środkowego. W pobliżu leży wyniosłość bębenkowa oraz rozwór kanału nerwu skalistego większego. Kanał przedni leży prostopadle do osi piramidy.$E$,
   'piramida kości skroniowej', 'ANATSTO-591'),
(23, 'ANA-NER',
   'Korzeń czuciowy zwoju żuchwowego (podżuchwowego) pochodzi z:',
   '[{"id": "a", "text": "nerwu pośredniego"}, {"id": "b", "text": "struny bębenkowej"}, {"id": "c", "text": "pierwszej gałęzi nerwu trójdzielnego"}, {"id": "d", "text": "drugiej gałęzi nerwu trójdzielnego"}, {"id": "e", "text": "trzeciej gałęzi nerwu trójdzielnego"}]'::jsonb,
   'e',
   $E$**Zwój podżuchwowy** zawieszony jest na **nerwie językowym**, który jest gałęzią **trzeciej gałęzi nerwu trójdzielnego (V3)** — stąd korzeń czuciowy zwoju pochodzi z **V3**. Korzeń **przywspółczulny** (wydzielniczy) dociera natomiast struną bębenkową od nerwu VII, a współczulny ze splotu t. twarzowej. Zwój zaopatruje ślinianki podżuchwową i podjęzykową. Trzy korzenie zwoju to klasyczny schemat.$E$,
   'zwoje przywspółczulne głowy', 'ANATSTO-595'),
(24, 'ANA-MIE',
   'Mięsień dwubrzuścowy unerwiony jest następująco:',
   '[{"id": "a", "text": "brzusiec przedni przez n. V, a brzusiec tylny przez n. VII"}, {"id": "b", "text": "brzusiec przedni przez n. VII, a brzusiec tylny przez n. V"}, {"id": "c", "text": "brzusiec przedni przez n. V, a brzusiec tylny przez n. IX"}, {"id": "d", "text": "brzusiec przedni przez n. IX, a brzusiec tylny przez n. V"}, {"id": "e", "text": "brzusiec przedni przez n. V, a brzusiec tylny przez n. X"}]'::jsonb,
   'a',
   $E$**Mięsień dwubrzuścowy**: **brzusiec przedni** unerwia nerw **żuchwowy (V3)** — przez n. żuchwowo-gnykowy, a **brzusiec tylny** nerw **twarzowy (VII)**. Odmienne unerwienie wynika z różnego pochodzenia rozwojowego (brzusiec przedni z I łuku skrzelowego, tylny z II łuku). Mięsień ten unosi kość gnykową i pomaga obniżać żuchwę. Klasyczny przykład mięśnia o dwojakim unerwieniu z dwóch łuków skrzelowych.$E$,
   'mięsień dwubrzuścowy', 'ANATSTO-596'),
(25, 'ANA-KON',
   'Mięsień odwodziciel długi kciuka należy do:',
   '[{"id": "a", "text": "warstwy powierzchownej grupy przedniej mięśni przedramienia"}, {"id": "b", "text": "warstwy głębokiej grupy przedniej mięśni przedramienia"}, {"id": "c", "text": "warstwy powierzchownej grupy tylnej mięśni przedramienia"}, {"id": "d", "text": "warstwy głębokiej grupy tylnej mięśni przedramienia"}, {"id": "e", "text": "grupy bocznej mięśni przedramienia"}]'::jsonb,
   'd',
   $E$**Mięsień odwodziciel długi kciuka** (*m. abductor pollicis longus*) należy do **warstwy głębokiej grupy tylnej (prostowników)** przedramienia, wraz z prostownikami kciuka (krótkim i długim) oraz prostownikiem wskaziciela i odwracaczem. Mięśnie te unerwia **nerw promieniowy** (gałąź głęboka / n. międzykostny tylny). Odwodziciel długi kciuka współtworzy boczną granicę **tabakierki anatomicznej**. Grupa głęboka leży pod prostownikami powierzchownymi.$E$,
   'mięśnie przedramienia', 'ANATSTO-597'),
(26, 'ANA-JAM',
   'Tylną 1/3 języka smakowo unerwia:',
   '[{"id": "a", "text": "nerw V"}, {"id": "b", "text": "nerw VII"}, {"id": "c", "text": "nerw IX"}, {"id": "d", "text": "nerw X"}, {"id": "e", "text": "nerw XII"}]'::jsonb,
   'c',
   $E$Smak z **tylnej 1/3 języka** (za bruzdą graniczną) przewodzi **nerw językowo-gardłowy (IX)** — zarówno czucie smaku, jak i czucie ogólne tej okolicy. Przednie 2/3: smak — struna bębenkowa (VII), czucie ogólne — n. językowy (V3). Okolica nagłośni: smak i czucie — nerw błędny (X). Mnemonik: "tył = IX dla obu modalności". Bruzda graniczna (V-kształtna) z otworem ślepym wyznacza granicę unerwienia.$E$,
   'unerwienie języka', 'ANATSTO-598'),
(27, 'ANA-OUN',
   'Włókna korowo-rdzeniowe przechodzą przez:',
   '[{"id": "a", "text": "część przednią odnogi przedniej torebki wewnętrznej"}, {"id": "b", "text": "część tylną odnogi przedniej torebki wewnętrznej"}, {"id": "c", "text": "kolano torebki wewnętrznej"}, {"id": "d", "text": "część przednią odnogi tylnej torebki wewnętrznej"}, {"id": "e", "text": "część tylną odnogi tylnej torebki wewnętrznej"}]'::jsonb,
   'd',
   $E$**Włókna korowo-rdzeniowe** (droga piramidowa do kończyn) biegną w **przedniej części odnogi tylnej torebki wewnętrznej**. W **kolanie** leżą włókna korowo-jądrowe (do nerwów czaszkowych), a bardziej ku tyłowi w odnodze tylnej — drogi czuciowe (wzgórzowo-korowe) oraz wzrokowa i słuchowa. Somatotopia: przód odnogi tylnej = kończyna górna, dalej tułów i kończyna dolna. Klasyczna lokalizacja udarowa.$E$,
   'torebka wewnętrzna', 'ANATSTO-599')
),
maxes AS (
  SELECT topic_id, COALESCE(MAX( (regexp_match(id, '([0-9]+)$'))[1]::int ), 0) AS mx
    FROM public.questions WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') GROUP BY topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam)
SELECT
  LOWER(n.topic_id) || '-' || LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_anat_sto_2024/1', 'Egzamin anatomia STOMA SUM 2024 (ANATSTO e2024-1)'
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (SELECT topic_id, COUNT(*) AS cnt FROM public.questions
         WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') AND COALESCE(is_active,true)=true GROUP BY topic_id) sub
 WHERE t.id = sub.topic_id;
