-- ============================================================
-- BATCH: e_anat_sto_2023/2  ·  subject_id=anatomia  ·  SHARED (oba kierunki, tracks=NULL)
-- Źródło: Egzamin anatomia STOMA SUM 2023 (ANATSTO e2023-2), 97 pytań (egzaminy STOMATOLOGII)
-- tracks NULL (anatomia wspólna) · source_code = oryginalne ANATSTO-NNN
-- Self-numbering id per dział = max seq z bazy + 1
--
-- Wersja po dedup (2026-05-28): 85 pytań — wycięte 12 duplikaty (batch + baza).
-- Audyt: exports/anatomia-batch-sto-2023-2-dedup-audit.md
-- ============================================================

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
(1, 'ANA-TRZ',
   'Czym jest zachyłek opłucnej?',
   '[{"id": "a", "text": "Przejściem blaszki trzewnej opłucnej w blaszkę ścienną"}, {"id": "b", "text": "Przejściem blaszki ściennej opłucnej w blaszkę trzewną"}, {"id": "c", "text": "Przejściem jednej blaszki ściennej opłucnej w drugą blaszkę ścienną"}, {"id": "d", "text": "Przejściem blaszki trzewnej opłucnej w nią samą"}, {"id": "e", "text": "Przejściem blaszki ściennej w osierdzie"}]'::jsonb,
   'c',
   $E$**Zachyłki opłucnej** (recessus pleurales) to przestrzenie rezerwowe powstające w miejscu, gdzie **jedna część opłucnej ściennej przechodzi w drugą** (np. część żebrowa w przeponową). Nie wypełnia ich płuco w czasie spokojnego oddychania — dopiero przy głębokim wdechu brzeg płuca tam wchodzi. Najważniejszy klinicznie to **zachyłek żebrowo-przeponowy** (miejsce nakłucia jamy opłucnej). Blaszka **trzewna** pokrywa płuco, **ścienna** wyściela ścianę klatki — zachyłek dotyczy wyłącznie ściennej.$E$,
   'opłucna', 'ANATSTO-609'),
(2, 'ANA-CZA',
   'Dół zażuchwowy jest ograniczony:',
   '[{"id": "a", "text": "Z tyłu wyrostkiem sutkowatym i przewodem słuchowym zewnętrznym"}, {"id": "b", "text": "Z przodu wyrostkiem rylcowatym"}, {"id": "c", "text": "Od dołu mięśniem żwaczem"}, {"id": "d", "text": "Od góry kością gnykową"}, {"id": "e", "text": "Od przyśrodka gałęzią żuchwy"}]'::jsonb,
   'a',
   $E$**Dół zażuchwowy** (fossa retromandibularis) leży za gałęzią żuchwy. Granice: **z przodu** – gałąź żuchwy, **z tyłu** – wyrostek sutkowaty i przewód słuchowy zewnętrzny, **przyśrodkowo** – wyrostek rylcowaty z mięśniami, **od góry** – staw skroniowo-żuchwowy. Mieści ślinankę przyuszną, nerw twarzowy, żyłę zażuchwową i tętnicę szyjną zewnętrzną. Wyrostek **rylcowaty** leży przyśrodkowo/od tyłu, nie z przodu — stąd B błędne.$E$,
   'dół zażuchwowy', 'ANATSTO-610'),
(3, 'ANA-NAC',
   'Czym jest ograniczona przestrzeń przygardłowa z tyłu?',
   '[{"id": "a", "text": "Powięzią przedkręgową"}, {"id": "b", "text": "Mięśniem skrzydłowym przyśrodkowym"}, {"id": "c", "text": "Ślinianką przyuszną"}, {"id": "d", "text": "Ścianą boczną gardła"}, {"id": "e", "text": "Powięzią policzkowo-gardłową"}]'::jsonb,
   'a',
   $E$**Przestrzeń przygardłowa** (spatium parapharyngeum) ma kształt odwróconej piramidy. Ograniczają ją: **przyśrodkowo** – ściana boczna gardła z powięzią policzkowo-gardłową, **bocznie** – mięsień skrzydłowy przyśrodkowy i ślinianka przyuszna, **z tyłu** – **powięź przedkręgowa** (blaszka przedkręgowa powięzi szyi) pokrywająca kręgosłup i mięśnie przedkręgowe. Ma znaczenie w szerzeniu się ropni okołomigdałkowych i zębopochodnych zakażeń przestrzeni głębokich szyi.$E$,
   'przestrzeń przygardłowa', 'ANATSTO-611'),
(4, 'ANA-TRZ',
   'Jaki jest najgłębszy zachyłek opłucnej?',
   '[{"id": "a", "text": "Żebrowo-śródpiersiowy przedni"}, {"id": "b", "text": "Żebrowo-śródpiersiowy tylny"}, {"id": "c", "text": "Żebrowo-przeponowy"}, {"id": "d", "text": "Przeponowo-śródpiersiowy"}, {"id": "e", "text": "Kręgowo-śródpiersiowy"}]'::jsonb,
   'c',
   $E$**Zachyłek żebrowo-przeponowy** (recessus costodiaphragmaticus) jest **najgłębszy** ze wszystkich zachyłków opłucnej — sięga w linii pachowej środkowej do ok. 5 cm. Powstaje na styku części żebrowej i przeponowej opłucnej ściennej. Klinicznie kluczowy: tu gromadzi się **płyn w jamie opłucnej** i tędy wykonuje się **nakłucie opłucnej (torakocentezę)**, zwykle w 7.–9. międzyżebrzu w linii pachowej tylnej. Pozostałe zachyłki są płytsze.$E$,
   'opłucna', 'ANATSTO-612'),
(5, 'ANA-NAC',
   'Do przednich gałęzi tętnicy szyjnej zewnętrznej należy:',
   '[{"id": "a", "text": "Tętnica językowa"}, {"id": "b", "text": "Tętnica uszna tylna"}, {"id": "c", "text": "Tętnica potyliczna"}, {"id": "d", "text": "Tętnica skroniowa powierzchowna"}, {"id": "e", "text": "Tętnica gardłowa wstępująca"}]'::jsonb,
   'a',
   $E$Tętnica szyjna zewnętrzna oddaje gałęzie w grupach. **Przednie**: tętnica **tarczowa górna, językowa, twarzowa**. **Tylne**: potyliczna i uszna tylna. **Przyśrodkowa**: gardłowa wstępująca. **Końcowe**: skroniowa powierzchowna i szczękowa. Mnemonik gałęzi ECA: **„Some Anatomists Like Freaking Out Poor Medical Students"** (Superior thyroid, Ascending pharyngeal, Lingual, Facial, Occipital, Posterior auricular, Maxillary, Superficial temporal). Językowa jest gałęzią przednią.$E$,
   'tętnica szyjna zewnętrzna', 'ANATSTO-613'),
(6, 'ANA-NAC',
   'Co tworzy kąt żylny?',
   '[{"id": "a", "text": "Żyła podobojczykowa i żyła szyjna wewnętrzna"}, {"id": "b", "text": "Żyła podobojczykowa i żyła szyjna zewnętrzna"}, {"id": "c", "text": "Żyła szyjna wewnętrzna i żyła kręgowa"}, {"id": "d", "text": "Żyła ramienno-głowowa i żyła nieparzysta"}, {"id": "e", "text": "Żyła szyjna przednia i żyła twarzowa"}]'::jsonb,
   'a',
   $E$**Kąt żylny** (angulus venosus) powstaje z połączenia **żyły szyjnej wewnętrznej** z **żyłą podobojczykową**, dając początek żyle ramienno-głowowej. Jest miejscem ujścia naczyń chłonnych: do **lewego kąta żylnego** uchodzi **przewód piersiowy**, do **prawego** – przewód chłonny prawy. Żyła szyjna zewnętrzna uchodzi zwykle do żyły podobojczykowej osobno, nie tworzy kąta żylnego — stąd B błędne. Kąt żylny jest też ważnym punktem dostępu naczyniowego (cewnikowanie żyły podobojczykowej i szyjnej wewnętrznej).$E$,
   'kąt żylny', 'ANATSTO-614'),
(7, 'ANA-TRZ',
   'Co tworzy przewód żółciowy wspólny?',
   '[{"id": "a", "text": "Przewód wątrobowy wspólny i przewód pęcherzykowy"}, {"id": "b", "text": "Przewód wątrobowy prawy i lewy"}, {"id": "c", "text": "Przewód trzustkowy i przewód pęcherzykowy"}, {"id": "d", "text": "Przewód wątrobowy wspólny i przewód trzustkowy"}, {"id": "e", "text": "Przewód pęcherzykowy i przewód trzustkowy dodatkowy"}]'::jsonb,
   'a',
   $E$**Przewód żółciowy wspólny** (ductus choledochus) powstaje z połączenia **przewodu wątrobowego wspólnego** (ductus hepaticus communis) z **przewodem pęcherzykowym** (ductus cysticus) odprowadzającym żółć z pęcherzyka. Następnie łączy się z **przewodem trzustkowym** tworząc bańkę wątrobowo-trzustkową (Vatera), uchodzącą na brodawce większej dwunastnicy. Przewód wątrobowy wspólny sam powstaje z połączenia przewodów wątrobowych prawego i lewego — stąd B opisuje wcześniejszy etap.$E$,
   'drogi żółciowe', 'ANATSTO-615'),
(8, 'ANA-TRZ',
   'Co znajduje się w świetle komory prawej serca?',
   '[{"id": "a", "text": "Mięsień brodawkowaty"}, {"id": "b", "text": "Mięsień grzebieniasty"}, {"id": "c", "text": "Zastawka dwudzielna"}, {"id": "d", "text": "Otwór owalny"}, {"id": "e", "text": "Wsierdzie zatoki wieńcowej"}]'::jsonb,
   'a',
   $E$W świetle **komory prawej** znajdują się **mięśnie brodawkowate** (przedni, tylny, przegrodowy), **beleczki mięśniowe**, **wstęga (beleczka) przegrodowo-brzeżna** (moderator band prowadząca odnogę pęczka Hisa) oraz **zastawka przedsionkowo-komorowa prawa (trójdzielna)**. Mięśnie brodawkowate przez **struny ścięgniste** napinają płatki zastawki, zapobiegając jej cofnięciu w skurczu. Mięśnie grzebieniaste są w przedsionkach, zastawka dwudzielna — w sercu lewym.$E$,
   'komora prawa serca', 'ANATSTO-616'),
(9, 'ANA-OUN',
   'Która odpowiedź zawiera wyłącznie pęcherzyki wtórne mózgowia?',
   '[{"id": "a", "text": "Kresomózgowie, międzymózgowie, tyłomózgowie wtórne"}, {"id": "b", "text": "Kresomózgowie, śródmózgowie, rdzeniomózgowie"}, {"id": "c", "text": "Przodomózgowie, śródmózgowie, tyłomózgowie"}, {"id": "d", "text": "Międzymózgowie, most, móżdżek"}, {"id": "e", "text": "Kresomózgowie, móżdżek, rdzeń przedłużony"}]'::jsonb,
   'a',
   $E$Z **trzech pęcherzyków pierwotnych** powstaje **pięć pęcherzyków wtórnych**: przodomózgowie dzieli się na **kresomózgowie** (telencephalon) i **międzymózgowie** (diencephalon); śródmózgowie pozostaje niepodzielone; tyłomózgowie dzieli się na **tyłomózgowie wtórne** (metencephalon → most i móżdżek) i **rdzeniomózgowie** (myelencephalon → rdzeń przedłużony). Pęcherzyki wtórne to: kresomózgowie, międzymózgowie, śródmózgowie, tyłomózgowie wtórne, rdzeniomózgowie.$E$,
   'rozwój mózgowia', 'ANATSTO-617'),
(10, 'ANA-NAC',
   'Na jakie naczynia dzieli się tętnica podstawna mózgu?',
   '[{"id": "a", "text": "Tętnice tylne mózgu (prawą i lewą)"}, {"id": "b", "text": "Tętnice środkowe mózgu"}, {"id": "c", "text": "Tętnice przednie mózgu"}, {"id": "d", "text": "Tętnice móżdżkowe dolne tylne"}, {"id": "e", "text": "Tętnice kręgowe"}]'::jsonb,
   'a',
   $E$**Tętnica podstawna** (a. basilaris) powstaje z połączenia obu **tętnic kręgowych** na granicy mostu i rdzenia przedłużonego. Biegnie po brzusznej powierzchni mostu i na jego górnym brzegu **dzieli się na dwie tętnice tylne mózgu** (aa. cerebri posteriores), które wchodzą w skład koła tętniczego Willisa. Po drodze oddaje tętnice móżdżkowe górne i dolne przednie oraz gałęzie do mostu. Tętnice środkowa i przednia mózgu pochodzą z t. szyjnej wewnętrznej.$E$,
   'tętnica podstawna', 'ANATSTO-618'),
(11, 'ANA-TRZ',
   'Co tworzy przewód żółciowy wspólny (wariant pytania)?',
   '[{"id": "a", "text": "Przewód wątrobowy prawy i przewód trzustkowy"}, {"id": "b", "text": "Przewód pęcherzykowy i przewód trzustkowy"}, {"id": "c", "text": "Przewód wątrobowy lewy i prawy"}, {"id": "d", "text": "Przewód pęcherzykowy i przewód wątrobowy prawy"}, {"id": "e", "text": "Żadna odpowiedź nie jest poprawna"}]'::jsonb,
   'e',
   $E$Przewód żółciowy wspólny powstaje z połączenia **przewodu wątrobowego wspólnego** z **przewodem pęcherzykowym**. Żadna z opcji A–D nie podaje tej prawidłowej pary: wymieniają błędne kombinacje (przewód trzustkowy łączy się dopiero później, tworząc bańkę wątrobowo-trzustkową; połączenie przewodów wątrobowych prawego i lewego daje przewód wątrobowy *wspólny*, nie żółciowy). Dlatego poprawna jest odpowiedź **E – żadna nie jest prawidłowa**.$E$,
   'drogi żółciowe', 'ANATSTO-619'),
(12, 'ANA-TRZ',
   'Przodozgięcie macicy (anteflexio) to kąt pomiędzy:',
   '[{"id": "a", "text": "Trzonem macicy a jej szyjką"}, {"id": "b", "text": "Szyjką macicy a osią pochwy"}, {"id": "c", "text": "Trzonem macicy a ścianą pęcherza"}, {"id": "d", "text": "Dnem macicy a jajowodem"}, {"id": "e", "text": "Osią macicy a płaszczyzną wchodu miednicy"}]'::jsonb,
   'a',
   $E$**Przodozgięcie (anteflexio)** to kąt zawarty **między trzonem a szyjką macicy** (osią trzonu i osią szyjki), otwarty ku przodowi, wynoszący ok. 120–170°. Należy odróżnić je od **przodopochylenia (anteversio)** — kąta między osią szyjki a osią pochwy. W prawidłowym ustawieniu macica jest jednocześnie w **anteversio-anteflexio (AVF)**. Odpowiedź B opisuje przodopochylenie, nie przodozgięcie. Tyłozgięcie (retroflexio) macicy, choć często prawidłowy wariant, może sprzyjać zaleganiu krwi miesiączkowej i bolesnym miesiączkom.$E$,
   'macica', 'ANATSTO-621'),
(13, 'ANA-TRZ',
   'Prawidłową kolejność odcinków jajowodu od macicy do jajnika przedstawia:',
   '[{"id": "a", "text": "Część maciczna, cieśń, bańka, lejek"}, {"id": "b", "text": "Lejek, bańka, cieśń, część maciczna"}, {"id": "c", "text": "Cieśń, część maciczna, bańka, lejek"}, {"id": "d", "text": "Część maciczna, bańka, cieśń, lejek"}, {"id": "e", "text": "Bańka, cieśń, lejek, część maciczna"}]'::jsonb,
   'a',
   $E$Jajowód od strony macicy ku jajnikowi dzieli się na: **część maciczną (śródścienną)** przebijającą ścianę macicy, **cieśń** (isthmus, najwęższa), **bańkę** (ampulla, najszersza i najdłuższa — miejsce zapłodnienia) oraz **lejek** (infundibulum) z **strzępkami** obejmującymi jajnik. Odpowiedź B podaje kolejność odwrotną (od jajnika do macicy). Bańka jest typowym miejscem ciąży ektopowej. Lejek z strzępkami (zwłaszcza strzępek jajnikowy) wychwytuje komórkę jajową po owulacji.$E$,
   'jajowód', 'ANATSTO-622'),
(14, 'ANA-TRZ',
   'Gdzie uchodzi przewód trzustkowy główny (Wirsunga)?',
   '[{"id": "a", "text": "Część odźwiernikowa żołądka"}, {"id": "b", "text": "Dwunastnica wstępująca"}, {"id": "c", "text": "Dwunastnica zstępująca"}, {"id": "d", "text": "Dwunastnica górna (opuszka)"}, {"id": "e", "text": "Dwunastnica pozioma"}]'::jsonb,
   'c',
   $E$**Przewód trzustkowy główny (Wirsunga)** łączy się z przewodem żółciowym wspólnym i uchodzi na **brodawce większej dwunastnicy (Vatera)** w **części zstępującej dwunastnicy**, na jej tylno-przyśrodkowej ścianie. Przewód trzustkowy dodatkowy (Santoriniego) uchodzi wyżej, na brodawce mniejszej, również w części zstępującej. Brodawkę otacza zwieracz bańki (Oddiego) regulujący wypływ żółci i soku trzustkowego.$E$,
   'trzustka', 'ANATSTO-623'),
(15, 'ANA-NER',
   'Droga słuchowa to droga:',
   '[{"id": "a", "text": "Jednoneuronowa"}, {"id": "b", "text": "Dwuneuronowa"}, {"id": "c", "text": "Trójneuronowa"}, {"id": "d", "text": "Czteroneuronowa"}, {"id": "e", "text": "Pięcioneuronowa"}]'::jsonb,
   'd',
   $E$**Droga słuchowa** jest klasycznie opisywana jako **czteroneuronowa**. Neuron I – w **zwoju spiralnym** ślimaka; neuron II – w **jądrach ślimakowych** (brzusznym i grzbietowym) w moście; neuron III – w **jądrze grzbietowym ciała czworobocznego/wstędze bocznej** lub we wzgórkach dolnych; neuron IV – w **ciele kolankowatym przyśrodkowym** wzgórza, skąd promienistość słuchowa biegnie do kory słuchowej (zakręty Heschla, pole 41/42). Droga jest częściowo skrzyżowana — stąd obustronna reprezentacja.$E$,
   'droga słuchowa', 'ANATSTO-624'),
(16, 'ANA-NER',
   'Jakie mięśnie unerwia ruchowo nerw dodatkowy (XI)?',
   '[{"id": "a", "text": "Mięsień mostkowo-obojczykowo-sutkowy i czworoboczny"}, {"id": "b", "text": "Mięsień żwacz i skroniowy"}, {"id": "c", "text": "Mięsień dwubrzuścowy i rylcowo-gnykowy"}, {"id": "d", "text": "Mięśnie podgnykowe"}, {"id": "e", "text": "Mięśnie pochyłe"}]'::jsonb,
   'a',
   $E$**Nerw dodatkowy (XI)** unerwia ruchowo dwa mięśnie: **mostkowo-obojczykowo-sutkowy (MOS)** i **czworoboczny (kapturowy)**. Jego część rdzeniowa pochodzi z motoneuronów rogów przednich C1–C5/6, wstępuje przez otwór wielki, by przez otwór szyjny opuścić czaszkę. Uszkodzenie XI daje opadanie barku, trudność w unoszeniu ramienia powyżej poziomu i osłabienie obracania głowy w stronę przeciwną. Pozostałe mięśnie głowy unerwiają inne nerwy czaszkowe.$E$,
   'nerw dodatkowy', 'ANATSTO-625'),
(17, 'ANA-OUN',
   'Za co odpowiada droga rdzeniowo-wzgórzowa boczna?',
   '[{"id": "a", "text": "Czucie bólu i temperatury"}, {"id": "b", "text": "Czucie dotyku różnicującego"}, {"id": "c", "text": "Czucie głębokie (propriocepcja)"}, {"id": "d", "text": "Czynność ruchową mięśni"}, {"id": "e", "text": "Czucie wibracji"}]'::jsonb,
   'a',
   $E$**Droga rdzeniowo-wzgórzowa boczna** przewodzi **czucie bólu i temperatury**. Neuron I leży w zwoju rdzeniowym, neuron II w rogu tylnym rdzenia — jego aksony **krzyżują się w spoidle przednim** (1–2 segmenty wyżej) i wstępują w sznurze bocznym, neuron III w jądrze brzuszno-tylno-bocznym wzgórza. Czucie dotyku różnicującego, wibracji i propriocepcji biegnie sznurami tylnymi. Droga przednia rdzeniowo-wzgórzowa przewodzi czucie dotyku prostego.$E$,
   'drogi czuciowe rdzenia', 'ANATSTO-626'),
(18, 'ANA-NAC',
   'Do jakiego trójkąta szyi należy nerw dodatkowy (XI)?',
   '[{"id": "a", "text": "Trójkąt tętnicy szyjnej"}, {"id": "b", "text": "Trójkąt łopatkowo-czworoboczny (potyliczny)"}, {"id": "c", "text": "Trójkąt podżuchwowy"}, {"id": "d", "text": "Trójkąt łopatkowo-tchawiczy"}, {"id": "e", "text": "Trójkąt podbródkowy"}]'::jsonb,
   'b',
   $E$**Nerw dodatkowy (XI)** przebiega w **trójkącie tylnym szyi**, konkretnie w jego górnej części – **trójkącie łopatkowo-czworobocznym (potylicznym)**, biegnąc skośnie od MOS do mięśnia czworobocznego. To istotne chirurgicznie miejsce – nerw leży tu powierzchownie i jest narażony na uszkodzenie przy biopsji węzłów chłonnych szyi. Trójkąt tętnicy szyjnej należy do trójkąta przedniego i zawiera m.in. tętnicę szyjną wewnętrzną i zewnętrzną.$E$,
   'trójkąty szyi', 'ANATSTO-627'),
(19, 'ANA-TRZ',
   'Gdzie jest zlokalizowane śródpiersie przednie?',
   '[{"id": "a", "text": "Między mostkiem a workiem osierdziowym"}, {"id": "b", "text": "Między osierdziem a kręgosłupem"}, {"id": "c", "text": "Między opłucnymi śródpiersiowymi"}, {"id": "d", "text": "Powyżej kąta mostka"}, {"id": "e", "text": "Między przeponą a wnęką płuc"}]'::jsonb,
   'a',
   $E$**Śródpiersie przednie** to wąska przestrzeń **między tylną powierzchnią mostka a przednią ścianą worka osierdziowego**, w obrębie śródpiersia dolnego. Zawiera tkankę łączną i tłuszczową, węzły chłonne przymostkowe, gałęzie naczyń piersiowych wewnętrznych oraz u dzieci dolny biegun **grasicy**. Śródpiersie środkowe mieści serce w osierdziu, a tylne — przełyk, aortę zstępującą, przewód piersiowy i nerwy błędne. B opisuje śródpiersie tylne.$E$,
   'śródpiersie', 'ANATSTO-628'),
(20, 'ANA-OUN',
   'Jak nazywa się część drogi piramidowej z włóknami biegnącymi do jąder nerwów czaszkowych?',
   '[{"id": "a", "text": "Droga korowo-rdzeniowa boczna"}, {"id": "b", "text": "Droga korowo-jądrowa"}, {"id": "c", "text": "Droga korowo-mostowa"}, {"id": "d", "text": "Droga rdzeniowo-móżdżkowa"}, {"id": "e", "text": "Droga czerwienno-rdzeniowa"}]'::jsonb,
   'b',
   $E$**Droga korowo-jądrowa (korowo-opuszkowa)** to część układu piramidowego, której włókna biegną od kory ruchowej do **jąder ruchowych nerwów czaszkowych** w pniu mózgu. Unerwia większość mięśni głowy i szyi obustronnie (wyjątek: dolna część twarzy i mięsień MOS/czworoboczny – jednostronnie). Droga korowo-rdzeniowa biegnie do motoneuronów rdzenia. Korowo-mostowa należy do układu pozapiramidowego (połączenia z móżdżkiem).$E$,
   'drogi piramidowe', 'ANATSTO-630'),
(21, 'ANA-OUN',
   'Jak nazywa się część drogi piramidowej biegnąca do rdzenia kręgowego?',
   '[{"id": "a", "text": "Droga korowo-rdzeniowa"}, {"id": "b", "text": "Droga korowo-jądrowa"}, {"id": "c", "text": "Droga rdzeniowo-wzgórzowa"}, {"id": "d", "text": "Droga przedsionkowo-rdzeniowa"}, {"id": "e", "text": "Droga oliwkowo-rdzeniowa"}]'::jsonb,
   'a',
   $E$**Droga korowo-rdzeniowa (tractus corticospinalis)** to główna droga ruchowa układu piramidowego, biegnąca od kory ruchowej do **motoneuronów rogów przednich rdzenia**. W rdzeniu przedłużonym ok. **80–90% włókien krzyżuje się** (skrzyżowanie piramid), tworząc drogę **korowo-rdzeniową boczną**; pozostałe biegną nieskrzyżowane jako droga **przednia**. Steruje precyzyjnymi ruchami dowolnymi, zwłaszcza dystalnych części kończyn. Korowo-jądrowa biegnie do nerwów czaszkowych.$E$,
   'drogi piramidowe', 'ANATSTO-631'),
(22, 'ANA-NAC',
   'Gdzie uchodzi przewód piersiowy?',
   '[{"id": "a", "text": "Lewy kąt żylny"}, {"id": "b", "text": "Prawy kąt żylny"}, {"id": "c", "text": "Żyła główna górna"}, {"id": "d", "text": "Żyła nieparzysta"}, {"id": "e", "text": "Prawa żyła ramienno-głowowa"}]'::jsonb,
   'a',
   $E$**Przewód piersiowy (ductus thoracicus)** to największe naczynie chłonne ciała. Zaczyna się od **zbiornika mleczu (cisterna chyli)** na wysokości L1–L2, wstępuje przez rozwór aortowy przepony i uchodzi do **lewego kąta żylnego** (połączenie lewej żyły szyjnej wewnętrznej i podobojczykowej). Drenuje chłonkę z całego ciała poza prawym górnym kwadrantem, który odprowadza **przewód chłonny prawy** do prawego kąta żylnego.$E$,
   'przewód piersiowy', 'ANATSTO-632'),
(23, 'ANA-JAM',
   'Jaki nerw unerwia czuciowo (czucie ogólne) tylną 1/3 języka?',
   '[{"id": "a", "text": "Nerw twarzowy (VII)"}, {"id": "b", "text": "Nerw językowo-gardłowy (IX)"}, {"id": "c", "text": "Nerw żuchwowy (V3)"}, {"id": "d", "text": "Nerw szczękowy (V2)"}, {"id": "e", "text": "Nerw błędny (X)"}]'::jsonb,
   'b',
   $E$**Czucie ogólne i smakowe tylnej 1/3 języka** zapewnia **nerw językowo-gardłowy (IX)**. Przednie 2/3 unerwia czuciowo nerw językowy (gałąź V3), a smakowo struna bębenkowa (VII). Najbardziej tylny fragment nasady języka i nagłośni — nerw błędny (X). Granicą jest bruzda graniczna (V-kształtna) z otworem ślepym. IX odpowiada więc równocześnie za czucie ogólne i smak w tylnej części. Nerw IX bierze też udział w odruchu gardłowym (ramię czuciowe) i unerwia błonę śluzową gardła oraz migdałka.$E$,
   'unerwienie języka', 'ANATSTO-633'),
(24, 'ANA-JAM',
   'Jaki nerw unerwia czuciowo (czucie ogólne) przednie 2/3 języka?',
   '[{"id": "a", "text": "Nerw żuchwowy (V3) – przez nerw językowy"}, {"id": "b", "text": "Nerw językowo-gardłowy (IX)"}, {"id": "c", "text": "Nerw twarzowy (VII)"}, {"id": "d", "text": "Nerw szczękowy (V2)"}, {"id": "e", "text": "Nerw błędny (X)"}]'::jsonb,
   'a',
   $E$**Czucie ogólne przednich 2/3 języka** zapewnia **nerw językowy** – gałąź **nerwu żuchwowego (V3)**, trzeciej gałęzi nerwu trójdzielnego. Czucie **smakowe** tej samej okolicy przewodzi natomiast **struna bębenkowa** (gałąź VII), która dołącza do nerwu językowego. To klasyczne rozróżnienie: V3 – czucie ogólne, VII – smak (przednie 2/3); IX – czucie ogólne i smak (tylna 1/3). Tylny fragment nasady — X.$E$,
   'unerwienie języka', 'ANATSTO-634'),
(25, 'ANA-JAM',
   'Jaki nerw odpowiada za unerwienie smakowe przednich 2/3 języka?',
   '[{"id": "a", "text": "Struna bębenkowa (gałąź nerwu twarzowego VII)"}, {"id": "b", "text": "Nerw językowo-gardłowy (IX)"}, {"id": "c", "text": "Nerw błędny (X)"}, {"id": "d", "text": "Nerw żuchwowy (V3)"}, {"id": "e", "text": "Nerw szczękowy (V2)"}]'::jsonb,
   'a',
   $E$**Smak przednich 2/3 języka** przewodzi **struna bębenkowa (chorda tympani)** – gałąź **nerwu twarzowego (VII)**. Włókna smakowe biegną z kubków smakowych przez nerw językowy, następnie odłączają się jako struna bębenkowa, przechodzą przez jamę bębenkową i docierają do zwoju kolanka VII, a dalej do jądra pasma samotnego. Czucie *ogólne* tej okolicy przewodzi nerw językowy (V3). Smak tylnej 1/3 — nerw IX.$E$,
   'unerwienie smakowe języka', 'ANATSTO-635'),
(26, 'ANA-JAM',
   'Jaki nerw odpowiada za unerwienie smakowe tylnej 1/3 języka?',
   '[{"id": "a", "text": "Nerw twarzowy (VII)"}, {"id": "b", "text": "Nerw żuchwowy (V3)"}, {"id": "c", "text": "Nerw językowo-gardłowy (IX)"}, {"id": "d", "text": "Nerw szczękowy (V2)"}, {"id": "e", "text": "Nerw bloczkowy (IV)"}]'::jsonb,
   'c',
   $E$**Smak tylnej 1/3 języka** przewodzi **nerw językowo-gardłowy (IX)**, który w tym obszarze odpowiada zarówno za czucie ogólne, jak i smakowe. Włókna smakowe docierają do jądra pasma samotnego w rdzeniu przedłużonym. Przednie 2/3 — smak przez strunę bębenkową (VII). Najbardziej tylna okolica nasady języka i nagłośni — nerw błędny (X). Brodawki okolone leżące wzdłuż bruzdy granicznej są szczególnie bogate w kubki smakowe IX.$E$,
   'unerwienie smakowe języka', 'ANATSTO-636'),
(27, 'ANA-TRZ',
   'Gałęzie trzewne parzyste aorty brzusznej to:',
   '[{"id": "a", "text": "Tętnice lędźwiowe"}, {"id": "b", "text": "Tętnice nadnerczowe środkowe, nerkowe i jądrowe/jajnikowe"}, {"id": "c", "text": "Pień trzewny"}, {"id": "d", "text": "Tętnica krezkowa górna"}, {"id": "e", "text": "Tętnica krezkowa dolna"}]'::jsonb,
   'b',
   $E$**Gałęzie trzewne parzyste** aorty brzusznej to: **tętnice nadnerczowe środkowe**, **tętnice nerkowe** oraz **tętnice jądrowe (u mężczyzn) / jajnikowe (u kobiet)**. Gałęzie trzewne **nieparzyste** to pień trzewny, tętnica krezkowa górna i dolna. Gałęzie **ścienne (parzyste)** to t. przeponowe dolne i lędźwiowe. Pierwotne pytanie miało jako klucz „nadnerczowa środkowa" — to prawidłowa parzysta gałąź trzewna, ujęta tu w pełnej grupie.$E$,
   'aorta brzuszna', 'ANATSTO-637'),
(28, 'ANA-OUN',
   'Dno komory III układu komorowego mózgu tworzy:',
   '[{"id": "a", "text": "Bruzda podstawna mostu"}, {"id": "b", "text": "Spoidło przednie"}, {"id": "c", "text": "Istota szara podwzgórza (i część niskowzgórza)"}, {"id": "d", "text": "Spoidło wielkie (ciało modzelowate)"}, {"id": "e", "text": "Sklepienie"}]'::jsonb,
   'c',
   $E$**Dno komory III** tworzą struktury **podwzgórza** (istota szara podwzgórza) oraz część niskowzgórza – m.in. **skrzyżowanie wzrokowe, guz popielaty z lejkiem, ciała suteczkowate**. **Ściany boczne** tworzy wzgórze i podwzgórze, **strop** – splot naczyniówkowy i blaszka przyczepu, **ścianę przednią** – spoidło przednie i blaszka krańcowa. Komora III łączy się z bocznymi przez otwory międzykomorowe (Monroe), a z IV przez wodociąg mózgu.$E$,
   'komora trzecia', 'ANATSTO-638'),
(29, 'ANA-NAC',
   'Z czego tworzy się tętnica podstawna?',
   '[{"id": "a", "text": "Z tętnic kręgowych"}, {"id": "b", "text": "Z tętnic szyjnych wewnętrznych"}, {"id": "c", "text": "Z tętnic tylnych mózgu"}, {"id": "d", "text": "Z tętnic móżdżkowych górnych"}, {"id": "e", "text": "Z tętnic szyjnych wspólnych"}]'::jsonb,
   'a',
   $E$**Tętnica podstawna (a. basilaris)** powstaje z połączenia obu **tętnic kręgowych** na granicy rdzenia przedłużonego i mostu. Tętnice kręgowe odchodzą od tętnic podobojczykowych. Tętnica podstawna biegnie w bruździe podstawnej mostu i dzieli się na dwie tętnice tylne mózgu. Wchodzi w skład **układu kręgowo-podstawnego** zaopatrującego tylną część mózgowia, pień i móżdżek, łącząc się z układem szyjnym w kole Willisa przez tętnice łączące tylne.$E$,
   'tętnica podstawna', 'ANATSTO-641'),
(30, 'ANA-TUL',
   'Jaki jest główny kierunek odpływu chłonki z sutka?',
   '[{"id": "a", "text": "Węzły pachowe"}, {"id": "b", "text": "Węzły przymostkowe"}, {"id": "c", "text": "Węzły nadobojczykowe"}, {"id": "d", "text": "Węzły międzypiersiowe"}, {"id": "e", "text": "Węzły śródpiersiowe przednie"}]'::jsonb,
   'a',
   $E$**Główny kierunek odpływu chłonki z sutka** (ok. 75%) prowadzi do **węzłów chłonnych pachowych**, zwłaszcza grupy piersiowej (przedniej). Pozostała chłonka spływa do węzłów **przymostkowych** (część przyśrodkowa sutka) oraz drogami międzyżebrowymi. Ma to kluczowe znaczenie w **raku piersi** – węzły pachowe są pierwszą stacją przerzutów i podstawą oceny węzła wartowniczego. Spływ przymostkowy umożliwia szerzenie przerzutów do drugiej piersi i śródpiersia.$E$,
   'chłonka sutka', 'ANATSTO-643'),
(31, 'ANA-TRZ',
   'Co biegnie razem z przełykiem przez rozwór przełykowy przepony?',
   '[{"id": "a", "text": "Nerwy błędne (pnie błędne przedni i tylny)"}, {"id": "b", "text": "Przewód piersiowy"}, {"id": "c", "text": "Aorta zstępująca"}, {"id": "d", "text": "Żyła główna dolna"}, {"id": "e", "text": "Pień współczulny"}]'::jsonb,
   'a',
   $E$Przez **rozwór przełykowy (hiatus oesophageus)**, na wysokości **Th10**, przechodzą **przełyk** oraz towarzyszące mu **pnie nerwów błędnych** – przedni (głównie z lewego X) i tylny (z prawego X). Rozwór aortowy (Th12) przepuszcza aortę i przewód piersiowy, a otwór żyły głównej dolnej (Th8) – żyłę główną dolną i gałąź nerwu przeponowego. Mnemonik wysokości: **8, 10, 12 – VC, eXophagus (X), Aorta**.$E$,
   'rozwór przełykowy przepony', 'ANATSTO-645'),
(32, 'ANA-TRZ',
   'Przebieg nerwów błędnych w śródpiersiu charakteryzuje się tym, że:',
   '[{"id": "a", "text": "Biegną do tyłu od korzeni płuc, tworząc sploty płucne"}, {"id": "b", "text": "Biegną do przodu od korzeni płuc"}, {"id": "c", "text": "Przebijają przeponę przez rozwór aortowy"}, {"id": "d", "text": "Oddają nerwy przeponowe"}, {"id": "e", "text": "Biegną w worku osierdziowym"}]'::jsonb,
   'a',
   $E$W śródpiersiu nerwy błędne biegną **ku tyłowi od korzeni płuc**, w odróżnieniu od **nerwów przeponowych**, które biegną **ku przodowi** od korzeni płuc (mnemonik: „**VAPD** – Vagus Behind, Phrenic in Front"). Na korzeniach płuc nerwy X tworzą **sploty płucne**, niżej **sploty przełykowe**, by jako pnie błędne przedni i tylny przejść przez rozwór przełykowy. Pierwotny plik nie miał klucza – ustalono na podstawie wiedzy.$E$,
   'nerwy błędne w śródpiersiu', 'ANATSTO-646'),
(33, 'ANA-NER',
   'Jaki nerw unerwia ruchowo przedni brzusiec mięśnia dwubrzuścowego?',
   '[{"id": "a", "text": "Nerw twarzowy (VII)"}, {"id": "b", "text": "Nerw językowo-gardłowy (IX)"}, {"id": "c", "text": "Nerw żuchwowy (V3 – nerw żuchwowo-gnykowy)"}, {"id": "d", "text": "Nerw podjęzykowy (XII)"}, {"id": "e", "text": "Pętla szyjna"}]'::jsonb,
   'c',
   $E$**Przedni brzusiec mięśnia dwubrzuścowego** unerwia **nerw żuchwowo-gnykowy**, gałąź **nerwu żuchwowego (V3)** z nerwu trójdzielnego – pochodna I łuku skrzelowego. **Tylny brzusiec** unerwia nerw twarzowy (VII) – pochodna II łuku. Nerw żuchwowo-gnykowy unerwia także mięsień żuchwowo-gnykowy. To powtórzenie zagadnienia z innego pytania zestawu – odzwierciedla dwułukowe pochodzenie mięśnia dwubrzuścowego.$E$,
   'mięsień dwubrzuścowy', 'ANATSTO-647'),
(34, 'ANA-NER',
   'Do obszaru unerwienia czuciowego nerwu ocznego (V1) należy:',
   '[{"id": "a", "text": "Powieka górna"}, {"id": "b", "text": "Powieka dolna"}, {"id": "c", "text": "Powieka górna i dolna"}, {"id": "d", "text": "Warga górna"}, {"id": "e", "text": "Skóra policzka"}]'::jsonb,
   'a',
   $E$**Nerw oczny (V1)** – pierwsza, czysto czuciowa gałąź nerwu trójdzielnego – unerwia **powiekę górną**, czoło, skórę nosa, gałkę oczną, spojówkę górną i błonę śluzową zatok czołowej i sitowych. **Powiekę dolną** i skórę policzka unerwia **nerw szczękowy (V2)**. Mnemonik zakresów trójdzielnego: V1 – czoło i oko, V2 – środkowe piętro twarzy, V3 – żuchwa. V1 wchodzi do oczodołu przez szczelinę oczodołową górną.$E$,
   'nerw oczny (V1)', 'ANATSTO-648'),
(35, 'ANA-OUN',
   'Strop komory III tworzą kolejno (od dołu):',
   '[{"id": "a", "text": "Splot naczyniówkowy, spoidło uzdeczek, szyszynka"}, {"id": "b", "text": "Spoidło przednie, blaszka krańcowa, sklepienie"}, {"id": "c", "text": "Wzgórze, podwzgórze, niskowzgórze"}, {"id": "d", "text": "Ciało modzelowate, przegroda przezroczysta"}, {"id": "e", "text": "Guz popielaty, lejek, ciała suteczkowate"}]'::jsonb,
   'a',
   $E$**Strop komory III** tworzą struktury okolicy nadwzgórza i splotu: **splot naczyniówkowy** komory III (z blaszką naczyniówkową i przyczepem), a w tylnej części okolica **spoidła uzdeczek** i **szyszynki (zachyłek szyszynkowy)**. Dno tworzy podwzgórze (guz popielaty, lejek, ciała suteczkowate – opcja E), ściany boczne – wzgórze i podwzgórze. Ściana przednia obejmuje spoidło przednie i blaszkę krańcową.$E$,
   'komora trzecia', 'ANATSTO-649'),
(36, 'ANA-KON',
   'Które głowy mięśnia trójgłowego ramienia działają na staw ramienny, a które tylko na łokciowy?',
   '[{"id": "a", "text": "Wszystkie trzy głowy działają tylko na staw łokciowy"}, {"id": "b", "text": "Głowa długa działa też na staw ramienny, wszystkie trzy na łokciowy"}, {"id": "c", "text": "Tylko głowa przyśrodkowa działa na staw ramienny"}, {"id": "d", "text": "Głowy boczna i przyśrodkowa działają na staw ramienny"}, {"id": "e", "text": "Głowa długa działa tylko na staw ramienny"}]'::jsonb,
   'b',
   $E$Mięsień **trójgłowy ramienia** prostuje przedramię w **stawie łokciowym wszystkimi trzema głowami** (długa, boczna, przyśrodkowa). Dodatkowo **głowa długa**, przyczepiająca się proksymalnie do **guzka podpanewkowego łopatki** (a nie do kości ramiennej), działa również na **staw ramienny** – pomaga w przywodzeniu i prostowaniu ramienia oraz stabilizuje staw. Głowy boczna i przyśrodkowa zaczynają się na kości ramiennej, więc działają tylko na łokieć.$E$,
   'mięsień trójgłowy ramienia', 'ANATSTO-650'),
(37, 'ANA-KON',
   'Troczek zginaczy w stosunku do kanału nadgarstka:',
   '[{"id": "a", "text": "Zamyka kanał nadgarstka od przodu (od strony dłoniowej)"}, {"id": "b", "text": "Zamyka kanał nadgarstka od tyłu"}, {"id": "c", "text": "Stanowi dno kanału nadgarstka"}, {"id": "d", "text": "Nie ma związku z kanałem nadgarstka"}, {"id": "e", "text": "Przyczepia się tylko do kości łódeczkowatej"}]'::jsonb,
   'a',
   $E$**Troczek zginaczy (retinaculum flexorum)** to silne pasmo łącznotkankowe **zamykające kanał nadgarstka od przodu (strony dłoniowej)**, rozpięte między czterema kośćmi: przyśrodkowo – kość grochowata i haczyk kości haczykowatej, bocznie – guzek kości łódeczkowatej i czworobocznej większej. **Dno i ściany** kanału tworzą kości nadgarstka. Przez kanał biegną **nerw pośrodkowy** i ścięgna zginaczy – ucisk nerwu daje zespół cieśni nadgarstka. Pierwotny plik bez klucza – ustalono z wiedzy.$E$,
   'kanał nadgarstka', 'ANATSTO-651'),
(38, 'ANA-KON',
   'Nerw pośrodkowy unerwia czuciowo skórę dłoniowej powierzchni:',
   '[{"id": "a", "text": "3,5 palca od strony promieniowej (kciuk, wskaziciel, środkowy, połowa serdecznego)"}, {"id": "b", "text": "2,5 palca od strony łokciowej"}, {"id": "c", "text": "Wszystkich pięciu palców"}, {"id": "d", "text": "Tylko kciuka"}, {"id": "e", "text": "1,5 palca od strony łokciowej"}]'::jsonb,
   'a',
   $E$**Nerw pośrodkowy** unerwia czuciowo dłoniową powierzchnię skóry **3,5 palca od strony promieniowej**: kciuk, palec wskazujący, środkowy oraz promieniową połowę palca serdecznego, wraz z odpowiadającą częścią dłoni. **Nerw łokciowy** unerwia **1,5 palca od strony łokciowej** (mały i łokciowa połowa serdecznego). Nerw promieniowy zaopatruje skórę grzbietu ręki po stronie promieniowej. Pierwotny plik bez klucza – ustalono z wiedzy.$E$,
   'unerwienie czuciowe ręki', 'ANATSTO-652'),
(39, 'ANA-OBW',
   'Przy porażeniu jakiego nerwu nie da się wykonać czynnego prostowania w stawie kolanowym?',
   '[{"id": "a", "text": "Nerwu udowego"}, {"id": "b", "text": "Nerwu sromowego"}, {"id": "c", "text": "Nerwu kulszowego"}, {"id": "d", "text": "Nerwu zasłonowego"}, {"id": "e", "text": "Nerwu pośladkowego górnego"}]'::jsonb,
   'a',
   $E$**Nerw udowy (L2–L4)** unerwia **mięsień czworogłowy uda** – główny i jedyny prostownik stawu kolanowego. Jego porażenie znosi czynne **prostowanie kolana** oraz osłabia zginanie biodra, a także daje zniesienie odruchu kolanowego i zaburzenia czucia na przedniej powierzchni uda i przyśrodkowej goleni (nerw udowo-goleniowy). Nerw zasłonowy unerwia przywodziciele, kulszowy – tylną grupę uda i podudzie, sromowy – krocze.$E$,
   'nerw udowy', 'ANATSTO-653'),
(40, 'ANA-OBW',
   'Dodatni objaw Trendelenburga występuje w porażeniu:',
   '[{"id": "a", "text": "Nerwu kulszowego"}, {"id": "b", "text": "Mięśnia pośladkowego średniego (porażenie nerwu pośladkowego górnego)"}, {"id": "c", "text": "Mięśnia dwugłowego uda"}, {"id": "d", "text": "Mięśnia krawieckiego"}, {"id": "e", "text": "Mięśnia czworogłowego uda"}]'::jsonb,
   'b',
   $E$**Objaw Trendelenburga** wynika z niewydolności **mięśni pośladkowych średniego i małego**, unerwionych przez **nerw pośladkowy górny (L4–S1)**. Mięśnie te stabilizują miednicę przy staniu na jednej nodze. Przy ich porażeniu w czasie obciążenia chorej kończyny **miednica opada po stronie przeciwnej (zdrowej)**. Obustronne osłabienie daje charakterystyczny **chód kaczkowaty**. Nerw pośladkowy górny ulega uszkodzeniu m.in. przy nieprawidłowych iniekcjach domięśniowych.$E$,
   'objaw Trendelenburga', 'ANATSTO-654'),
(41, 'ANA-OUN',
   'Rogi tylne rdzenia kręgowego to rogi:',
   '[{"id": "a", "text": "Ruchowe"}, {"id": "b", "text": "Czuciowe"}, {"id": "c", "text": "Mieszane"}, {"id": "d", "text": "Zawierające wyłącznie motoneurony"}, {"id": "e", "text": "Wegetatywne współczulne"}]'::jsonb,
   'b',
   $E$**Rogi tylne** rdzenia kręgowego mają charakter **czuciowy** – zawierają neurony II rzędu odbierające impulsy czuciowe z ciała (ból, temperatura, dotyk), przekazywane przez neurony zwojów rdzeniowych. **Rogi przednie** są ruchowe (motoneurony α i γ do mięśni szkieletowych). **Rogi boczne** (Th1–L2/3 i S2–S4) zawierają neurony układu autonomicznego. W rogu tylnym wyróżnia się m.in. istotę galaretowatą Rolanda – ważną w modulacji bólu.$E$,
   'rdzeń kręgowy', 'ANATSTO-655'),
(42, 'ANA-NER',
   'Nerwy węchowe (I) wchodzą do jamy czaszki przez:',
   '[{"id": "a", "text": "Blaszkę sitową kości sitowej (dół przedni czaszki)"}, {"id": "b", "text": "Otwór owalny (dół środkowy czaszki)"}, {"id": "c", "text": "Otwór wielki (dół tylny czaszki)"}, {"id": "d", "text": "Szczelinę oczodołową górną"}, {"id": "e", "text": "Kanał wzrokowy"}]'::jsonb,
   'a',
   $E$**Nici węchowe (nerw I)** przechodzą z błony śluzowej węchowej jamy nosowej przez liczne otworki **blaszki sitowej kości sitowej**, docierając do **opuszki węchowej** w **dole przednim czaszki**. To najkrótszy nerw czaszkowy i jedyny niemający osłonki Schwanna – jest pochodną OUN. **Złamania blaszki sitowej** mogą uszkodzić włókna węchowe (anozmia) i powodować wyciek płynu mózgowo-rdzeniowego z nosa. Otwór owalny przepuszcza V3.$E$,
   'nerw węchowy', 'ANATSTO-657'),
(43, 'ANA-JAM',
   'Przewód ślinianki podżuchwowej (Whartona) uchodzi:',
   '[{"id": "a", "text": "Na mięsku podjęzykowym"}, {"id": "b", "text": "W przedsionku jamy ustnej naprzeciw drugiego górnego trzonowca"}, {"id": "c", "text": "Na powierzchni grzbietowej języka"}, {"id": "d", "text": "W okolicy migdałka podniebiennego"}, {"id": "e", "text": "Na podniebieniu twardym"}]'::jsonb,
   'a',
   $E$**Przewód ślinianki podżuchwowej (przewód Whartona)** uchodzi na **mięsku podjęzykowym (caruncula sublingualis)** – małym uwypukleniu dna jamy ustnej po obu stronach **wędzidełka języka**. Przewód krzyżuje od dołu nerw językowy. To częste miejsce **kamicy ślinowej** (sialolithiasis) z powodu wstępującego, długiego przebiegu przewodu. Przewód ślinianki przyusznej (Stenona) uchodzi w przedsionku naprzeciw 2. górnego trzonowca.$E$,
   'ślinianka podżuchwowa', 'ANATSTO-658'),
(44, 'ANA-NER',
   'Gdzie znajduje się jądro ruchowe nerwu twarzowego (VII)?',
   '[{"id": "a", "text": "W moście (nakrywka mostu)"}, {"id": "b", "text": "W śródmózgowiu"}, {"id": "c", "text": "W rdzeniu przedłużonym"}, {"id": "d", "text": "W międzymózgowiu"}, {"id": "e", "text": "W rdzeniu kręgowym"}]'::jsonb,
   'a',
   $E$**Jądro ruchowe nerwu twarzowego** leży w **nakrywce mostu**. Włókna ruchowe tworzą charakterystyczne **kolano wewnętrzne** okrążając jądro nerwu odwodzącego (VI), co tworzy **wzgórek twarzowy** na dnie komory IV. Nerw VII unerwia mięśnie mimiczne. Górna część jądra (czoło) otrzymuje unerwienie korowo-jądrowe obustronne, dolna (dolna część twarzy) – tylko z przeciwległej półkuli, co różnicuje porażenie ośrodkowe i obwodowe. Plik bez klucza – ustalono z wiedzy.$E$,
   'jądro ruchowe nerwu twarzowego', 'ANATSTO-660'),
(45, 'ANA-NAC',
   'Nieparzystym naczyniem tętniczym mózgu jest:',
   '[{"id": "a", "text": "Tętnica podstawna"}, {"id": "b", "text": "Tętnica tylna mózgu"}, {"id": "c", "text": "Tętnica środkowa mózgu"}, {"id": "d", "text": "Tętnica kręgowa"}, {"id": "e", "text": "Tętnica łącząca tylna"}]'::jsonb,
   'a',
   $E$**Tętnica podstawna** jest jedynym **nieparzystym** dużym naczyniem tętniczym mózgowia – powstaje z połączenia dwóch parzystych tętnic kręgowych i biegnie pojedynczo w linii pośrodkowej po brzusznej stronie mostu. Pozostałe wymienione tętnice (tylna, środkowa, przednia mózgu, kręgowe, łączące tylne) występują parzyście. W kole Willisa nieparzysta jest jeszcze tętnica łącząca przednia, łącząca obie tętnice przednie mózgu.$E$,
   'tętnice mózgu', 'ANATSTO-661'),
(46, 'ANA-TRZ',
   'Dwunastnica jest unaczyniona przez gałęzie:',
   '[{"id": "a", "text": "Pnia trzewnego i tętnicy krezkowej górnej"}, {"id": "b", "text": "Wyłącznie tętnicy krezkowej dolnej"}, {"id": "c", "text": "Wyłącznie pnia trzewnego"}, {"id": "d", "text": "Tętnicy krezkowej górnej i dolnej"}, {"id": "e", "text": "Tętnic nerkowych"}]'::jsonb,
   'a',
   $E$Dwunastnica leży na **granicy unaczynienia jelita przedniego i środkowego**, dlatego zaopatrują ją gałęzie obu pni: z **pnia trzewnego** – tętnica trzustkowo-dwunastnicza górna (przez tętnicę żołądkowo-dwunastniczą), z **tętnicy krezkowej górnej** – tętnica trzustkowo-dwunastnicza dolna. Tworzą one **zespolenia (arkady)** wokół głowy trzustki. Granica obu obszarów leży na wysokości brodawki większej dwunastnicy.$E$,
   'unaczynienie dwunastnicy', 'ANATSTO-662'),
(47, 'ANA-NER',
   'Porażenie nerwu okoruchowego (III) objawia się:',
   '[{"id": "a", "text": "Opadnięciem powieki, zezem rozbieżnym i poszerzeniem źrenicy"}, {"id": "b", "text": "Zezem zbieżnym i zwężeniem źrenicy"}, {"id": "c", "text": "Wytrzeszczem oka"}, {"id": "d", "text": "Brakiem odruchu rogówkowego"}, {"id": "e", "text": "Porażeniem mięśni mimicznych"}]'::jsonb,
   'a',
   $E$**Porażenie nerwu okoruchowego (III)** daje triadę: **opadnięcie powieki górnej (ptosis)** – porażenie dźwigacza powieki, **zez rozbieżny** (oko ustawione „w dół i na zewnątrz" – przewaga mięśnia prostego bocznego VI i skośnego górnego IV), oraz **poszerzenie źrenicy (mydriasis)** z brakiem reakcji na światło – porażenie włókien przywspółczulnych do zwieracza źrenicy. Występuje też podwójne widzenie. Włókna przywspółczulne leżą powierzchownie – ucisk uszkadza je wcześnie.$E$,
   'porażenie nerwu okoruchowego', 'ANATSTO-663'),
(48, 'ANA-TRZ',
   'Jakie jest położenie esicy względem otrzewnej?',
   '[{"id": "a", "text": "Wewnątrzotrzewnowe (posiada krezkę)"}, {"id": "b", "text": "Zewnątrzotrzewnowe"}, {"id": "c", "text": "Pozaotrzewnowe pierwotnie"}, {"id": "d", "text": "Pozaotrzewnowe wtórnie"}, {"id": "e", "text": "Podotrzewnowe"}]'::jsonb,
   'a',
   $E$**Esica (okrężnica esowata)** leży **wewnątrzotrzewnowo** – posiada własną **krezkę esicy (mesocolon sigmoideum)**, co zapewnia jej dużą ruchomość. Ta ruchomość predysponuje do **skrętu esicy (volvulus)**. Wewnątrzotrzewnowo leżą też m.in. żołądek, jelito cienkie, kątnica, okrężnica poprzeczna, śledziona. Pozaotrzewnowo (wtórnie) leżą okrężnica wstępująca i zstępująca oraz dwunastnica (poza opuszką).$E$,
   'stosunek do otrzewnej', 'ANATSTO-664'),
(49, 'ANA-TRZ',
   'Mięśniówka komór i przedsionków serca:',
   '[{"id": "a", "text": "Tworzy ciągłą warstwę bezpośrednio połączoną mięśniowo"}, {"id": "b", "text": "Jest oddzielona szkieletem włóknistym, a czynnościowo łączy je pęczek przedsionkowo-komorowy (Hisa)"}, {"id": "c", "text": "Jest zawsze trójwarstwowa w obu jamach"}, {"id": "d", "text": "Łączy się przez węzeł zatokowo-przedsionkowy"}, {"id": "e", "text": "Jest połączona wyłącznie przez włókna Purkinjego"}]'::jsonb,
   'b',
   $E$Mięśniówka przedsionków i komór jest **rozdzielona elektrycznie i mechanicznie szkieletem włóknistym serca** (pierścienie włókniste zastawek). Jedynym fizjologicznym połączeniem przewodzącym jest **pęczek przedsionkowo-komorowy (Hisa)** odchodzący od węzła AV. Zapewnia to opóźnienie i uporządkowane przewodzenie pobudzenia z przedsionków na komory. Włókna Purkinjego rozprowadzają impuls już w obrębie komór. Mięśniówka przedsionków jest cieńsza (2-warstwowa), komór grubsza (3-warstwowa).$E$,
   'układ przewodzący serca', 'ANATSTO-665'),
(50, 'ANA-TRZ',
   'Krążenie oboczne w okolicy odbytnicy prowadzi krew z układu wrotnego do układu żyły głównej dolnej przez:',
   '[{"id": "a", "text": "Żyły odbytnicze środkowe i dolne (do żył biodrowych wewnętrznych)"}, {"id": "b", "text": "Żyłę nieparzystą"}, {"id": "c", "text": "Żyły przełykowe"}, {"id": "d", "text": "Żyły przyodbytnicze do żyły wrotnej tylko"}, {"id": "e", "text": "Żyły nerkowe"}]'::jsonb,
   'a',
   $E$W okolicy odbytnicy istnieje ważne **zespolenie wrotno-układowe**: **żyła odbytnicza górna** (układ wrotny, przez żyłę krezkową dolną) zespala się z **żyłami odbytniczymi środkową i dolną** (układ systemowy, przez żyły biodrowe wewnętrzne do żyły głównej dolnej). W **nadciśnieniu wrotnym** zespolenie to się poszerza, dając **żylaki odbytu (hemoroidy)**. Inne zespolenia: przełykowe (żylaki przełyku), okołopępkowe (caput medusae) i pozaotrzewnowe.$E$,
   'krążenie oboczne (zespolenia wrotno-układowe)', 'ANATSTO-666'),
(51, 'ANA-OUN',
   'Blaszka (przegroda) przezroczysta ogranicza komorę boczną:',
   '[{"id": "a", "text": "Róg przedni (część przednią) od strony przyśrodkowej"}, {"id": "b", "text": "Róg tylny od strony bocznej"}, {"id": "c", "text": "Róg dolny od dołu"}, {"id": "d", "text": "Część środkową od góry"}, {"id": "e", "text": "Trzon od strony bocznej"}]'::jsonb,
   'a',
   $E$**Przegroda (blaszka) przezroczysta (septum pellucidum)** to cienka, podwójna blaszka rozpięta między ciałem modzelowatym a sklepieniem, stanowiąca **przyśrodkową ścianę rogu przedniego (czołowego)** komory bocznej. Oddziela rogi przednie obu komór. Ścianę boczną i dno rogu przedniego tworzy głowa jądra ogoniastego, strop – ciało modzelowate. Między blaszkami może występować jama przegrody przezroczystej (cavum septi pellucidi).$E$,
   'komory boczne', 'ANATSTO-667'),
(52, 'ANA-OBW',
   'Nerw potyliczny mniejszy ma charakter:',
   '[{"id": "a", "text": "Czuciowy"}, {"id": "b", "text": "Ruchowy"}, {"id": "c", "text": "Mieszany"}, {"id": "d", "text": "Wyłącznie autonomiczny (współczulny)"}, {"id": "e", "text": "Przywspółczulny"}]'::jsonb,
   'a',
   $E$**Nerw potyliczny mniejszy (C2–C3)** to **czuciowa** gałąź skórna **splotu szyjnego**. Unerwia skórę bocznej części potylicy i okolicy zausznej, biegnąc wzdłuż tylnego brzegu mięśnia MOS. Pozostałe czuciowe gałęzie skórne splotu szyjnego to nerw uszny wielki, poprzeczny szyi i nerwy nadobojczykowe – wszystkie wychodzą w **punkcie nerwowym (punkcie Erba)** na tylnym brzegu MOS. Gałęzie ruchowe splotu szyjnego tworzą pętlę szyjną.$E$,
   'nerw potyliczny mniejszy', 'ANATSTO-668'),
(53, 'ANA-NAC',
   'Dolną część błony włóknisto-sprężystej krtani stanowi:',
   '[{"id": "a", "text": "Stożek sprężysty"}, {"id": "b", "text": "Błona czworokątna"}, {"id": "c", "text": "Więzadło pierścienno-tarczowe pośrodkowe wyłącznie"}, {"id": "d", "text": "Błona tarczowo-gnykowa"}, {"id": "e", "text": "Więzadło językowo-nagłośniowe"}]'::jsonb,
   'a',
   $E$**Błona włóknisto-sprężysta krtani** dzieli się na dwie części. **Część górna** to **błona czworokątna** – jej dolny brzeg tworzy więzadło przedsionkowe (fałd rzekomy). **Część dolna** to **stożek sprężysty (membrana cricovocalis)** – jego górny wolny brzeg tworzy **więzadła głosowe** (fałdy prawdziwe), a pośrodku z przodu pogrubia się jako więzadło pierścienno-tarczowe pośrodkowe (miejsce konikotomii). Stożek rozpięty jest między chrząstką pierścieniowatą a głosowymi.$E$,
   'krtań – błona włóknisto-sprężysta', 'ANATSTO-669'),
(54, 'ANA-NAC',
   'Mięśniem rozszerzającym szparę głośni jest:',
   '[{"id": "a", "text": "Mięsień pierścienno-nalewkowy tylny"}, {"id": "b", "text": "Mięsień pierścienno-nalewkowy boczny"}, {"id": "c", "text": "Mięsień poprzeczny nalewkowy"}, {"id": "d", "text": "Mięsień głosowy"}, {"id": "e", "text": "Mięsień tarczowo-nalewkowy"}]'::jsonb,
   'a',
   $E$**Mięsień pierścienno-nalewkowy tylny** jest **jedynym mięśniem rozszerzającym (odwodzącym) szparę głośni** – odwodzi wyrostki głosowe chrząstek nalewkowatych. Pozostałe mięśnie wewnętrzne krtani zwężają głośnię (pierścienno-nalewkowy boczny, poprzeczny i skośny nalewkowy, tarczowo-nalewkowy). Wszystkie mięśnie wewnętrzne krtani unerwia **nerw krtaniowy wsteczny** (gałąź X), poza pierścienno-tarczowym (nerw krtaniowy górny). Jego obustronne porażenie grozi uduszeniem.$E$,
   'mięśnie krtani', 'ANATSTO-670'),
(55, 'ANA-OUN',
   'Przez wstęgę boczną przebiega droga:',
   '[{"id": "a", "text": "Słuchowa"}, {"id": "b", "text": "Wzrokowa"}, {"id": "c", "text": "Węchowa"}, {"id": "d", "text": "Czucia głębokiego"}, {"id": "e", "text": "Smakowa"}]'::jsonb,
   'a',
   $E$**Wstęga boczna (lemniscus lateralis)** to główny pęczek **drogi słuchowej** w pniu mózgu, biegnący ku górze do **wzgórka dolnego blaszki pokrywy** i dalej do ciała kolankowatego przyśrodkowego. **Wstęga przyśrodkowa** przewodzi czucie głębokie i dotyk różnicujący (sznury tylne). **Wstęga rdzeniowa** – ból i temperaturę. Droga wzrokowa biegnie przez pasmo wzrokowe do ciała kolankowatego bocznego, węchowa nie przechodzi przez wzgórze klasyczną drogą wstęgową.$E$,
   'drogi czuciowe – droga słuchowa', 'ANATSTO-671'),
(56, 'ANA-TRZ',
   'Oskrzele główne lewe dzieli się na oskrzela płatowe:',
   '[{"id": "a", "text": "Górne i dolne"}, {"id": "b", "text": "Górne, środkowe i dolne"}, {"id": "c", "text": "Wyłącznie górne"}, {"id": "d", "text": "Cztery oskrzela płatowe"}, {"id": "e", "text": "Górne i środkowe"}]'::jsonb,
   'a',
   $E$**Oskrzele główne lewe** dzieli się na **dwa oskrzela płatowe – górne i dolne**, odpowiednio do dwóch płatów płuca lewego. **Oskrzele główne prawe** dzieli się na **trzy** (górne, środkowe, dolne) – płuco prawe ma trzy płaty. Oskrzele prawe jest szersze, krótsze i bardziej pionowe, dlatego **ciała obce częściej trafiają do prawego płuca**. Lewe oskrzele jest dłuższe i bardziej poziome (omija łuk aorty).$E$,
   'drzewo oskrzelowe', 'ANATSTO-672'),
(57, 'ANA-OBW',
   'Mięsień równoległoboczny unerwia (gałąź krótka splotu ramiennego):',
   '[{"id": "a", "text": "Nerw grzbietowy łopatki"}, {"id": "b", "text": "Nerw sromowy"}, {"id": "c", "text": "Nerw płciowo-udowy"}, {"id": "d", "text": "Nerw piersiowy długi"}, {"id": "e", "text": "Nerw nadłopatkowy"}]'::jsonb,
   'a',
   $E$**Mięsień równoległoboczny** (większy i mniejszy) unerwia **nerw grzbietowy łopatki (C4–C5)** – krótka gałąź **splotu ramiennego** odchodząca od korzenia C5. Nerw ten unerwia także mięsień dźwigacz łopatki. Mięśnie równoległoboczne przyciągają łopatkę do kręgosłupa i ku górze. **Nerw piersiowy długi (C5–C7)** unerwia mięsień zębaty przedni – jego uszkodzenie daje „łopatkę skrzydlatą". Pozostałe wymienione nerwy nie należą do splotu ramiennego.$E$,
   'nerw grzbietowy łopatki', 'ANATSTO-674'),
(58, 'ANA-NAC',
   'Zawartością dołu zażuchwowego jest m.in.:',
   '[{"id": "a", "text": "Ślinianka przyuszna, nerw twarzowy, żyła zażuchwowa i tętnica szyjna zewnętrzna"}, {"id": "b", "text": "Ślinianka podżuchwowa i nerw językowy"}, {"id": "c", "text": "Tarczyca i nerw krtaniowy wsteczny"}, {"id": "d", "text": "Migdałek podniebienny"}, {"id": "e", "text": "Gruczoł przytarczyczny"}]'::jsonb,
   'a',
   $E$**Dół zażuchwowy** zawiera (od powierzchni w głąb): **ślinianka przyuszna**, w niej **nerw twarzowy (VII)** dzielący się na gałęzie, **żyła zażuchwowa** oraz najgłębiej **tętnica szyjna zewnętrzna** dzieląca się na gałęzie końcowe (skroniową powierzchowną i szczękową). Przebiega tu też nerw uszno-skroniowy. Dół ograniczają: gałąź żuchwy (przód), wyrostek sutkowaty (tył), wyrostek rylcowaty (przyśrodek). Plik bez klucza – ustalono z wiedzy.$E$,
   'dół zażuchwowy', 'ANATSTO-675'),
(59, 'ANA-NAC',
   'Tętnica podobojczykowa w stosunku do mięśni pochyłych przebiega:',
   '[{"id": "a", "text": "Przez szczelinę mięśni pochyłych (między pochyłym przednim a środkowym)"}, {"id": "b", "text": "Do przodu od mięśnia pochyłego przedniego"}, {"id": "c", "text": "Do tyłu od mięśnia pochyłego tylnego"}, {"id": "d", "text": "Przez mięsień pochyły środkowy"}, {"id": "e", "text": "Pod obojczykiem, omijając mięśnie pochyłe"}]'::jsonb,
   'a',
   $E$**Tętnica podobojczykowa** (jej część druga) oraz **pnie splotu ramiennego** przechodzą przez **szczelinę mięśni pochyłych (trójkąt międzypochyłowy)** – między mięśniem pochyłym przednim a środkowym, nad I żebrem. **Żyła podobojczykowa** biegnie natomiast **do przodu od mięśnia pochyłego przedniego**. Zwężenie tej szczeliny powoduje **zespół górnego otworu klatki piersiowej (TOS)**. Plik bez klucza – ustalono z wiedzy.$E$,
   'tętnica podobojczykowa', 'ANATSTO-676'),
(60, 'ANA-NAC',
   'Przewód piersiowy uchodzi do:',
   '[{"id": "a", "text": "Lewego kąta żylnego"}, {"id": "b", "text": "Prawego kąta żylnego"}, {"id": "c", "text": "Żyły głównej górnej"}, {"id": "d", "text": "Prawej żyły podobojczykowej"}, {"id": "e", "text": "Żyły nieparzystej"}]'::jsonb,
   'a',
   $E$**Przewód piersiowy** uchodzi do **lewego kąta żylnego** (połączenie lewej żyły szyjnej wewnętrznej z lewą podobojczykową). Drenuje chłonkę z całego ciała poza prawą górną ćwiartką (prawa połowa głowy, szyi, prawa kończyna górna i prawa połowa klatki) – tę odprowadza **przewód chłonny prawy** do **prawego kąta żylnego**. To powtórzenie zagadnienia z wcześniejszej części zestawu, ujęte tu samodzielnie.$E$,
   'przewód piersiowy', 'ANATSTO-677'),
(61, 'ANA-NER',
   'Nerw podoczodołowy jest gałęzią nerwu:',
   '[{"id": "a", "text": "Ocznego (V1)"}, {"id": "b", "text": "Szczękowego (V2)"}, {"id": "c", "text": "Żuchwowego (V3)"}, {"id": "d", "text": "Twarzowego (VII)"}, {"id": "e", "text": "Językowo-gardłowego (IX)"}]'::jsonb,
   'b',
   $E$**Nerw podoczodołowy** to bezpośrednie przedłużenie **nerwu szczękowego (V2)** – drugiej gałęzi nerwu trójdzielnego. Wchodzi do oczodołu przez szczelinę oczodołową dolną, biegnie w bruździe i kanale podoczodołowym, wychodząc przez **otwór podoczodołowy** na twarz. Unerwia czuciowo skórę dolnej powieki, bocznej części nosa, wargi górnej oraz zęby szczęki (przez gałązki zębodołowe górne). V2 opuszcza czaszkę przez otwór okrągły.$E$,
   'nerw szczękowy (V2)', 'ANATSTO-678'),
(62, 'ANA-TRZ',
   'Moczowód u kobiety w stosunku do tętnicy macicznej:',
   '[{"id": "a", "text": "Krzyżuje się z tętnicą maciczną, przebiegając pod nią (tętnica leży nad moczowodem)"}, {"id": "b", "text": "Biegnie zawsze nad tętnicą maciczną"}, {"id": "c", "text": "Nie ma kontaktu z tętnicą maciczną"}, {"id": "d", "text": "Przebija tętnicę maciczną"}, {"id": "e", "text": "Biegnie równolegle do tętnicy macicznej bez krzyżowania"}]'::jsonb,
   'a',
   $E$W miednicy żeńskiej **moczowód krzyżuje się z tętnicą maciczną**, przebiegając **pod tętnicą** („**woda płynie pod mostem**" – *water under the bridge*). Skrzyżowanie leży ok. 1,5–2 cm bocznie od szyjki macicy. To miejsce o ogromnym znaczeniu chirurgicznym – moczowód jest tu narażony na **przypadkowe podwiązanie lub uszkodzenie** podczas histerektomii przy podwiązywaniu tętnicy macicznej. Tętnica maciczna jest gałęzią tętnicy biodrowej wewnętrznej.$E$,
   'moczowód', 'ANATSTO-679'),
(63, 'ANA-NAC',
   'Której z wymienionych gałęzi NIE oddaje tętnica szyjna zewnętrzna?',
   '[{"id": "a", "text": "Tętnicy ocznej"}, {"id": "b", "text": "Tętnicy językowej"}, {"id": "c", "text": "Tętnicy twarzowej"}, {"id": "d", "text": "Tętnicy potylicznej"}, {"id": "e", "text": "Tętnicy szczękowej"}]'::jsonb,
   'a',
   $E$**Tętnica oczna** jest gałęzią **tętnicy szyjnej wewnętrznej**, a nie zewnętrznej – odchodzi tuż po wyjściu t. szyjnej wewnętrznej z zatoki jamistej i wchodzi do oczodołu przez kanał wzrokowy. Tętnica szyjna **zewnętrzna** oddaje 8 gałęzi: tarczową górną, językową, twarzową, gardłową wstępującą, potyliczną, uszną tylną oraz końcowe – skroniową powierzchowną i szczękową. Pytanie typu „która NIE" – pozostałe opcje to prawidłowe gałęzie ECA.$E$,
   'tętnica szyjna zewnętrzna', 'ANATSTO-680'),
(64, 'ANA-NER',
   'Wyłącznie czuciowymi nerwami czaszkowymi są nerwy:',
   '[{"id": "a", "text": "I i II (oraz VIII)"}, {"id": "b", "text": "III i IV"}, {"id": "c", "text": "V i VII"}, {"id": "d", "text": "IX i X"}, {"id": "e", "text": "XI i XII"}]'::jsonb,
   'a',
   $E$**Czysto czuciowe** nerwy czaszkowe to **I (węchowy), II (wzrokowy) i VIII (przedsionkowo-ślimakowy)**. Czysto ruchowe: III, IV, VI, XI, XII (klasycznie). Mieszane: V, VII, IX, X. Mnemonik charakteru nerwów I–XII: **„Some Say Marry Money But My Brother Says Big Brains Matter More"** (S – sensory, M – motor, B – both). Nerwy I i II to wypustki OUN. Pytanie zawężono do pary I, II z uzupełnieniem o VIII w opcji.$E$,
   'rodzaje nerwów czaszkowych', 'ANATSTO-681'),
(65, 'ANA-TRZ',
   'Która warstwa ściany serca tworzy zastawki?',
   '[{"id": "a", "text": "Wsierdzie"}, {"id": "b", "text": "Śródsierdzie (mięsień sercowy)"}, {"id": "c", "text": "Nasierdzie"}, {"id": "d", "text": "Osierdzie ścienne"}, {"id": "e", "text": "Worek osierdziowy"}]'::jsonb,
   'a',
   $E$**Zastawki serca** to fałdy **wsierdzia (endocardium)** – najbardziej wewnętrznej warstwy, wzmocnione rdzeniem łącznotkankowym (płytka włóknista). Wsierdzie pokrywa wszystkie struktury w jamach serca, jest ciągłe ze śródbłonkiem naczyń. **Śródsierdzie (myocardium)** to gruba warstwa mięśniowa odpowiedzialna za kurczliwość. **Nasierdzie (epicardium)** to blaszka trzewna osierdzia surowiczego. Zastawki są beznaczyniowe, odżywiane dyfuzyjnie z krwi.$E$,
   'warstwy ściany serca', 'ANATSTO-682'),
(66, 'ANA-OUN',
   'Spoidło uzdeczek należy do:',
   '[{"id": "a", "text": "Nadwzgórza"}, {"id": "b", "text": "Podwzgórza"}, {"id": "c", "text": "Niskowzgórza"}, {"id": "d", "text": "Wzgórza"}, {"id": "e", "text": "Zawzgórza"}]'::jsonb,
   'a',
   $E$**Spoidło uzdeczek (commissura habenularum)** należy do **nadwzgórza (epithalamus)** – tylno-górnej części międzymózgowia. W skład nadwzgórza wchodzą także: **szyszynka (ciało szyszynkowate)**, **trójkąty uzdeczek z jądrami uzdeczki**, **smugi rdzenne wzgórza** oraz **spoidło tylne**. Jądra uzdeczki łączą układ limbiczny z pniem mózgu. Szyszynka wydziela melatoninę regulującą rytm dobowy. Podwzgórze tworzy dno komory III, wzgórze – jej ściany boczne.$E$,
   'nadwzgórze', 'ANATSTO-683'),
(67, 'ANA-OBW',
   'Korzeń przyśrodkowy nerwu pośrodkowego pochodzi od:',
   '[{"id": "a", "text": "Pęczka przyśrodkowego splotu ramiennego (włókna C8–Th1)"}, {"id": "b", "text": "Pęczka bocznego splotu ramiennego"}, {"id": "c", "text": "Pęczka tylnego splotu ramiennego"}, {"id": "d", "text": "Nerwu pachowego"}, {"id": "e", "text": "Nerwu mięśniowo-skórnego"}]'::jsonb,
   'a',
   $E$**Nerw pośrodkowy** powstaje z dwóch korzeni: **korzeń przyśrodkowy** odchodzi od **pęczka przyśrodkowego** splotu ramiennego (włókna **C8–Th1**), a **korzeń boczny** – od pęczka bocznego (C5–C7). Oba łączą się ku przodowi od tętnicy pachowej, obejmując ją „widełkami". Nerw pośrodkowy unerwia większość zginaczy przedramienia i mięśnie kłębu kciuka. Plik bez klucza – ustalono z wiedzy. Pęczek przyśrodkowy daje też nerw łokciowy.$E$,
   'nerw pośrodkowy', 'ANATSTO-684'),
(68, 'ANA-OUN',
   'Droga rdzeniowo-wzgórzowa boczna przewodzi:',
   '[{"id": "a", "text": "Czucie bólu i temperatury"}, {"id": "b", "text": "Czucie dotyku różnicującego i wibracji"}, {"id": "c", "text": "Czucie głębokie świadome"}, {"id": "d", "text": "Impulsy ruchowe"}, {"id": "e", "text": "Czucie smaku"}]'::jsonb,
   'a',
   $E$**Droga rdzeniowo-wzgórzowa boczna** przewodzi **ból i temperaturę**. Aksony neuronu II (z rogu tylnego) **krzyżują się w spoidle przednim** 1–2 segmenty wyżej i wstępują w sznurze bocznym do wzgórza (jądro VPL). Czucie dotyku różnicującego, wibracji i propriocepcji świadomej biegnie sznurami tylnymi (wstęga przyśrodkowa). To powtórzenie zagadnienia z wcześniejszej części zestawu. Plik nie miał klucza – ustalono z wiedzy.$E$,
   'drogi czuciowe rdzenia', 'ANATSTO-685'),
(69, 'ANA-CZA',
   'Przewód słuchowy wewnętrzny przebiega w obrębie:',
   '[{"id": "a", "text": "Części skalistej (piramidy) kości skroniowej"}, {"id": "b", "text": "Części bębenkowej kości skroniowej"}, {"id": "c", "text": "Łuski kości skroniowej"}, {"id": "d", "text": "Wyrostka sutkowatego"}, {"id": "e", "text": "Kości potylicznej"}]'::jsonb,
   'a',
   $E$**Przewód słuchowy wewnętrzny (meatus acusticus internus)** przebiega w **części skalistej (piramidzie) kości skroniowej**, otwierając się otworem słuchowym wewnętrznym na tylnej powierzchni piramidy (dół tylny czaszki). Przechodzą przez niego **nerw twarzowy (VII)**, **nerw przedsionkowo-ślimakowy (VIII)** oraz **tętnica i żyła błędnikowa**. Część bębenkowa kości skroniowej otacza przewód słuchowy *zewnętrzny*.$E$,
   'kość skroniowa – przewody słuchowe', 'ANATSTO-687'),
(70, 'ANA-KON',
   'W co przechodzi tętnica udowa po przejściu przez kanał przywodzicieli?',
   '[{"id": "a", "text": "Tętnica podkolanowa"}, {"id": "b", "text": "Tętnica piszczelowa przednia"}, {"id": "c", "text": "Tętnica strzałkowa"}, {"id": "d", "text": "Tętnica biodrowa zewnętrzna"}, {"id": "e", "text": "Tętnica głęboka uda"}]'::jsonb,
   'a',
   $E$**Tętnica udowa** po przejściu przez **kanał przywodzicieli (Huntera)** i jego rozwór (rozwór ścięgnisty przywodziciela wielkiego) przechodzi do dołu podkolanowego jako **tętnica podkolanowa**. Ta z kolei dzieli się na tętnicę piszczelową przednią i pień piszczelowo-strzałkowy. Tętnica udowa jest przedłużeniem tętnicy biodrowej zewnętrznej (od więzadła pachwinowego). Tętnica głęboka uda jest jej największą gałęzią odchodzącą w trójkącie udowym.$E$,
   'tętnica udowa', 'ANATSTO-688'),
(71, 'ANA-JAM',
   'Podniebienie kostne tworzą:',
   '[{"id": "a", "text": "Wyrostki podniebienne szczęk i blaszki poziome kości podniebiennych"}, {"id": "b", "text": "Wyrostki zębodołowe szczęk i blaszki pionowe kości podniebiennych"}, {"id": "c", "text": "Blaszki skrzydłowe kości klinowej"}, {"id": "d", "text": "Wyrostek jarzmowy szczęki i kość jarzmowa"}, {"id": "e", "text": "Lemiesz i blaszki pionowe kości podniebiennych"}]'::jsonb,
   'a',
   $E$**Podniebienie kostne (twarde)** tworzą: z przodu **wyrostki podniebienne szczęk** (ok. 2/3 przednie), z tyłu **blaszki poziome kości podniebiennych** (ok. 1/3 tylna). Łączą się one szwami: pośrodkowym i poprzecznym podniebiennym. Z przodu leży **otwór przysieczny** (nerw nosowo-podniebienny), z tyłu **otwory podniebienne większy i mniejsze** (nerwy podniebienne). Zaburzenie zrostu wyrostków podniebiennych powoduje wadę – **rozszczep podniebienia**.$E$,
   'podniebienie kostne', 'ANATSTO-689'),
(72, 'ANA-TUL',
   'Żyła główna dolna powstaje z połączenia:',
   '[{"id": "a", "text": "Żył biodrowych wspólnych"}, {"id": "b", "text": "Żył biodrowych wewnętrznych"}, {"id": "c", "text": "Żył biodrowych zewnętrznych"}, {"id": "d", "text": "Żył nerkowych"}, {"id": "e", "text": "Żył lędźwiowych"}]'::jsonb,
   'a',
   $E$**Żyła główna dolna** powstaje z połączenia **prawej i lewej żyły biodrowej wspólnej** na wysokości **L5** (ku tyłowi i nieco na prawo od rozwidlenia aorty). Każda żyła biodrowa wspólna powstaje z połączenia żyły biodrowej wewnętrznej i zewnętrznej. Żyła główna dolna wstępuje po prawej stronie kręgosłupa, przyjmuje m.in. żyły nerkowe, prawą jądrową/jajnikową, wątrobowe, i przebija przeponę na wysokości **Th8**, uchodząc do prawego przedsionka.$E$,
   'żyła główna dolna', 'ANATSTO-691'),
(73, 'ANA-TRZ',
   'Gałęziami aorty piersiowej (zstępującej) są:',
   '[{"id": "a", "text": "Tętnice wieńcowe"}, {"id": "b", "text": "Tętnica podobojczykowa prawa i szyjna wspólna prawa"}, {"id": "c", "text": "Pień ramienno-głowowy, tętnica szyjna wspólna lewa, tętnica podobojczykowa lewa"}, {"id": "d", "text": "Tętnice nerkowe i krezkowe"}, {"id": "e", "text": "Gałęzie międzyżebrowe tylne, oskrzelowe i przełykowe"}]'::jsonb,
   'e',
   $E$**Aorta piersiowa (zstępująca)** oddaje gałęzie **trzewne** (oskrzelowe, przełykowe, śródpiersiowe, osierdziowe) oraz **ścienne** (tętnice międzyżebrowe tylne, podżebrowe i przeponowe górne). Opcja C wymienia gałęzie **łuku aorty** (pień ramienno-głowowy, t. szyjna wspólna lewa, t. podobojczykowa lewa), tętnice wieńcowe odchodzą od aorty wstępującej, a nerkowe i krezkowe – od aorty brzusznej. Stąd jedyna poprawna to E.$E$,
   'aorta piersiowa', 'ANATSTO-692'),
(74, 'ANA-OUN',
   'Ciało kolankowate boczne jest stacją przekaźnikową drogi:',
   '[{"id": "a", "text": "Wzrokowej"}, {"id": "b", "text": "Słuchowej"}, {"id": "c", "text": "Czucia bólu"}, {"id": "d", "text": "Węchowej"}, {"id": "e", "text": "Ruchowej piramidowej"}]'::jsonb,
   'a',
   $E$**Ciało kolankowate boczne (corpus geniculatum laterale)** wzgórza jest główną stacją przekaźnikową **drogi wzrokowej** – tu kończą się włókna pasma wzrokowego, a rozpoczyna **promienistość wzrokowa** biegnąca do kory wzrokowej (pole 17, okolica bruzdy ostrogowej płata potylicznego). **Ciało kolankowate przyśrodkowe** jest stacją drogi **słuchowej**. Część włókien pasma wzrokowego biegnie do wzgórków górnych (odruchy) i jąder przedpokrywowych (odruch źreniczny). Plik bez klucza – ustalono z wiedzy.$E$,
   'droga wzrokowa', 'ANATSTO-693'),
(75, 'ANA-NAC',
   'Na szyjce żuchwy (do tyłu od niej) przebiega naczynie:',
   '[{"id": "a", "text": "Tętnica szczękowa"}, {"id": "b", "text": "Tętnica twarzowa"}, {"id": "c", "text": "Tętnica językowa"}, {"id": "d", "text": "Tętnica oczna"}, {"id": "e", "text": "Tętnica podobojczykowa"}]'::jsonb,
   'a',
   $E$**Tętnica szczękowa** – większa gałąź końcowa tętnicy szyjnej zewnętrznej – rozpoczyna się w obrębie ślinianki przyusznej **do tyłu od szyjki żuchwy** i biegnie ku przodowi do dołu podskroniowego i skrzydłowo-podniebiennego. Dzieli się na trzy odcinki (żuchwowy, skrzydłowy, skrzydłowo-podniebienny) i liczne gałęzie, m.in. **tętnicę oponową środkową** i **zębodołową dolną**. Złamanie szyjki żuchwy grozi uszkodzeniem tej tętnicy. Plik bez klucza – ustalono z wiedzy.$E$,
   'tętnica szczękowa', 'ANATSTO-694'),
(76, 'ANA-KON',
   'Z ilu kości składa się kościec ręki (nadgarstek, śródręcze, palce)?',
   '[{"id": "a", "text": "27"}, {"id": "b", "text": "8"}, {"id": "c", "text": "14"}, {"id": "d", "text": "19"}, {"id": "e", "text": "30"}]'::jsonb,
   'a',
   $E$Kościec ręki tworzy **27 kości**: **8 kości nadgarstka** (w dwóch szeregach), **5 kości śródręcza** oraz **14 paliczków** (po 3 w palcach II–V i 2 w kciuku). Mnemonik szeregu bliższego nadgarstka (od kciuka): **„Łódka Płynie Tuż Grzbietem"** (łódeczkowata, księżycowata, trójgraniasta, grochowata); szereg dalszy: czworoboczna większa i mniejsza, główkowata, haczykowata. Cała kończyna górna ma 30 kości (z obojczykiem i łopatką – 32 w obręczy z ręką).$E$,
   'kościec ręki', 'ANATSTO-695'),
(77, 'ANA-NAC',
   'Mięsień łopatkowo-gnykowy (brzusiec dolny) ogranicza od góry trójkąt:',
   '[{"id": "a", "text": "Łopatkowo-obojczykowy (podobojczykowy)"}, {"id": "b", "text": "Tętnicy szyjnej"}, {"id": "c", "text": "Podżuchwowy"}, {"id": "d", "text": "Podbródkowy"}, {"id": "e", "text": "Łopatkowo-tchawiczy od dołu"}]'::jsonb,
   'a',
   $E$**Brzusiec dolny mięśnia łopatkowo-gnykowego** dzieli trójkąt tylny (boczny) szyi i ogranicza **od góry trójkąt łopatkowo-obojczykowy (podobojczykowy)** – którego dolną granicę stanowi obojczyk, a przednią tylny brzeg MOS. W trójkącie tym leży m.in. tętnica podobojczykowa (część trzecia) i pnie splotu ramiennego. Mięsień łopatkowo-gnykowy ogranicza też trójkąty przednie. Plik bez klucza – ustalono z wiedzy.$E$,
   'trójkąty szyi', 'ANATSTO-696'),
(78, 'ANA-NAC',
   'Przyśrodkowo przestrzeń przygardłową ogranicza:',
   '[{"id": "a", "text": "Boczna ściana gardła (z powięzią policzkowo-gardłową)"}, {"id": "b", "text": "Powięź przedkręgowa"}, {"id": "c", "text": "Mięsień skrzydłowy przyśrodkowy"}, {"id": "d", "text": "Ślinianka przyuszna"}, {"id": "e", "text": "Gałąź żuchwy"}]'::jsonb,
   'a',
   $E$**Przyśrodkową ścianę przestrzeni przygardłowej** stanowi **boczna ściana gardła** pokryta **powięzią policzkowo-gardłową**. Bocznie przestrzeń ogranicza mięsień skrzydłowy przyśrodkowy, gałąź żuchwy i ślinianka przyuszna, a z tyłu – powięź przedkręgowa. Przestrzeń ta dzieli się wyrostkiem rylcowatym i mięśniami na część przedstyloidalną i zastyloidalną (w tej biegną duże naczynia i nerwy IX–XII). Ma znaczenie w szerzeniu zakażeń zębopochodnych.$E$,
   'przestrzeń przygardłowa', 'ANATSTO-697'),
(79, 'ANA-NAC',
   'Tętnica krtaniowa górna jest gałęzią:',
   '[{"id": "a", "text": "Tętnicy tarczowej górnej (od tętnicy szyjnej zewnętrznej)"}, {"id": "b", "text": "Tętnicy tarczowej dolnej"}, {"id": "c", "text": "Tętnicy podobojczykowej bezpośrednio"}, {"id": "d", "text": "Tętnicy szyjnej wewnętrznej"}, {"id": "e", "text": "Tętnicy kręgowej"}]'::jsonb,
   'a',
   $E$**Tętnica krtaniowa górna** odchodzi od **tętnicy tarczowej górnej** (pierwszej gałęzi tętnicy szyjnej zewnętrznej). Wraz z **nerwem krtaniowym górnym** (gałęzią wewnętrzną) przebija błonę tarczowo-gnykową i zaopatruje górną część krtani oraz jej błonę śluzową i mięśnie. Dolną część krtani unaczynia tętnica krtaniowa dolna (od t. tarczowej dolnej z pnia tarczowo-szyjnego). Plik bez klucza – ustalono z wiedzy.$E$,
   'tętnica krtaniowa górna', 'ANATSTO-698'),
(80, 'ANA-OUN',
   'Jądro dwuznaczne jest jądrem ruchowym wspólnym dla nerwów:',
   '[{"id": "a", "text": "IX, X i XI (część czaszkowa)"}, {"id": "b", "text": "V, VII i IX"}, {"id": "c", "text": "III, IV i VI"}, {"id": "d", "text": "VII, VIII i IX"}, {"id": "e", "text": "X, XI i XII"}]'::jsonb,
   'a',
   $E$**Jądro dwuznaczne (nucleus ambiguus)** w rdzeniu przedłużonym to wspólne jądro ruchowe (branchiomotoryczne) dla nerwów **IX (językowo-gardłowy), X (błędny) i części czaszkowej XI (dodatkowy)**. Unerwia mięśnie gardła, krtani i podniebienia miękkiego (pochodne łuków skrzelowych). Jego uszkodzenie powoduje dyzartrię, dysfagię i zniesienie odruchu gardłowego. Włókna ruchowe XII pochodzą z osobnego jądra nerwu podjęzykowego.$E$,
   'jądra nerwów czaszkowych', 'ANATSTO-699'),
(81, 'ANA-NAC',
   'Tętnica podobojczykowa przechodzi przez:',
   '[{"id": "a", "text": "Szczelinę mięśni pochyłych (między pochyłym przednim a środkowym)"}, {"id": "b", "text": "Szczelinę tylną mięśni pochyłych (za pochyłym tylnym)"}, {"id": "c", "text": "Trójkąt podżuchwowy"}, {"id": "d", "text": "Otwór kręgowy C7"}, {"id": "e", "text": "Kanał tętnicy szyjnej"}]'::jsonb,
   'a',
   $E$**Tętnica podobojczykowa** (część druga) przechodzi przez **szczelinę mięśni pochyłych** – trójkątną przestrzeń między mięśniem **pochyłym przednim a środkowym**, nad I żebrem, razem z pniami splotu ramiennego. Żyła podobojczykowa biegnie do przodu od mięśnia pochyłego przedniego. To powtórzenie zagadnienia o tętnicy podobojczykowej z wcześniejszej części zestawu (pierwotny zapis „szczelina tylna" był nieprawidłowy). Zwężenie tej szczeliny daje zespół TOS.$E$,
   'tętnica podobojczykowa', 'ANATSTO-700'),
(82, 'ANA-NER',
   'Włókna przywspółczulne nerwu okoruchowego (III) przełączają się w:',
   '[{"id": "a", "text": "Zwoju rzęskowym"}, {"id": "b", "text": "Zwoju skrzydłowo-podniebiennym"}, {"id": "c", "text": "Zwoju usznym"}, {"id": "d", "text": "Zwoju podżuchwowym"}, {"id": "e", "text": "Zwoju szyjnym górnym"}]'::jsonb,
   'a',
   $E$**Włókna przywspółczulne nerwu III** (z jądra dodatkowego Edingera-Westphala) przełączają się (synapsa neuronu przedzwojowego z pozazwojowym) w **zwoju rzęskowym**, leżącym w oczodole. Włókna pozazwojowe (nerwy rzęskowe krótkie) unerwiają **zwieracz źrenicy** (zwężenie źrenicy) i **mięsień rzęskowy** (akomodacja). Pozostałe zwoje przywspółczulne głowy: skrzydłowo-podniebienny i podżuchwowy (VII), uszny (IX). Plik bez klucza – ustalono z wiedzy.$E$,
   'nerw okoruchowy – włókna przywspółczulne', 'ANATSTO-702'),
(83, 'ANA-NER',
   'Który z wymienionych nerwów czaszkowych zawiera włókna przywspółczulne?',
   '[{"id": "a", "text": "III (okoruchowy)"}, {"id": "b", "text": "IV (bloczkowy)"}, {"id": "c", "text": "VI (odwodzący)"}, {"id": "d", "text": "XII (podjęzykowy)"}, {"id": "e", "text": "XI (dodatkowy)"}]'::jsonb,
   'a',
   $E$**Włókna przywspółczulne** zawierają cztery nerwy czaszkowe: **III, VII, IX i X**. Nerw **III (okoruchowy)** prowadzi włókna do zwoju rzęskowego (zwężenie źrenicy, akomodacja). Mnemonik nerwów z komponentą przywspółczulną: „**1, 9, 7, 10**" lub czterocyfrowo III–VII–IX–X. Nerwy IV, VI, XII i XI są czysto somatoruchowe i nie mają komponenty autonomicznej. Najszersze pole działania ma X – unerwia narządy klatki i jamy brzusznej.$E$,
   'składowa przywspółczulna nerwów czaszkowych', 'ANATSTO-703'),
(84, 'ANA-NAC',
   'Zachyłki gruszkowate znajdują się:',
   '[{"id": "a", "text": "Bocznie od wejścia do krtani (w części krtaniowej gardła)"}, {"id": "b", "text": "W nosogardle"}, {"id": "c", "text": "Na nasadzie języka"}, {"id": "d", "text": "W przedsionku krtani"}, {"id": "e", "text": "W okolicy migdałków podniebiennych"}]'::jsonb,
   'a',
   $E$**Zachyłki gruszkowate (recessus piriformes)** to parzyste zagłębienia części **krtaniowej gardła (gardła dolnego)**, leżące **bocznie od wejścia do krtani**, po obu stronach. Ograniczają je przyśrodkowo fałd nalewkowo-nagłośniowy, bocznie chrząstka tarczowata i błona tarczowo-gnykowa. Pod błoną śluzową biegnie tu **nerw krtaniowy górny**. To częste miejsce zatrzymywania się **ciał obcych (ości)** i punkt wyjścia raka gardła dolnego.$E$,
   'krtań – gardło dolne', 'ANATSTO-704'),
(85, 'ANA-OBW',
   'Splot ramienny tworzą gałęzie brzuszne nerwów rdzeniowych:',
   '[{"id": "a", "text": "C5–Th1"}, {"id": "b", "text": "C1–C4"}, {"id": "c", "text": "C3–C7"}, {"id": "d", "text": "C6–Th2"}, {"id": "e", "text": "C5–C8"}]'::jsonb,
   'a',
   $E$**Splot ramienny (plexus brachialis)** tworzą gałęzie brzuszne nerwów rdzeniowych **C5–Th1** (z niestałym udziałem C4 i Th2). Z korzeni powstają **pnie** (górny C5–C6, środkowy C7, dolny C8–Th1), które dzielą się na części przednie i tylne, te zaś tworzą **pęczki** (boczny, przyśrodkowy, tylny) wokół tętnicy pachowej. Pęczki dają nerwy końcowe (m.in. pośrodkowy, łokciowy, promieniowy, pachowy, mięśniowo-skórny). Mnemonik: **„Robert Taylor Drinks Cold Beer"** (Roots, Trunks, Divisions, Cords, Branches).$E$,
   'splot ramienny', 'ANATSTO-705')
),
maxes AS (
  SELECT topic_id, COALESCE(MAX( (regexp_match(id, '([0-9]+)$'))[1]::int ), 0) AS mx
    FROM public.questions WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') GROUP BY topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam)
SELECT
  LOWER(n.topic_id) || '-' || LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_anat_sto_2023/2', 'Egzamin anatomia STOMA SUM 2023 (ANATSTO e2023-2)'
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (SELECT topic_id, COUNT(*) AS cnt FROM public.questions
         WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') AND COALESCE(is_active,true)=true GROUP BY topic_id) sub
 WHERE t.id = sub.topic_id;
