-- ============================================================
-- BATCH: e_anat_2019/1  ·  subject_id=anatomia  ·  SHARED (oba kierunki, tracks=NULL)
-- Źródło: Egzamin anatomia LEK SUM 2019 (ANATLEK e2019-1), 100 pytań (egzaminy STOMATOLOGII)
-- tracks NULL (anatomia wspólna) · source_code = oryginalne ANATSTO-NNN
-- Self-numbering id per dział = max seq z bazy + 1
--
-- Wersja po dedup (2026-05-28): 89 pytań — wycięte 11 duplikaty (batch + baza).
-- Audyt: exports/anatomia-batch-lek-2019-1-dedup-audit.md
-- ============================================================

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
(1, 'ANA-NAC',
   'Nerw przeponowy jest gałęzią:',
   '[{"id": "a", "text": "bezpośrednią splotu szyjnego"}, {"id": "b", "text": "pętli szyjnej"}, {"id": "c", "text": "zwojów szyjnych pnia współczulnego"}, {"id": "d", "text": "zwojów piersiowych pnia współczulnego"}, {"id": "e", "text": "nerwu podżebrowego"}]'::jsonb,
   'a',
   $E$Nerw przeponowy (**n. phrenicus**) powstaje głównie z gałęzi przedniej **C4**, z domieszką C3 i C5, jako bezpośrednia gałąź **splotu szyjnego**. Jest mieszany — ruchowo unerwia przeponę, czuciowo osierdzie i otrzewną przeponową. Biegnie po przednim mięśniu pochyłym i wnika do klatki. Pętla szyjna (ansa cervicalis, C1–C3) unerwia mięśnie podgnykowe, a nie przeponę. Mnemonik: **C3,4,5 keep the diaphragm alive**.$E$,
   'splot szyjny', 'ANATLEK-258'),
(2, 'ANA-CZA',
   'Błona bębenkowa wtórna:',
   '[{"id": "a", "text": "oddziela ucho zewnętrzne od wewnętrznego"}, {"id": "b", "text": "oddziela ucho środkowe od wewnętrznego"}, {"id": "c", "text": "oddziela ucho zewnętrzne od środkowego"}, {"id": "d", "text": "zamyka okienko przedsionka"}, {"id": "e", "text": "oddziela jamę bębenkową od komórek sutkowych"}]'::jsonb,
   'b',
   $E$Błona bębenkowa wtórna (**membrana tympanica secundaria**) zamyka **okienko ślimaka (okrągłe)**, oddzielając jamę bębenkową (ucho środkowe) od schodów bębenka ślimaka (ucho wewnętrzne). Drga przeciwfazowo do podstawy strzemiączka w okienku przedsionka (owalnym), umożliwiając przemieszczanie perylimfy. **Okienko przedsionka** zamyka podstawa strzemiączka, nie błona — dlatego D błędne. Błona bębenkowa pierwotna oddziela ucho zewnętrzne od środkowego.$E$,
   'ucho', 'ANATLEK-259'),
(3, 'ANA-OUN',
   'Promienistość wzrokowa:',
   '[{"id": "a", "text": "przebiega w ramieniu wzgórka górnego"}, {"id": "b", "text": "przebiega od skrzyżowania wzrokowego do ciał kolankowatych bocznych"}, {"id": "c", "text": "przebiega od skrzyżowania wzrokowego do ciał kolankowatych przyśrodkowych"}, {"id": "d", "text": "przebiega od ciał kolankowatych bocznych do kory potylicznej"}, {"id": "e", "text": "przebiega od ciał kolankowatych bocznych do kory skroniowej"}]'::jsonb,
   'd',
   $E$Promienistość wzrokowa (**radiatio optica**, droga Graziolego) biegnie od **ciała kolankowatego bocznego** (LGN, IV neuron drogi wzrokowej) przez odnogę tylną torebki wewnętrznej do **kory wzrokowej płata potylicznego** (pole 17, wokół bruzdy ostrogowej). Pasmo wzrokowe (tractus opticus) łączy skrzyżowanie z LGN — to inny odcinek. **Ciało kolankowate przyśrodkowe** należy do drogi słuchowej. Pętla Meyera promienistości zakręca przez płat skroniowy.$E$,
   'droga wzrokowa', 'ANATLEK-260'),
(4, 'ANA-CZA',
   'Komora przednia oka jest zawarta pomiędzy:',
   '[{"id": "a", "text": "rogówką a tęczówką i soczewką"}, {"id": "b", "text": "twardówką a tęczówką"}, {"id": "c", "text": "siatkówką a ciałem szklistym"}, {"id": "d", "text": "tęczówką a źrenicą"}, {"id": "e", "text": "tęczówką a soczewką"}]'::jsonb,
   'a',
   $E$Komora przednia oka leży między tylną powierzchnią **rogówki** z przodu a przednią powierzchnią **tęczówki** i widoczną przez źrenicę częścią **soczewki** z tyłu. Wypełnia ją ciecz wodnista. Komunikuje się z komorą tylną przez źrenicę; ciecz odpływa kątem przesączania (kąt tęczówkowo-rogówkowy) przez **utkanie beleczkowe i kanał Schlemma**. Komora tylna leży między tęczówką a soczewką/ciałem rzęskowym — stąd E opisuje komorę tylną.$E$,
   'gałka oczna', 'ANATLEK-261'),
(5, 'ANA-NAC',
   'Tętnica zębodołowa górna jest gałęzią:',
   '[{"id": "a", "text": "pierwszego odcinka tętnicy szczękowej"}, {"id": "b", "text": "drugiego odcinka tętnicy szczękowej"}, {"id": "c", "text": "przednią tętnicy szyjnej zewnętrznej"}, {"id": "d", "text": "przyśrodkową tętnicy szyjnej zewnętrznej"}, {"id": "e", "text": "końcową tętnicy szyjnej zewnętrznej"}]'::jsonb,
   'e',
   $E$Tętnice zębodołowe górne tylne odchodzą od **trzeciego (skrzydłowo-podniebiennego) odcinka tętnicy szczękowej**. Tętnica szczękowa jest jedną z dwóch **gałęzi końcowych tętnicy szyjnej zewnętrznej** (obok t. skroniowej powierzchownej), dlatego E jest poprawne. Odcinek I (kostny) oddaje m.in. t. oponową środkową i zębodołową dolną; odcinek II (mięśniowy) zaopatruje mięśnie żucia. Brak odcinka „pierwszego” dla zębodołowej górnej — stąd A błędne.$E$,
   'tętnica szczękowa', 'ANATLEK-263'),
(6, 'ANA-TRZ',
   'W obrębie trójkąta pęcherzowego ścianę pęcherza tworzą kolejno warstwy:',
   '[{"id": "a", "text": "błona śluzowa, błona podśluzowa, mięśniówka, przydanka"}, {"id": "b", "text": "błona śluzowa, mięśniówka, przydanka"}, {"id": "c", "text": "błona śluzowa, błona podśluzowa, mięśniówka, błona surowicza"}, {"id": "d", "text": "błona śluzowa, błona podśluzowa, przydanka"}, {"id": "e", "text": "błona śluzowa, błona podśluzowa, błona surowicza"}]'::jsonb,
   'b',
   $E$W **trójkącie pęcherzowym (trigonum)** błona śluzowa jest gładka i **trwale przyrośnięta do mięśniówki** — brak tu błony podśluzowej i fałdów, w odróżnieniu od reszty pęcherza. Na zewnątrz mięśniówki (mięsień wypieracz) leży przydanka, bo dno i trójkąt nie są pokryte otrzewną (surowiczą). Stąd kolejność: **śluzowa → mięśniówka → przydanka**. Otrzewna (surowicza) pokrywa tylko szczyt i górno-tylną ścianę pęcherza.$E$,
   'pęcherz moczowy', 'ANATLEK-265'),
(7, 'ANA-TRZ',
   'Moczowód w części brzusznej:',
   '[{"id": "a", "text": "nie posiada styku z otrzewną"}, {"id": "b", "text": "krzyżuje naczynia gonadowe i nerw udowy"}, {"id": "c", "text": "krzyżuje naczynia gonadowe i nerw płciowo-udowy"}, {"id": "d", "text": "prawy leży pomiędzy okrężnicą wstępującą a aortą"}, {"id": "e", "text": "lewy krzyżuje korzeń jelita krezkowego"}]'::jsonb,
   'c',
   $E$W części brzusznej moczowód biegnie zaotrzewnowo po mięśniu lędźwiowym większym, **krzyżując od przodu nerw płciowo-udowy**, a naczynia jajnikowe/jądrowe (gonadowe) krzyżują moczowód od przodu. Jest pokryty otrzewną ścienną od przodu (przylega do niej) — stąd A błędne. Prawy moczowód leży bocznie od żyły głównej dolnej, nie między okrężnicą a aortą. Mnemonik: „**water under the bridge**” dotyczy odcinka miednicznego (moczowód pod naczyniami).$E$,
   'moczowód', 'ANATLEK-266'),
(8, 'ANA-TRZ',
   'Parametrium to jest:',
   '[{"id": "a", "text": "otrzewna pokrywająca macicę"}, {"id": "b", "text": "błona śluzowa macicy"}, {"id": "c", "text": "więzadło szerokie macicy"}, {"id": "d", "text": "zawartość więzadła szerokiego macicy"}, {"id": "e", "text": "jajnik i jajowód"}]'::jsonb,
   'd',
   $E$Parametrium (przymacicze) to **tkanka łączna i tłuszczowa wraz z naczyniami zawarta między blaszkami więzadła szerokiego macicy**, w pobliżu szyjki. Przez nie przebiega m.in. tętnica maciczna krzyżująca moczowód oraz moczowód. Samo więzadło szerokie to fałd otrzewnej (C błędne, bo to fałd, nie jego zawartość). Błona śluzowa macicy to endometrium (perimetrium = otrzewna pokrywająca macicę). Stąd parametrium = zawartość, nie sam fałd.$E$,
   'macica', 'ANATLEK-267'),
(9, 'ANA-TRZ',
   'Przedsionek pochwy otoczony jest przez mięsień:',
   '[{"id": "a", "text": "opuszkowo-gąbczasty"}, {"id": "b", "text": "kulszowo-jamisty"}, {"id": "c", "text": "zwieracz pochwy"}, {"id": "d", "text": "poprzeczny krocza powierzchowny"}, {"id": "e", "text": "zwieracz cewki moczowej"}]'::jsonb,
   'a',
   $E$Przedsionek pochwy obejmuje u kobiety **mięsień opuszkowo-gąbczasty (m. bulbospongiosus)**, który u kobiet jest podzielony na dwie części otaczające ujście pochwy i pokrywające opuszki przedsionka oraz gruczoły przedsionkowe większe (Bartholina). Działa jak słaby zwieracz pochwy i pomaga we wzwodzie łechtaczki. Mięsień kulszowo-jamisty pokrywa odnogi łechtaczki. Anatomiczny „zwieracz pochwy” jako odrębny mięsień nie istnieje — funkcję pełni bulbospongiosus.$E$,
   'krocze', 'ANATLEK-268'),
(10, 'ANA-TRZ',
   'Pęcherz moczowy pokryty jest otrzewną:',
   '[{"id": "a", "text": "w całości"}, {"id": "b", "text": "w obrębie trójkąta pęcherzowego"}, {"id": "c", "text": "na szczycie i ścianie tylnej do przedniego sklepienia pochwy"}, {"id": "d", "text": "na szczycie i ścianie tylnej wraz z gruczołem krokowym"}, {"id": "e", "text": "na szczycie i ścianie tylnej do szczytów pęcherzyków nasiennych"}]'::jsonb,
   'e',
   $E$Pęcherz moczowy jest narządem **podotrzewnowym** — otrzewna pokrywa jego szczyt i ścianę górno-tylną. U mężczyzny schodzi po ścianie tylnej do poziomu **szczytów pęcherzyków nasiennych**, tworząc zagłębienie odbytniczo-pęcherzowe. Gruczoł krokowy leży podotrzewnowo i nie jest pokryty otrzewną (D błędne). U kobiety otrzewna przechodzi na macicę tworząc zagłębienie pęcherzowo-maciczne — nie sięga do sklepienia pochwy (C dotyczy innego poziomu).$E$,
   'pęcherz moczowy', 'ANATLEK-269'),
(11, 'ANA-OUN',
   'Sklepienie jest to:',
   '[{"id": "a", "text": "pęk włókien nerwowych wychodzących z hipokampa"}, {"id": "b", "text": "górna ściana komory czwartej"}, {"id": "c", "text": "jedno ze spoideł"}, {"id": "d", "text": "środkowa część ciała modzelowatego"}, {"id": "e", "text": "boczna część jądra soczewkowatego"}]'::jsonb,
   'a',
   $E$Sklepienie (**fornix**) to pasmo istoty białej — **pęk włókien wychodzących z hipokampa** (głównie z podkładki/subiculum), biegnący przez odnogi, ciało i słupy do ciał suteczkowatych podwzgórza (droga hipokampowo-suteczkowata, część obwodu Papeza). Górną ścianę komory IV tworzy zasłona rdzeniowa górna (B błędne). Spoidło to np. ciało modzelowate czy spoidło przednie; sam fornix nie jest spoidłem, choć ma spoidło sklepienia (psalterium).$E$,
   'układ limbiczny', 'ANATLEK-270'),
(12, 'ANA-OUN',
   'Korowy ośrodek ruchu dowolnego dla mięśni żucia leży w:',
   '[{"id": "a", "text": "przedniej części płacika okołośrodkowego"}, {"id": "b", "text": "tylnej części płacika okołośrodkowego"}, {"id": "c", "text": "dolnej części zakrętu przedśrodkowego"}, {"id": "d", "text": "dolnej części zakrętu zaśrodkowego"}, {"id": "e", "text": "hipokampie"}]'::jsonb,
   'c',
   $E$Korowy ośrodek ruchowy dla mięśni żucia (głowy, twarzy) leży w **dolnej części zakrętu przedśrodkowego** (pierwszorzędowa kora ruchowa, pole 4), zgodnie z homunkulusem ruchowym — głowa i twarz reprezentowane są najniżej, bocznie. **Zakręt zaśrodkowy** to kora czuciowa (D błędne). Płacik okołośrodkowy reprezentuje kończynę dolną i krocze, nie żucie. Mięśnie żucia są unerwione przez nerw V3, ale ich reprezentacja korowa to dolny zakręt przedśrodkowy.$E$,
   'kora ruchowa', 'ANATLEK-271'),
(13, 'ANA-OUN',
   'Do jądra brzusznego tylno-bocznego wzgórza dochodzi:',
   '[{"id": "a", "text": "tylko wstęga rdzeniowa"}, {"id": "b", "text": "tylko wstęga boczna"}, {"id": "c", "text": "tylko wstęga rdzeniowa i wstęga przyśrodkowa"}, {"id": "d", "text": "tylko wstęga trójdzielna i wstęga przyśrodkowa"}, {"id": "e", "text": "wstęga rdzeniowa, wstęga trójdzielna i wstęga przyśrodkowa"}]'::jsonb,
   'c',
   $E$Jądro brzuszne tylno-boczne (**VPL**) wzgórza odbiera czucie z **tułowia i kończyn**: drogę czucia głębokiego i epikrytycznego prowadzi **wstęga przyśrodkowa**, a ból i temperaturę **wstęga rdzeniowa**. Czucie z twarzy (wstęga trójdzielna) dochodzi do jądra brzusznego tylno-**przyśrodkowego (VPM)**, nie VPL — dlatego odpowiedzi z wstęgą trójdzielną są błędne dla VPL. Wstęga boczna to droga słuchowa, niezwiązana z VPL.$E$,
   'wzgórze', 'ANATLEK-272'),
(14, 'ANA-OUN',
   'Pęczek smukły tworzą aksony neuronów:',
   '[{"id": "a", "text": "zwojowych dolnych nerwów rdzeniowych"}, {"id": "b", "text": "zwojowych górnych nerwów rdzeniowych"}, {"id": "c", "text": "rogów tylnych dolnych neuromerów"}, {"id": "d", "text": "rogów tylnych górnych neuromerów"}, {"id": "e", "text": "jądra smukłego"}]'::jsonb,
   'a',
   $E$Pęczek smukły (**Golla**) tworzą wypustki ośrodkowe **neuronów zwojów rdzeniowych dolnej połowy ciała** (poniżej Th6 — kończyna dolna, dolny tułów). To I neuron drogi czucia głębokiego, biegnący w sznurze tylnym przyśrodkowo, kończący się w jądrze smukłym rdzenia przedłużonego. Pęczek klinowaty (Burdacha) prowadzi czucie z górnej połowy ciała. Jądro smukłe zawiera II neuron — jego aksony tworzą wstęgę przyśrodkową, nie pęczek (E błędne).$E$,
   'sznury tylne rdzenia', 'ANATLEK-273'),
(15, 'ANA-NAC',
   'Kora powierzchni przyśrodkowej kresomózgowia jest unaczyniana przez tętnice mózgu:',
   '[{"id": "a", "text": "przednią i tylną"}, {"id": "b", "text": "wyłącznie środkową"}, {"id": "c", "text": "środkową i tylną"}, {"id": "d", "text": "wyłącznie przednią"}, {"id": "e", "text": "przednią i środkową"}]'::jsonb,
   'a',
   $E$Powierzchnię przyśrodkową półkuli unaczyniają **tętnica mózgu przednia** (przednio-górna część, do bruzdy ciemieniowo-potylicznej — m.in. zakręt obręczy, część przyśrodkowa płata czołowego i ciemieniowego) oraz **tętnica mózgu tylna** (płat potyliczny i dolno-przyśrodkowa część skroniowego z korą wzrokową). **Tętnica środkowa** zaopatruje głównie powierzchnię boczną (nadboczną). Stąd dla powierzchni przyśrodkowej właściwa para to przednia + tylna.$E$,
   'unaczynienie mózgu', 'ANATLEK-274'),
(16, 'ANA-NAC',
   'Krew z zatoki poprzecznej opony twardej płynie w kierunku:',
   '[{"id": "a", "text": "zatoki prostej"}, {"id": "b", "text": "spływu zatok"}, {"id": "c", "text": "zatoki esowatej"}, {"id": "d", "text": "zatoki skalistej dolnej"}, {"id": "e", "text": "zatoki jamistej"}]'::jsonb,
   'c',
   $E$Zatoka poprzeczna odprowadza krew od **spływu zatok** bocznie ku **zatoce esowatej (sigmoideus)**, która przechodzi w opuszkę górną żyły szyjnej wewnętrznej. Kierunek przepływu: spływ → poprzeczna → esowata → żyła szyjna wewnętrzna. Zatoka prosta i strzałkowa górna uchodzą DO spływu (powyżej poprzecznej), więc krew nie płynie ku nim. Zatoka skalista dolna łączy zatokę jamistą z opuszką żyły szyjnej, nie jest bezpośrednim odpływem poprzecznej.$E$,
   'zatoki opony twardej', 'ANATLEK-276'),
(17, 'ANA-OUN',
   'Jądro pośrednio-boczne rdzenia kręgowego:',
   '[{"id": "a", "text": "leży wyłącznie w segmentach szyjnych"}, {"id": "b", "text": "leży wyłącznie w segmentach krzyżowych"}, {"id": "c", "text": "oddaje włókna przywspółczulne przedzwojowe"}, {"id": "d", "text": "oddaje włókna współczulne przedzwojowe"}, {"id": "e", "text": "jest początkiem drogi rdzeniowo-móżdżkowej"}]'::jsonb,
   'd',
   $E$Jądro pośrednio-boczne (**nucleus intermediolateralis**) leży w rogu bocznym rdzenia na poziomie **Th1–L2/L3** i zawiera ciała **współczulnych neuronów przedzwojowych**. Ich aksony opuszczają rdzeń korzeniem przednim i gałęzią łączącą białą. Przywspółczulne neurony przedzwojowe leżą w jądrze pośrednio-bocznym krzyżowym (S2–S4), nie w klasycznym IML (C błędne). Początkiem drogi rdzeniowo-móżdżkowej jest jądro grzbietowe Clarke'a, nie IML.$E$,
   'rdzeń kręgowy', 'ANATLEK-277'),
(18, 'ANA-NER',
   'Nerw żuchwowy jest nerwem:',
   '[{"id": "a", "text": "ruchowym"}, {"id": "b", "text": "czuciowym"}, {"id": "c", "text": "mieszanym"}, {"id": "d", "text": "ruchowym i przywspółczulnym"}, {"id": "e", "text": "mieszanym i przywspółczulnym"}]'::jsonb,
   'c',
   $E$Nerw żuchwowy (**V3**) jest jedyną **mieszaną** gałęzią nerwu trójdzielnego — prowadzi włókna **czuciowe** (skóra dolnej twarzy, zęby dolne, 2/3 przednie języka, błona śluzowa policzka) oraz **ruchowe** do mięśni żucia, żuchwowo-gnykowego, brzuśca przedniego dwubrzuścowego i napinaczy. Gałęzie oczna (V1) i szczękowa (V2) są czysto czuciowe. Włókna przywspółczulne (do zwojów usznego i podżuchwowego) tylko *towarzyszą* gałęziom V3, ale nie pochodzą z samego nerwu trójdzielnego.$E$,
   'nerw trójdzielny', 'ANATLEK-278'),
(19, 'ANA-OBW',
   'Gałęzie łączące szare nerwów rdzeniowych prowadzą włókna:',
   '[{"id": "a", "text": "współczulne przedzwojowe i trzewnoczuciowe"}, {"id": "b", "text": "wyłącznie współczulne przedzwojowe"}, {"id": "c", "text": "współczulne zazwojowe i trzewnoczuciowe"}, {"id": "d", "text": "współczulne przedzwojowe i przywspółczulne przedzwojowe"}, {"id": "e", "text": "wszystkich rodzajów"}]'::jsonb,
   'c',
   $E$Gałąź łącząca **szara (ramus communicans griseus)** prowadzi **współczulne włókna zazwojowe** (bezmielinowe, stąd szara) ze zwoju pnia współczulnego z powrotem do nerwu rdzeniowego, by zaopatrzyć naczynia, gruczoły potowe i mięśnie przywłosowe. Towarzyszą jej włókna **trzewnoczuciowe**. Występuje przy wszystkich nerwach rdzeniowych. Gałąź biała (ramus albus) prowadzi włókna przedzwojowe i istnieje tylko na poziomie Th1–L2 — stąd opcje z „przedzwojowe” są błędne.$E$,
   'gałęzie łączące', 'ANATLEK-279'),
(20, 'ANA-OBW',
   'Sploty somatyczne powstają z połączenia:',
   '[{"id": "a", "text": "nerwów rdzeniowych"}, {"id": "b", "text": "korzeni przednich nerwów rdzeniowych"}, {"id": "c", "text": "gałęzi brzusznych nerwów rdzeniowych"}, {"id": "d", "text": "gałęzi brzusznych i grzbietowych nerwów rdzeniowych"}, {"id": "e", "text": "korzeni przednich i tylnych nerwów rdzeniowych"}]'::jsonb,
   'c',
   $E$Sploty somatyczne (szyjny, ramienny, lędźwiowy, krzyżowy) powstają z połączenia **gałęzi brzusznych (przednich) nerwów rdzeniowych**. Gałęzie grzbietowe (tylne) unerwiają segmentarnie mięśnie i skórę grzbietu i **nie wchodzą** w skład splotów — stąd D błędne. Cały nerw rdzeniowy (A) to krótki pień zaraz za otworem międzykręgowym, dzielący się na gałęzie; to nie on, lecz jego gałąź brzuszna tworzy sploty. Korzenie łączą się w nerw rdzeniowy wcześniej.$E$,
   'budowa splotów', 'ANATLEK-280'),
(21, 'ANA-NER',
   'Struna bębenkowa jest to:',
   '[{"id": "a", "text": "prążek na błonie bębenkowej"}, {"id": "b", "text": "ścięgno mięśnia napinacza błony bębenkowej"}, {"id": "c", "text": "gałąź czuciowa nerwu przedsionkowego unerwiająca jamę bębenkową"}, {"id": "d", "text": "gałąź nerwu twarzowego prowadząca włókna wydzielnicze i smakowe"}, {"id": "e", "text": "gałąź nerwu twarzowego prowadząca włókna ruchowe"}]'::jsonb,
   'd',
   $E$Struna bębenkowa (**chorda tympani**) to gałąź **nerwu twarzowego (VII)** odchodząca w kanale nerwu twarzowego przed otworem rylcowo-sutkowym. Prowadzi **włókna smakowe** z 2/3 przednich języka oraz **przywspółczulne (wydzielnicze) przedzwojowe** do zwoju podżuchwowego (ślinianki podżuchwowa i podjęzykowa). Przebiega przez jamę bębenkową i dołącza do nerwu językowego (V3). Nie zawiera włókien ruchowych (E błędne).$E$,
   'nerw twarzowy', 'ANATLEK-282'),
(22, 'ANA-CZA',
   'Podstawa strzemiączka umocowana jest:',
   '[{"id": "a", "text": "stawowo do kowadełka"}, {"id": "b", "text": "do mięśnia strzemiączkowego"}, {"id": "c", "text": "do wtórnej błony bębenkowej"}, {"id": "d", "text": "w okienku przedsionka"}, {"id": "e", "text": "w okienku ślimaka"}]'::jsonb,
   'd',
   $E$Podstawa strzemiączka (**basis stapedis**) jest osadzona w **okienku przedsionka (owalnym)** i połączona z jego brzegami **więzadłem pierścieniowatym strzemiączka**, co umożliwia ruch tłokowy przenoszący drgania na perylimfę przedsionka. Główka strzemiączka łączy się stawowo z kowadełkiem (A dotyczy główki, nie podstawy). Okienko ślimaka (okrągłe) zamyka błona bębenkowa wtórna (C/E błędne). Mięsień strzemiączkowy przyczepia się do główki/szyjki, nie do podstawy.$E$,
   'kosteczki słuchowe', 'ANATLEK-283'),
(23, 'ANA-NER',
   'Gruczoł łzowy jest unerwiony przez:',
   '[{"id": "a", "text": "nerw twarzowy drogą nerwu jarzmowego"}, {"id": "b", "text": "nerw twarzowy drogą nerwu podoczodołowego"}, {"id": "c", "text": "nerw oczny drogą nerwu nosowo-rzęskowego"}, {"id": "d", "text": "nerw okoruchowy drogą nerwu łzowego"}, {"id": "e", "text": "zwój szyjny środkowy drogą splotu szyjno-tętniczego"}]'::jsonb,
   'a',
   $E$Wydzielniczo gruczoł łzowy unerwia **nerw twarzowy (VII)**: włókna przedzwojowe biegną nerwem skalistym większym do **zwoju skrzydłowo-podniebiennego**; włókna zazwojowe dołączają do **nerwu szczękowego (V2)**, potem nerwu jarzmowego, a przez gałąź łączącą do **nerwu łzowego (V1)** docierają do gruczołu. Klasycznie droga opisywana „przez nerw jarzmowy” — stąd A. Czuciowo gruczoł zaopatruje nerw łzowy (V1). Współczulne włókna z splotu tętnicy szyjnej tylko towarzyszą.$E$,
   'unerwienie gruczołu łzowego', 'ANATLEK-284'),
(24, 'ANA-NAC',
   'W punkcie nerwowym, tzn. za mięśniem mostkowo-obojczykowo-sutkowym, wychodzi:',
   '[{"id": "a", "text": "gałąź zewnętrzna nerwu dodatkowego"}, {"id": "b", "text": "nerw przeponowy"}, {"id": "c", "text": "gałęzie skórne części nadobojczykowej splotu ramiennego"}, {"id": "d", "text": "gałęzie skórne splotu szyjnego"}, {"id": "e", "text": "korzeń dolny pętli szyjnej"}]'::jsonb,
   'd',
   $E$Punkt nerwowy (**punctum nervosum, punkt Erba**) leży przy tylnym brzegu mięśnia mostkowo-obojczykowo-sutkowego, w połowie jego długości. Wychodzą tu **skórne gałęzie splotu szyjnego**: nerw potyliczny mniejszy, uszny wielki, poprzeczny szyi i nadobojczykowe. Gałąź zewnętrzna nerwu dodatkowego przebiega przez trójkąt boczny szyi, ale nie definiuje punktu nerwowego (A błędne). Nerw przeponowy biegnie głęboko po mięśniu pochyłym przednim, nie wychodzi w punkcie nerwowym.$E$,
   'punkt nerwowy szyi', 'ANATLEK-285'),
(25, 'ANA-OBW',
   'Część podobojczykowa splotu ramiennego w jamie pachowej ma postać:',
   '[{"id": "a", "text": "poziomo nieuporządkowanych włókien nerwowych"}, {"id": "b", "text": "trzech pni nerwowych: górnego, środkowego i dolnego"}, {"id": "c", "text": "trzech pęczków: bocznego, przyśrodkowego i tylnego"}, {"id": "d", "text": "trzech pęczków: bocznego, przyśrodkowego i przedniego"}, {"id": "e", "text": "wyłącznie nerwów: pośrodkowego, łokciowego, promieniowego, pachowego i mięśniowo-skórnego"}]'::jsonb,
   'c',
   $E$Część podobojczykowa splotu ramiennego w jamie pachowej tworzy **trzy pęczki** nazwane wg położenia względem tętnicy pachowej: **boczny, przyśrodkowy i tylny**. Z nich powstają nerwy długie kończyny. Trzy **pnie** (górny, środkowy, dolny) należą do części nadobojczykowej (B błędne). Nie ma pęczka „przedniego” (D błędne). Mnemonik kolejności pni→podziałów→pęczków: „**Real Texans Drink Cold Beer**” (Roots, Trunks, Divisions, Cords, Branches).$E$,
   'splot ramienny', 'ANATLEK-286'),
(26, 'ANA-OBW',
   'Gałąź brzuszna nerwu rdzeniowego S3 zawiera wyłącznie włókna:',
   '[{"id": "a", "text": "ruchowe"}, {"id": "b", "text": "ruchowe i czuciowe"}, {"id": "c", "text": "ruchowe, czuciowe, współczulne i przywspółczulne przedzwojowe"}, {"id": "d", "text": "ruchowe, czuciowe, współczulne i przywspółczulne zazwojowe"}, {"id": "e", "text": "ruchowe, czuciowe, współczulne zazwojowe i przywspółczulne przedzwojowe"}]'::jsonb,
   'e',
   $E$Gałąź brzuszna S3 prowadzi włókna **ruchowe i czuciowe** (somatyczne), **współczulne zazwojowe** (dołączone gałęzią łączącą szarą z pnia współczulnego — na tym poziomie nie ma już gałęzi białych) oraz **przywspółczulne przedzwojowe**, które wychodzą z jądra krzyżowego (S2–S4) i tworzą nerwy trzewne miedniczne. Stąd brak włókien współczulnych przedzwojowych i przywspółczulnych zazwojowych — co eliminuje C i D.$E$,
   'nerwy rdzeniowe krzyżowe', 'ANATLEK-287'),
(27, 'ANA-OBW',
   'Nerwy trzewne miedniczne są to gałęzie:',
   '[{"id": "a", "text": "autonomiczne splotu krezkowego dolnego"}, {"id": "b", "text": "przywspółczulne splotu krzyżowego"}, {"id": "c", "text": "części lędźwiowej pnia współczulnego"}, {"id": "d", "text": "części krzyżowej pnia współczulnego"}, {"id": "e", "text": "splotu podbrzusznego górnego"}]'::jsonb,
   'b',
   $E$Nerwy trzewne miedniczne (**nn. splanchnici pelvici**) to **przywspółczulne** włókna przedzwojowe wychodzące z gałęzi brzusznych **S2–S4** (splot krzyżowy). Wnikają do splotu podbrzusznego dolnego i unerwiają narządy miednicy oraz zstępnicę i esicę. Są to jedyne przywspółczulne nerwy trzewne — pozostałe nerwy trzewne (piersiowe, lędźwiowe, krzyżowe pnia współczulnego) są **współczulne**. Stąd opcje wskazujące pień współczulny (C, D) są błędne.$E$,
   'układ przywspółczulny krzyżowy', 'ANATLEK-288'),
(28, 'ANA-TUL',
   'Przewód tętniczy:',
   '[{"id": "a", "text": "powstaje przez połączenie tętnic pępkowych"}, {"id": "b", "text": "łączy łożysko z aortą płodu"}, {"id": "c", "text": "łączy lewą tętnicę płucną z łukiem aorty"}, {"id": "d", "text": "jest podwójny i łączy łożysko z tętnicami biodrowymi wewnętrznymi"}, {"id": "e", "text": "przebiega na powierzchni trzewnej wątroby płodu"}]'::jsonb,
   'c',
   $E$Przewód tętniczy (**ductus arteriosus, przewód Botalla**) łączy **pień/lewą tętnicę płucną z łukiem aorty**, kierując krew z prawej komory z pominięciem nieczynnych płuc bezpośrednio do aorty zstępującej. Po urodzeniu zarasta w **więzadło tętnicze**. Przewód żylny (Arancjusza) łączy żyłę pępkową z żyłą główną dolną na powierzchni wątroby (E myli z nim). Tętnice pępkowe prowadzą krew do łożyska — nie tworzą przewodu tętniczego.$E$,
   'krążenie płodowe', 'ANATLEK-289'),
(29, 'ANA-TUL',
   'Mięśnie międzyżebrowe wewnętrzne i zewnętrzne leżą w dwu warstwach:',
   '[{"id": "a", "text": "w całej przestrzeni międzyżebrowej"}, {"id": "b", "text": "od kręgosłupa do granicy chrzęstno-kostnej żebra"}, {"id": "c", "text": "od kąta żebra do mostka"}, {"id": "d", "text": "od kąta żebra do granicy chrzęstno-kostnej żebra"}, {"id": "e", "text": "nie pokrywają się w przestrzeni międzyżebrowej"}]'::jsonb,
   'd',
   $E$Obie warstwy leżą obok siebie (dwuwarstwowo) tylko tam, gdzie się **nakładają — od kąta żebra do granicy chrzęstno-kostnej**. Mięsień międzyżebrowy **zewnętrzny** rozciąga się od guzka żebra do połączenia chrzęstno-kostnego (dalej jako błona międzyżebrowa zewnętrzna), a **wewnętrzny** od mostka do kąta żebra (przyśrodkowo błona międzyżebrowa wewnętrzna). Wspólny odcinek dwuwarstwowy to właśnie kąt żebra–granica chrzęstno-kostna. Stąd A i E błędne.$E$,
   'mięśnie międzyżebrowe', 'ANATLEK-290'),
(30, 'ANA-TUL',
   'Pęczek naczyniowo-nerwowy przestrzeni międzyżebrowej zawiera w kolejności od żebra:',
   '[{"id": "a", "text": "tętnicę międzyżebrową, żyły towarzyszące i nerw międzyżebrowy"}, {"id": "b", "text": "żyłę, tętnicę i nerw międzyżebrowe"}, {"id": "c", "text": "żyłę, nerw i tętnicę międzyżebrowe"}, {"id": "d", "text": "tętnicę, żyłę i nerw międzyżebrowe"}, {"id": "e", "text": "nerw, żyłę i tętnicę międzyżebrowe"}]'::jsonb,
   'b',
   $E$W bruździe żebra, licząc **od góry (od żebra) ku dołowi**, pęczek układa się: **żyła – tętnica – nerw** międzyżebrowy. Mnemonik: **VAN** (Vein, Artery, Nerve) od góry. Pęczek biegnie w bruździe na dolnym brzegu żebra, osłonięty nim, dlatego nakłucie opłucnej wykonuje się przy **górnym brzegu żebra niżej leżącego**, by go ominąć. Stąd kolejność z A (tętnica pierwsza) i pozostałe są błędne.$E$,
   'przestrzeń międzyżebrowa', 'ANATLEK-291'),
(31, 'ANA-TUL',
   'Główna droga odpływu chłonki z sutka jest odpływ do węzłów:',
   '[{"id": "a", "text": "nadobojczykowych"}, {"id": "b", "text": "międzyżebrowych przednich"}, {"id": "c", "text": "międzyżebrowych tylnych"}, {"id": "d", "text": "pachowych"}, {"id": "e", "text": "śródpiersiowych przednich"}]'::jsonb,
   'd',
   $E$Główna droga odpływu chłonki z sutka (ok. **75%**) prowadzi do **węzłów pachowych**, zwłaszcza ich grupy piersiowej. Pozostała chłonka (głównie z kwadrantów przyśrodkowych) odpływa do węzłów **piersiowych wewnętrznych (przymostkowych)** wzdłuż naczyń piersiowych wewnętrznych. Dominacja spływu pachowego ma kluczowe znaczenie w raku piersi (węzeł wartowniczy). Stąd węzły nadobojczykowe i śródpiersiowe są drogą wtórną, nie główną.$E$,
   'chłonka sutka', 'ANATLEK-293'),
(32, 'ANA-TUL',
   'Najniżej położone miejsce zachyłka żebrowo-przeponowego leży w linii:',
   '[{"id": "a", "text": "środkowoobojczykowej"}, {"id": "b", "text": "pachowej przedniej"}, {"id": "c", "text": "pachowej środkowej"}, {"id": "d", "text": "pachowej tylnej"}, {"id": "e", "text": "przykregowej"}]'::jsonb,
   'c',
   $E$Zachyłek żebrowo-przeponowy (**recessus costodiaphragmaticus**) sięga najniżej w **linii pachowej środkowej**, gdzie dolna granica opłucnej osiąga żebro X (a płuca tylko VIII). To najgłębszy zachyłek opłucnej, miejsce gromadzenia płynu wysiękowego i typowe dla nakłucia jamy opłucnej. W linii środkowoobojczykowej granica opłucnej leży na żebrze VIII, w przykręgowej na XII — wyżej lub bardziej z tyłu, ale nie najniżej bezwzględnie w pionie ciała.$E$,
   'opłucna', 'ANATLEK-294'),
(33, 'ANA-TRZ',
   'Sieć mniejsza to jest:',
   '[{"id": "a", "text": "zdwojenie otrzewnej pomiędzy przełykiem, żołądkiem i dwunastnicą a wątrobą"}, {"id": "b", "text": "inna nazwa więzadła żołądkowo-okrężniczego"}, {"id": "c", "text": "fałd otrzewnej schodzący z okrężnicy poprzecznej"}, {"id": "d", "text": "fałd otrzewnej schodzący z krzywizny większej żołądka"}, {"id": "e", "text": "krezka wyrostka robaczkowego"}]'::jsonb,
   'a',
   $E$Sieć mniejsza (**omentum minus**) to zdwojenie otrzewnej łączące **krzywiznę mniejszą żołądka i początek dwunastnicy (oraz przełyk brzuszny) z wątrobą**. Składa się z więzadła wątrobowo-żołądkowego i wątrobowo-dwunastniczego (to ostatnie zawiera triadę wrotną: żyłę wrotną, tętnicę wątrobową, przewód żółciowy). Sieć większa schodzi z krzywizny większej (D opisuje sieć większą). Więzadło żołądkowo-okrężnicze należy do sieci większej (B błędne).$E$,
   'otrzewna jamy brzusznej', 'ANATLEK-295'),
(34, 'ANA-TRZ',
   'Błona śluzowa odbytnicy tworzy:',
   '[{"id": "a", "text": "na całej długości podłużne fałdy zwane słupami"}, {"id": "b", "text": "w kanale odbytu podłużne fałdy zwane słupami"}, {"id": "c", "text": "fałdy półksiężycowate"}, {"id": "d", "text": "wcięcia półksiężycowate"}, {"id": "e", "text": "zastawkę okrężniczo-odbytniczą"}]'::jsonb,
   'b',
   $E$W **kanale odbytu** błona śluzowa tworzy podłużne fałdy zwane **słupami odbytowymi (Morgagniego)**, połączone u dołu zastawkami odbytowymi, nad którymi leżą zatoki odbytowe. W bańce odbytnicy występują natomiast **poprzeczne fałdy półksiężycowate** (fałdy Houstona/Kohlrauscha) — to one są półksiężycowate, ale nie nazywają się słupami (C/D mylą poziom i kształt). Słupy odbytowe są wyłącznie cechą kanału odbytu, nie całej odbytnicy (A błędne).$E$,
   'odbytnica i kanał odbytu', 'ANATLEK-296'),
(35, 'ANA-TUL',
   'Pod więzadłem łukowatym pośrodkowym przepony przechodzi:',
   '[{"id": "a", "text": "wyłącznie aorta"}, {"id": "b", "text": "wyłącznie żyła główna dolna"}, {"id": "c", "text": "żyła lędźwiowa wstępująca i przewód piersiowy"}, {"id": "d", "text": "aorta i przewód piersiowy"}, {"id": "e", "text": "przewód piersiowy i pnie błędne"}]'::jsonb,
   'd',
   $E$Więzadło łukowate pośrodkowe ogranicza od przodu **rozwór aortowy (hiatus aorticus)** na poziomie **Th12**, przez który przechodzą **aorta** oraz leżący za nią/po prawej **przewód piersiowy** (czasem żyła nieparzysta). Rozwór aortowy jest najbardziej tylnym i jako jedyny nie przechodzi przez włókna mięśniowe przepony. Pnie błędne przechodzą przez rozwór przełykowy (Th10), żyła główna dolna przez rozwór żyły głównej (Th8) — stąd pozostałe opcje błędne.$E$,
   'przepona', 'ANATLEK-297'),
(36, 'ANA-TRZ',
   'Korzeń krezki jelita krezkowego przyczepia się do ściany brzucha wzdłuż linii biegnącej:',
   '[{"id": "a", "text": "od wysokości drugiego kręgu lędźwiowego po stronie lewej do wysokości prawego stawu biodrowo-krzyżowego"}, {"id": "b", "text": "od wysokości drugiego kręgu lędźwiowego po stronie prawej do wysokości lewego stawu biodrowo-krzyżowego"}, {"id": "c", "text": "poprzecznie, na wysokości dwunastego kręgu piersiowego"}, {"id": "d", "text": "poprzecznie, na wysokości drugiego kręgu lędźwiowego"}, {"id": "e", "text": "esowato, zgodnie z pętlami jelita"}]'::jsonb,
   'a',
   $E$Korzeń krezki jelita cienkiego biegnie skośnie, długości ok. **15 cm**, od **zgięcia dwunastniczo-czczego (po lewej, na wysokości L2)** do **prawego stawu krzyżowo-biodrowego**, gdzie kątnica przechodzi w jelito grube. Przekracza poprzecznie dolną część dwunastnicy, aortę, żyłę główną dolną, prawy moczowód i naczynia jądrowe/jajnikowe. Mimo długiej krezki samo jelito jest upakowane w pętle — stąd przyczep nie jest esowaty (E błędne).$E$,
   'krezka jelita cienkiego', 'ANATLEK-298'),
(37, 'ANA-TRZ',
   'Trzustka jest położona:',
   '[{"id": "a", "text": "pierwotnie zewnątrzotrzewnowo"}, {"id": "b", "text": "w całości wtórnie zaotrzewnowo"}, {"id": "c", "text": "głowa wtórnie zewnątrzotrzewnowo, trzon i ogon wewnątrzotrzewnowo"}, {"id": "d", "text": "wewnątrzotrzewnowo, w krezce okrężnicy poprzecznej"}, {"id": "e", "text": "głowa i trzon wtórnie zewnątrzotrzewnowo, ogon wewnątrzotrzewnowo w więzadle żołądkowo-śledzionowym"}]'::jsonb,
   'e',
   $E$Większość trzustki (głowa i trzon) leży **wtórnie zaotrzewnowo** — pierwotnie miała krezkę, która zrosła się z otrzewną ścienną tylną. **Ogon** trzustki sięga wnęki śledziony w obrębie **więzadła śledzionowo-nerkowego (przy żołądkowo-śledzionowym)** i jest pokryty otrzewną z obu stron, więc leży **wewnątrzotrzewnowo**. Stąd opcja łącząca zaotrzewnowe położenie głowy/trzonu z wewnątrzotrzewnowym ogonem jest poprawna; „w całości zaotrzewnowo” (B) pomija ogon.$E$,
   'trzustka', 'ANATLEK-299'),
(38, 'ANA-TRZ',
   'Lewa bruzda strzałkowa na powierzchni trzewnej wątroby jest utworzona przez:',
   '[{"id": "a", "text": "więzadło tętnicze i więzadło żylne"}, {"id": "b", "text": "dół pęcherzyka żółciowego i żyłę główną dolną"}, {"id": "c", "text": "więzadło żylne i więzadło obłe wątroby"}, {"id": "d", "text": "więzadło tętnicze i więzadło obłe wątroby"}, {"id": "e", "text": "dół pęcherzyka żółciowego i więzadło obłe wątroby"}]'::jsonb,
   'c',
   $E$Lewa bruzda strzałkowa powierzchni trzewnej wątroby oddziela płat lewy od czworobocznego i ogoniastego. Jej część przednia mieści **więzadło obłe wątroby (pozostałość żyły pępkowej)** w szczelinie więzadła obłego, a część tylna **więzadło żylne (pozostałość przewodu żylnego Arancjusza)** w szczelinie więzadła żylnego. Prawą bruzdę tworzą dół pęcherzyka żółciowego (z przodu) i bruzda żyły głównej dolnej (z tyłu) — stąd B opisuje bruzdę prawą.$E$,
   'wątroba', 'ANATLEK-300'),
(39, 'ANA-TRZ',
   'Wątroba:',
   '[{"id": "a", "text": "jest całkowicie pokryta otrzewną, z wyjątkiem wnęki stanowiącej pole nagie"}, {"id": "b", "text": "jest całkowicie pokryta otrzewną, z wyjątkiem wnęki i pola nagiego"}, {"id": "c", "text": "jest całkowicie pokryta otrzewną, z wyjątkiem wrót, pola nagiego i dołu pęcherzyka żółciowego"}, {"id": "d", "text": "posiada pole nagie, niepokryte otrzewną, na powierzchni trzewnej"}, {"id": "e", "text": "posiada pole nagie, niepokryte otrzewną między blaszkami więzadła sierpowatego"}]'::jsonb,
   'c',
   $E$Wątroba jest narządem wewnątrzotrzewnowym, niemal całkowicie pokrytym otrzewną, z wyjątkiem: **wrót (porta hepatis)**, **pola nagiego (area nuda)** na powierzchni przeponowej między blaszkami więzadła wieńcowego oraz **dołu pęcherzyka żółciowego**. Pole nagie leży na powierzchni przeponowej, nie trzewnej (D błędne) i nie między blaszkami więzadła sierpowatego (E błędne). Stąd najpełniejsza i poprawna jest opcja wymieniająca wrota, pole nagie i dół pęcherzyka.$E$,
   'wątroba', 'ANATLEK-302'),
(40, 'ANA-TRZ',
   'Nerka średnio ma wymiary:',
   '[{"id": "a", "text": "9 x 6 x 3 cm"}, {"id": "b", "text": "5 x 4 x 2 cm"}, {"id": "c", "text": "12 x 4 x 2 cm"}, {"id": "d", "text": "6 x 3 x 1,5 cm"}, {"id": "e", "text": "10 x 4 x 4 cm"}]'::jsonb,
   'a',
   $E$Przeciętna nerka dorosłego mierzy ok. **10–12 cm długości, 5–6 cm szerokości i 3–4 cm grubości**, waży ok. 120–170 g. Spośród podanych opcji najbliższy tym wartościom jest wymiar **9 × 6 × 3 cm** — zachowuje prawidłową proporcję długość > szerokość > grubość. Pozostałe opcje są albo zbyt małe (B, D), albo mają nieprawidłową proporcję szerokości do grubości (C zbyt wąska, E zbyt gruba). Stąd A najlepiej oddaje typowe wymiary narządu.$E$,
   'nerki', 'ANATLEK-303'),
(41, 'ANA-TRZ',
   'Przepuklina pachwinowa wrodzona może wystąpić jeśli:',
   '[{"id": "a", "text": "zachowana jest osłonka pochwowa jądra"}, {"id": "b", "text": "zachowana jest przestrzeń surowicza jądra"}, {"id": "c", "text": "niewykształcony jest mięsień dźwigacz jądra"}, {"id": "d", "text": "brak jest włókien międzyodnogowych"}, {"id": "e", "text": "zachowany jest wyrostek pochwowy otrzewnej"}]'::jsonb,
   'e',
   $E$Przepuklina pachwinowa **wrodzona (skośna)** powstaje, gdy **wyrostek pochwowy otrzewnej (processus vaginalis)** nie ulegnie zarośnięciu po zstąpieniu jądra — pozostaje otwarte połączenie jamy otrzewnej z moszną, którym wsuwają się trzewia, podążając drogą powrózka nasiennego przez pierścień pachwinowy głęboki. Osłonka pochwowa jądra (A) jest prawidłowo zachowaną, odgraniczoną częścią wyrostka — to fizjologia, nie przyczyna przepukliny. Brak włókien międzyodnogowych nie warunkuje typu wrodzonego.$E$,
   'kanał pachwinowy', 'ANATLEK-305'),
(42, 'ANA-TRZ',
   'W czasie opróżniania pęcherza moczowego moczowód jest zamykany przez:',
   '[{"id": "a", "text": "mięsień zwieracz moczowodu"}, {"id": "b", "text": "zastawkę moczowodu"}, {"id": "c", "text": "mięsień wypieracz moczu, zaciskający część śródścienną moczowodu"}, {"id": "d", "text": "fałd międzymoczowodowy"}, {"id": "e", "text": "nie jest zamykany i mocz częściowo cofa się do moczowodów"}]'::jsonb,
   'c',
   $E$Moczowód przebija ścianę pęcherza **skośnie**, tworząc część śródścienną. Podczas mikcji skurcz **mięśnia wypieracza (detrusor)** podnosi ciśnienie i jednocześnie **zaciska skośny, śródścienny odcinek moczowodu**, działając jak czynnościowa zastawka zapobiegająca **odpływowi wstecznemu (refluksowi)** moczu. Nie istnieje odrębny anatomiczny zwieracz ani zastawka moczowodu (A, B błędne). Stąd mechanizm jest czynnościowy, oparty na geometrii ujścia i skurczu wypieracza.$E$,
   'pęcherz moczowy', 'ANATLEK-306'),
(43, 'ANA-TUL',
   'Od przedniej ściany aorty brzusznej odchodzą kolejno tętnice:',
   '[{"id": "a", "text": "żołądkowa, śledzionowa, krezkowa"}, {"id": "b", "text": "wątrobowa wspólna, krezkowa górna, krezkowa dolna"}, {"id": "c", "text": "pień trzewny, krezkowa górna, krezkowa dolna"}, {"id": "d", "text": "krezkowa górna, krezkowa dolna, odbytnicza górna"}, {"id": "e", "text": "żołądkowa lewa, wątrobowa wspólna i śledzionowa"}]'::jsonb,
   'c',
   $E$Od **przedniej** ściany aorty brzusznej odchodzą trzy nieparzyste tętnice trzewne, kolejno od góry: **pień trzewny (Th12), tętnica krezkowa górna (L1) i tętnica krezkowa dolna (L3)**. Tętnice żołądkowa lewa, wątrobowa wspólna i śledzionowa są gałęziami pnia trzewnego, nie odchodzą bezpośrednio od aorty (A, E błędne). Tętnica odbytnicza górna jest końcową gałęzią krezkowej dolnej, nie gałęzią aorty (D błędne).$E$,
   'aorta brzuszna', 'ANATLEK-307'),
(44, 'ANA-TUL',
   'Zatoka poprzeczna osierdzia:',
   '[{"id": "a", "text": "leży w koronie serca pomiędzy pniem płucnym a aortą"}, {"id": "b", "text": "jest zachyłkiem jamy osierdzia pomiędzy tętnicami a żyłą główną górną"}, {"id": "c", "text": "jest zachyłkiem jamy osierdzia pomiędzy przedsionkami a komorami"}, {"id": "d", "text": "jest zachyłkiem jamy osierdzia pomiędzy tętnicami a ścianą przedsionków"}, {"id": "e", "text": "jest zachyłkiem jamy osierdzia pomiędzy żyłą główną górną a żyłami płucnymi"}]'::jsonb,
   'd',
   $E$Zatoka poprzeczna osierdzia (**sinus transversus pericardii**) to kanał w jamie osierdzia leżący **z tyłu za pniami tętniczymi (aortą i pniem płucnym), a z przodu przedsionków/żyły głównej górnej**. Powstaje z zagięcia osierdzia surowiczego między „rurką tętniczą” a „rurką żylną” serca. Umożliwia chirurgiczne zaciśnięcie naczyń tętniczych (manewr przy operacjach). Zatoka skośna leży za lewym przedsionkiem, między żyłami płucnymi a żyłą główną dolną (E myli z nią).$E$,
   'osierdzie', 'ANATLEK-308'),
(45, 'ANA-TUL',
   'Optymalnym miejscem osłuchu zastawki dwudzielnej jest:',
   '[{"id": "a", "text": "miejsce uderzenia koniuszkowego"}, {"id": "b", "text": "czwarta przestrzeń międzyżebrowa prawa, przy mostku"}, {"id": "c", "text": "rzut tej zastawki na mostku"}, {"id": "d", "text": "druga przestrzeń międzyżebrowa prawa, przy mostku"}, {"id": "e", "text": "druga przestrzeń międzyżebrowa lewa, przy mostku"}]'::jsonb,
   'a',
   $E$Zastawkę dwudzielną (mitralną) osłuchuje się nad **koniuszkiem serca**, czyli w **V lewej przestrzeni międzyżebrowej w linii środkowoobojczykowej** — tam, gdzie wyczuwalne jest uderzenie koniuszkowe. Punkty osłuchowe nie pokrywają się z rzutem anatomicznym zastawek (C błędne), bo dźwięk przewodzony jest zgodnie z kierunkiem strumienia krwi. II przestrzeń prawa to zastawka aortalna, II lewa — pnia płucnego, dolny brzeg mostka — trójdzielna.$E$,
   'osłuchiwanie serca', 'ANATLEK-309'),
(46, 'ANA-TUL',
   'Stożek tętniczy to jest:',
   '[{"id": "a", "text": "początkowy odcinek aorty"}, {"id": "b", "text": "początkowy odcinek pnia płucnego"}, {"id": "c", "text": "odpływowa część komory serca"}, {"id": "d", "text": "miejsce umocowania zastawek przedsionkowo-komorowych"}, {"id": "e", "text": "odejście tętnic wieńcowych od aorty"}]'::jsonb,
   'c',
   $E$Stożek tętniczy (**conus arteriosus, infundibulum**) to gładkościenna, lejkowata **droga odpływu prawej komory**, prowadząca krew ku ujściu pnia płucnego. Rozwija się z embrionalnego bulbus cordis. Jest częścią komory, nie samego pnia płucnego ani aorty (A, B błędne). Zastawki przedsionkowo-komorowe są umocowane w pierścieniach włóknistych szkieletu serca, nie w stożku (D błędne). Lewa komora ma analogiczny, krótszy przedsionek aorty.$E$,
   'budowa serca', 'ANATLEK-311'),
(47, 'ANA-NAC',
   'Kąt żylny to jest miejsce:',
   '[{"id": "a", "text": "powstania żyły głównej dolnej z żył biodrowych wspólnych"}, {"id": "b", "text": "powstania żyły biodrowej wspólnej z żyły biodrowej wewnętrznej i zewnętrznej"}, {"id": "c", "text": "powstania żyły ramienno-głowowej z żyły szyjnej wewnętrznej i podobojczykowej"}, {"id": "d", "text": "powstania żyły ramienno-głowowej z żyły szyjnej wspólnej i podobojczykowej"}, {"id": "e", "text": "dojścia żył nerkowych do żyły głównej dolnej"}]'::jsonb,
   'c',
   $E$Kąt żylny (**angulus venosus**) to miejsce połączenia **żyły szyjnej wewnętrznej z żyłą podobojczykową**, dające początek żyle ramienno-głowowej. Do kąta żylnego **lewego** uchodzi **przewód piersiowy**, do **prawego** przewód chłonny prawy — stąd jego duże znaczenie dla spływu chłonki. Nie istnieje „żyła szyjna wspólna” (D błędne — to mylenie z tętnicą szyjną wspólną). Pozostałe opcje dotyczą żył jamy brzusznej i miednicy.$E$,
   'żyły szyi', 'ANATLEK-312'),
(48, 'ANA-TRZ',
   'Żyły gonadowe uchodzą do:',
   '[{"id": "a", "text": "u mężczyzn obydwie do żyły głównej dolnej"}, {"id": "b", "text": "żył biodrowych wewnętrznych"}, {"id": "c", "text": "żył biodrowych zewnętrznych"}, {"id": "d", "text": "u kobiet do żył macicznych"}, {"id": "e", "text": "prawa do żyły głównej dolnej, lewa do żyły nerkowej lewej"}]'::jsonb,
   'e',
   $E$Żyła gonadowa (jądrowa/jajnikowa) **prawa** uchodzi skośnie wprost do **żyły głównej dolnej**, natomiast **lewa** pod kątem prostym do **żyły nerkowej lewej**. Ta asymetria sprzyja zastojowi po lewej i tłumaczy częstszą lewostronną **żylakę powrózka nasiennego (varicocele)** oraz ucisk żyły nerkowej lewej (efekt „nutcracker”). Dotyczy obu płci, więc twierdzenie o ujściu obu żył do IVC (A) lub do żył macicznych (D) jest błędne.$E$,
   'żyły gonadowe', 'ANATLEK-313'),
(49, 'ANA-MIE',
   'Szew skrzydłowo-żuchwowy łączy mięsień:',
   '[{"id": "a", "text": "policzkowy ze zwieraczem górnym gardła"}, {"id": "b", "text": "policzkowy z zwieraczem środkowym gardła"}, {"id": "c", "text": "policzkowy z mięśniem zwaczem"}, {"id": "d", "text": "zwacz z mięśniem skrzydłowym przyśrodkowym"}, {"id": "e", "text": "skrzydłowy boczny z mięśniami języka"}]'::jsonb,
   'a',
   $E$Szew skrzydłowo-żuchwowy (**raphe pterygomandibularis**) to pasmo ścięgniste rozpięte między haczykiem skrzydłowym kości klinowej a kresą żuchwowo-gnykową żuchwy. Stanowi wspólne miejsce przyczepu **mięśnia policzkowego (z przodu)** i **mięśnia zwieracza górnego gardła (z tyłu)**. Jest istotnym punktem orientacyjnym przy znieczuleniu nerwu zębodołowego dolnego. Stąd opcje łączące policzkowy ze zwaczem lub ze zwieraczem środkowym są błędne.$E$,
   'ściana gardła i policzka', 'ANATLEK-314'),
(50, 'ANA-MIE',
   'Z mięśni wyrazowych pokrycie powięziowe posiada:',
   '[{"id": "a", "text": "okrężny ust"}, {"id": "b", "text": "okrężny oka"}, {"id": "c", "text": "policzkowy"}, {"id": "d", "text": "jarzmowy większy"}, {"id": "e", "text": "jarzmowy mniejszy"}]'::jsonb,
   'c',
   $E$Większość mięśni mimicznych (wyrazowych) nie ma powięzi i przyczepia się bezpośrednio do skóry, co umożliwia mimikę. Wyjątkiem jest **mięsień policzkowy (m. buccinator)**, który pokryty jest **powięzią policzkowo-gardłową** — to ona przechodzi ku tyłowi na zwieracz górny gardła. Policzkowy bywa zaliczany do mięśni mimicznych, ale czynnościowo wspomaga żucie. Mięśnie okrężne i jarzmowe pozbawione są wyraźnej osłonki powięziowej, dlatego pozostałe opcje są błędne.$E$,
   'mięśnie mimiczne', 'ANATLEK-315'),
(51, 'ANA-JAM',
   'Zachyłek gruszkowaty jest położony:',
   '[{"id": "a", "text": "pomiędzy łukami: podniebienno-językowym i podniebienno-gardłowym"}, {"id": "b", "text": "do boku od nozdrzy tylnych"}, {"id": "c", "text": "do boku od cieśni gardzieli"}, {"id": "d", "text": "do boku od wejścia do krtani"}, {"id": "e", "text": "w przejściu gardła w przełyk"}]'::jsonb,
   'd',
   $E$Zachyłek gruszkowaty (**recessus piriformis**) to parzyste zagłębienie części krtaniowej gardła, położone **bocznie od wejścia do krtani**, między fałdem nalewkowo-nagłośniowym a przyśrodkową powierzchnią chrząstki tarczowatej. Pod jego błoną śluzową biegnie **nerw krtaniowy górny** (gałąź wewnętrzna). Jest typowym miejscem zaklinowania ciał obcych (ości). Między łukami podniebiennymi leży migdałek podniebienny (A błędne), nie zachyłek gruszkowaty.$E$,
   'gardło', 'ANATLEK-316'),
(52, 'ANA-NAC',
   'Mięśnie i więzadła odchodzące od wyrostka rylcowatego oddzielają:',
   '[{"id": "a", "text": "przestrzeń przygardłową od przestrzeni zażuchwowej"}, {"id": "b", "text": "przestrzeń przygardłową od dołu skrzydłowo-podniebiennego"}, {"id": "c", "text": "dół podskroniowy od dołu skrzydłowo-podniebiennego"}, {"id": "d", "text": "przestrzeń przygardłową od zagardłowej"}, {"id": "e", "text": "okolicę przyuszniczo-żwaczową od przestrzeni zażuchwowej"}]'::jsonb,
   'a',
   $E$Mięśnie i więzadła odchodzące od wyrostka rylcowatego tworzą tzw. **pęczek (bukiet) Riolana** — m. rylcowo-językowy, rylcowo-gnykowy, rylcowo-gardłowy oraz więzadła rylcowo-gnykowe i rylcowo-żuchwowe. Tworzą one **przeponę rylcowatą**, która oddziela **przestrzeń przygardłową od przestrzeni zażuchwowej (przyusznej)**. Stąd to przegroda między tymi dwiema przestrzeniami, nie między przygardłową a zagardłową (D błędne). Dzieli przestrzeń przygardłową na część przednią i tylną.$E$,
   'przestrzenie szyi', 'ANATLEK-317'),
(53, 'ANA-CZA',
   'Szczelina oczodołowa dolna łączy oczodół z:',
   '[{"id": "a", "text": "dołem środkowym czaszki"}, {"id": "b", "text": "dołem przednim czaszki"}, {"id": "c", "text": "przestrzenią zażuchwową"}, {"id": "d", "text": "dołem skrzydłowo-podniebiennym"}, {"id": "e", "text": "brak poprawnej odpowiedzi"}]'::jsonb,
   'd',
   $E$Szczelina oczodołowa dolna łączy oczodół z **dołem skrzydłowo-podniebiennym** (przyśrodkowo) oraz z **dołem podskroniowym** (bocznie). Przechodzą przez nią m.in. nerw szczękowy (V2) i jego gałąź podoczodołowa, nerw jarzmowy oraz naczynia podoczodołowe. Szczelina oczodołowa **górna** łączy oczodół z dołem środkowym czaszki (A opisuje górną). Stąd dla szczeliny dolnej poprawne jest połączenie z dołem skrzydłowo-podniebiennym.$E$,
   'oczodół', 'ANATLEK-318'),
(54, 'ANA-NAC',
   'Trójkąt podżuchwowy ograniczony jest przez:',
   '[{"id": "a", "text": "przedni brzusiec mięśnia dwubrzuścowego, brzeg mięśnia mostkowo-obojczykowo-sutkowego i brzeg trzonu żuchwy"}, {"id": "b", "text": "tylny brzusiec mięśnia dwubrzuścowego, brzeg mięśnia mostkowo-obojczykowo-sutkowego i górny brzusiec mięśnia łopatkowo-gnykowego"}, {"id": "c", "text": "brzegi mięśni: żuchwowo-gnykowego, gnykowo-językowego i brzeg trzonu żuchwy"}, {"id": "d", "text": "brzuśce mięśnia dwubrzuścowego i brzeg trzonu żuchwy"}, {"id": "e", "text": "przyśrodkowe brzegi przednich brzuśców mięśni dwubrzuścowych i kość gnykową"}]'::jsonb,
   'd',
   $E$Trójkąt podżuchwowy (**trigonum submandibulare**) ograniczają: od góry **dolny brzeg trzonu żuchwy**, a od dołu **przedni i tylny brzusiec mięśnia dwubrzuścowego**. Dno tworzą mięśnie żuchwowo-gnykowy i gnykowo-językowy. Mieści śliniankę podżuchwową, węzły chłonne i nerw językowy. Opcja E opisuje trójkąt podbródkowy (między przednimi brzuścami i kością gnykową), C wymienia jedynie mięśnie dna, nie granice.$E$,
   'trójkąty szyi', 'ANATLEK-319'),
(55, 'ANA-NAC',
   'Żyła szczękowa:',
   '[{"id": "a", "text": "łączy się z żyłą skroniową powierzchowną w żyłę szyjną zewnętrzną"}, {"id": "b", "text": "towarzyszy tętnicy szczękowej w całym jej przebiegu"}, {"id": "c", "text": "łączy się z żyłą skroniową powierzchowną w żyłę zażuchwową"}, {"id": "d", "text": "łączy splot skrzydłowy z żyłą szyjną zewnętrzną"}, {"id": "e", "text": "łączy splot skrzydłowy z żyłą twarzową"}]'::jsonb,
   'c',
   $E$Żyła szczękowa odprowadza krew ze **splotu skrzydłowego** i łączy się z **żyłą skroniową powierzchowną**, tworząc **żyłę zażuchwową (v. retromandibularis)** w obrębie ślinianki przyusznej. Żyła zażuchwowa dzieli się następnie na gałąź przednią (do żyły twarzowej → szyjna wewnętrzna) i tylną (do żyły szyjnej zewnętrznej). Sama żyła szczękowa nie towarzyszy tętnicy na całej długości jako pień (B błędne) — odprowadza krew głównie ze splotu skrzydłowego.$E$,
   'żyły twarzy', 'ANATLEK-320'),
(56, 'ANA-NAC',
   'Trójkąt tętnicy szyjnej ograniczają:',
   '[{"id": "a", "text": "brzeg mięśnia mostkowo-obojczykowo-sutkowego, brzusiec tylny mięśnia dwubrzuścowego, mięsień mostkowo-gnykowy"}, {"id": "b", "text": "brzeg mięśnia mostkowo-obojczykowo-sutkowego, brzusiec przedni mięśnia dwubrzuścowego, mięsień mostkowo-gnykowy"}, {"id": "c", "text": "brzeg mięśnia mostkowo-obojczykowo-sutkowego, brzusiec dolny mięśnia łopatkowo-gnykowego, brzusiec tylny mięśnia dwubrzuścowego"}, {"id": "d", "text": "brzeg mięśnia mostkowo-obojczykowo-sutkowego, brzusiec górny mięśnia łopatkowo-gnykowego, brzusiec tylny mięśnia dwubrzuścowego"}, {"id": "e", "text": "brzusiec mięśnia dwubrzuścowego i brzeg trzonu żuchwy"}]'::jsonb,
   'd',
   $E$Trójkąt tętnicy szyjnej (**trigonum caroticum**) ograniczają: z tyłu przedni brzeg **mięśnia mostkowo-obojczykowo-sutkowego**, z góry **tylny brzusiec mięśnia dwubrzuścowego**, z dołu/przodu **górny brzusiec mięśnia łopatkowo-gnykowego**. W jego obrębie leży podział tętnicy szyjnej wspólnej oraz nerw błędny i podjęzykowy. Opcja z brzuścem dolnym łopatkowo-gnykowego (C) dotyczy trójkąta łopatkowo-tchawiczego, nie tętnicy szyjnej.$E$,
   'trójkąty szyi', 'ANATLEK-322'),
(57, 'ANA-NAC',
   'Odcinek szczytny pnia współczulnego jest położony:',
   '[{"id": "a", "text": "w przestrzeni zamostkowej, za krzywizną przedkręgową"}, {"id": "b", "text": "w przestrzeni szyi"}, {"id": "c", "text": "w pęczku naczyniowo-nerwowym szyi"}, {"id": "d", "text": "pomiędzy mięśniami przedtrzonowymi szyi"}, {"id": "e", "text": "w szczelinie tylnej mięśni pochyłych"}]'::jsonb,
   'b',
   $E$Pień współczulny szyjny leży na **blaszce przedkręgowej powięzi szyi**, ku tyłowi od pęczka naczyniowo-nerwowego, na mięśniach przedkręgowych (długim głowy i szyi). Jego odcinek szyjny (szczytny — najwyższy, ze zwojem szyjnym górnym) położony jest **w obrębie szyi**, poza pęczkiem naczyniowo-nerwowym (C błędne). Nie biegnie zamostkowo (to odcinek piersiowy) ani w szczelinie pochyłych. Stąd najogólniej poprawne: w przestrzeni szyi.$E$,
   'pień współczulny szyjny', 'ANATLEK-323'),
(58, 'ANA-TRZ',
   'Fałdy na wewnętrznej powierzchni ściany przełyku przebiegają:',
   '[{"id": "a", "text": "okrężnie w górnej i podłużnie w dolnej części przełyku"}, {"id": "b", "text": "podłużnie i są fałdami błony śluzowej"}, {"id": "c", "text": "podłużnie i są fałdami mięśniówki przełyku"}, {"id": "d", "text": "okrężnie i są fałdami błony mięśniowej"}, {"id": "e", "text": "ściana przełyku nie posiada fałdów"}]'::jsonb,
   'b',
   $E$Błona śluzowa przełyku w stanie spoczynku tworzy **podłużne fałdy**, dzięki którym światło na przekroju ma gwiaździsty zarys; rozprostowują się one przy przechodzeniu kęsa pokarmowego. Są to fałdy **błony śluzowej** (z udziałem podśluzowej), a nie mięśniówki (C błędne). Mają przebieg podłużny na całej długości, nie zmieniają się na okrężne (A, D błędne). Umożliwiają rozszerzalność przełyku podczas połykania.$E$,
   'przełyk', 'ANATLEK-324'),
(59, 'ANA-NER',
   'Lewy nerw błędny w przebiegu przez szyję:',
   '[{"id": "a", "text": "krzyżuje lewą tętnicę podobojczykową od przodu"}, {"id": "b", "text": "krzyżuje lewą tętnicę podobojczykową od tyłu"}, {"id": "c", "text": "przebiega pomiędzy lewą tętnicą podobojczykową i lewą tętnicą szyjną wspólną"}, {"id": "d", "text": "leży na mięśniu pochyłym przednim"}, {"id": "e", "text": "oddaje nerw krtaniowy wsteczny"}]'::jsonb,
   'a',
   $E$Lewy nerw błędny schodzi w pęczku naczyniowo-nerwowym szyi i wchodząc do klatki **krzyżuje lewą tętnicę podobojczykową od przodu**, po czym przebiega po łuku aorty, gdzie oddaje **lewy nerw krtaniowy wsteczny** zawracający pod łukiem. Oddanie nerwu krtaniowego wstecznego (E) zachodzi w klatce, nie na szyi — pytanie dotyczy przebiegu szyjnego, więc opisem szyjnym jest krzyżowanie tętnicy podobojczykowej od przodu.$E$,
   'nerw błędny', 'ANATLEK-325'),
(60, 'ANA-NAC',
   'Tętnica szyjna zewnętrzna oddaje większość gałęzi w obrębie:',
   '[{"id": "a", "text": "trójkąta tętnicy szyjnej"}, {"id": "b", "text": "trójkąta łopatkowo-obojczykowego"}, {"id": "c", "text": "przestrzeni zażuchwowej"}, {"id": "d", "text": "okolicy mostkowo-sutkowo-obojczykowej"}, {"id": "e", "text": "przestrzeni przygardłowej"}]'::jsonb,
   'a',
   $E$Tętnica szyjna zewnętrzna powstaje z rozwidlenia tętnicy szyjnej wspólnej na wysokości górnego brzegu chrząstki tarczowatej, w obrębie **trójkąta tętnicy szyjnej**, i to tu oddaje większość gałęzi: tarczową górną, językową, twarzową, gardłową wstępującą, potyliczną i uszną tylną. Gałęzie końcowe (szczękowa i skroniowa powierzchowna) odchodzą dopiero w obrębie ślinianki przyusznej (zażuchwowo). Stąd „większość” przypada na trójkąt tętnicy szyjnej.$E$,
   'tętnica szyjna zewnętrzna', 'ANATLEK-326'),
(61, 'ANA-NAC',
   'Powyżej górnego brzegu chrząstki tarczowatej pęczek naczyniowo-nerwowy szyi zawiera:',
   '[{"id": "a", "text": "tętnicę szyjną wewnętrzną, żyłę szyjną wewnętrzną i nerw błędny"}, {"id": "b", "text": "tętnicę szyjną wspólną, żyłę szyjną wewnętrzną i nerw błędny"}, {"id": "c", "text": "tętnicę szyjną zewnętrzną, żyłę szyjną zewnętrzną i nerw błędny"}, {"id": "d", "text": "tętnicę skroniową powierzchowną, żyłę szyjną wewnętrzną i nerw błędny"}, {"id": "e", "text": "tętnicę szyjną wewnętrzną, żyłę szyjną wewnętrzną i nerw przeponowy"}]'::jsonb,
   'a',
   $E$Tętnica szyjna wspólna dzieli się na wysokości **górnego brzegu chrząstki tarczowatej (C3/C4)**. Powyżej tego poziomu w pęczku naczyniowo-nerwowym szyi biegnie już **tętnica szyjna wewnętrzna** (zewnętrzna odchyla się przyśrodkowo-przednio), wraz z **żyłą szyjną wewnętrzną** i **nerwem błędnym** w pochewce naczyniowej. Poniżej podziału byłaby tętnica szyjna wspólna (B). Nerw przeponowy nie wchodzi w skład pęczka (E błędne).$E$,
   'pęczek naczyniowo-nerwowy szyi', 'ANATLEK-327'),
(62, 'ANA-NAC',
   'W trójkącie łopatkowo-czworobocznym przebiegają:',
   '[{"id": "a", "text": "gałęzie skórne splotu ramiennego i nerw dodatkowy"}, {"id": "b", "text": "gałęzie skórne splotu szyjnego i nerw dodatkowy"}, {"id": "c", "text": "gałęzie skórne splotu ramiennego i nerw przeponowy"}, {"id": "d", "text": "splot ramienny i tętnica podobojczykowa"}, {"id": "e", "text": "żyła szyjna zewnętrzna"}]'::jsonb,
   'b',
   $E$Trójkąt łopatkowo-czworoboczny (potyliczny) to górna część trójkąta bocznego szyi, powyżej dolnego brzuśca mięśnia łopatkowo-gnykowego. Przebiegają w nim **skórne gałęzie splotu szyjnego** (wychodzące z punktu nerwowego) oraz **gałąź zewnętrzna nerwu dodatkowego (XI)** zdążająca do mięśnia czworobocznego. Splot ramienny i tętnica podobojczykowa leżą w dolnym trójkącie łopatkowo-obojczykowym (D opisuje go), nie w czworobocznym.$E$,
   'trójkąty szyi', 'ANATLEK-328'),
(63, 'ANA-TUL',
   'Pierwsza para żeber połączona jest z mostkiem:',
   '[{"id": "a", "text": "więzozrostem"}, {"id": "b", "text": "chrząstkozrostem"}, {"id": "c", "text": "połączeniem wolnym"}, {"id": "d", "text": "kościozrostem"}, {"id": "e", "text": "nie łączy się z mostkiem"}]'::jsonb,
   'b',
   $E$Pierwsze żebro łączy się z rękojeścią mostka za pośrednictwem chrząstki żebrowej **trwałym chrząstkozrostem (synchondrosis sternocostalis prima)** — to połączenie nieruchome, w odróżnieniu od żeber II–VII, które tworzą z mostkiem prawdziwe **stawy mostkowo-żebrowe** (maziowe). Stąd pierwsze żebro nie ma jamy stawowej. Żebra VIII–X łączą się pośrednio (chrzęstnie z żebrem wyżej), a XI–XII są wolne. To tłumaczy, dlaczego B jest poprawne.$E$,
   'klatka piersiowa', 'ANATLEK-329'),
(64, 'ANA-KON',
   'Ruchy ręki w osi strzałkowej to:',
   '[{"id": "a", "text": "nawracanie i odwracanie"}, {"id": "b", "text": "odwodzenie"}, {"id": "c", "text": "odwodzenie i przywodzenie"}, {"id": "d", "text": "zginanie i prostowanie"}, {"id": "e", "text": "obracanie"}]'::jsonb,
   'c',
   $E$Ruchy wokół osi **strzałkowej** (przednio-tylnej) zachodzą w płaszczyźnie czołowej — dla ręki w stawie promieniowo-nadgarstkowym są to **odwodzenie (promieniowe) i przywodzenie (łokciowe)**. Zginanie i prostowanie (D) odbywają się wokół osi poprzecznej (czołowej), w płaszczyźnie strzałkowej. Nawracanie i odwracanie dotyczą przedramienia (ruch obrotowy), nie ręki w osi strzałkowej. Stąd poprawne jest odwodzenie i przywodzenie.$E$,
   'ruchy w stawach', 'ANATLEK-330'),
(65, 'ANA-KON',
   'W skład ręki wchodzą:',
   '[{"id": "a", "text": "ramię, przedramię i dłoń"}, {"id": "b", "text": "śródręcze i palce"}, {"id": "c", "text": "nadgarstek, śródręcze i palce"}, {"id": "d", "text": "obręcz, ramię, przedramię i dłoń"}, {"id": "e", "text": "ręka nie jest określeniem anatomicznym"}]'::jsonb,
   'c',
   $E$W anatomii **ręka (manus)** to najbardziej obwodowa część kończyny górnej, na którą składają się: **nadgarstek (carpus), śródręcze (metacarpus) i palce (digiti)**. Pojęcie to nie obejmuje ramienia ani przedramienia (A, D błędne — to wyższe odcinki). Śródręcze i palce bez nadgarstka (B) to niepełny opis. Termin „dłoń” odnosi się tylko do powierzchni dłoniowej ręki, nie do całego segmentu, dlatego nie zastępuje pojęcia ręki.$E$,
   'podział kończyny górnej', 'ANATLEK-331'),
(66, 'ANA-KON',
   'Podczas nawracania przedramienia:',
   '[{"id": "a", "text": "kość łokciowa porusza się wyłącznie względem kości promieniowej"}, {"id": "b", "text": "kość łokciowa porusza się wyłącznie względem kości ramiennej"}, {"id": "c", "text": "kość łokciowa porusza się względem kości promieniowej i ramiennej"}, {"id": "d", "text": "kość promieniowa porusza się względem kości ramiennej i łokciowej"}, {"id": "e", "text": "kość promieniowa porusza się wyłącznie względem kości łokciowej"}]'::jsonb,
   'd',
   $E$Podczas nawracania (pronacji) ruchoma jest **kość promieniowa**, która „obraca się” wokół kości łokciowej, krzyżując się z nią. Ruch zachodzi w stawach promieniowo-łokciowych bliższym i dalszym (względem **kości łokciowej**) oraz w stawie ramienno-promieniowym, gdzie głowa kości promieniowej obraca się względem **główki kości ramiennej**. Stąd promieniowa porusza się względem zarówno łokciowej, jak i ramiennej. Kość łokciowa pozostaje względnie nieruchoma.$E$,
   'stawy przedramienia', 'ANATLEK-332'),
(67, 'ANA-KON',
   'Prawa i lewa kość miednicza łączą się ze sobą:',
   '[{"id": "a", "text": "wyłącznie przez kość krzyżową, stawami krzyżowo-biodrowymi"}, {"id": "b", "text": "żyłami więzozrostami pomiędzy kośćmi łonowymi"}, {"id": "c", "text": "wyłącznie chrząstkozrostem pomiędzy kośćmi łonowymi"}, {"id": "d", "text": "więzozrostami i chrząstkozrostem pomiędzy kośćmi łonowymi"}, {"id": "e", "text": "wyłącznie spojeniem łonowym"}]'::jsonb,
   'e',
   $E$Prawa i lewa kość miednicza łączą się ze sobą z przodu **spojeniem łonowym (symphysis pubica)** — to połączenie półścisłe (chrząstkozrost włóknisty) z krążkiem międzyłonowym z chrząstki włóknistej, wzmocnione więzadłami łonowymi. Z tyłu łączą się z kością krzyżową (nie bezpośrednio ze sobą). Określenie „spojenie łonowe” obejmuje cały ten zespół połączenia półścisłego.$E$,
   'miednica kostna', 'ANATLEK-333'),
(68, 'ANA-KON',
   'Mięśnie prostowniki na przedramieniu leżą w grupie:',
   '[{"id": "a", "text": "przedniej"}, {"id": "b", "text": "wyłącznie tylnej"}, {"id": "c", "text": "tylnej i bocznej"}, {"id": "d", "text": "tylnej i przyśrodkowej"}, {"id": "e", "text": "wyłącznie przyśrodkowej"}]'::jsonb,
   'c',
   $E$Mięśnie prostujące nadgarstek i palce leżą na przedramieniu w grupie **tylnej** (właściwe prostowniki, m.in. prostownik palców, łokciowy nadgarstka) oraz w grupie **bocznej (promieniowej)** — należą tu prostowniki promieniowe nadgarstka długi i krótki oraz ramienno-promieniowy. Grupa przednia to zginacze i nawracacze. Stąd prostowniki obejmują przedział tylny i boczny, a nie wyłącznie tylny (B) ani przyśrodkowy (E).$E$,
   'mięśnie przedramienia', 'ANATLEK-334'),
(69, 'ANA-KON',
   'Ścięgno jest to:',
   '[{"id": "a", "text": "stały element stawu"}, {"id": "b", "text": "dodatkowy element stawu"}, {"id": "c", "text": "część mięśnia przyczepiająca się do szkieletu"}, {"id": "d", "text": "błona osłaniająca grupę mięśniową lub pojedyncze mięśnie"}, {"id": "e", "text": "odmiana więzozrostu"}]'::jsonb,
   'c',
   $E$Ścięgno (**tendo**) to zbudowana z gęstej tkanki łącznej włóknistej **część mięśnia, którą przyczepia się on do kości (szkieletu)**. Przenosi siłę skurczu mięśnia na kość. Nie jest elementem stawu (A, B błędne) ani osłonką mięśnia — taką jest powięź (D opisuje powięź). Więzozrost (E) to rodzaj połączenia kości tkanką włóknistą (np. więzadłem), a nie ścięgno. Stąd jedyną poprawną definicją jest część mięśnia łącząca go ze szkieletem.$E$,
   'budowa mięśnia', 'ANATLEK-335'),
(70, 'ANA-KON',
   'Rozcięgno jest to:',
   '[{"id": "a", "text": "zwielokrotnienie ścięgna mięśnia"}, {"id": "b", "text": "ścięgno pomiędzy głowami mięśnia dwubrzuścowego"}, {"id": "c", "text": "szerokie, płaskie ścięgno"}, {"id": "d", "text": "rodzaj więzozrostu"}, {"id": "e", "text": "rodzaj więzadła"}]'::jsonb,
   'c',
   $E$Rozcięgno (**aponeurosis**) to **szerokie, płaskie ścięgno**, którym płaskie mięśnie (np. mięśnie szerokie brzucha, mięsień naramienny czy czepiec ścięgnisty głowy) przyczepiają się do kości lub łączą z innymi mięśniami. W odróżnieniu od ścięgna powrózkowatego ma kształt blaszki. Ścięgno pośrednie między brzuścami (B) to inna struktura (ścięgno pośrednie), a nie rozcięgno. Nie jest też więzozrostem ani więzadłem (D, E błędne).$E$,
   'budowa mięśnia', 'ANATLEK-336'),
(71, 'ANA-TUL',
   'Rzut koniuszka serca znajduje się:',
   '[{"id": "a", "text": "w trzeciej przestrzeni międzyżebrowej lewej w linii przymostkowej"}, {"id": "b", "text": "w czwartej przestrzeni międzyżebrowej lewej w linii przymostkowej"}, {"id": "c", "text": "w czwartej przestrzeni międzyżebrowej lewej w linii środkowoobojczykowej"}, {"id": "d", "text": "w piątej przestrzeni międzyżebrowej lewej w linii przymostkowej"}, {"id": "e", "text": "w piątej przestrzeni międzyżebrowej lewej pomiędzy linią przymostkową a środkowoobojczykową"}]'::jsonb,
   'e',
   $E$Koniuszek serca rzutuje się w **V lewej przestrzeni międzyżebrowej**, nieco **przyśrodkowo od linii środkowoobojczykowej** (ok. 1–2 cm), czyli pomiędzy linią przymostkową a środkowoobojczykową. Tam wyczuwa się uderzenie koniuszkowe i osłuchuje zastawkę mitralną. Lokalizacja dokładnie „w linii środkowoobojczykowej w IV międzyżebrzu” (C) jest błędna — to zbyt wysoko i zbyt bocznie. Stąd najściślej poprawne jest położenie w V międzyżebrzu, przyśrodkowo od linii środkowoobojczykowej.$E$,
   'rzuty serca', 'ANATLEK-337'),
(72, 'ANA-TUL',
   'Worek osierdziowy składa się z:',
   '[{"id": "a", "text": "wyłącznie z osierdzia włóknistego"}, {"id": "b", "text": "osierdzia włóknistego, surowiczego ściennego i trzewnego"}, {"id": "c", "text": "osierdzia włóknistego i surowiczego ściennego"}, {"id": "d", "text": "osierdzia włóknistego i surowiczego trzewnego"}, {"id": "e", "text": "blaszki ściennej i trzewnej osierdzia surowiczego"}]'::jsonb,
   'b',
   $E$Osierdzie składa się z zewnętrznego **osierdzia włóknistego** oraz wewnętrznego **osierdzia surowiczego**, które ma dwie blaszki: **ścienną** (wyściela osierdzie włókniste) i **trzewną (nasierdzie)** pokrywającą serce. Między blaszkami znajduje się jama osierdzia z płynem surowiczym. Pełny opis worka osierdziowego musi obejmować wszystkie trzy elementy: włókniste + surowicze ścienne + trzewne. Opcja E pomija osierdzie włókniste, dlatego jest niepełna.$E$,
   'osierdzie', 'ANATLEK-338'),
(73, 'ANA-TUL',
   'Więzadło łukowate przyśrodkowe ogranicza:',
   '[{"id": "a", "text": "rozwór przełykowy"}, {"id": "b", "text": "rozwór aortowy"}, {"id": "c", "text": "przejście mięśnia lędźwiowego większego"}, {"id": "d", "text": "przejście mięśnia czworobocznego lędźwi"}, {"id": "e", "text": "otwór żyły głównej dolnej"}]'::jsonb,
   'c',
   $E$Więzadło łukowate **przyśrodkowe** przepony rozpięte jest nad **mięśniem lędźwiowym większym** (przyczep od trzonu L1/L2 do wyrostka poprzecznego L1), ograniczając jego przejście. Więzadło łukowate **boczne** przerzuca się nad mięśniem czworobocznym lędźwi (D opisuje boczne). Rozwór aortowy ogranicza więzadło łukowate **pośrodkowe** (B błędne). Stąd dla więzadła przyśrodkowego poprawne jest przejście mięśnia lędźwiowego większego.$E$,
   'przepona', 'ANATLEK-339'),
(74, 'ANA-TUL',
   'W czasie skurczu przepona:',
   '[{"id": "a", "text": "obniża żebra"}, {"id": "b", "text": "podnosi żebra"}, {"id": "c", "text": "prostuje odcinek piersiowy kręgosłupa"}, {"id": "d", "text": "zmniejsza ciśnienie w klatce piersiowej"}, {"id": "e", "text": "zmniejsza ciśnienie w jamie brzusznej"}]'::jsonb,
   'd',
   $E$Podczas skurczu przepona **spłaszcza się i obniża** (kopuła schodzi w dół), zwiększając wymiar pionowy klatki piersiowej. Powoduje to **obniżenie ciśnienia w klatce piersiowej** (poniżej atmosferycznego), co napędza wdech i napływ powietrza. Jednocześnie **zwiększa** ciśnienie w jamie brzusznej (uciska trzewia), więc E jest błędne. Przepona przy stałym przyczepie obwodowym może lekko unosić dolne żebra, ale jej kluczowy efekt to spadek ciśnienia wewnątrzklatkowego.$E$,
   'mechanika oddychania', 'ANATLEK-340'),
(75, 'ANA-TRZ',
   'Dół kulszowo-odbytniczy ograniczony jest przez:',
   '[{"id": "a", "text": "powięź zasłonową, otrzewną odbytnicy i skórę krocza"}, {"id": "b", "text": "powięź zasłonową, powięź dolną miednicy i skórę krocza"}, {"id": "c", "text": "powięź górną i dolną miednicy oraz skórę krocza"}, {"id": "d", "text": "powięź błoniastą miednicy i powięź moczowo-płciową"}, {"id": "e", "text": "powięź dolną miednicy, otrzewną odbytnicy i guz kulszowy"}]'::jsonb,
   'b',
   $E$Dół kulszowo-odbytniczy ma na przekroju kształt klina. Ścianę **boczną** tworzy **powięź zasłonowa** (na mięśniu zasłonowym wewnętrznym i guzie kulszowym), ścianę **przyśrodkowo-górną** **powięź dolna przepony miednicy** (na mięśniu dźwigaczu odbytu), a **dno** stanowi **skóra krocza**. Wypełnia go tkanka tłuszczowa, a w bocznej ścianie biegnie kanał sromowy (Alcocka) z naczyniami i nerwem sromowym. Otrzewna nie sięga tego dołu (A, E błędne).$E$,
   'krocze', 'ANATLEK-341'),
(76, 'ANA-TRZ',
   'Unaczynienie z pnia trzewnego i tętnicy krezkowej górnej występuje w:',
   '[{"id": "a", "text": "okrężnicy poprzecznej"}, {"id": "b", "text": "jelicie czczym"}, {"id": "c", "text": "głowie trzustki"}, {"id": "d", "text": "ogonie trzustki"}, {"id": "e", "text": "zewnątrzwątrobowych drogach żółciowych"}]'::jsonb,
   'c',
   $E$**Głowa trzustki** jest unaczyniona z dwóch źródeł na granicy zakresów: z **pnia trzewnego** (przez tętnicę trzustkowo-dwunastniczą górną, gałąź t. żołądkowo-dwunastniczej) oraz z **tętnicy krezkowej górnej** (przez tętnicę trzustkowo-dwunastniczą dolną). Tętnice te tworzą łuki na granicy unaczynienia jelita przedniego i środkowego. Ogon trzustki zaopatruje tętnica śledzionowa (pień trzewny), bez udziału krezkowej górnej — stąd C jest poprawne.$E$,
   'unaczynienie trzustki', 'ANATLEK-342'),
(77, 'ANA-TRZ',
   'Wyrostek pochwowy to:',
   '[{"id": "a", "text": "otrzewna pokrywająca tylną ścianę pochwy"}, {"id": "b", "text": "pozostałość po błonie dziewiczej"}, {"id": "c", "text": "otrzewna zachyłka pęcherzowo-macicznego"}, {"id": "d", "text": "pozostałość rozwojowa w przyjajniczu"}, {"id": "e", "text": "otrzewna w kanale pachwinowym u mężczyzn"}]'::jsonb,
   'e',
   $E$Wyrostek pochwowy otrzewnej (**processus vaginalis peritonei**) to uchyłek otrzewnej zstępujący w okresie płodowym przez **kanał pachwinowy** do moszny u mężczyzn, poprzedzając zstępujące jądro. Jego dystalna część tworzy **osłonkę pochwową jądra**, a reszta zarasta. Niezarośnięcie powoduje wrodzoną przepuklinę pachwinową lub wodniak. U kobiet odpowiednikiem jest zanikający kanał Nucka. Stąd opis „otrzewna w kanale pachwinowym u mężczyzn” jest poprawny.$E$,
   'kanał pachwinowy', 'ANATLEK-343'),
(78, 'ANA-TRZ',
   'Kanał sromowy jest to:',
   '[{"id": "a", "text": "żeński odpowiednik kanału pachwinowego"}, {"id": "b", "text": "kanał ograniczony wyrostkiem sierpowatym i powięzią zasłonową"}, {"id": "c", "text": "przedłużenie kanału zasłonowego"}, {"id": "d", "text": "część przestrzeni głębokiej krocza"}, {"id": "e", "text": "część przestrzeni podotrzewnowej miednicy"}]'::jsonb,
   'b',
   $E$Kanał sromowy (**kanał Alcocka, canalis pudendalis**) to przestrzeń w **rozdwojeniu powięzi zasłonowej** na bocznej ścianie dołu kulszowo-odbytniczego, ograniczona m.in. wyrostkiem sierpowatym więzadła krzyżowo-guzowego i powięzią mięśnia zasłonowego wewnętrznego. Przebiegają w nim **naczynia sromowe wewnętrzne i nerw sromowy**. Nie jest odpowiednikiem kanału pachwinowego (A — to kanał Nucka) ani przedłużeniem kanału zasłonowego (C błędne).$E$,
   'krocze', 'ANATLEK-344'),
(79, 'ANA-CZA',
   'Lejek sitowy jest to:',
   '[{"id": "a", "text": "zachyłek jamy nosowej, z którym łączą się wszystkie zatoki przynosowe"}, {"id": "b", "text": "zachyłek jamy nosowej, z którym łączą się tylko komórki sitowe przednie"}, {"id": "c", "text": "zachyłek jamy nosowej, z którym łączy się zatoka czołowa, szczękowa i komórki sitowe przednie"}, {"id": "d", "text": "zachyłek jamy nosowej, z którym łączą się wszystkie komórki sitowe"}, {"id": "e", "text": "ślepo zakończony zachyłek jamy nosowej"}]'::jsonb,
   'c',
   $E$Lejek sitowy (**infundibulum ethmoidale**) to rynienka w przewodzie nosowym środkowym, do której uchodzą: **zatoka czołowa** (przez przewód czołowo-nosowy), **zatoka szczękowa** oraz **przednie komórki sitowe**. Te struktury tworzą tzw. kompleks ujściowo-przewodowy. Zatoka klinowa i tylne komórki sitowe uchodzą poza lejkiem (do zachyłka klinowo-sitowego i przewodu górnego). Stąd opcja wymieniająca czołową, szczękową i sitowe przednie jest poprawna.$E$,
   'jama nosowa i zatoki przynosowe', 'ANATLEK-345'),
(80, 'ANA-NER',
   'Kanał nerwu twarzowego przebiega od:',
   '[{"id": "a", "text": "przewodu słuchowego wewnętrznego do otworu kolcowego"}, {"id": "b", "text": "otworu okrągłego do otworu rylcowo-sutkowego"}, {"id": "c", "text": "przewodu słuchowego wewnętrznego do otworu rylcowo-sutkowego"}, {"id": "d", "text": "przewodu słuchowego wewnętrznego do szczeliny skalisto-bębenkowej"}, {"id": "e", "text": "otworu szyjnego do otworu rylcowo-sutkowego"}]'::jsonb,
   'c',
   $E$Kanał nerwu twarzowego (**canalis facialis, kanał Fallopiusza**) biegnie w części skalistej kości skroniowej od **dna przewodu słuchowego wewnętrznego** do **otworu rylcowo-sutkowego**, gdzie nerw VII opuszcza czaszkę. Na przebiegu tworzy kolanko (z węzłem kolanka) i oddaje m.in. nerw skalisty większy, gałąź do mięśnia strzemiączkowego oraz strunę bębenkową. Otwór kolcowy i okrągły dotyczą innych struktur (t. oponowa środkowa, V2), stąd są błędne.$E$,
   'nerw twarzowy', 'ANATLEK-346'),
(81, 'ANA-TUL',
   'Zrazik płucny jest to część miąższu płuc:',
   '[{"id": "a", "text": "posiadająca własne oskrzele i tętnicę"}, {"id": "b", "text": "posiadająca własne oskrzele i naczynia krwionośne"}, {"id": "c", "text": "posiadająca tylko własne oskrzele"}, {"id": "d", "text": "różnej wielkości, nieposiadająca odrębnego oskrzela ani odrębnych naczyń krwionośnych"}, {"id": "e", "text": "posiadająca tylko własne naczynia krwionośne"}]'::jsonb,
   'a',
   $E$Zrazik płucny (**lobulus pulmonis**) to najmniejsza, makroskopowo wyodrębniona (odgraniczona przegrodami łącznotkankowymi) część miąższu, zaopatrywana przez **własny oskrzelik (oskrzele zrazikowe) i towarzyszącą gałąź tętnicy płucnej** wnikające do jego szczytu. Żyły biegną na obwodzie, w przegrodach międzyzrazikowych. Stąd zrazik ma odrębne oskrzele i tętnicę. Opis o braku odrębnego oskrzela i naczyń (D) jest błędny, bo przeczy definicji jednostki strukturalnej.$E$,
   'płuca', 'ANATLEK-347'),
(82, 'ANA-TUL',
   'W czasie wdechu płuco wchodzi w obręb:',
   '[{"id": "a", "text": "zachyłka śródpiersiowo-przeponowego"}, {"id": "b", "text": "zachyłka żebrowo-śródpiersiowego przedniego"}, {"id": "c", "text": "zachyłka żebrowo-śródpiersiowego tylnego"}, {"id": "d", "text": "osklepka"}, {"id": "e", "text": "zachyłka żebrowego"}]'::jsonb,
   'e',
   $E$Podczas głębokiego wdechu dolne brzegi płuc rozszerzają się i częściowo wsuwają w **zachyłek żebrowo-przeponowy (recessus costodiaphragmaticus)** — najgłębszy zachyłek opłucnej, w którym w spoczynku stykają się tylko blaszki opłucnej ściennej. W nomenklaturze pytania określono go jako „zachyłek żebrowy”. Płuco nigdy nie wypełnia go całkowicie, co umożliwia rozprężanie. Osklepek (D) to opłucna ponad szczytem, nie zachyłek wdechowy.$E$,
   'opłucna', 'ANATLEK-348'),
(83, 'ANA-TUL',
   'Więzadło płucne jest to:',
   '[{"id": "a", "text": "zdwojenie błony surowiczej opłucnej ściennej"}, {"id": "b", "text": "opłucna pokrywająca korzeń płuca"}, {"id": "c", "text": "inna nazwa krezki płuca"}, {"id": "d", "text": "przejście opłucnej ze śródpiersia na płuco"}, {"id": "e", "text": "połączenie szczytu płuca z osklepkiem"}]'::jsonb,
   'c',
   $E$Więzadło płucne (**ligamentum pulmonale**) to dwublaszkowy fałd opłucnej zwisający pionowo **poniżej wnęki płuca**, łączący przyśrodkową powierzchnię płuca ze śródpiersiem. Powstaje z połączenia blaszek opłucnej poniżej korzenia płuca i bywa nazywane **„krezką płuca”**, bo stabilizuje płuco i zostawia rezerwę dla ruchów naczyń płucnych. Sam korzeń płuca pokrywa opłucna jako mankiet (B opisuje inną relację), stąd najtrafniejsze jest określenie krezki płuca.$E$,
   'opłucna', 'ANATLEK-349'),
(84, 'ANA-TUL',
   'Cechą wyróżniającą oskrzelik końcowy jest:',
   '[{"id": "a", "text": "jedynie mały rozmiar"}, {"id": "b", "text": "zaopatrywanie zrazika płucnego"}, {"id": "c", "text": "brak dalszych podziałów na oskrzela"}, {"id": "d", "text": "jego ślepe zakończenie"}, {"id": "e", "text": "brak chrząstek w ścianie"}]'::jsonb,
   'e',
   $E$Oskrzelik (w tym **końcowy/terminalny**) różni się od oskrzela **brakiem chrząstek i gruczołów w ścianie** — światło utrzymuje napięcie mięśniówki gładkiej i otaczający miąższ. Oskrzelik końcowy jest ostatnim odcinkiem części **przewodzącej**; dzieli się dalej na oskrzeliki oddechowe (część wymiany gazowej), więc nie kończy się ślepo (D błędne) ani nie jest pozbawiony podziałów (C błędne). Stąd kluczową cechą jest brak chrząstek w ścianie.$E$,
   'drzewo oskrzelowe', 'ANATLEK-350'),
(85, 'ANA-NER',
   'Nerw żuchwowy wchodzi do dołu podskroniowego przez:',
   '[{"id": "a", "text": "otwór okrągły"}, {"id": "b", "text": "otwór owalny"}, {"id": "c", "text": "otwór rylcowo-sutkowy"}, {"id": "d", "text": "szczelinę skrzydłowo-szczękową"}, {"id": "e", "text": "nie wchodzi do dołu podskroniowego"}]'::jsonb,
   'b',
   $E$Nerw żuchwowy (**V3**) opuszcza jamę czaszki przez **otwór owalny (foramen ovale)** w skrzydle większym kości klinowej i wchodzi do **dołu podskroniowego**, gdzie oddaje gałęzie do mięśni żucia oraz nerwy językowy i zębodołowy dolny. Otwór okrągły przepuszcza nerw szczękowy V2 (A błędne), a otwór rylcowo-sutkowy nerw twarzowy. Mnemonik zawartości otworu owalnego: **OVALE** — Otic ganglion, V3, Accessory meningeal artery, Lesser petrosal n., Emissary veins.$E$,
   'nerw trójdzielny', 'ANATLEK-351'),
(86, 'ANA-NAC',
   'W przestrzeni zażuchwowej znajduje się:',
   '[{"id": "a", "text": "splot przyuszniczy nerwu twarzowego"}, {"id": "b", "text": "nerw dodatkowy"}, {"id": "c", "text": "nerw błędny"}, {"id": "d", "text": "tętnice skroniowe głębokie"}, {"id": "e", "text": "tętnica szyjna wewnętrzna"}]'::jsonb,
   'a',
   $E$W przestrzeni zażuchwowej (dole zażuchwowym) leży głównie **ślinianka przyuszna**, a w jej obrębie dzieli się nerw twarzowy, tworząc **splot przyuszniczy (pes anserinus)**, z którego wychodzą gałęzie ruchowe do mięśni mimicznych. Przebiegają tu też żyła zażuchwowa i tętnica szyjna zewnętrzna z gałęziami końcowymi. Tętnica szyjna wewnętrzna leży głębiej, w przestrzeni przygardłowej (E błędne). Nerwy dodatkowy i błędny biegną w innych okolicach szyi.$E$,
   'przestrzeń zażuchwowa', 'ANATLEK-352'),
(87, 'ANA-MIE',
   'Powięź skroniowa:',
   '[{"id": "a", "text": "pokrywa mięsień skroniowy przyśrodkowo i bocznie"}, {"id": "b", "text": "jest pojedynczą blaszką"}, {"id": "c", "text": "między jej dwoma blaszkami znajduje się ciało tłuszczowe skroniowe"}, {"id": "d", "text": "nie obejmuje ciała tłuszczowego skroniowego"}, {"id": "e", "text": "pokrywa mięsień skroniowo-ciemieniowy"}]'::jsonb,
   'c',
   $E$Powięź skroniowa pokrywa mięsień skroniowy tylko od **strony bocznej** (powierzchownej), nie przyśrodkowo (A błędne). W dolnej części, nad łukiem jarzmowym, rozdwaja się na **blaszkę powierzchowną i głęboką**, między którymi leży **powierzchowne ciało tłuszczowe skroniowe** wraz z gałęzią tętnicy skroniowej środkowej. Jest więc strukturą dwublaszkową (B, D błędne). Mięsień skroniowo-ciemieniowy to odrębny mięsień naczaszny, nieobjęty tą powięzią.$E$,
   'powięzie głowy', 'ANATLEK-354'),
(88, 'ANA-JAM',
   'Zatoka szczękowa znajduje się w ścisłym związku przestrzennym z korzeniami:',
   '[{"id": "a", "text": "wszystkich zębów szczęki"}, {"id": "b", "text": "zębów trzonowych i przedtrzonowych"}, {"id": "c", "text": "wyłącznie kłów"}, {"id": "d", "text": "kłów i zębów siecznych"}, {"id": "e", "text": "wyłącznie zębów siecznych"}]'::jsonb,
   'b',
   $E$Dno zatoki szczękowej leży tuż nad wyrostkiem zębodołowym szczęki i pozostaje w ścisłym sąsiedztwie z korzeniami **zębów trzonowych i przedtrzonowych** (zwłaszcza pierwszego i drugiego trzonowca), które mogą wpuklać się do światła zatoki, oddzielone jedynie cienką blaszką kostną lub samą błoną śluzową. Stąd ryzyko połączenia ustno-zatokowego po ekstrakcji i szerzenia się zapaleń zębopochodnych. Zęby sieczne i kły leżą zbyt z przodu (C, D, E błędne).$E$,
   'zatoka szczękowa a zęby', 'ANATLEK-355'),
(89, 'ANA-NAC',
   'Splot skrzydłowy jest splotem:',
   '[{"id": "a", "text": "nerwu skrzydłowego większego"}, {"id": "b", "text": "nerwu twarzowego"}, {"id": "c", "text": "żylnym w przestrzeni zażuchwowej"}, {"id": "d", "text": "żylnym w okolicach bocznych głębokich twarzy"}, {"id": "e", "text": "żylnym w dole skrzydłowym"}]'::jsonb,
   'd',
   $E$Splot skrzydłowy (**plexus pterygoideus**) to gęsta sieć żylna położona w **głębokiej bocznej okolicy twarzy**, wokół i między mięśniami skrzydłowymi, w dole podskroniowym. Zbiera krew z obszaru zaopatrywanego przez tętnicę szczękową i odprowadza ją żyłą szczękową do żyły zażuchwowej. Łączy się też z zatoką jamistą (przez żyły emisariusze) i żyłą oczną — stąd droga szerzenia zakażeń twarzy. Określenie „w dole skrzydłowym” (E) jest zbyt wąskie i nieścisłe.$E$,
   'żyły głębokie twarzy', 'ANATLEK-356')
),
maxes AS (
  SELECT topic_id, COALESCE(MAX( (regexp_match(id, '([0-9]+)$'))[1]::int ), 0) AS mx
    FROM public.questions WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') GROUP BY topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam)
SELECT
  LOWER(n.topic_id) || '-' || LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_anat_2019/1', 'Egzamin anatomia LEK SUM 2019 (ANATLEK e2019-1)'
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (SELECT topic_id, COUNT(*) AS cnt FROM public.questions
         WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') AND COALESCE(is_active,true)=true GROUP BY topic_id) sub
 WHERE t.id = sub.topic_id;
