-- ============================================================
-- BATCH: e_anat_2026/1  ·  subject_id=anatomia  ·  SHARED (oba kierunki, tracks=NULL)
-- Źródło: Egzamin anatomia LEK SUM 2026 (ANATLEK e2026-1), 100 pytań
-- tracks NULL (anatomia wspólna) · source_code = oryginalne ANATLEK-NNN
-- Self-numbering id per dział = max seq z bazy + 1
-- Wygenerowane przez scripts/build-anatlek-e2026-1.py (nie edytować ręcznie)
-- ============================================================

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
(1, 'ANA-TUL',
   'Powięź nasienna wewnętrzna odpowiada w ścianie brzucha:',
   '[{"id": "a", "text": "tkance podskórnej"}, {"id": "b", "text": "powięzi poprzecznej"}, {"id": "c", "text": "rozcięgnu mięśnia skośnego wewnętrznego brzucha"}, {"id": "d", "text": "rozcięgnu mięśnia poprzecznego brzucha"}, {"id": "e", "text": "powięzi podskórnej"}]'::jsonb,
   'b',
   $E$Osłonki powrózka nasiennego powstają z kolejnych warstw ściany brzucha uwypuklanych podczas zstępowania jądra przez kanał pachwinowy. **Powięź nasienna wewnętrzna** jest bezpośrednim przedłużeniem **powięzi poprzecznej** i stanowi najgłębszą osłonkę. Warstwę środkową, **mięsień dźwigacz jądra z powięzią**, daje mięsień skośny wewnętrzny, a **powięź nasienna zewnętrzna** wywodzi się z rozcięgna mięśnia skośnego zewnętrznego.$E$,
   'Ściana brzucha', 'ANATLEK-706'),
(2, 'ANA-TRZ',
   'Kolejne odcinki cewki moczowej męskiej to:',
   '[{"id": "a", "text": "odcinek śródścienny, sterczowy, jamisty, gąbczasty"}, {"id": "b", "text": "odcinek śródścienny, sterczowy, łonowy, gąbczasty"}, {"id": "c", "text": "odcinek śródścienny, sterczowy, łonowy, jamisty"}, {"id": "d", "text": "odcinek śródścienny, sterczowy, błoniasty, gąbczasty"}, {"id": "e", "text": "odcinek śródścienny, sterczowy, błoniasty, łonowy"}]'::jsonb,
   'd',
   $E$Cewka męska ma cztery części: **śródścienną** w ścianie pęcherza, **sterczową** – najszerszą, ze wzgórkiem nasiennym i ujściami przewodów wytryskowych, **błoniastą** – najkrótszą i najwęższą, przebijającą przeponę moczowo-płciową ze zwieraczem zewnętrznym, oraz **gąbczastą** – najdłuższą, biegnącą w ciele gąbczastym prącia. Określenia „jamisty” i „łonowy” nie są nazwami odcinków cewki. Zwężenia cewki odpowiadają ujściu wewnętrznemu, części błoniastej i ujściu zewnętrznemu.$E$,
   'Układ moczowy', 'ANATLEK-707'),
(3, 'ANA-TRZ',
   'Gruczoł krokowy położony jest:',
   '[{"id": "a", "text": "poniżej części gąbczastej cewki moczowej, do przodu od części miednicznej odbytnicy"}, {"id": "b", "text": "poniżej części błoniastej cewki moczowej, do przodu od części miednicznej odbytnicy"}, {"id": "c", "text": "poniżej części sterczowej cewki moczowej, do przodu od części miednicznej odbytnicy"}, {"id": "d", "text": "poniżej części błoniastej cewki moczowej, do przodu od bańki odbytnicy"}, {"id": "e", "text": "poniżej pęcherza moczowego, do przodu od bańki odbytnicy"}]'::jsonb,
   'e',
   $E$Stercz leży **poniżej pęcherza moczowego**, opierając się podstawą o jego dno, a szczytem o **przeponę moczowo-płciową**. Ku tyłowi sąsiaduje z **bańką odbytnicy**, od której oddziela go przegroda odbytniczo-pęcherzowa – dlatego jest dostępny w badaniu palcem przez odbytnicę. Nie może leżeć poniżej części sterczowej cewki, bo ta **przechodzi przez jego miąższ**, podobnie jak przewody wytryskowe. Rozrost stercza zwęża cewkę i utrudnia mikcję – to typowe podłoże objawów u starszych mężczyzn.$E$,
   'Gruczoły płciowe dodatkowe', 'ANATLEK-708'),
(4, 'ANA-TRZ',
   'Kolejne odcinki jajowodu licząc od strony macicznej to:',
   '[{"id": "a", "text": "bańka, cieśń, lejek"}, {"id": "b", "text": "cieśń, bańka, lejek"}, {"id": "c", "text": "lejek, bańka, cieśń"}, {"id": "d", "text": "bańka, lejek, cieśń"}, {"id": "e", "text": "lejek, cieśń, bańka"}]'::jsonb,
   'b',
   $E$Po części śródściennej (macicznej) następuje **cieśń** – wąska, grubościenna, o świetle ok. 1 mm, potem szeroka i kręta **bańka**, najdłuższy odcinek, w którym zwykle dochodzi do **zapłodnienia**, a na końcu **lejek** ze strzępkami obejmującymi jajnik. Kierunek jest więc od wąskiego do szerokiego – odwrotna kolejność opisuje drogę komórki jajowej, nie budowę liczoną od macicy. Część maciczna (śródścienna) przebiega w ścianie macicy i otwiera się ujściem macicznym jajowodu.$E$,
   'Narząd rodny żeński', 'ANATLEK-709'),
(5, 'ANA-TRZ',
   'Otrzewna powlekająca macicę to:',
   '[{"id": "a", "text": "przymacicze"}, {"id": "b", "text": "śródmacicze"}, {"id": "c", "text": "omacicze"}, {"id": "d", "text": "endometrium"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'c',
   $E$Ściana macicy ma trzy warstwy: **błonę śluzową (endometrium)**, grubą **błonę mięśniową (myometrium)** i zewnętrzną **błonę surowiczą, czyli omacicze (perimetrium)** – jest nią otrzewna. **Przymacicze (parametrium)** to tkanka łączna przywięzadłowa między blaszkami więzadła szerokiego, z tętnicą maciczną i moczowodem, a nie otrzewna. Termin „śródmacicze” nie funkcjonuje w mianownictwie. Otrzewna przechodzi z macicy na odbytnicę, tworząc **zagłębienie odbytniczo-maciczne (Douglasa)**.$E$,
   'Narząd rodny żeński', 'ANATLEK-710'),
(6, 'ANA-TRZ',
   'Dno macicy stanowi jej część:',
   '[{"id": "a", "text": "dolną, poniżej ujść macicznych jajowodów"}, {"id": "b", "text": "górną, powyżej ujść macicznych jajowodów"}, {"id": "c", "text": "przednią, poniżej ujść macicznych jajowodów"}, {"id": "d", "text": "tylną, poniżej ujść macicznych jajowodów"}, {"id": "e", "text": "przednią i tylną, poniżej ujść macicznych jajowodów"}]'::jsonb,
   'b',
   $E$Macica dzieli się na **dno**, **trzon** i **szyjkę**. **Dno** to część leżąca **powyżej linii łączącej ujścia maciczne jajowodów** – wypukła ku górze i do przodu, pokryta otrzewną. Miejsca odejścia jajowodów to **rogi macicy**. Dolna, zwężona część to szyjka z częścią nadpochwową i pochwową. Mimo nazwy dno leży najwyżej, ponieważ narząd w typowym ustawieniu jest przodozgięty i przodopochylony. Wysokość dna bada się palpacyjnie przez powłoki i wykorzystuje do oceny zaawansowania ciąży.$E$,
   'Narząd rodny żeński', 'ANATLEK-711'),
(7, 'ANA-TRZ',
   'Unaczynienie tętnicze macicy pochodzi z tętnic:',
   '[{"id": "a", "text": "macicznej od t. biodrowej zewnętrznej i t. jajnikowej z t. biodrowej wewnętrznej"}, {"id": "b", "text": "macicznej od t. biodrowej wewnętrznej i t. jajnikowej z t. biodrowej zewnętrznej"}, {"id": "c", "text": "macicznej od t. biodrowej wewnętrznej i t. jajnikowej z t. krezkowej dolnej"}, {"id": "d", "text": "macicznej od t. biodrowej wewnętrznej i t. jajnikowej z t. krezkowej górnej"}, {"id": "e", "text": "macicznej od t. biodrowej wewnętrznej i t. jajnikowej z aorty brzusznej"}]'::jsonb,
   'e',
   $E$**Tętnica maciczna** jest gałęzią trzewną **tętnicy biodrowej wewnętrznej**; w podstawie więzadła szerokiego krzyżuje **moczowód od góry** („woda pod mostem”) i oddaje gałęzie jajowodowe oraz jajnikowe, tworząc zespolenia. **Tętnica jajnikowa** odchodzi natomiast bezpośrednio od **aorty brzusznej** na wysokości L2, jak tętnica jądrowa – jest to konsekwencja pierwotnego, wysokiego położenia gonady. Uszkodzenie moczowodu przy podwiązywaniu tętnicy macicznej to klasyczne powikłanie histerektomii.$E$,
   'Narząd rodny żeński', 'ANATLEK-712'),
(8, 'ANA-TRZ',
   'Ujście żyły głównej górnej znajduje się w:',
   '[{"id": "a", "text": "ścianie przedniej przedsionka prawego"}, {"id": "b", "text": "ścianie tylnej przedsionka prawego"}, {"id": "c", "text": "ścianie górnej przedsionka prawego"}, {"id": "d", "text": "ścianie przedniej przedsionka lewego"}, {"id": "e", "text": "ścianie tylnej przedsionka lewego"}]'::jsonb,
   'c',
   $E$**Żyła główna górna** uchodzi do **górnej ściany przedsionka prawego**, bez zastawki, w okolicy zatoki żył głównych. **Żyła główna dolna** wchodzi od dołu, w ścianie dolnej, i ma szczątkową **zastawkę Eustachiusza**, a **zatoka wieńcowa** uchodzi tuż przy niej z zastawką Tebezjusza. W okolicy ujścia żyły głównej górnej leży **węzeł zatokowo-przedsionkowy** – nadrzędny rozrusznik serca. Ujście żyły głównej górnej pozbawione jest zastawki, co wykorzystuje się przy cewnikowaniu centralnym.$E$,
   'Serce', 'ANATLEK-713'),
(9, 'ANA-TRZ',
   'Pozostałością po krążeniu płodowym są między innymi:',
   '[{"id": "a", "text": "więzadło sierpowate wątroby, dół owalny, uszko prawe serca"}, {"id": "b", "text": "więzadło sierpowate wątroby, przewód żylny, uszko prawe serca"}, {"id": "c", "text": "więzadło obłe wątroby, więzadło tętnicze, więzadło żylne"}, {"id": "d", "text": "więzadło obłe wątroby, dół owalny, uszko prawe serca"}, {"id": "e", "text": "więzadło obłe wątroby, żyła pępkowa, uszko prawe serca"}]'::jsonb,
   'c',
   $E$Po urodzeniu zarastają: **żyła pępkowa → więzadło obłe wątroby**, **przewód żylny (Arancjusza) → więzadło żylne**, **przewód tętniczy (Botalla) → więzadło tętnicze**, a otwór owalny → dół owalny. **Uszko prawe** jest stałym elementem serca, a **więzadło sierpowate** to fałd otrzewnej, w którego wolnym brzegu biegnie więzadło obłe – same w sobie nie są pozostałościami płodowymi. Przetrwały przewód tętniczy wymaga zamknięcia farmakologicznego lub zabiegowego.$E$,
   'Serce', 'ANATLEK-714'),
(10, 'ANA-TRZ',
   'Tętnica wieńcowa lewa:',
   '[{"id": "a", "text": "rozpoczyna się w lewej zatoce aorty"}, {"id": "b", "text": "biegnie między uszkiem lewym a opuszką aorty"}, {"id": "c", "text": "oddaje gałąź międzykomorową tylną"}, {"id": "d", "text": "Prawidłowe A i B"}, {"id": "e", "text": "Prawidłowe A, B i C"}]'::jsonb,
   'a',
   $E$Tętnica wieńcowa lewa odchodzi od **lewej zatoki aorty (Valsalvy)**, tuż nad płatkiem zastawki. Krótki pień dzieli się na **gałąź międzykomorową przednią** i **gałąź okalającą**, biegnąc między **uszkiem lewym a pniem płucnym**, nie opuszką aorty – dlatego opis przebiegu między uszkiem lewym a opuszką aorty jest fałszywy. **Gałąź międzykomorowa tylna** u ok. 70% osób pochodzi z tętnicy wieńcowej prawej (typ prawostronny unaczynienia). Zamknięcie gałęzi międzykomorowej przedniej daje rozległy zawał ściany przedniej i przegrody.$E$,
   'Serce', 'ANATLEK-715'),
(11, 'ANA-TRZ',
   'Okrężnica wstępująca jest unaczyniona przez gałęzie:',
   '[{"id": "a", "text": "t. krezkowej górnej"}, {"id": "b", "text": "t. krezkowej dolnej"}, {"id": "c", "text": "t. biodrowej wewnętrznej"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A, B i C"}]'::jsonb,
   'a',
   $E$Okrężnica wstępująca pochodzi ze **środkowej części jelita pierwotnego**, więc zaopatruje ją **tętnica krezkowa górna** – przez **tętnicę okrężniczą prawą** i gałąź okrężniczą tętnicy krętniczo-okrężniczej. Granicą dorzeczy jest **zgięcie śledzionowe** (punkt Griffithsa): dalszy odcinek należy do **tętnicy krezkowej dolnej**. Zespolenia zapewnia **tętnica brzeżna Drummonda** wzdłuż całej okrężnicy. Zgięcie śledzionowe, jako obszar graniczny, jest typowym miejscem niedokrwienia jelita.$E$,
   'Jelito grube', 'ANATLEK-716'),
(12, 'ANA-CZA',
   'Do przewodu nosowego dolnego uchodzą:',
   '[{"id": "a", "text": "zatoka szczękowa"}, {"id": "b", "text": "zatoka czołowa"}, {"id": "c", "text": "komórki sitowe tylne"}, {"id": "d", "text": "przewód nosowo-łzowy"}, {"id": "e", "text": "Prawidłowe A, B i D"}]'::jsonb,
   'd',
   $E$Do **przewodu nosowego dolnego** uchodzi wyłącznie **przewód nosowo-łzowy**, osłonięty fałdem błony śluzowej (zastawka Hasnera) – stąd łzawienie przy nieżycie nosa. Do **przewodu środkowego** spływają **zatoka szczękowa, czołowa oraz komórki sitowe przednie i środkowe** (kompleks ujściowo-przewodowy), do **górnego** – komórki sitowe tylne, a do **zachyłka klinowo-sitowego** – zatoka klinowa. Niedrożność przewodu nosowo-łzowego u noworodka objawia się przewlekłym łzawieniem.$E$,
   'Jama nosowa i zatoki przynosowe', 'ANATLEK-717'),
(13, 'ANA-TRZ',
   'Stożek sprężysty stanowi element:',
   '[{"id": "a", "text": "górnego piętra krtani"}, {"id": "b", "text": "środkowego piętra krtani"}, {"id": "c", "text": "dolnego piętra krtani"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe B i C"}]'::jsonb,
   'c',
   $E$**Stożek sprężysty** to dolna część błony włóknisto-sprężystej krtani: rozpina się od **górnego brzegu łuku chrząstki pierścieniowatej** ku górze, a jego wolny brzeg tworzy **więzadło głosowe**. Leży zatem poniżej szpary głośni, w **jamie podgłośniowej**, czyli w **dolnym piętrze krtani**. Górne piętro (przedsionek) i piętro środkowe ograniczone są błoną czworokątną z więzadłem przedsionkowym. Luźna błona śluzowa jamy podgłośniowej łatwo obrzęka, co u dzieci grozi zwężeniem podgłośniowym.$E$,
   'Krtań', 'ANATLEK-718'),
(14, 'ANA-TRZ',
   'Do mięśni napinających wargi głosowe zaliczamy:',
   '[{"id": "a", "text": "m. tarczowo-nalewkowy zewnętrzny i m. pierścienno-nalewkowy tylny"}, {"id": "b", "text": "m. pierścienno-tarczowy i m. tarczowo-nalewkowy zewnętrzny"}, {"id": "c", "text": "m. tarczowo-nalewkowy zewnętrzny i m. pierścienno-nalewkowy boczny"}, {"id": "d", "text": "m. pierścienno-tarczowy i m. tarczowo-nalewkowy wewnętrzny"}, {"id": "e", "text": "m. pierścienno-nalewkowy boczny i m. tarczowo-nalewkowy wewnętrzny"}]'::jsonb,
   'd',
   $E$Napinaczami więzadeł głosowych są **mięsień pierścienno-tarczowy** (napinacz zewnętrzny, pochylający chrząstkę tarczowatą do przodu i wydłużający fałd) oraz **mięsień tarczowo-nalewkowy wewnętrzny, czyli mięsień głosowy** (napinacz wewnętrzny, regulujący napięcie odcinkowe). Mięsień pierścienno-tarczowy jest jedynym unerwionym przez **nerw krtaniowy górny**, pozostałe – przez **nerw krtaniowy wsteczny**. Obustronne porażenie nerwu krtaniowego wstecznego prowadzi do duszności krtaniowej.$E$,
   'Krtań', 'ANATLEK-719'),
(15, 'ANA-TRZ',
   'We wnęce płuca lewego najwyżej położona jest:',
   '[{"id": "a", "text": "tętnica płucna"}, {"id": "b", "text": "oskrzele nadtętnicze"}, {"id": "c", "text": "żyła płucna przednia"}, {"id": "d", "text": "żyła płucna dolna"}, {"id": "e", "text": "oskrzele główne"}]'::jsonb,
   'a',
   $E$Po stronie lewej układ jest **hiparteryjny**: najwyżej leży **tętnica płucna**, pod nią **oskrzele główne**, a najniżej i najbardziej z przodu **żyły płucne**. Po stronie prawej najwyżej biegnie **oskrzele płatowe górne (nadtętnicze)** – stąd określenie płuca prawego jako **eparteryjnego**. Mnemonik dla wnęk: **RALS** – Right Anterior, Left Superior, czyli po prawej tętnica z przodu, po lewej u góry. Struktury wnęki obejmuje wspólna osłonka opłucnej przechodząca ku dołowi w więzadło płucne.$E$,
   'Płuca', 'ANATLEK-720'),
(16, 'ANA-TRZ',
   'Segment przedni występuje w:',
   '[{"id": "a", "text": "płacie górnym płuca lewego"}, {"id": "b", "text": "płacie dolnym płuca lewego"}, {"id": "c", "text": "płacie środkowym płuca prawego"}, {"id": "d", "text": "płacie dolnym płuca prawego"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'a',
   $E$**Segment przedni (S3)** należy do **płata górnego** – zarówno po stronie prawej, jak i lewej, gdzie wchodzi w skład części szczytowej płata górnego. Płat środkowy prawy dzieli się na segment **boczny i przyśrodkowy**, a płaty dolne na segment **szczytowy (S6)** oraz segmenty **podstawne: przyśrodkowy, przedni, boczny i tylny** – w nich występuje segment „podstawny przedni”, a nie sam „przedni”. Segmenty stanowią jednostki chirurgiczne z własnym oskrzelem segmentowym i gałęzią tętniczą.$E$,
   'Płuca', 'ANATLEK-721'),
(17, 'ANA-TRZ',
   'Szczelina skośna płuca lewego przebiega:',
   '[{"id": "a", "text": "od wyrostka poprzecznego II kręgu piersiowego do chrząstki V żebra w linii środkowoobojczykowej"}, {"id": "b", "text": "od wyrostka poprzecznego IV kręgu piersiowego do chrząstki VI żebra w linii środkowoobojczykowej"}, {"id": "c", "text": "od wyrostka kolczystego V kręgu piersiowego do chrząstki IV żebra w linii przymostkowej"}, {"id": "d", "text": "od wyrostka kolczystego IV kręgu piersiowego do chrząstki IV żebra w linii przymostkowej"}, {"id": "e", "text": "od wyrostka kolczystego III kręgu piersiowego do chrząstki VI żebra w linii przymostkowej"}]'::jsonb,
   'e',
   $E$Rzut szczeliny skośnej biegnie od **wyrostka kolczystego Th3** skośnie w dół i do przodu, wzdłuż przebiegu **VI żebra**, do **chrząstki VI żebra** przy mostku. Po stronie lewej szczelina ustawiona jest nieco bardziej stromo niż po prawej. Praktyczny odpowiednik: linia poprowadzona od kręgu Th3 do połączenia żebrowo-chrzęstnego VI żebra przy uniesionej kończynie górnej. Po stronie prawej dodatkowo biegnie szczelina pozioma na wysokości IV żebra, odgraniczając płat środkowy.$E$,
   'Płuca', 'ANATLEK-722'),
(18, 'ANA-TUL',
   'Śródpiersie dolne tylne zawiera między innymi:',
   '[{"id": "a", "text": "przełyk, aortę wstępującą, nerwy błędne, przewód piersiowy"}, {"id": "b", "text": "przełyk, aortę zstępującą, nerwy błędne, żyłę nieparzystą"}, {"id": "c", "text": "nerwy przeponowe, aortę zstępującą, nerwy błędne, żyłę nieparzystą"}, {"id": "d", "text": "nerwy przeponowe, nerwy błędne, żyłę nieparzystą dodatkową"}, {"id": "e", "text": "nerwy błędne, aortę wstępującą, tchawicę, żyłę nieparzystą"}]'::jsonb,
   'b',
   $E$W śródpiersiu tylnym leżą: **przełyk** ze splotem przełykowym **nerwów błędnych**, **aorta piersiowa zstępująca**, **przewód piersiowy**, **żyła nieparzysta i nieparzysta krótka** oraz pnie współczulne i nerwy trzewne. **Aorta wstępująca i tchawica** należą do śródpiersia środkowego i górnego, a **nerwy przeponowe** biegną w śródpiersiu środkowym, po bokach osierdzia. Śródpiersie dolne dzieli się na przednie, środkowe z sercem i tylne; granicę górną wyznacza płaszczyzna Th4/Th5.$E$,
   'Śródpiersie', 'ANATLEK-723'),
(19, 'ANA-TRZ',
   'Kolejno pokrywające nerkę osłonki to:',
   '[{"id": "a", "text": "powięź nerkowa, błona włóknista, torebka tłuszczowa, błona mięśniowa"}, {"id": "b", "text": "powięź nerkowa, błona włóknista, błona mięśniowa, torebka tłuszczowa"}, {"id": "c", "text": "błona mięśniowa, błona włóknista, torebka tłuszczowa, powięź nerkowa"}, {"id": "d", "text": "błona włóknista, błona mięśniowa, torebka tłuszczowa, powięź nerkowa"}, {"id": "e", "text": "torebka tłuszczowa, błona włóknista, błona mięśniowa, powięź nerkowa"}]'::jsonb,
   'c',
   $E$Licząc od miąższu na zewnątrz: cienka **błona mięśniowa**, **błona (torebka) włóknista** – łatwa do zdjęcia ze zdrowej nerki, **torebka tłuszczowa** stabilizująca narząd oraz **powięź nerkowa (Geroty)** z blaszką przednią i tylną. Zewnętrznie leży jeszcze ciało tłuszczowe okołonerkowe. Osłabienie torebki tłuszczowej sprzyja **nerce ruchomej**, a powięź wyznacza drogę szerzenia się ropni. Nerka prawa leży nieco niżej niż lewa z powodu sąsiedztwa wątroby.$E$,
   'Układ moczowy', 'ANATLEK-724'),
(20, 'ANA-TRZ',
   'Prawidłowe stwierdzenia dotyczące moczowodu to:',
   '[{"id": "a", "text": "składa się z trzech części"}, {"id": "b", "text": "ujście pęcherzowe moczowodu stanowi kąt tylno-boczny podstawy trójkąta pęcherzowego"}, {"id": "c", "text": "posiada trzy naturalne zagięcia"}, {"id": "d", "text": "Prawidłowe B i C"}, {"id": "e", "text": "Wszystkie odpowiedzi prawidłowe"}]'::jsonb,
   'e',
   $E$Moczowód dzieli się na **część brzuszną, miedniczną i śródścienną**, wykazuje **trzy zagięcia** (przy przejściu w miednicę, w miednicy i przed wejściem w ścianę pęcherza) oraz trzy **zwężenia**: przy miedniczce, na skrzyżowaniu z naczyniami biodrowymi i w ujściu pęcherzowym – to typowe miejsca zaklinowania złogów. **Ujścia moczowodów** wyznaczają tylno-boczne kąty **trójkąta pęcherzowego**. Perystaltyka warstwy mięśniowej przesuwa mocz niezależnie od siły ciężkości.$E$,
   'Układ moczowy', 'ANATLEK-725'),
(21, 'ANA-OUN',
   'Do wypustek opony twardej nie należy:',
   '[{"id": "a", "text": "sierp mózgu"}, {"id": "b", "text": "sierp móżdżku"}, {"id": "c", "text": "namiot móżdżku"}, {"id": "d", "text": "namiot mózgu"}, {"id": "e", "text": "przepona siodła"}]'::jsonb,
   'd',
   $E$Blaszka wewnętrzna opony twardej tworzy cztery wypustki: **sierp mózgu** między półkulami, **namiot móżdżku** oddzielający płaty potyliczne od móżdżku, **sierp móżdżku** w tylnej części dołu tylnego oraz **przeponę siodła** nad przysadką. Struktura o nazwie „namiot mózgu” nie istnieje. W obrębie wypustek biegną **zatoki żylne opony twardej**, m.in. strzałkowa górna i prosta, a wcięcie namiotu jest miejscem **wgłobienia haka hipokampa**.$E$,
   'Opony mózgowia', 'ANATLEK-726'),
(22, 'ANA-OBW',
   'Splot szyjny nie łączy się z:',
   '[{"id": "a", "text": "nerwem twarzowym"}, {"id": "b", "text": "nerwem podjęzykowym"}, {"id": "c", "text": "nerwem dodatkowym"}, {"id": "d", "text": "nerwem językowo-gardłowym"}, {"id": "e", "text": "pniem współczulnym"}]'::jsonb,
   'd',
   $E$Splot szyjny (**C1–C4**) tworzy połączenia z **nerwem podjęzykowym** – włókna C1 biegną z nim jako korzeń górny **pętli szyjnej**, z **nerwem dodatkowym** w obrębie mięśnia mostkowo-obojczykowo-sutkowego i czworobocznego, z **nerwem twarzowym** przez nerw uszny wielki oraz z **pniem współczulnym szyjnym**. Nerw językowo-gardłowy nie wchodzi w skład tych połączeń – jego pole to gardło, migdałek i tylna część języka. Splot leży na mięśniach głębokich szyi, pod mięśniem mostkowo-obojczykowo-sutkowym.$E$,
   'Splot szyjny', 'ANATLEK-727'),
(23, 'ANA-OBW',
   'Pętla szyjna:',
   '[{"id": "a", "text": "jest gałęzią mięśniową krótką splotu szyjnego"}, {"id": "b", "text": "składa się z gałęzi górnej i dolnej"}, {"id": "c", "text": "składa się z gałęzi przedniej i tylnej"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A i C"}]'::jsonb,
   'b',
   $E$**Pętla szyjna** powstaje z połączenia **korzenia (gałęzi) górnego**, biegnącego z C1 wraz z nerwem podjęzykowym, oraz **korzenia dolnego** z włókien **C2–C3**. Zaopatruje ruchowo mięśnie **podgnykowe**: mostkowo-gnykowy, mostkowo-tarczowy i łopatkowo-gnykowy, natomiast mięsień tarczowo-gnykowy – bezpośrednio z C1. Jest to gałąź **długa** splotu szyjnego, a nie gałąź mięśniowa krótka, dlatego określenie jej jako gałęzi mięśniowej krótkiej jest błędne. Pętla leży zwykle na powierzchni żyły szyjnej wewnętrznej.$E$,
   'Splot szyjny', 'ANATLEK-728'),
(24, 'ANA-OBW',
   'Do nerwów krótkich splotu ramiennego nie należy nerw:',
   '[{"id": "a", "text": "mięśniowo-skórny"}, {"id": "b", "text": "grzbietowy łopatki"}, {"id": "c", "text": "piersiowy długi"}, {"id": "d", "text": "piersiowy boczny"}, {"id": "e", "text": "podobojczykowy"}]'::jsonb,
   'a',
   $E$Nerwy **krótkie** odchodzą głównie od części nadobojczykowej splotu i zaopatrują mięśnie obręczy: **grzbietowy łopatki**, **piersiowy długi**, **podobojczykowy**, **nadłopatkowy**, **piersiowe boczny i przyśrodkowy**, **podłopatkowe**, **piersiowo-grzbietowy** oraz **pachowy**. **Nerw mięśniowo-skórny** to gałąź **długa** pęczka bocznego – unerwia mięśnie przedziału przedniego ramienia i przechodzi w nerw skórny boczny przedramienia. Uszkodzenie nerwu piersiowego długiego daje charakterystyczną łopatkę skrzydlatą.$E$,
   'Splot ramienny', 'ANATLEK-729'),
(25, 'ANA-OBW',
   '„Ręka szponiasta” jest skutkiem uszkodzenia nerwu:',
   '[{"id": "a", "text": "promieniowego"}, {"id": "b", "text": "pośrodkowego"}, {"id": "c", "text": "łokciowego"}, {"id": "d", "text": "pachowego"}, {"id": "e", "text": "mięśniowo-skórnego"}]'::jsonb,
   'c',
   $E$Porażenie **nerwu łokciowego** znosi czynność **mięśni glistowatych III i IV oraz międzykostnych**, przez co przewaga prostownika długiego palców powoduje przeprost w stawach śródręczno-paliczkowych i zgięcie w międzypaliczkowych – typowa **ręka szponiasta**, najwyraźniejsza w palcach IV i V. Uszkodzenie nerwu pośrodkowego daje **rękę błogosławiącą** przy próbie zaciśnięcia pięści, a promieniowego – **rękę opadającą**.$E$,
   'Nerwy kończyny górnej', 'ANATLEK-730'),
(26, 'ANA-OBW',
   'Nerw pośrodkowy zaopatruje czuciowo skórę ręki na powierzchni:',
   '[{"id": "a", "text": "dłoniowej 2 i ½ palca strony bocznej"}, {"id": "b", "text": "dłoniowej 3 i ½ palca strony bocznej"}, {"id": "c", "text": "dłoniowej 3 i ½ palca strony przyśrodkowej"}, {"id": "d", "text": "grzbietowej 3 i ½ palca strony bocznej"}, {"id": "e", "text": "grzbietowej 3 i ½ palca strony przyśrodkowej"}]'::jsonb,
   'b',
   $E$Nerw pośrodkowy unerwia czuciowo **dłoniową powierzchnię 3½ palca po stronie bocznej (promieniowej)**: kciuk, palec wskazujący, środkowy i połowę serdecznego, a dodatkowo **grzbietowe powierzchnie paliczków dalszych** tych palców. Pozostałe 1½ palca od strony przyśrodkowej należy do **nerwu łokciowego**. Skórę kłębu zaopatruje **gałąź dłoniowa** odchodząca powyżej troczka – dlatego bywa oszczędzona w zespole cieśni nadgarstka.$E$,
   'Nerwy kończyny górnej', 'ANATLEK-731'),
(27, 'ANA-OBW',
   'Nerw udowy:',
   '[{"id": "a", "text": "jest gałęzią długą splotu lędźwiowego"}, {"id": "b", "text": "jego początkowy odcinek leży na mięśniu lędźwiowym mniejszym"}, {"id": "c", "text": "jest nerwem czysto ruchowym"}, {"id": "d", "text": "wszystkie odpowiedzi prawidłowe"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'a',
   $E$Nerw udowy (**L2–L4**) to najgrubsza **gałąź długa splotu lędźwiowego**. Powstaje w obrębie **mięśnia lędźwiowego większego** i wychodzi spod jego brzegu bocznego, biegnąc w bruździe między nim a mięśniem biodrowym – mięsień lędźwiowy mniejszy jest szczątkowy i nieobecny u połowy osób. Jest nerwem **mieszanym**: ruchowo zaopatruje mięsień czworogłowy i krawiecki, czuciowo – przednią powierzchnię uda oraz przyśrodkową goleni przez **nerw udowo-goleniowy**.$E$,
   'Splot lędźwiowy', 'ANATLEK-732'),
(28, 'ANA-OBW',
   'Chód ptasi (koguci) jest skutkiem uszkodzenia nerwu:',
   '[{"id": "a", "text": "podeszwowego przyśrodkowego"}, {"id": "b", "text": "podeszwowego bocznego"}, {"id": "c", "text": "piszczelowego"}, {"id": "d", "text": "strzałkowego wspólnego"}, {"id": "e", "text": "udowego"}]'::jsonb,
   'd',
   $E$Uszkodzenie **nerwu strzałkowego wspólnego** – najczęściej na szyjce kości strzałkowej, gdzie leży powierzchownie – poraża prostowniki stopy i mięśnie strzałkowe. Powstaje **stopa opadająca**, którą chory musi wysoko unosić i „kłuć” palcami o podłoże, co daje **chód brodzący (koguci)**. Towarzyszy temu zniesienie czucia na grzbiecie stopy i bocznej powierzchni goleni. Porażenie nerwu piszczelowego daje **stopę piętową** z brakiem zgięcia podeszwowego.$E$,
   'Nerwy kończyny dolnej', 'ANATLEK-733'),
(29, 'ANA-NER',
   'Do gałęzi nerwu szczękowego nie należy:',
   '[{"id": "a", "text": "n. jarzmowy"}, {"id": "b", "text": "nn. skrzydłowo-podniebienne"}, {"id": "c", "text": "gałąź oponowa środkowa"}, {"id": "d", "text": "n. oczny"}, {"id": "e", "text": "n. podoczodołowy"}]'::jsonb,
   'd',
   $E$**Nerw szczękowy (V2)** opuszcza czaszkę przez **otwór okrągły** i oddaje: **gałąź oponową środkową**, **nerw jarzmowy**, **nerwy skrzydłowo-podniebienne** do zwoju oraz przechodzi w **nerw podoczodołowy** z nerwami zębodołowymi górnymi. **Nerw oczny (V1)** jest odrębną, równorzędną gałęzią nerwu trójdzielnego – odchodzi od zwoju trójdzielnego i biegnie do oczodołu przez **szczelinę oczodołową górną**, więc nie może być gałęzią V2.$E$,
   'Nerw trójdzielny', 'ANATLEK-734'),
(30, 'ANA-NER',
   'Gałęzie doprowadzające zwoju skrzydłowo-podniebiennego to:',
   '[{"id": "a", "text": "ruchowa z n. szczękowego, przywspółczulna z n. twarzowego, współczulna ze splotu szyjno-tętniczego wewnętrznego"}, {"id": "b", "text": "czuciowa z n. szczękowego, przywspółczulna z n. twarzowego, współczulna ze splotu szyjno-tętniczego wewnętrznego"}, {"id": "c", "text": "czuciowa z n. szczękowego, ruchowa z n. twarzowego, przywspółczulna ze splotu szyjno-tętniczego wewnętrznego"}, {"id": "d", "text": "czuciowa z n. szczękowego, przywspółczulna z n. językowo-gardłowego, współczulna ze splotu szyjno-tętniczego wewnętrznego"}, {"id": "e", "text": "czuciowa z n. szczękowego, ruchowa z n. językowo-gardłowego, współczulna ze splotu szyjno-tętniczego wewnętrznego"}]'::jsonb,
   'b',
   $E$Zwój skrzydłowo-podniebienny otrzymuje trzy korzenie: **czuciowy** – nerwy skrzydłowo-podniebienne od **V2** (włókna tylko przechodzą, bez przełączenia), **przywspółczulny** – **nerw skalisty większy** z nerwu twarzowego, oraz **współczulny** – **nerw skalisty głęboki** ze splotu tętnicy szyjnej wewnętrznej. Oba tworzą **nerw kanału skrzydłowego (widiański)**. Włókna zazwojowe unerwiają gruczoł łzowy oraz gruczoły nosa i podniebienia.$E$,
   'Zwoje przywspółczulne głowy', 'ANATLEK-735'),
(31, 'ANA-TUL',
   'Grzebień głowy żebra występuje na:',
   '[{"id": "a", "text": "pierwszym żebrze"}, {"id": "b", "text": "drugim żebrze"}, {"id": "c", "text": "jedenastym żebrze"}, {"id": "d", "text": "dwunastym żebrze"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'b',
   $E$**Grzebień głowy żebra** oddziela dwie powierzchnie stawowe głowy i występuje tam, gdzie żebro łączy się z **trzonami dwóch sąsiednich kręgów** – czyli na żebrach **II–X**. Żebra **I, XI i XII** mają głowę z **jedną powierzchnią stawową**, bez grzebienia, ponieważ łączą się tylko z odpowiadającym im kręgiem. Żebra XI i XII nie mają też **guzka żebra** i nie tworzą stawu żebrowo-poprzecznego – to żebra wolne. Głowa łączy się z trzonami stawem, a guzek – z wyrostkiem poprzecznym kręgu.$E$,
   'Żebra', 'ANATLEK-736'),
(32, 'ANA-TUL',
   'Więzadło podłużne przednie:',
   '[{"id": "a", "text": "biegnie na tylnej powierzchni trzonów kręgów"}, {"id": "b", "text": "biegnie na przedniej powierzchni trzonów kręgów"}, {"id": "c", "text": "rozpoczyna się na części podstawnej kości klinowej"}, {"id": "d", "text": "prawidłowe A i C"}, {"id": "e", "text": "prawidłowe B i C"}]'::jsonb,
   'b',
   $E$**Więzadło podłużne przednie** biegnie po **przedniej powierzchni trzonów kręgów**, od **części podstawnej kości potylicznej** (guzka gardłowego) i kręgu szczytowego aż do kości krzyżowej – nie od kości klinowej. Zrasta się mocno z trzonami, a luźno z krążkami, i **ogranicza przeprost** kręgosłupa. Powierzchnię tylną trzonów, w kanale kręgowym, pokrywa **więzadło podłużne tylne**, węższe w odcinku lędźwiowym.$E$,
   'Kręgosłup', 'ANATLEK-737'),
(33, 'ANA-CZA',
   'Elementem kości skroniowej nie jest:',
   '[{"id": "a", "text": "część łuskowa"}, {"id": "b", "text": "część stokowa"}, {"id": "c", "text": "część bębenkowa"}, {"id": "d", "text": "część sutkowa"}, {"id": "e", "text": "część skalista"}]'::jsonb,
   'b',
   $E$Kość skroniowa składa się z części **łuskowej**, **skalistej (piramidy)**, **bębenkowej** i **sutkowej**, a dodatkowo wytwarza **wyrostek rylcowaty** i **jarzmowy**. **Stok (clivus)** nie jest jej częścią – tworzą go **część podstawna kości potylicznej i trzon kości klinowej**. W piramidzie mieści się ucho wewnętrzne i przebiega kanał nerwu twarzowego, a przez część sutkową szerzą się zapalenia ucha środkowego. Wyrostek rylcowaty daje przyczep mięśniom i więzadłom pęczka Riolana.$E$,
   'Kość skroniowa', 'ANATLEK-738'),
(34, 'ANA-KON',
   'Staw skokowy dolny to staw:',
   '[{"id": "a", "text": "skokowo-goleniowy"}, {"id": "b", "text": "skokowo-piętowo-sześcienny"}, {"id": "c", "text": "skokowo-piętowo-łódkowy"}, {"id": "d", "text": "piętowo-łódkowo-sześcienny"}, {"id": "e", "text": "piętowo-łódkowo-klinowy"}]'::jsonb,
   'c',
   $E$**Staw skokowy dolny** obejmuje czynnościowo połączoną parę: **staw skokowo-piętowy (tylny)** i **staw skokowo-piętowo-łódkowy (przedni)**, rozdzielone **zatoką stępu** z więzadłem skokowo-piętowym międzykostnym. Odbywają się w nim ruchy **inwersji i ewersji** stopy wokół osi skośnej. Staw skokowo-goleniowy to staw skokowy **górny**, zawiasowy, odpowiadający za zgięcie grzbietowe i podeszwowe. Oba stawy skokowe działają wspólnie, umożliwiając ustawienie stopy na nierównym podłożu.$E$,
   'Stawy stopy', 'ANATLEK-739'),
(35, 'ANA-JAM',
   'Do mięśni wewnętrznych języka nie należy:',
   '[{"id": "a", "text": "mięsień podłużny górny"}, {"id": "b", "text": "mięsień podłużny dolny"}, {"id": "c", "text": "mięsień poprzeczny języka"}, {"id": "d", "text": "mięsień pionowy języka"}, {"id": "e", "text": "mięsień poprzeczny dolny języka"}]'::jsonb,
   'e',
   $E$Mięśnie **wewnętrzne** języka to cztery grupy włókien: **podłużny górny**, **podłużny dolny**, **poprzeczny** i **pionowy** – zmieniają kształt narządu, nie zmieniając jego położenia. Mięsień „poprzeczny dolny” nie istnieje. Mięśnie **zewnętrzne** (bródkowo-, gnykowo-, rylcowo- i podniebienno-językowy) przemieszczają język jako całość. Wszystkie poza podniebienno-językowym unerwia ruchowo **nerw podjęzykowy (XII)**. Czucie smaku z przednich dwóch trzecich języka prowadzi struna bębenkowa.$E$,
   'Język', 'ANATLEK-740'),
(36, 'ANA-TRZ',
   'Wybierz prawidłowe informacje dotyczące przełyku:',
   '[{"id": "a", "text": "przełyk składa się z części szyjnej, piersiowej i żołądkowej"}, {"id": "b", "text": "tylko zwężenie środkowe przełyku jest anatomiczne"}, {"id": "c", "text": "zwężenie górne przełyku znajduje się w jego części szyjnej"}, {"id": "d", "text": "wszystkie odpowiedzi prawidłowe"}, {"id": "e", "text": "prawidłowe tylko odpowiedzi B i C"}]'::jsonb,
   'c',
   $E$Przełyk dzieli się na część **szyjną, piersiową i brzuszną** (nie żołądkową). **Zwężenie górne (pierścienno-gardłowe)** leży na wysokości **C6**, w części szyjnej, i jest jedynym **anatomicznym** – zależy od budowy samej ściany. Zwężenie środkowe (aortowo-oskrzelowe) i dolne (przeponowe) wynikają z ucisku z zewnątrz i czynności zwieracza, więc nie jest prawdą, że tylko zwężenie środkowe jest anatomiczne.$E$,
   'Przełyk', 'ANATLEK-741'),
(37, 'ANA-TRZ',
   'Zachyłki otrzewnej znajdują się w:',
   '[{"id": "a", "text": "okolicy dwunastnicy"}, {"id": "b", "text": "okolicy jelita ślepego"}, {"id": "c", "text": "okolicy okrężnicy esowatej"}, {"id": "d", "text": "wszystkie odpowiedzi prawidłowe"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'd',
   $E$Zachyłki to kieszonki otrzewnej powstałe w miejscach zrastania krezek. Przy zgięciu dwunastniczo-czczym leżą **zachyłki dwunastnicze górny i dolny**, wokół kątnicy – **zachyłki krętniczo-kątnicze i zakątniczy**, a przy krezce esicy – **zachyłek międzyesowaty**. Wszystkie mają znaczenie kliniczne jako miejsca **przepuklin wewnętrznych** i zbierania się treści ropnej. Odrębne są zachyłki podprzeponowe i torba sieciowa.$E$,
   'Otrzewna', 'ANATLEK-742'),
(38, 'ANA-TRZ',
   'Przewód żółciowy wspólny powstaje z połączenia:',
   '[{"id": "a", "text": "przewodu wątrobowego prawego z przewodem pęcherzykowym"}, {"id": "b", "text": "przewodu wątrobowego lewego z przewodem pęcherzykowym"}, {"id": "c", "text": "przewodu wątrobowego wspólnego z przewodem pęcherzykowym"}, {"id": "d", "text": "przewodu wątrobowego wspólnego z przewodem pęcherzykowym i trzustkowym większym"}, {"id": "e", "text": "przewodu wątrobowego wspólnego z przewodem pęcherzykowym i trzustkowym mniejszym"}]'::jsonb,
   'c',
   $E$Przewody **wątrobowe prawy i lewy** łączą się we wnęce w **przewód wątrobowy wspólny**, który po dołączeniu **przewodu pęcherzykowego** tworzy **przewód żółciowy wspólny**. Biegnie on w więzadle wątrobowo-dwunastniczym, po prawej stronie tętnicy wątrobowej i przed żyłą wrotną. Dopiero w ścianie dwunastnicy łączy się z **przewodem trzustkowym większym**, tworząc **bańkę wątrobowo-trzustkową** ze zwieraczem Oddiego. Kamica przewodu żółciowego wspólnego prowadzi do żółtaczki mechanicznej.$E$,
   'Drogi żółciowe', 'ANATLEK-743'),
(39, 'ANA-TRZ',
   'Więzadło płucne jest:',
   '[{"id": "a", "text": "przedłużeniem opłucnej płucnej"}, {"id": "b", "text": "przedłużeniem opłucnej ściennej"}, {"id": "c", "text": "strukturą obejmującą korzeń płuca"}, {"id": "d", "text": "wytwarza wszystkie zachyłki opłucnej"}, {"id": "e", "text": "wytwarza tylko zachyłek żebrowo-śródpiersiowy opłucnej"}]'::jsonb,
   'a',
   $E$**Więzadło płucne** to podwójny fałd opłucnej **poniżej wnęki**, powstający jako przedłużenie **opłucnej płucnej** przechodzącej w opłucną śródpiersiową. Ma kształt trójkąta schodzącego ku przeponie i zapewnia płucu **rezerwę ruchomości** przy oddychaniu, nie obejmując samego korzenia. Zachyłki opłucnej – **żebrowo-przeponowy**, najgłębszy i najczęściej nakłuwany, oraz żebrowo-śródpiersiowy – powstają z opłucnej **ściennej**.$E$,
   'Opłucna', 'ANATLEK-744'),
(40, 'ANA-TRZ',
   'Tętnica wieńcowa lewa:',
   '[{"id": "a", "text": "rozpoczyna się w lewej zatoce aorty"}, {"id": "b", "text": "biegnie między uszkiem prawym a aortą wstępującą"}, {"id": "c", "text": "dzieli się na gałąź międzykomorową tylną i gałąź okalającą"}, {"id": "d", "text": "towarzyszy jej żyła średnia serca"}, {"id": "e", "text": "wszystkie odpowiedzi prawidłowe"}]'::jsonb,
   'a',
   $E$Pień lewej tętnicy wieńcowej odchodzi od **lewej zatoki aorty**, biegnie między **uszkiem lewym a pniem płucnym** i dzieli się na **gałąź międzykomorową przednią** oraz **gałąź okalającą** – nie na gałąź międzykomorową tylną, która u większości osób pochodzi z tętnicy wieńcowej prawej. Gałęzi międzykomorowej przedniej towarzyszy **żyła wielka serca**, natomiast **żyła średnia** biegnie w bruździe międzykomorowej tylnej. Pień lewej tętnicy wieńcowej jest krótki – ma zwykle 1–2 cm długości.$E$,
   'Serce', 'ANATLEK-745'),
(41, 'ANA-NAC',
   'Pęczek naczyniowo-nerwowy szyi:',
   '[{"id": "a", "text": "towarzyszy mu mięsień pochyły przedni"}, {"id": "b", "text": "zawiera tętnicę szyjną wspólną"}, {"id": "c", "text": "zawiera żyłę szyjną wspólną"}, {"id": "d", "text": "prawidłowe B i C"}, {"id": "e", "text": "wszystkie odpowiedzi prawidłowe"}]'::jsonb,
   'b',
   $E$Pęczek biegnie w **pochewce naczyń szyjnych** i zawiera trzy elementy: **tętnicę szyjną wspólną** przyśrodkowo, **żyłę szyjną wewnętrzną** bocznie oraz **nerw błędny** między nimi, w rowku od tyłu. Naczynie o nazwie „żyła szyjna wspólna” nie istnieje – są żyły szyjne wewnętrzna, zewnętrzna i przednia. Pęczek leży pod mięśniem mostkowo-obojczykowo-sutkowym; na mięśniu pochyłym przednim biegnie natomiast **nerw przeponowy**.$E$,
   'Pęczek naczyniowo-nerwowy szyi', 'ANATLEK-746'),
(42, 'ANA-NAC',
   'Prawidłowe pochodzenie gałęzi tętnicy szyjnej zewnętrznej to:',
   '[{"id": "a", "text": "t. językowa z gałęzi przednich, t. potyliczna z gałęzi tylnych i t. szczękowa z gałęzi końcowych"}, {"id": "b", "text": "t. językowa z gałęzi środkowych, t. uszna tylna z gałęzi tylnych i t. twarzowa z gałęzi końcowych"}, {"id": "c", "text": "t. twarzowa z gałęzi przednich, t. gardłowa wstępująca z gałęzi tylnych i t. szczękowa z gałęzi końcowych"}, {"id": "d", "text": "t. tarczowa górna z gałęzi przednich, t. skroniowa powierzchowna i t. szczękowa z gałęzi końcowych"}, {"id": "e", "text": "t. językowa z gałęzi przednich, t. twarzowa z gałęzi tylnych i t. językowa z gałęzi końcowych"}]'::jsonb,
   'a',
   $E$Gałęzie **przednie** to tętnice **tarczowa górna, językowa i twarzowa**, **tylne** – **potyliczna i uszna tylna**, gałąź **przyśrodkowa** to **tętnica gardłowa wstępująca**, a gałęzie **końcowe** to **szczękowa i skroniowa powierzchowna**, na które tętnica dzieli się w obrębie ślinianki przyusznej. Tętnica gardłowa wstępująca nie należy więc do gałęzi tylnych, a wariant z samą tarczową górną wśród przednich i dwoma gałęziami końcowymi pomija językową oraz twarzową.$E$,
   'Tętnica szyjna zewnętrzna', 'ANATLEK-747'),
(43, 'ANA-TRZ',
   'Unaczynienie śledziony pochodzi z:',
   '[{"id": "a", "text": "tętnicy śledzionowej z t. krezkowej górnej"}, {"id": "b", "text": "tętnicy śledzionowej z t. krezkowej dolnej"}, {"id": "c", "text": "tętnicy śledzionowej z t. żołądkowej krótkiej"}, {"id": "d", "text": "tętnicy śledzionowej z t. wątrobowej wspólnej"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'e',
   $E$**Tętnica śledzionowa** jest najgrubszą gałęzią **pnia trzewnego**, a nie żadnej z wymienionych tętnic – dlatego żadna odpowiedź nie jest prawdziwa. Biegnie krętym torem wzdłuż górnego brzegu trzustki i wchodzi do wnęki przez **więzadło przeponowo-śledzionowe**, oddając po drodze gałęzie trzustkowe, **tętnice żołądkowe krótkie** i tętnicę żołądkowo-sieciową lewą. Pień trzewny odchodzi od aorty na wysokości **Th12**. Krętość naczynia rośnie z wiekiem wraz ze zmianami miażdżycowymi.$E$,
   'Śledziona', 'ANATLEK-748'),
(44, 'ANA-TUL',
   'Żyła nieparzysta:',
   '[{"id": "a", "text": "leży w śródpiersiu tylnym dolnym"}, {"id": "b", "text": "leży w śródpiersiu górnym"}, {"id": "c", "text": "leży po stronie prawej klatki piersiowej"}, {"id": "d", "text": "prawidłowe A i C"}, {"id": "e", "text": "prawidłowe A, B i C"}]'::jsonb,
   'e',
   $E$Żyła nieparzysta powstaje z połączenia żyły lędźwiowej wstępującej prawej i żyły podżebrowej, wstępuje **po prawej stronie kręgosłupa** w **śródpiersiu tylnym**, a następnie jej **łuk** kieruje się do przodu nad korzeniem płuca prawego, w obrębie **śródpiersia górnego**, uchodząc do **żyły głównej górnej**. Stanowi główne połączenie obocznego krążenia między żyłą główną górną i dolną, co ma znaczenie przy niedrożności tych naczyń.$E$,
   'Żyły klatki piersiowej', 'ANATLEK-749'),
(45, 'ANA-KON',
   'Żyły powierzchowne kończyn uchodzą:',
   '[{"id": "a", "text": "ż. odłokciowa do ż. ramiennej, a ż. odstrzałkowa do ż. udowej"}, {"id": "b", "text": "ż. odłokciowa do ż. pachowej, a ż. odstrzałkowa do ż. udowej"}, {"id": "c", "text": "ż. odłokciowa do ż. ramiennej, a ż. odstrzałkowa do ż. podkolanowej"}, {"id": "d", "text": "ż. odpromieniowa do ż. pachowej, a ż. odstrzałkowa do ż. udowej"}, {"id": "e", "text": "ż. odpromieniowa do ż. ramiennej, a ż. odpiszczelowa do ż. udowej"}]'::jsonb,
   'c',
   $E$**Żyła odłokciowa** biegnie po stronie przyśrodkowej i przebija powięź w połowie ramienia, uchodząc do **żyły ramiennej**, natomiast **żyła odpromieniowa** wstępuje w bruździe naramienno-piersiowej do **żyły pachowej**. Na kończynie dolnej **żyła odstrzałkowa** kończy się w dole podkolanowym w **żyle podkolanowej**, a **żyła odpiszczelowa** uchodzi przez rozwór odpiszczelowy do **żyły udowej**. Wariant z odstrzałkową uchodzącą do żyły udowej myli ją z odpiszczelową.$E$,
   'Żyły powierzchowne', 'ANATLEK-750'),
(46, 'ANA-TRZ',
   'Żyła śledzionowa łączy się z:',
   '[{"id": "a", "text": "ż. nerkową lewą"}, {"id": "b", "text": "ż. biodrową wewnętrzną"}, {"id": "c", "text": "ż. główną dolną"}, {"id": "d", "text": "ż. krezkową górną"}, {"id": "e", "text": "ż. wątrobową wspólną"}]'::jsonb,
   'd',
   $E$**Żyła wrotna** powstaje za szyjką trzustki z połączenia **żyły śledzionowej** i **żyły krezkowej górnej**; **żyła krezkowa dolna** uchodzi zwykle do śledzionowej. Naczynie o nazwie „żyła wątrobowa wspólna” nie istnieje – żyły wątrobowe uchodzą wprost do żyły głównej dolnej. Zablokowanie odpływu wrotnego otwiera **zespolenia wrotno-układowe**: przełykowe, odbytnicze i okołopępkowe (głowa meduzy). Żyła wrotna dzieli się we wrotach wątroby na gałąź prawą i lewą.$E$,
   'Żyła wrotna', 'ANATLEK-751'),
(47, 'ANA-NAC',
   'Trójkąt tętnicy szyjnej jest ograniczony przez:',
   '[{"id": "a", "text": "m. MOS (mostkowo-obojczykowo-sutkowy), brzusiec dolny m. łopatkowo-gnykowego, brzusiec przedni m. dwubrzuścowego"}, {"id": "b", "text": "m. MOS (mostkowo-obojczykowo-sutkowy), brzusiec górny m. łopatkowo-gnykowego, brzusiec tylny m. dwubrzuścowego"}, {"id": "c", "text": "m. MOS (mostkowo-obojczykowo-sutkowy), brzusiec dolny i górny m. łopatkowo-gnykowego, brzusiec tylny m. dwubrzuścowego"}, {"id": "d", "text": "m. MOS (mostkowo-obojczykowo-sutkowy), brzusiec dolny i górny m. łopatkowo-gnykowego, brzusiec przedni m. dwubrzuścowego"}, {"id": "e", "text": "m. żuchwowo-gnykowy, brzusiec dolny i górny m. łopatkowo-gnykowego, brzusiec tylny m. dwubrzuścowego"}]'::jsonb,
   'b',
   $E$Trójkąt tętnicy szyjnej ograniczają: od tyłu **brzeg przedni mięśnia mostkowo-obojczykowo-sutkowego**, od dołu i przodu **brzusiec górny mięśnia łopatkowo-gnykowego**, a od góry **brzusiec tylny mięśnia dwubrzuścowego**. Brzusiec dolny należy do trójkąta łopatkowo-obojczykowego. W trójkącie leży **podział tętnicy szyjnej wspólnej** na wysokości chrząstki tarczowatej.$E$,
   'Trójkąty szyi', 'ANATLEK-752'),
(48, 'ANA-NAC',
   'Trójkąt Pirogowa zawiera:',
   '[{"id": "a", "text": "t. szyjną zewnętrzną"}, {"id": "b", "text": "t. twarzową"}, {"id": "c", "text": "t. szczękową"}, {"id": "d", "text": "t. językową"}, {"id": "e", "text": "t. gardłową wstępującą"}]'::jsonb,
   'd',
   $E$**Trójkąt Pirogowa** ograniczają: **ścięgno pośrednie mięśnia dwubrzuścowego**, **tylny brzeg mięśnia żuchwowo-gnykowego** i **nerw podjęzykowy**; dnem jest mięsień gnykowo-językowy. Pod nim przebiega **tętnica językowa** – dostęp ten wykorzystuje się do jej podwiązania. Sama tętnica odchodzi od tętnicy szyjnej zewnętrznej na wysokości rogu większego kości gnykowej, powyżej tętnicy tarczowej górnej. Nerw podjęzykowy stanowi granicę górną trójkąta i biegnie tuż nad nim.$E$,
   'Tętnica językowa', 'ANATLEK-753'),
(49, 'ANA-NAC',
   'Blaszka powierzchowna powięzi szyi przyczepia się do:',
   '[{"id": "a", "text": "gałęzi żuchwy, grzebienia łopatki, mostka i obojczyka"}, {"id": "b", "text": "kąta żuchwy, wyrostka kruczego łopatki, mostka i obojczyka"}, {"id": "c", "text": "trzonu żuchwy, wyrostka barkowego łopatki, mostka i obojczyka"}, {"id": "d", "text": "gałęzi żuchwy, wyrostka barkowego łopatki, mostka i obojczyka"}, {"id": "e", "text": "trzonu żuchwy, grzebienia łopatki, mostka i obojczyka"}]'::jsonb,
   'c',
   $E$Blaszka powierzchowna otacza szyję kołnierzowato: ku górze przyczepia się do **dolnego brzegu trzonu żuchwy**, kresy karkowej i wyrostka sutkowatego, ku dołowi do **rękojeści mostka, obojczyka oraz wyrostka barkowego i grzebienia łopatki**. Tworzy pochewki dla mięśni **mostkowo-obojczykowo-sutkowego i czworobocznego** oraz torebkę ślinianki przyusznej. Gałąź żuchwy leży głębiej i nie daje jej przyczepu. Blaszka ta zamyka od zewnątrz wszystkie przestrzenie międzypowięziowe szyi.$E$,
   'Powięzie szyi', 'ANATLEK-754'),
(50, 'ANA-MIE',
   'Mięsień skrzydłowy przyśrodkowy przyczepia się:',
   '[{"id": "a", "text": "w dole skrzydłowym, na wyrostku piramidowym kości podniebiennej, na wewnętrznej powierzchni kąta żuchwy"}, {"id": "b", "text": "w dole skrzydłowym, na wyrostku piramidowym kości sitowej, na wewnętrznej powierzchni kąta żuchwy"}, {"id": "c", "text": "w dole skrzydłowym, na wyrostku piramidowym kości sitowej, na zewnętrznej powierzchni kąta żuchwy"}, {"id": "d", "text": "w dole skrzydłowym, na wyrostku piramidowym kości skroniowej, na zewnętrznej powierzchni kąta żuchwy"}, {"id": "e", "text": "w dole skrzydłowym, na wyrostku piramidowym kości skroniowej, na wewnętrznej powierzchni kąta żuchwy"}]'::jsonb,
   'a',
   $E$Mięsień rozpoczyna się w **dole skrzydłowym** (na przyśrodkowej powierzchni blaszki bocznej wyrostka skrzydłowatego) oraz na **wyrostku piramidowym kości podniebiennej** i guzie szczęki, a kończy na **guzowatości skrzydłowej – wewnętrznej powierzchni kąta żuchwy**. Tworzy z mięśniem żwaczem **pętlę żwaczową** obejmującą kąt żuchwy. Unosi żuchwę i wysuwa ją do przodu; unerwia go **nerw żuchwowy (V3)**. Razem ze skrzydłowym bocznym odpowiada za ruchy żucia typu mielenia pokarmu.$E$,
   'Mięśnie żucia', 'ANATLEK-755'),
(51, 'ANA-KON',
   'W stawie nadgarstkowo-śródręcznym kciuka możliwe do wykonania ruchy to:',
   '[{"id": "a", "text": "przywodzenie, odwodzenie"}, {"id": "b", "text": "przeciwstawianie, odprowadzanie"}, {"id": "c", "text": "obwodzenie"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A, B i C"}]'::jsonb,
   'e',
   $E$Staw nadgarstkowo-śródręczny kciuka jest stawem **siodełkowym** między kością **czworoboczną większą** a podstawą I kości śródręcza. Ma **dwie osie ruchu**: zginanie i prostowanie oraz **odwodzenie i przywodzenie**, a ich złożenie daje **obwodzenie** i najważniejsze czynnościowo **przeciwstawianie (opozycję)** z odprowadzeniem. Ta ruchomość odpowiada za chwyt precyzyjny; jej utrata przy porażeniu nerwu pośrodkowego daje **rękę małpią**.$E$,
   'Stawy ręki', 'ANATLEK-756'),
(52, 'ANA-KON',
   'Mięsień prostownik wskaziciela należy do grupy:',
   '[{"id": "a", "text": "przedniej mięśni przedramienia, warstwy powierzchownej"}, {"id": "b", "text": "tylnej mięśni przedramienia, warstwy głębokiej"}, {"id": "c", "text": "bocznej mięśni przedramienia, warstwy powierzchownej"}, {"id": "d", "text": "przedniej mięśni przedramienia, warstwy głębokiej"}, {"id": "e", "text": "tylnej mięśni przedramienia, warstwy powierzchownej"}]'::jsonb,
   'b',
   $E$**Prostownik wskaziciela** należy do **warstwy głębokiej grupy tylnej** przedramienia, razem z **odwodzicielem długim kciuka, prostownikiem krótkim i długim kciuka** oraz odwracaczem. Jego ścięgno biegnie w czwartym przedziale pod troczkiem prostowników, przyśrodkowo od ścięgna prostownika palców, i umożliwia **niezależne prostowanie palca wskazującego**. Grupę tylną unerwia **nerw międzykostny tylny** z nerwu promieniowego.$E$,
   'Mięśnie przedramienia', 'ANATLEK-757'),
(53, 'ANA-JAM',
   'Prawidłowe stwierdzenia dotyczące ślinianki podjęzykowej to:',
   '[{"id": "a", "text": "przewód podjęzykowy większy uchodzi wzdłuż fałdu podjęzykowego"}, {"id": "b", "text": "jest unerwiona przez nerw językowo-gardłowy"}, {"id": "c", "text": "jest unaczyniona tętniczo przez gałęzie tętnicy twarzowej"}, {"id": "d", "text": "wszystkie odpowiedzi prawdziwe"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'e',
   $E$**Przewód podjęzykowy większy (Bartholina)** uchodzi na **mięsku podjęzykowym**, razem z przewodem podżuchwowym – wzdłuż fałdu podjęzykowego otwierają się jedynie **przewody mniejsze (Rivinusa)**. Unerwienie wydzielnicze pochodzi ze **struny bębenkowej nerwu twarzowego** przez zwój podżuchwowy, nie z nerwu IX. Głównym źródłem krwi jest **tętnica podjęzykowa** z tętnicy językowej, choć dochodzi też gałąź podbródkowa tętnicy twarzowej; to jednak nie jest główne źródło unaczynienia.$E$,
   'Ślinianki', 'ANATLEK-758'),
(54, 'ANA-JAM',
   'Unerwienie czuciowe języka pochodzi z nerwów:',
   '[{"id": "a", "text": "V2, VII i IX"}, {"id": "b", "text": "V2 i VII"}, {"id": "c", "text": "V2 i IX"}, {"id": "d", "text": "V3, VII i IX"}, {"id": "e", "text": "V3, IX i X"}]'::jsonb,
   'e',
   $E$Czucie ogólne przednich **2/3** języka prowadzi **nerw językowy z V3**, tylnej **1/3** – **nerw językowo-gardłowy (IX)**, a okolicy nasady i nagłośni – **nerw krtaniowy górny z nerwu błędnego (X)**. Nerw szczękowy (V2) nie unerwia języka. Czucie **smaku** biegnie natomiast z przodu **struną bębenkową (VII)**, z tyłu nerwem IX i X – dlatego wariant z VII dotyczy smaku, a nie czucia ogólnego, o które pyta zadanie. Jednostronne uszkodzenie IX znosi odruch wymiotny po tej samej stronie.$E$,
   'Unerwienie języka', 'ANATLEK-759'),
(55, 'ANA-TRZ',
   'Prawidłowe stwierdzenia dotyczące przełyku to:',
   '[{"id": "a", "text": "zaczyna się na wysokości VI kręgu szyjnego"}, {"id": "b", "text": "kończy się na wysokości kręgu XII piersiowego lub I lędźwiowego"}, {"id": "c", "text": "posiada trzy naturalne zwężenia, z czego dwa anatomiczne i jedno czynnościowe"}, {"id": "d", "text": "żyły dolnej części przełyku uchodzą do żyły żołądkowej prawej"}, {"id": "e", "text": "wszystkie odpowiedzi prawidłowe"}]'::jsonb,
   'a',
   $E$Przełyk zaczyna się na wysokości **C6**, na dolnym brzegu chrząstki pierścieniowatej, a kończy ujściem do żołądka na wysokości **Th11**, nie Th12/L1. Z trzech zwężeń **anatomiczne jest tylko górne**, pierścienno-gardłowe. Krew żylna z dolnego odcinka odpływa do **żyły żołądkowej lewej**, tworząc kluczowe **zespolenie wrotno-układowe** – podłoże żylaków przełyku w nadciśnieniu wrotnym. Ściana przełyku nie ma błony surowiczej poza krótkim odcinkiem brzusznym, co sprzyja szerzeniu się nowotworu.$E$,
   'Przełyk', 'ANATLEK-760'),
(56, 'ANA-TRZ',
   'Dwunastnica unaczyniona jest między innymi przez:',
   '[{"id": "a", "text": "t. trzustkowo-dwunastniczą górną, która jest gałęzią t. żołądkowo-dwunastniczej"}, {"id": "b", "text": "t. trzustkowo-dwunastniczą górną, która jest gałęzią t. wątrobowo-dwunastniczej"}, {"id": "c", "text": "t. trzustkowo-dwunastniczą dolną, która jest gałęzią t. krezkowej dolnej"}, {"id": "d", "text": "prawidłowe A i C"}, {"id": "e", "text": "prawidłowe B i C"}]'::jsonb,
   'a',
   $E$**Tętnica trzustkowo-dwunastnicza górna** odchodzi od **tętnicy żołądkowo-dwunastniczej**, czyli pośrednio z **pnia trzewnego**, a **dolna** – od **tętnicy krezkowej górnej**, nie dolnej. Ich zespolenie w łukach przednim i tylnym czyni dwunastnicę **strefą graniczną** między dorzeczami jelita przedniego i środkowego, co odpowiada miejscu ujścia przewodu żółciowego. Tętnica „wątrobowo-dwunastnicza” nie istnieje – to nazwa więzadła.$E$,
   'Dwunastnica', 'ANATLEK-761'),
(57, 'ANA-TRZ',
   'Słupy odbytu:',
   '[{"id": "a", "text": "utworzone są przez fałdy błony śluzowej"}, {"id": "b", "text": "występują w liczbie 5-10"}, {"id": "c", "text": "znajdują się w kanale odbytu"}, {"id": "d", "text": "wszystkie odpowiedzi prawidłowe"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'd',
   $E$**Słupy odbytowe (Morgagniego)** to podłużne **fałdy błony śluzowej** kanału odbytu, w liczbie około **5–10**, zawierające gałęzie **tętnicy odbytniczej górnej** i **splot żylny odbytniczy wewnętrzny**. U ich podstawy leżą **zatoki i zastawki odbytowe**, tworzące **linię grzebieniastą** – granicę między częścią endodermalną a ektodermalną. Poszerzenie splotu w tej okolicy daje **żylaki odbytu (hemoroidy) wewnętrzne**, niebolesne.$E$,
   'Odbytnica i kanał odbytu', 'ANATLEK-762'),
(58, 'ANA-TRZ',
   'Więzadłem wątroby nie jest więzadło:',
   '[{"id": "a", "text": "wieńcowe wątroby"}, {"id": "b", "text": "trójkątne wątroby przednie i tylne"}, {"id": "c", "text": "wątrobowo-przeponowe"}, {"id": "d", "text": "wątrobowo-nerkowe"}, {"id": "e", "text": "sierpowate"}]'::jsonb,
   'b',
   $E$Wątrobę mocują więzadła: **sierpowate**, **wieńcowe** z blaszką górną i dolną, **trójkątne prawe i lewe** (nie przednie i tylne), **wątrobowo-przeponowe**, **wątrobowo-nerkowe** oraz sieć mniejsza z więzadłami **wątrobowo-żołądkowym i wątrobowo-dwunastniczym**. Wszystkie są fałdami otrzewnej. Blaszki więzadła wieńcowego ograniczają **pole nagie** wątroby, pozbawione otrzewnej i przylegające bezpośrednio do przepony. Więzadło sierpowate dzieli powierzchnię przeponową na płat prawy i lewy.$E$,
   'Wątroba', 'ANATLEK-763'),
(59, 'ANA-TRZ',
   'Wątroba posiada unaczynienie:',
   '[{"id": "a", "text": "czynnościowe z żyły wrotnej"}, {"id": "b", "text": "odżywcze z tętnicy krezkowej górnej"}, {"id": "c", "text": "odżywcze z pnia trzewnego"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A i C"}]'::jsonb,
   'e',
   $E$Wątroba ma **podwójne unaczynienie**: **czynnościowe** – **żyła wrotna** przynosi ok. **75%** krwi bogatej we wchłonięte substancje, oraz **odżywcze** – **tętnica wątrobowa właściwa**, gałąź tętnicy wątrobowej wspólnej z **pnia trzewnego**, dostarczająca krew utlenowaną. Oba naczynia wchodzą przez **wrota wątroby** i rozgałęziają się aż do przestrzeni wrotno-żółciowych, a krew odpływa **żyłami wątrobowymi** do żyły głównej dolnej. Mieszanie się obu strumieni krwi następuje dopiero w sinusoidach zrazika.$E$,
   'Unaczynienie wątroby', 'ANATLEK-764'),
(60, 'ANA-TRZ',
   'Trzustka położona jest względem otrzewnej:',
   '[{"id": "a", "text": "głowa wewnątrzotrzewnowo, a trzon i ogon zaotrzewnowo"}, {"id": "b", "text": "głowa i trzon wewnątrzotrzewnowo, a ogon zaotrzewnowo"}, {"id": "c", "text": "głowa i ogon wewnątrzotrzewnowo, a trzon zaotrzewnowo"}, {"id": "d", "text": "cała wewnątrzotrzewnowo"}, {"id": "e", "text": "cała zaotrzewnowo"}]'::jsonb,
   'e',
   $E$Trzustka leży **zaotrzewnowo**, przy czym jest to położenie **wtórne** – pierwotnie miała krezkę, która zrosła się z tylną ścianą jamy brzusznej. Otrzewna pokrywa ją tylko od przodu, tworząc tylną ścianę **torby sieciowej**. Narząd rozciąga się od pętli dwunastnicy do wnęki śledziony na wysokości **L1–L2**. Ogon, biegnący w więzadle przeponowo-śledzionowym, bywa opisywany jako jedyna część o cechach wewnątrzotrzewnowych.$E$,
   'Trzustka', 'ANATLEK-765'),
(61, 'ANA-NER',
   'Splot przyuszniczy:',
   '[{"id": "a", "text": "jest utworzony przez gałęzie czuciowe nerwu twarzowego"}, {"id": "b", "text": "jest utworzony przez gałęzie czuciowe nerwu językowo-gardłowego"}, {"id": "c", "text": "jest utworzony przez gałęzie czuciowe pętli szyjnej"}, {"id": "d", "text": "jest utworzony przez gałęzie ruchowe nerwu twarzowego"}, {"id": "e", "text": "jest utworzony przez gałęzie ruchowe nerwu językowo-gardłowego"}]'::jsonb,
   'd',
   $E$**Splot przyuszniczy (gęsia stopka większa)** powstaje w miąższu ślinianki przyusznej z podziału pnia **nerwu twarzowego** po wyjściu z otworu rylcowo-sutkowego. Oddaje pięć grup gałęzi **ruchowych** do mięśni mimicznych: **skroniowe, jarzmowe, policzkowe, brzeżną żuchwy i szyjną**. Splot dzieli gruczoł na płat powierzchowny i głęboki, dlatego zabiegi w tej okolicy grożą **porażeniem obwodowym twarzy**. Włókna wydzielnicze dla ślinianki niesie natomiast nerw IX.$E$,
   'Nerw twarzowy', 'ANATLEK-766'),
(62, 'ANA-JAM',
   '2/3 przednie języka smakowo są unerwione przez:',
   '[{"id": "a", "text": "włókna smakowe z nerwu skalistego większego"}, {"id": "b", "text": "włókna smakowe z nerwu skalistego mniejszego"}, {"id": "c", "text": "włókna smakowe ze struny bębenkowej"}, {"id": "d", "text": "włókna smakowe z nerwu szczękowego"}, {"id": "e", "text": "włókna smakowe z nerwu żuchwowego"}]'::jsonb,
   'c',
   $E$Smak z przednich **2/3** języka prowadzi **struna bębenkowa** – gałąź **nerwu twarzowego**, która dołącza do nerwu językowego z V3 i wraz z nim dociera do błony śluzowej. Ciała komórek leżą w **zwoju kolanka**, a włókna kończą się w **jądrze pasma samotnego**. Nerw skalisty większy niesie włókna wydzielnicze do gruczołu łzowego, a skalisty mniejszy – z nerwu IX do ślinianki przyusznej. Nerw językowy odpowiada w tej okolicy tylko za **czucie ogólne**.$E$,
   'Czucie smaku', 'ANATLEK-767'),
(63, 'ANA-NER',
   'Jądra nerwu językowo-gardłowego to:',
   '[{"id": "a", "text": "jądro dwuznaczne – ruchowe, jądro pasma samotnego – przywspółczulne, jądro ślinowe górne – czuciowe"}, {"id": "b", "text": "jądro dwuznaczne – ruchowe, jądro klinowe górne – przywspółczulne, jądro pasma samotnego – czuciowe"}, {"id": "c", "text": "jądro dodatkowe – ruchowe, jądro ślinowe górne – przywspółczulne, jądro pasma samotnego – czuciowe"}, {"id": "d", "text": "jądro dwuznaczne – ruchowe, jądro klinowe dolne – przywspółczulne, jądro pasma samotnego – czuciowe"}, {"id": "e", "text": "jądro dwuznaczne – ruchowe, jądro ślinowe dolne – przywspółczulne, jądro pasma samotnego – czuciowe"}]'::jsonb,
   'e',
   $E$Nerw IX ma trzy jądra w **rdzeniu przedłużonym**: **dwuznaczne** – ruchowe dla mięśnia rylcowo-gardłowego, **ślinowe dolne** – przywspółczulne, którego włókna przez nerw skalisty mniejszy i **zwój uszny** unerwiają śliniankę przyuszną, oraz **pasma samotnego** – czuciowe i smakowe dla tylnej 1/3 języka, gardła i zatoki szyjnej. **Jądro ślinowe górne** należy do nerwu twarzowego, a jądra klinowe to jądra dróg czucia głębokiego.$E$,
   'Nerw językowo-gardłowy', 'ANATLEK-768'),
(64, 'ANA-NER',
   'Opadanie powieki górnej jest skutkiem uszkodzenia nerwu:',
   '[{"id": "a", "text": "trójdzielnego"}, {"id": "b", "text": "twarzowego"}, {"id": "c", "text": "bloczkowego"}, {"id": "d", "text": "okoruchowego"}, {"id": "e", "text": "odwodzącego"}]'::jsonb,
   'd',
   $E$**Nerw okoruchowy (III)** unerwia **dźwigacz powieki górnej**, dlatego jego porażenie daje **opadnięcie powieki (ptozę)**, ustawienie gałki **w dół i na zewnątrz** oraz – przy zajęciu włókien przywspółczulnych – **szeroką, sztywną źrenicę**. Nerw bloczkowy poraża mięsień skośny górny (dwojenie przy schodzeniu ze schodów), a odwodzący – prosty boczny, dając zez zbieżny. Niewielka ptoza z **wąską źrenicą** to natomiast zespół Hornera.$E$,
   'Nerw okoruchowy', 'ANATLEK-769'),
(65, 'ANA-OUN',
   'We wzgórkach górnych blaszki pokrywy znajdują się podkorowe ośrodki:',
   '[{"id": "a", "text": "smaku"}, {"id": "b", "text": "węchu"}, {"id": "c", "text": "wzroku"}, {"id": "d", "text": "słuchu"}, {"id": "e", "text": "wszystkich wyżej wymienionych"}]'::jsonb,
   'c',
   $E$**Wzgórki górne** blaszki pokrywy są podkorowymi ośrodkami **wzroku** – odbierają włókna z pasma wzrokowego przez ramię wzgórka górnego i pośredniczą w **odruchach źrenicznych oraz orientacyjnych ruchach głowy i oczu**. **Wzgórki dolne** to ośrodki **słuchu**, połączone z ciałem kolankowatym przyśrodkowym. Ośrodki podkorowe smaku i węchu leżą poza blaszką pokrywy: odpowiednio we wzgórzu i w opuszce oraz korze węchowej.$E$,
   'Śródmózgowie', 'ANATLEK-770'),
(66, 'ANA-CZA',
   'Błona naczyniowa gałki ocznej składa się z:',
   '[{"id": "a", "text": "naczyniówki, ciała rzęskowego i tęczówki"}, {"id": "b", "text": "naczyniówki, ciała szklistego i tęczówki"}, {"id": "c", "text": "naczyniówki, ciała rzęskowego i źrenicy"}, {"id": "d", "text": "naczyniówki, rogówki i tęczówki"}, {"id": "e", "text": "naczyniówki, tęczówki i spojówki"}]'::jsonb,
   'a',
   $E$Błona naczyniowa (**uvea**) obejmuje trzy odcinki: **naczyniówkę**, odżywiającą warstwy zewnętrzne siatkówki, **ciało rzęskowe** wytwarzające ciecz wodnistą i nastawiające soczewkę przez obwódkę rzęskową, oraz **tęczówkę** z mięśniami zwieraczem i rozwieraczem źrenicy. **Źrenica** to jedynie otwór w tęczówce, **rogówka i twardówka** tworzą błonę włóknistą, a **ciało szkliste** wypełnia wnętrze gałki. Zapalenie uvei nazywamy zapaleniem błony naczyniowej.$E$,
   'Gałka oczna', 'ANATLEK-771'),
(67, 'ANA-CZA',
   'Ściana dolna jamy bębenkowej to:',
   '[{"id": "a", "text": "ściana błędnikowa"}, {"id": "b", "text": "ściana błoniasta"}, {"id": "c", "text": "ściana szyjno-tętnicza"}, {"id": "d", "text": "ściana żyły szyjnej"}, {"id": "e", "text": "ściana sutkowa"}]'::jsonb,
   'd',
   $E$Jama bębenkowa ma sześć ścian: górną **pokrywkową** (od dołu środkowego czaszki), dolną **żyły szyjnej** – oddzielającą ją od **opuszki żyły szyjnej wewnętrznej**, boczną **błoniastą** z błoną bębenkową, przyśrodkową **błędnikową** ze wzgórkiem i okienkami, przednią **szyjno-tętniczą** przy tętnicy szyjnej wewnętrznej z ujściem trąbki oraz tylną **sutkową** z wejściem do jaskini. Cienka ściana dolna tłumaczy ryzyko krwawienia przy zabiegach na uchu.$E$,
   'Ucho środkowe', 'ANATLEK-772'),
(68, 'ANA-CZA',
   'Trąbka słuchowa (Eustachiusza) uchodzi w:',
   '[{"id": "a", "text": "części nosowej gardła"}, {"id": "b", "text": "części ustnej gardła"}, {"id": "c", "text": "przewodzie nosowym górnym"}, {"id": "d", "text": "przewodzie nosowym środkowym"}, {"id": "e", "text": "przewodzie nosowym dolnym"}]'::jsonb,
   'a',
   $E$Ujście gardłowe trąbki leży na **ścianie bocznej części nosowej gardła**, na wysokości małżowiny nosowej dolnej, otoczone **wałem trąbkowym** i migdałkiem trąbkowym; ku tyłowi od niego znajduje się **zachyłek gardłowy (Rosenmüllera)**. Trąbka wyrównuje ciśnienie w jamie bębenkowej, otwierając się przy połykaniu dzięki mięśniowi **napinaczowi podniebienia miękkiego**. U dzieci jest krótsza i bardziej pozioma, co sprzyja **zapaleniom ucha środkowego**.$E$,
   'Trąbka słuchowa', 'ANATLEK-773'),
(69, 'ANA-NER',
   'Jądro przywspółczulne nerwu podjęzykowego znajduje się w:',
   '[{"id": "a", "text": "międzymózgowiu przednim"}, {"id": "b", "text": "międzymózgowiu tylnym"}, {"id": "c", "text": "dole równoległobocznym"}, {"id": "d", "text": "śródmózgowiu"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'e',
   $E$**Nerw podjęzykowy (XII) nie ma jądra przywspółczulnego** – jest nerwem czysto **ruchowym somatycznym**. Jego jądro leży w **rdzeniu przedłużonym**, pod trójkątem nerwu podjęzykowego w dole równoległobocznym. Włókna przywspółczulne w obrębie głowy niosą tylko nerwy **III, VII, IX i X**, z jądrami: dodatkowym (Edingera-Westphala), ślinowym górnym, ślinowym dolnym i grzbietowym nerwu błędnego. Uszkodzenie XII zbacza język **w stronę uszkodzenia**.$E$,
   'Nerw podjęzykowy', 'ANATLEK-774'),
(70, 'ANA-CZA',
   'Stok jest utworzony przez kości:',
   '[{"id": "a", "text": "klinową, skroniową i potyliczną"}, {"id": "b", "text": "sitową, klinową i skroniową"}, {"id": "c", "text": "sitową, potyliczną i skroniową"}, {"id": "d", "text": "tylko klinową i potyliczną"}, {"id": "e", "text": "tylko klinową i skroniową"}]'::jsonb,
   'd',
   $E$**Stok (clivus)** powstaje ze zrośnięcia **części podstawnej kości potylicznej** z **tylną powierzchnią trzonu kości klinowej** – połączenie to kostnieje ostatecznie około 20. roku życia. Tworzy pochyłą powierzchnię dołu tylnego czaszki, na której spoczywają **most i rdzeń przedłużony**, a wzdłuż niej biegnie **tętnica podstawna**. Kość skroniowa sąsiaduje ze stokiem przez **szczelinę skalisto-potyliczną**, ale go nie buduje.$E$,
   'Podstawa czaszki', 'ANATLEK-775'),
(71, 'ANA-NAC',
   'Tętnica szczękowa:',
   '[{"id": "a", "text": "jest jedną z gałęzi końcowych tętnicy szyjnej zewnętrznej"}, {"id": "b", "text": "składa się z części żuchwowej, skrzydłowej i żwaczowej"}, {"id": "c", "text": "składa się z części żuchwowej, skrzydłowej i zębodołowej"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A i C"}]'::jsonb,
   'a',
   $E$Tętnica szczękowa jest większą **gałęzią końcową tętnicy szyjnej zewnętrznej**, odchodzącą w miąższu ślinianki przyusznej za szyjką żuchwy. Dzieli się na trzy odcinki: **żuchwowy**, **skrzydłowy** i **skrzydłowo-podniebienny** – nazwy „żwaczowa” i „zębodołowa” dotyczą jej gałęzi, a nie części. Z odcinka pierwszego odchodzi **tętnica oponowa środkowa**, której uszkodzenie przy złamaniu łuski skroniowej daje **krwiak nadtwardówkowy**.$E$,
   'Tętnica szczękowa', 'ANATLEK-776'),
(72, 'ANA-TRZ',
   'Tętnica nadnerczowa środkowa jest gałęzią:',
   '[{"id": "a", "text": "trzewną nieparzystą aorty piersiowej"}, {"id": "b", "text": "trzewną parzystą aorty brzusznej"}, {"id": "c", "text": "ścienną parzystą aorty piersiowej"}, {"id": "d", "text": "trzewną nieparzystą aorty brzusznej"}, {"id": "e", "text": "trzewną parzystą aorty piersiowej"}]'::jsonb,
   'b',
   $E$**Tętnica nadnerczowa środkowa** odchodzi bezpośrednio od **aorty brzusznej** na wysokości **L1**, obok tętnicy krezkowej górnej, i należy do gałęzi **trzewnych parzystych** – tak jak tętnice **nerkowe** oraz **jądrowe/jajnikowe**. Gałęzie trzewne nieparzyste to pień trzewny oraz tętnice krezkowe górna i dolna. Nadnercze otrzymuje ponadto **tętnicę nadnerczową górną** z tętnicy przeponowej dolnej i **dolną** z tętnicy nerkowej. Prawa tętnica nadnerczowa środkowa biegnie za żyłą główną dolną.$E$,
   'Nadnercza', 'ANATLEK-777'),
(73, 'ANA-KON',
   'Głównym naczyniem doprowadzającym krew do łuku tętniczego dłoniowego głębokiego jest:',
   '[{"id": "a", "text": "tętnica łokciowa"}, {"id": "b", "text": "tętnica promieniowa"}, {"id": "c", "text": "tętnica ramienna"}, {"id": "d", "text": "tętnica pachowa"}, {"id": "e", "text": "tętnica pośrodkowa przedramienia"}]'::jsonb,
   'b',
   $E$**Łuk dłoniowy głęboki** tworzy głównie **tętnica promieniowa**, która przechodzi przez tabakierkę anatomiczną i pierwszą przestrzeń międzykostną na stronę dłoniową, gdzie zespala się z **gałęzią głęboką tętnicy łokciowej**. Odwrotnie jest w **łuku dłoniowym powierzchownym**, zasilanym przede wszystkim przez **tętnicę łokciową**. Drożność obu naczyń sprawdza się **próbą Allena** przed nakłuciem tętnicy promieniowej. Łuk głęboki leży bliżej nadgarstka niż powierzchowny.$E$,
   'Tętnice ręki', 'ANATLEK-778'),
(74, 'ANA-OUN',
   'Dół równoległoboczny:',
   '[{"id": "a", "text": "tworzy dno komory trzeciej"}, {"id": "b", "text": "składa się z części przedniej i tylnej"}, {"id": "c", "text": "jest podzielony na całej swojej długości bruzdą pośrodkową"}, {"id": "d", "text": "w jego części mostowej znajduje się wzgórek nerwu trójdzielnego"}, {"id": "e", "text": "wszystkie odpowiedzi prawdziwe"}]'::jsonb,
   'c',
   $E$Dół równoległoboczny stanowi **dno komory czwartej** i dzieli się na część **mostową (górną) i rdzeniową (dolną)**, rozgraniczone **prążkami rdzennymi**, a nie na przednią i tylną. Na całej długości biegnie przez niego **bruzda pośrodkowa**, a po bokach **wyniosłość przyśrodkowa**. W części mostowej leży **wzgórek nerwu twarzowego** (kolano VII nad jądrem VI), natomiast trójkąt nerwu podjęzykowego i błędnego – w części rdzeniowej.$E$,
   'Komora czwarta', 'ANATLEK-779'),
(75, 'ANA-OUN',
   'Który z elementów śródmózgowia zawiera drogi korowo-jądrowe?',
   '[{"id": "a", "text": "nakrywka"}, {"id": "b", "text": "blaszka pokrywy"}, {"id": "c", "text": "odnogi mózgu"}, {"id": "d", "text": "wodociąg mózgu"}, {"id": "e", "text": "istota czarna"}]'::jsonb,
   'c',
   $E$Drogi **korowo-jądrowe i korowo-rdzeniowe** biegną w **odnogach mózgu**, dokładniej w ich brzusznej części – **podstawie (crus cerebri)**, gdzie zajmują środkowe 3/5 wraz z drogami korowo-mostowymi. **Istota czarna** oddziela podstawę od **nakrywki**, w której leżą jądra nerwów III i IV, jądro czerwienne i wstęgi. **Blaszka pokrywy** to wzgórki górne i dolne, a **wodociąg mózgu** łączy komorę trzecią z czwartą. Uszkodzenie odnogi daje niedowład połowiczy po stronie przeciwnej.$E$,
   'Śródmózgowie', 'ANATLEK-780'),
(76, 'ANA-OUN',
   'Kora czuciowa zajmuje:',
   '[{"id": "a", "text": "zakręt przedśrodkowy i zakręt zaśrodkowy"}, {"id": "b", "text": "zakręt zaśrodkowy i część płacika okołośrodkowego"}, {"id": "c", "text": "zakręt przedśrodkowy i część płacika okołośrodkowego"}, {"id": "d", "text": "zakręt skroniowy poprzeczny i pole prążkowe"}, {"id": "e", "text": "zakręt skroniowy górny i pole prążkowe"}]'::jsonb,
   'b',
   $E$Pierwszorzędowa kora czuciowa (**pola 3, 1, 2**) leży w **zakręcie zaśrodkowym** płata ciemieniowego i przechodzi na powierzchnię przyśrodkową jako **tylna część płacika okołośrodkowego**, gdzie reprezentowana jest kończyna dolna i krocze. Odpowiada jej **homunkulus czuciowy** z ogromną reprezentacją ręki i twarzy. **Zakręt przedśrodkowy** to kora ruchowa (pole 4), **zakręty skroniowe poprzeczne** – kora słuchowa, a pole prążkowe – wzrokowa.$E$,
   'Kora mózgu', 'ANATLEK-781'),
(77, 'ANA-OUN',
   'Drogi korowo-jądrowe przebiegają przez:',
   '[{"id": "a", "text": "odnogę przednią torebki wewnętrznej"}, {"id": "b", "text": "odnogę tylną torebki wewnętrznej"}, {"id": "c", "text": "odnogę przednią torebki zewnętrznej"}, {"id": "d", "text": "odnogę tylną torebki zewnętrznej"}, {"id": "e", "text": "kolano torebki wewnętrznej"}]'::jsonb,
   'e',
   $E$**Kolano torebki wewnętrznej** zawiera **drogi korowo-jądrowe** kierujące się do jąder ruchowych nerwów czaszkowych. W **odnodze tylnej** biegną drogi **korowo-rdzeniowe**, wstęga przyśrodkowa oraz promienistości wzrokowa i słuchowa, a w **odnodze przedniej** – drogi czołowo-mostowe i pasmo wzgórzowe przednie. Torebka zewnętrzna to cienka warstwa istoty białej między skorupą a przedmurzem, bez odnóg. Unaczynienie kolana zapewniają **tętnice prążkowiowo-torebkowe**.$E$,
   'Torebka wewnętrzna', 'ANATLEK-782'),
(78, 'ANA-KON',
   'Staw ramienny jest:',
   '[{"id": "a", "text": "stawem kulistym panewkowym"}, {"id": "b", "text": "stawem kulistym wolnym"}, {"id": "c", "text": "jego panewka powiększona jest przez więzadło kruczo-barkowe"}, {"id": "d", "text": "prawidłowe A i C"}, {"id": "e", "text": "prawidłowe B i C"}]'::jsonb,
   'b',
   $E$Staw ramienny to **staw kulisty wolny** – mała, płytka **panewka** obejmuje jedynie około jednej trzeciej głowy kości ramiennej, co daje największy zakres ruchów w organizmie kosztem stabilności i sprzyja **zwichnięciom**. Panewkę pogłębia **obrąbek stawowy**, a nie więzadło kruczo-barkowe, które wraz z wyrostkami tworzy **sklepienie stawu**. Przykładem stawu kulistego **panewkowego** o głębokiej panewce jest staw biodrowy.$E$,
   'Staw ramienny', 'ANATLEK-783'),
(79, 'ANA-TUL',
   'Najsilniejszą częścią przepony jest:',
   '[{"id": "a", "text": "środek ścięgnisty"}, {"id": "b", "text": "część żebrowa"}, {"id": "c", "text": "część mostkowa"}, {"id": "d", "text": "część lędźwiowa"}, {"id": "e", "text": "wszystkie części przepony są jednakowo silne"}]'::jsonb,
   'd',
   $E$**Część lędźwiowa** jest najsilniejsza i najgrubsza – tworzą ją **odnoga prawa i lewa** przyczepiające się do trzonów kręgów L1–L4 oraz więzadła łukowate. Przez nią przechodzą **rozwór aortowy (Th12)** i **rozwór przełykowy (Th10)**. Część mostkowa jest najsłabsza; między nią a żebrową leży **trójkąt mostkowo-żebrowy (Larreya)**, a między żebrową a lędźwiową **trójkąt lędźwiowo-żebrowy (Bochdaleka)** – typowe miejsca **przepuklin przeponowych**.$E$,
   'Przepona', 'ANATLEK-784'),
(80, 'ANA-TUL',
   'Otwór żyły głównej znajduje się w:',
   '[{"id": "a", "text": "części żebrowej przepony"}, {"id": "b", "text": "części mostkowej przepony"}, {"id": "c", "text": "części lędźwiowej przepony"}, {"id": "d", "text": "środku ścięgnistym przepony"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'd',
   $E$**Otwór żyły głównej** leży w **środku ścięgnistym**, na wysokości **Th8**, nieco na prawo od linii pośrodkowej; przechodzi przez niego żyła główna dolna i gałąź przeponowo-brzuszna **nerwu przeponowego prawego**. Ponieważ ściany otworu są ścięgniste, wdech go **rozszerza** i ułatwia powrót żylny. Wyżej niż pozostałe otwory: **przełykowy** leży na Th10 w części mięśniowej, a **aortowy** na Th12, między odnogami. Mnemonik: **żyła 8, przełyk 10, aorta 12**.$E$,
   'Przepona', 'ANATLEK-785'),
(81, 'ANA-OUN',
   'Z rdzeniem kręgowym łączy się:',
   '[{"id": "a", "text": "30 par nerwów rdzeniowych za pomocą korzeni brzusznych"}, {"id": "b", "text": "30 par nerwów rdzeniowych za pomocą korzeni grzbietowych"}, {"id": "c", "text": "30 par nerwów rdzeniowych za pomocą korzeni bocznych"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'e',
   $E$Z rdzeniem łączy się **31 par** nerwów rdzeniowych: 8 szyjnych, 12 piersiowych, 5 lędźwiowych, 5 krzyżowych i 1 guziczna – liczba 30 jest błędna, dlatego żadna odpowiedź nie jest prawdziwa. Każdy nerw powstaje z połączenia **korzenia brzusznego (ruchowego)** i **grzbietowego (czuciowego)** ze **zwojem rdzeniowym**; korzenie boczne nie istnieją. Poniżej **L1–L2** korzenie tworzą **ogon koński**, co umożliwia bezpieczne nakłucie lędźwiowe.$E$,
   'Rdzeń kręgowy', 'ANATLEK-786'),
(82, 'ANA-OUN',
   'Do dróg rdzeniowo-mózgowych sznura tylnego należy:',
   '[{"id": "a", "text": "pęczek smukły"}, {"id": "b", "text": "pęczek przegrodowo-brzeżny"}, {"id": "c", "text": "pęczek własny"}, {"id": "d", "text": "pęczek międzypęczkowy"}, {"id": "e", "text": "wszystkie wyżej wymienione"}]'::jsonb,
   'a',
   $E$Sznur tylny zawiera dwie drogi **rdzeniowo-mózgowe** czucia głębokiego i dotyku różnicującego: **pęczek smukły (Golla)** – przyśrodkowy, z kończyny dolnej i tułowia poniżej Th6, oraz **pęczek klinowaty (Burdacha)** – boczny, z kończyny górnej. Kończą się w jądrach smukłym i klinowatym rdzenia przedłużonego. Pęczki **przegrodowo-brzeżny, międzypęczkowy i własne** to drogi **spoidłowo-kojarzeniowe** łączące sąsiednie segmenty w obrębie samego rdzenia.$E$,
   'Drogi rdzenia kręgowego', 'ANATLEK-787'),
(83, 'ANA-OUN',
   'Zachyłek nadszyszynkowy jest elementem:',
   '[{"id": "a", "text": "komory bocznej mózgu"}, {"id": "b", "text": "komory trzeciej mózgu"}, {"id": "c", "text": "komory czwartej mózgu"}, {"id": "d", "text": "zatoki strzałkowej dolnej"}, {"id": "e", "text": "zatoki strzałkowej górnej"}]'::jsonb,
   'b',
   $E$**Komora trzecia** wytwarza cztery zachyłki: **nadszyszynkowy** i **szyszynkowy** w ścianie tylnej, **wzrokowy** nad skrzyżowaniem oraz **lejka** w dnie. Zachyłek nadszyszynkowy leży nad podstawą szyszynki, pod przyczepem splotu naczyniówkowego. Komora trzecia łączy się z bocznymi przez **otwory międzykomorowe (Monroe)**, a z czwartą przez **wodociąg mózgu**. Zatoki strzałkowe to naczynia żylne opony twardej i nie mają zachyłków.$E$,
   'Układ komorowy', 'ANATLEK-788'),
(84, 'ANA-OUN',
   'Do elementów układu pozapiramidowego nie należy:',
   '[{"id": "a", "text": "jądro brzuszne przednie wzgórza"}, {"id": "b", "text": "jądro ogoniaste"}, {"id": "c", "text": "jądro pasma samotnego"}, {"id": "d", "text": "istota czarna"}, {"id": "e", "text": "gałka blada"}]'::jsonb,
   'c',
   $E$**Jądro pasma samotnego** to jądro **czuciowo-smakowe i trzewne** nerwów VII, IX i X w rdzeniu przedłużonym – nie ma związku z kontrolą ruchu. Układ pozapiramidowy tworzą **jądra podstawne**: ogoniaste, skorupa i **gałka blada**, wraz z **istotą czarną**, jądrem niskowzgórzowym, jądrem czerwiennym oraz jądrami wzgórza (**brzusznym przednim i bocznym**) jako stacją przekaźnikową do kory. Zwyrodnienie istoty czarnej daje **chorobę Parkinsona**.$E$,
   'Układ pozapiramidowy', 'ANATLEK-789'),
(85, 'ANA-OUN',
   'Głównym skupiskiem dróg rzutowych jest:',
   '[{"id": "a", "text": "gałka blada"}, {"id": "b", "text": "skorupa"}, {"id": "c", "text": "sklepienie"}, {"id": "d", "text": "ciało modzelowate"}, {"id": "e", "text": "torebka wewnętrzna"}]'::jsonb,
   'e',
   $E$**Drogi rzutowe (projekcyjne)** łączą korę z niższymi piętrami układu nerwowego i zbiegają się w **torebce wewnętrznej**, tworząc poniżej **wieniec promienisty**, a niżej odnogi mózgu. **Ciało modzelowate** to największe włókna **spoidłowe** łączące obie półkule, **sklepienie** należy do układu limbicznego, a gałka blada i skorupa to jądra podstawne. Ognisko w torebce wewnętrznej daje rozległy **niedowład połowiczy** mimo niewielkich rozmiarów.$E$,
   'Istota biała półkul', 'ANATLEK-790'),
(86, 'ANA-OUN',
   'Torebka ostatnia leży między:',
   '[{"id": "a", "text": "skorupą a gałką bladą"}, {"id": "b", "text": "gałką bladą a przedmurzem"}, {"id": "c", "text": "gałką bladą a wyspą"}, {"id": "d", "text": "przedmurzem a wyspą"}, {"id": "e", "text": "wzgórzem a skorupą"}]'::jsonb,
   'd',
   $E$Idąc od boku ku środkowi: kora **wyspy**, **torebka ostatnia**, **przedmurze**, **torebka zewnętrzna**, **skorupa**, gałka blada i wreszcie **torebka wewnętrzna** oddzielająca jądro soczewkowate od wzgórza i jądra ogoniastego. Torebka ostatnia jest więc cienką blaszką istoty białej **między przedmurzem a korą wyspy**. Prosty sposób zapamiętania: obie „zewnętrzne” torebki otaczają przedmurze – zewnętrzna od strony skorupy, ostatnia od strony wyspy.$E$,
   'Torebki istoty białej', 'ANATLEK-791'),
(87, 'ANA-OUN',
   'Blaszka krańcowa jest elementem ściany:',
   '[{"id": "a", "text": "przyśrodkowej rogu przedniego komory bocznej"}, {"id": "b", "text": "przyśrodkowej rogu tylnego komory bocznej"}, {"id": "c", "text": "przedniej komory trzeciej"}, {"id": "d", "text": "górnej komory trzeciej"}, {"id": "e", "text": "tylnej komory czwartej"}]'::jsonb,
   'c',
   $E$**Blaszka krańcowa** to cienka płytka istoty szarej rozpięta między **skrzyżowaniem wzrokowym a spoidłem przednim**, tworząca **przednią ścianę komory trzeciej** – jest pozostałością przedniego końca cewy nerwowej. Ścianę górną stanowi **splot naczyniówkowy z tkanką naczyniówkową**, boczne – **wzgórza i podwzgórza**, a tylną – **spoidło tylne i szyszynka**. W obrębie blaszki leży **narząd naczyniowy** pozbawiony bariery krew–mózg.$E$,
   'Komora trzecia', 'ANATLEK-792'),
(88, 'ANA-OUN',
   'Do elementów nadwzgórza nie należy:',
   '[{"id": "a", "text": "szyszynka"}, {"id": "b", "text": "przysadka"}, {"id": "c", "text": "trójkąt uzdeczki"}, {"id": "d", "text": "spoidło uzdeczki"}, {"id": "e", "text": "spoidło tylne"}]'::jsonb,
   'b',
   $E$**Nadwzgórze (epithalamus)** obejmuje **szyszynkę**, **uzdeczki z trójkątami i spoidłem uzdeczki**, **spoidło tylne** oraz **prążek rdzenny wzgórza**. **Przysadka** należy do **podwzgórza**: zawieszona jest na lejku i spoczywa w siodle tureckim, a jej płat tylny stanowi wypustkę międzymózgowia. Szyszynka wydziela **melatoninę** i bierze udział w regulacji rytmu dobowego; u dorosłych często wapnieje, co czyni ją punktem odniesienia w obrazowaniu.$E$,
   'Międzymózgowie', 'ANATLEK-793'),
(89, 'ANA-OUN',
   'Do elementów ośrodków i drogi słuchowej należą:',
   '[{"id": "a", "text": "jądra ciała czworobocznego, jądra wzgórka górnego, jądra ciała kolankowatego bocznego"}, {"id": "b", "text": "jądra wstęgi bocznej, jądra wzgórka górnego, jądra ciała kolankowatego bocznego"}, {"id": "c", "text": "jądra ciała czworobocznego, jądra wzgórka dolnego, jądra ciała kolankowatego przyśrodkowego"}, {"id": "d", "text": "jądra wstęgi bocznej, jądra wzgórka dolnego, jądra ciała kolankowatego bocznego"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'c',
   $E$Droga słuchowa biegnie od jąder ślimakowych przez **jądra ciała czworobocznego** i jądra wstęgi bocznej do **wzgórka dolnego**, następnie do **ciała kolankowatego przyśrodkowego** i przez promienistość słuchową do **zakrętów skroniowych poprzecznych (Heschla)**. **Wzgórek górny i ciało kolankowate boczne** należą do drogi **wzrokowej** – to najczęstsza pułapka w tym pytaniu. Częściowe skrzyżowanie włókien sprawia, że jednostronne uszkodzenie ośrodków nie daje głuchoty.$E$,
   'Droga słuchowa', 'ANATLEK-794'),
(90, 'ANA-NAC',
   'Tętnica mózgu tylna:',
   '[{"id": "a", "text": "jest parzysta"}, {"id": "b", "text": "jest gałęzią tętnicy szyjnej wewnętrznej"}, {"id": "c", "text": "jest gałęzią tętnicy kręgowej"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A i C"}]'::jsonb,
   'a',
   $E$**Tętnice mózgu tylne** są **parzyste** i powstają z podziału **tętnicy podstawnej**, utworzonej przez połączenie obu tętnic kręgowych – nie odchodzą więc ani od tętnicy szyjnej wewnętrznej, ani wprost od kręgowej. Z tętnicą szyjną wewnętrzną łączy je **tętnica łącząca tylna**, zamykająca **koło tętnicze mózgu (Willisa)**. Zaopatrują płat potyliczny i dolną część skroniowego, dlatego ich niedrożność powoduje **niedowidzenie połowicze**.$E$,
   'Koło tętnicze mózgu', 'ANATLEK-795'),
(91, 'ANA-TUL',
   'Mięśnie płatowate głowy i szyi należą do:',
   '[{"id": "a", "text": "mięśni powierzchownych grzbietu"}, {"id": "b", "text": "mięśni głębokich grzbietu"}, {"id": "c", "text": "mięśni głębokich szyi"}, {"id": "d", "text": "mięśni powierzchownych szyi"}, {"id": "e", "text": "mięśni głębokich klatki piersiowej"}]'::jsonb,
   'b',
   $E$Mięśnie **płatowate głowy i szyi** to najbardziej powierzchowna warstwa mięśni **głębokich (właściwych) grzbietu**, rozwijających się z **miotomów grzbietowych** i unerwionych przez **gałęzie grzbietowe nerwów rdzeniowych** – to kryterium rozstrzyga o przynależności. Biegną skośnie od wyrostków kolczystych do kresy karkowej i wyrostków poprzecznych kręgów szyjnych, prostując i skręcając głowę. Mięśnie powierzchowne grzbietu, jak czworoboczny, unerwiają gałęzie brzuszne.$E$,
   'Mięśnie grzbietu', 'ANATLEK-796'),
(92, 'ANA-KON',
   'Ścianę dolną jamy pachowej tworzy między innymi:',
   '[{"id": "a", "text": "mięsień piersiowy mniejszy"}, {"id": "b", "text": "mięsień zębaty tylny"}, {"id": "c", "text": "mięsień zębaty przedni"}, {"id": "d", "text": "mięsień najszerszy grzbietu"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'e',
   $E$Ściana dolna, czyli **podstawa jamy pachowej**, nie zawiera mięśni – tworzą ją **skóra dołu pachowego i powięź pachowa**, dlatego żadna z odpowiedzi nie jest prawdziwa. Mięsień **piersiowy mniejszy** wchodzi w skład ściany przedniej, **najszerszy grzbietu** wraz z obłym większym i podłopatkowym – tylnej, a **zębaty przedni** buduje ścianę przyśrodkową. Ścianę boczną stanowi **bruzda międzyguzkowa** kości ramiennej z mięśniami dwugłowym i kruczo-ramiennym.$E$,
   'Jama pachowa', 'ANATLEK-797'),
(93, 'ANA-KON',
   'Do mięśni kłębu kciuka nie należy:',
   '[{"id": "a", "text": "m. odwodziciel krótki kciuka"}, {"id": "b", "text": "m. zginacz krótki kciuka"}, {"id": "c", "text": "m. przeciwstawiacz kciuka"}, {"id": "d", "text": "m. przywodziciel kciuka"}, {"id": "e", "text": "m. przywodziciel krótki kciuka"}]'::jsonb,
   'e',
   $E$Kłąb tworzą cztery mięśnie: **odwodziciel krótki**, **zginacz krótki**, **przeciwstawiacz** i **przywodziciel kciuka** – mięsień „przywodziciel krótki kciuka” nie istnieje. Pierwsze trzy unerwia **nerw pośrodkowy** (gałąź mięśniowa oddawana za troczkiem zginaczy), a przywodziciel i głowę głęboką zginacza krótkiego – **gałąź głęboka nerwu łokciowego**. Zanik kłębu z brakiem opozycji to obraz **ręki małpiej** w zaawansowanym zespole cieśni nadgarstka.$E$,
   'Mięśnie ręki', 'ANATLEK-798'),
(94, 'ANA-KON',
   'Mięsień dwugłowy uda:',
   '[{"id": "a", "text": "jest w całości mięśniem jednostawowym"}, {"id": "b", "text": "jest w całości mięśniem dwustawowym"}, {"id": "c", "text": "należy do grupy tylnej mięśni uda"}, {"id": "d", "text": "prawidłowe A i C"}, {"id": "e", "text": "prawidłowe B i C"}]'::jsonb,
   'c',
   $E$Mięsień dwugłowy uda należy do **grupy tylnej** wraz z półścięgnistym i półbłoniastym. Jego **głowa długa** rozpoczyna się na guzie kulszowym i jest **dwustawowa** – prostuje staw biodrowy i zgina kolano, natomiast **głowa krótka** odchodzi od kresy chropawej kości udowej i działa **tylko na staw kolanowy**. Dlatego stwierdzenia o jednolitym charakterze mięśnia są fałszywe. Głowę długą unerwia część piszczelowa, a krótką – strzałkowa **nerwu kulszowego**.$E$,
   'Mięśnie uda', 'ANATLEK-799'),
(95, 'ANA-KON',
   'Dół biodrowo-łonowy znajduje się w obrębie:',
   '[{"id": "a", "text": "kanału przywodzicieli"}, {"id": "b", "text": "kanału pachwinowego"}, {"id": "c", "text": "kanału udowego"}, {"id": "d", "text": "kanału zasłonowego"}, {"id": "e", "text": "trójkąta udowego"}]'::jsonb,
   'e',
   $E$**Dół biodrowo-łonowy** to zagłębienie dna **trójkąta udowego**, utworzone przez mięsień **biodrowo-lędźwiowy** bocznie i **grzebieniowy** przyśrodkowo, oddzielone **łukiem biodrowo-grzebieniowym**. Trójkąt ograniczają **więzadło pachwinowe**, mięsień **krawiecki** i **przywodziciel długi**. W dole leży pęczek naczyniowy: od boku **nerw udowy**, tętnica i żyła udowa oraz przyśrodkowo **kanał udowy** – miejsce przepukliny udowej. Mnemonik ułożenia: **NAŻP** od boku ku środkowi.$E$,
   'Trójkąt udowy', 'ANATLEK-800'),
(96, 'ANA-KON',
   'Kanał przywodzicieli:',
   '[{"id": "a", "text": "łączy trójkąt udowy z dołem podkolanowym"}, {"id": "b", "text": "jego ścianę przednią stanowi głowa przyśrodkowa m. czworogłowego"}, {"id": "c", "text": "jego ścianę boczną stanowi m. przywodziciel wielki"}, {"id": "d", "text": "jego ścianę przyśrodkową stanowi blaszka ścięgnista"}, {"id": "e", "text": "wszystkie odpowiedzi prawidłowe"}]'::jsonb,
   'a',
   $E$**Kanał przywodzicieli (Huntera)** biegnie w przyśrodkowej części uda i łączy **trójkąt udowy** z **dołem podkolanowym** przez **rozwór ścięgnisty przywodzicieli**. Ścianę **boczną** tworzy **mięsień obszerny przyśrodkowy**, **przyśrodkowo-tylną** – przywodziciele długi i wielki, a **przednią** – **blaszka ścięgnista (vastoadductoria)**, co odwraca opisy z pozostałych wariantów. Przechodzą tędy **tętnica i żyła udowa** oraz **nerw udowo-goleniowy**.$E$,
   'Kanał przywodzicieli', 'ANATLEK-801'),
(97, 'ANA-KON',
   'Dół podkolanowy ograniczony jest przez:',
   '[{"id": "a", "text": "mm. półścięgnisty, półbłoniasty, podeszwowy, dwugłowy uda"}, {"id": "b", "text": "mm. półścięgnisty, półbłoniasty, piszczelowy tylny, dwugłowy uda"}, {"id": "c", "text": "mm. półścięgnisty, półbłoniasty, strzałkowy długi, dwugłowy uda"}, {"id": "d", "text": "mm. półścięgnisty, półbłoniasty, strzałkowy krótki, dwugłowy uda"}, {"id": "e", "text": "brak prawidłowej odpowiedzi"}]'::jsonb,
   'a',
   $E$Dół podkolanowy ma kształt rombu: od góry i przyśrodkowo ograniczają go **mięśnie półścięgnisty i półbłoniasty**, od góry i bocznie **mięsień dwugłowy uda**, a od dołu **głowy mięśnia brzuchatego łydki** wraz z **mięśniem podeszwowym**. Dno tworzą powierzchnia podkolanowa kości udowej i mięsień podkolanowy. Zawartość, licząc od głębi: **tętnica podkolanowa**, żyła, a najbardziej powierzchownie **nerw piszczelowy** – kolejność istotna przy urazach.$E$,
   'Dół podkolanowy', 'ANATLEK-802'),
(98, 'ANA-CZA',
   'Kość skroniowa składa się z części:',
   '[{"id": "a", "text": "łuskowej, kolcowej, bębenkowej i podstawy"}, {"id": "b", "text": "łuskowej, sutkowej, bębenkowej i podstawy"}, {"id": "c", "text": "łuskowej, kolcowej, sutkowej i podstawy"}, {"id": "d", "text": "łuskowej, bębenkowej, sutkowej i piramidy"}, {"id": "e", "text": "łuskowej, bębenkowej, piramidy i podstawy"}]'::jsonb,
   'd',
   $E$Kość skroniowa powstaje ze zrośnięcia czterech elementów: **łuski**, **części bębenkowej** otaczającej przewód słuchowy zewnętrzny, **części sutkowej** z komórkami powietrznymi oraz **części skalistej, czyli piramidy**, mieszczącej ucho wewnętrzne. „Podstawa” i „część kolcowa” to elementy kości **klinowej** – kolec klinowy leży obok otworu owalnego. Od łuski odchodzi **wyrostek jarzmowy**, a między częścią bębenkową a sutkową – **wyrostek rylcowaty**.$E$,
   'Kość skroniowa', 'ANATLEK-803'),
(99, 'ANA-CZA',
   'Ścianę przyśrodkową oczodołu budują między innymi:',
   '[{"id": "a", "text": "wyrostek czołowy szczęki, blaszka oczodołowa kości sitowej, kość nosowa"}, {"id": "b", "text": "wyrostek czołowy szczęki, powierzchnia oczodołowa kości podniebiennej, kość łzowa"}, {"id": "c", "text": "wyrostek czołowy szczęki, blaszka sitowa kości sitowej, kość łzowa"}, {"id": "d", "text": "wyrostek czołowy szczęki, kość łzowa, kość klinowa"}, {"id": "e", "text": "wyrostek czołowy szczęki, blaszka sitowa kości sitowej, kość klinowa"}]'::jsonb,
   'd',
   $E$Ścianę przyśrodkową tworzą kolejno od przodu: **wyrostek czołowy szczęki**, **kość łzowa** z dołem woreczka łzowego, **blaszka oczodołowa (papierowata) kości sitowej** i **trzon kości klinowej**. **Blaszka sitowa** leży poziomo w dole przednim czaszki i nie wchodzi w skład oczodołu, a kość nosowa buduje szkielet nosa. Bardzo cienka blaszka papierowata sprzyja szerzeniu się **zapaleń z zatok sitowych** oraz złamaniom przyśrodkowym typu blow-out.$E$,
   'Oczodół', 'ANATLEK-804'),
(100, 'ANA-CZA',
   'Do zawartości dołu skrzydłowo-podniebiennego nie należy:',
   '[{"id": "a", "text": "splot żylny skrzydłowy"}, {"id": "b", "text": "zwój skrzydłowo-podniebienny"}, {"id": "c", "text": "nerw szczękowy"}, {"id": "d", "text": "tętnica szczękowa"}, {"id": "e", "text": "naczynia skrzydłowo-podniebienne"}]'::jsonb,
   'a',
   $E$W dole skrzydłowo-podniebiennym znajdują się: **nerw szczękowy (V2)**, **zwój skrzydłowo-podniebienny** z nerwem kanału skrzydłowego oraz **trzeci, skrzydłowo-podniebienny odcinek tętnicy szczękowej** z gałęziami. **Splot żylny skrzydłowy** leży w **dole podskroniowym**, między mięśniami skrzydłowymi – to on łączy się z zatoką jamistą przez żyły emisariuszowe. Dół komunikuje się z oczodołem szczeliną oczodołową dolną, a z jamą czaszki – **otworem okrągłym**.$E$,
   'Dół skrzydłowo-podniebienny', 'ANATLEK-805')
),
maxes AS (
  SELECT topic_id, COALESCE(MAX( (regexp_match(id, '([0-9]+)$'))[1]::int ), 0) AS mx
    FROM public.questions WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') GROUP BY topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam)
SELECT
  LOWER(n.topic_id) || '-' || LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_anat_2026/1', 'Egzamin anatomia LEK SUM 2026 (ANATLEK e2026-1)'
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (SELECT topic_id, COUNT(*) AS cnt FROM public.questions
         WHERE topic_id IN ('ANA-CZA', 'ANA-JAM', 'ANA-KON', 'ANA-MIE', 'ANA-NAC', 'ANA-NER', 'ANA-OBW', 'ANA-OUN', 'ANA-TRZ', 'ANA-TUL') AND COALESCE(is_active,true)=true GROUP BY topic_id) sub
 WHERE t.id = sub.topic_id;
