-- ============================================================
-- BATCH: e_biof_lek_2026/1  ·  subject_id=biofizyka  ·  tracks=lekarski
-- Źródło: BIOFIZLEK e2026-1, 69 pytań A–D, LaTeX/$...$ bez zmian
-- id = biofiz-{suffix}-NNN · theme_label = 2026 (kafelek wirtualny, bez duplikatu)
-- Wygenerowane przez scripts/build-biofizlek-e2026-1.py (nie edytować ręcznie)
-- ============================================================

INSERT INTO public.topics (id, subject_id, name, display_order, question_count, tracks)
VALUES (
  'BIOF-INNE',
  'biofizyka',
  'Inne',
  12,
  0,
  ARRAY['lekarski']::TEXT[]
)
ON CONFLICT (id) DO UPDATE SET
  subject_id    = EXCLUDED.subject_id,
  name          = EXCLUDED.name,
  display_order = EXCLUDED.display_order,
  tracks        = EXCLUDED.tracks;

INSERT INTO public.topics (id, subject_id, name, display_order, question_count, tracks)
VALUES (
  'biofizyka-THEME-2026',
  'biofizyka',
  '2026',
  13,
  0,
  ARRAY['lekarski']::TEXT[]
)
ON CONFLICT (id) DO UPDATE SET
  subject_id    = EXCLUDED.subject_id,
  name          = EXCLUDED.name,
  display_order = EXCLUDED.display_order,
  tracks        = EXCLUDED.tracks;

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
(1, 'BIOF-W1',
   $STEM$Na wykresie zależności dwóch wielkości ($y=f(x)$) można przedstawić punkty pomiarowe ($x_i$ i $y_i$) oraz ich błędy bezwzględne ($\Delta x_i$ i $\Delta y_i$) w postaci prostokątów błędów wokół punktów pomiarowych. Boki każdego z prostokątów błędów są odpowiednio równe:$STEM$,
   $OPTS$[{"id": "a", "text": "$2\\Delta x_i$ i $2\\Delta y_i$"}, {"id": "b", "text": "$\\Delta x_i$ i $\\Delta y_i$"}, {"id": "c", "text": "$\\frac{\\Delta x_i}{2}$ i $\\frac{\\Delta y_i}{2}$"}, {"id": "d", "text": "$\\frac{\\Delta x_i}{x_i}$ i $\\frac{\\Delta y_i}{y_i}$"}]$OPTS$::jsonb,
   'a',
   $EXPL$Prostokąt błędu rysuje się tak, aby punkt pomiarowy $(x_i,y_i)$ leżał w jego **środku**, a niepewność odkładana jest w **obie strony**: od $x_i-\Delta x_i$ do $x_i+\Delta x_i$ oraz od $y_i-\Delta y_i$ do $y_i+\Delta y_i$. Bok poziomy ma zatem długość $2\Delta x_i$, a pionowy $2\Delta y_i$. Prosta dopasowana do danych powinna przechodzić przez wszystkie prostokąty. Iloraz $\Delta x_i/x_i$ to **błąd względny**, a nie bok prostokąta.$EXPL$,
   $SUB$Graficzna prezentacja wyników$SUB$, 'BIOFIZLEK-71'),
(2, 'BIOF-W5',
   $STEM$W przypadku tomografii NMR (jądrowy rezonans magnetyczny) przeciwwskazaniem do badań jest:$STEM$,
   $OPTS$[{"id": "a", "text": "reakcja uczuleniowa na silne pole magnetyczne"}, {"id": "b", "text": "zmiany miażdżycowe w tętnicach"}, {"id": "c", "text": "nowotwór"}, {"id": "d", "text": "posiadanie metalowej protezy w ciele"}]$OPTS$::jsonb,
   'd',
   $EXPL$Stałe pole o indukcji **1,5–3 T** działa siłą na elementy ferromagnetyczne: mogą się one przemieszczać, nagrzewać prądami wirowymi i uszkadzać tkanki, a dodatkowo dają rozległe **artefakty** obrazu. Bezwzględne przeciwwskazania to rozrusznik serca, klipsy naczyniowe, implant ślimakowy i opiłki metalu w gałce ocznej. Uczulenie na pole magnetyczne nie istnieje, a nowotwór i miażdżyca są **wskazaniami** do badania, nie przeciwwskazaniami.$EXPL$,
   $SUB$Przeciwwskazania do badania$SUB$, 'BIOFIZLEK-72'),
(3, 'BIOF-S3',
   $STEM$Wraz ze zwiększaniem się głębokości wnikania fal ultradźwiękowych w tkanki miękkie zmniejsza się amplituda drgań ultradźwięków. Efekt ten charakteryzuje współczynnik osłabiania ultradźwięków w tkankach, który zależy od zjawisk:$STEM$,
   $OPTS$[{"id": "a", "text": "rozpraszania i odbicia ultradźwięków w tkankach"}, {"id": "b", "text": "załamania i odbicia ultradźwięków w tkankach"}, {"id": "c", "text": "załamania i absorpcji ultradźwięków w tkankach"}, {"id": "d", "text": "rozpraszania i absorpcji ultradźwięków w tkankach"}]$OPTS$::jsonb,
   'd',
   $EXPL$Osłabianie opisuje zależność $I=I_0e^{-\alpha x}$, gdzie $\alpha$ to **współczynnik osłabiania**. Składają się na niego **absorpcja** (zamiana energii akustycznej w ciepło, dominująca w tkankach miękkich) i **rozpraszanie** na niejednorodnościach mniejszych od długości fali. Odbicie i załamanie zachodzą na granicach dużych struktur i tworzą obraz, ale nie wchodzą do $\alpha$. Ponieważ $\alpha$ rośnie z częstotliwością, wyższe częstotliwości dają lepszą rozdzielczość kosztem głębokości.$EXPL$,
   $SUB$Osłabianie ultradźwięków w tkankach$SUB$, 'BIOFIZLEK-73'),
(4, 'BIOF-C2',
   $STEM$Wadę oka zwaną krótkowzrocznością koryguje się soczewkami rozpraszającymi. Jaka jest zdolność skupiająca takiej soczewki wyrażona w postaci wzoru, jeżeli $R$ oznacza refrakcję oka, a $c$ — odległość soczewki od oka?$STEM$,
   $OPTS$[{"id": "a", "text": "$\\frac{-R}{1+cR}$"}, {"id": "b", "text": "$\\frac{R}{1-cR}$"}, {"id": "c", "text": "$\\frac{-R}{1-cR}$"}, {"id": "d", "text": "$\\frac{R}{1+cR}$"}]$OPTS$::jsonb,
   'd',
   $EXPL$Soczewka ma odwzorować nieskończoność w **punkcie dalekim** oka, leżącym w odległości $1/R$ od oka (dla krótkowzroczności $R<0$, punkt przed okiem). Soczewkę oddaloną o $c$ dzieli od tego punktu odcinek $1/R+c$, stąd $Z=\frac{1}{1/R+c}=\frac{R}{1+cR}$ — wartość ujemna, czyli soczewka **rozpraszająca**. Wariant $\frac{-R}{1-cR}$ daje znak dodatni i przeczy konwencji znaku refrakcji przyjętej w pytaniu o oko dalekowzroczne.$EXPL$,
   $SUB$Refrakcja i optyka oka$SUB$, 'BIOFIZLEK-74'),
(5, 'BIOF-C2',
   $STEM$Dla oka dalekowzrocznego ($R$ – refrakcja oka) punkt daleki znajduje się w skończonej odległości:$STEM$,
   $OPTS$[{"id": "a", "text": "przed okiem, a $R>0$"}, {"id": "b", "text": "za okiem, a $R<0$"}, {"id": "c", "text": "przed okiem, a $R<0$"}, {"id": "d", "text": "za okiem, a $R>0$"}]$OPTS$::jsonb,
   'd',
   $EXPL$Punkt daleki to punkt sprzężony z siatkówką przy **braku akomodacji**. W oku dalekowzrocznym układ optyczny jest za słaby względem długości gałki, więc na siatkówce ostro skupiają się jedynie promienie **zbieżne** — punkt daleki jest **pozorny** i leży za okiem. Odpowiada temu dodatnia refrakcja $R>0$ i korekcja soczewką **skupiającą**. W krótkowzroczności punkt daleki leży realnie przed okiem, a $R<0$; w oku miarowym $R=0$ i punkt daleki jest w nieskończoności.$EXPL$,
   $SUB$Refrakcja i optyka oka$SUB$, 'BIOFIZLEK-75'),
(6, 'BIOF-C2',
   $STEM$Większą zdolność rozdzielczą mikroskopu można uzyskać poprzez:$STEM$,
   $OPTS$[{"id": "a", "text": "zastosowanie promieniowania o większej długości fali"}, {"id": "b", "text": "zwiększenie apertury numerycznej obiektywu"}, {"id": "c", "text": "zwiększenie powiększenia okularu"}, {"id": "d", "text": "zwiększenie natężenia oświetlenia preparatu"}]$OPTS$::jsonb,
   'b',
   $EXPL$Granicę rozdzielczości opisuje wzór Abbego $d=\frac{0{,}61\lambda}{NA}$, gdzie $NA=n\sin\alpha$. Rozdzielczość rośnie (czyli $d$ maleje) przy **zwiększeniu apertury numerycznej**, np. dzięki **immersji olejowej** ($n\approx1{,}5$), albo przy **skróceniu** długości fali — nigdy przy jej wydłużeniu. Zwiększanie powiększenia okularu ponad granicę wyznaczoną przez $NA$ daje **powiększenie puste**: obraz jest większy, lecz bez nowych szczegółów. Jaśniejsze oświetlenie poprawia tylko kontrast.$EXPL$,
   $SUB$Mikroskopia optyczna$SUB$, 'BIOFIZLEK-76'),
(7, 'BIOF-C1',
   $STEM$Prawo Lamberta-Beera opisuje zależność absorbancji promieniowania elektromagnetycznego przechodzącego przez roztwór. Absorbancja definiowana zgodnie z tym prawem jest wprost proporcjonalna do:$STEM$,
   $OPTS$[{"id": "a", "text": "stężenia substancji absorbującej oraz kąta padania światła"}, {"id": "b", "text": "stężenia substancji absorbującej oraz współczynnika ekstynkcji"}, {"id": "c", "text": "stężenia substancji absorbującej oraz natężenia światła padającego"}, {"id": "d", "text": "stężenia substancji absorbującej oraz długości fali"}]$OPTS$::jsonb,
   'b',
   $EXPL$Prawo Lamberta-Beera: $A=\varepsilon cl$, przy czym $A=\log\frac{I_0}{I}$, $\varepsilon$ to **molowy współczynnik absorpcji (ekstynkcji)**, $c$ — stężenie, $l$ — grubość warstwy. Absorbancja rośnie więc liniowo ze stężeniem, ze współczynnikiem ekstynkcji i z drogą optyczną, co pozwala oznaczać stężenia w spektrofotometrii. Nie zależy natomiast od natężenia wiązki padającej ani od kąta padania; $\varepsilon$ zmienia się z długością fali, ale dla ustalonej $\lambda$ jest stałą substancji.$EXPL$,
   $SUB$Absorpcja promieniowania$SUB$, 'BIOFIZLEK-77'),
(8, 'BIOF-S2',
   $STEM$Głębokości wnikania fali elektromagnetycznej z zakresu promieniowania widzialnego zielonego (VIS-G), nadfioletowego (UV) i podczerwonego (IR) w skórę i tkanki podskórne można uszeregować od największej do najmniejszej w następujący sposób:$STEM$,
   $OPTS$[{"id": "a", "text": "UV, VIS-G, IR"}, {"id": "b", "text": "IR, VIS-G, UV"}, {"id": "c", "text": "VIS-G, IR, UV"}, {"id": "d", "text": "UV, IR, VIS-G"}]$OPTS$::jsonb,
   'b',
   $EXPL$W zakresie od UV do bliskiej podczerwieni głębokość wnikania **rośnie z długością fali**. **UV** jest silnie pochłaniany przez DNA, białka i melaninę już w naskórku (UVB ułamki mm, UVA do skóry właściwej). Światło **zielone** dociera na ok. 1 mm i jest silnie absorbowane przez hemoglobinę, a **IR-A** (ok. 1000 nm) sięga kilku–kilkunastu mm, do tkanki podskórnej. Stąd tzw. okno terapeutyczne laserów biostymulacyjnych obejmuje **600–1200 nm**.$EXPL$,
   $SUB$Oddziaływanie promieniowania ze skórą$SUB$, 'BIOFIZLEK-78'),
(9, 'BIOF-C3',
   $STEM$Zgodnie z wzorem Stokesa, siła lepkości działająca na kulkę o promieniu $r$, opadającą z prędkością $v$ w cieczy lepkiej jest:$STEM$,
   $OPTS$[{"id": "a", "text": "odwrotnie proporcjonalna do $v$ oraz do $r$"}, {"id": "b", "text": "wprost proporcjonalna do $v$ oraz do $r$"}, {"id": "c", "text": "wprost proporcjonalna do $v$, a odwrotnie proporcjonalna do $r$"}, {"id": "d", "text": "wprost proporcjonalna do $r$, a odwrotnie proporcjonalna do $v$"}]$OPTS$::jsonb,
   'b',
   $EXPL$Wzór Stokesa: $F=6\pi\eta rv$ — siła oporu lepkiego jest **wprost proporcjonalna** do lepkości $\eta$, promienia kulki i jej prędkości. Obowiązuje dla opływu laminarnego kuli, czyli małych liczb Reynoldsa. Po zrównoważeniu ciężaru przez siłę wyporu i opór kulka opada ruchem **jednostajnym**, a z pomiaru czasu przelotu wyznacza się $\eta$ — na tej zasadzie działa **wiskozymetr Höpplera** (kulkowy), używany m.in. do oznaczania lepkości osocza i krwi.$EXPL$,
   $SUB$Wiskozymetria$SUB$, 'BIOFIZLEK-79'),
(10, 'BIOF-S2',
   $STEM$Fala elektromagnetyczna z zakresu UV ma w porównaniu z falą elektromagnetyczną z zakresu IR:$STEM$,
   $OPTS$[{"id": "a", "text": "większą długość fali i mniejszą częstotliwość"}, {"id": "b", "text": "mniejszą długość fali i mniejszą częstotliwość"}, {"id": "c", "text": "większą długość fali i większą częstotliwość"}, {"id": "d", "text": "mniejszą długość fali i większą częstotliwość"}]$OPTS$::jsonb,
   'd',
   $EXPL$Dla fali elektromagnetycznej $c=\lambda\nu$, więc długość fali i częstotliwość są **odwrotnie proporcjonalne**. Zakres **UV** to 100–400 nm, **IR** — od 780 nm do 1 mm, zatem UV ma krótszą falę, wyższą częstotliwość i zgodnie z $E=h\nu$ większą energię fotonu. Dlatego UV wywołuje reakcje **fotochemiczne** (dimery tyminy, rumień), a niskoenergetyczna IR głównie efekty **cieplne**, pobudzając drgania oscylacyjne cząsteczek.$EXPL$,
   $SUB$Widmo fal elektromagnetycznych$SUB$, 'BIOFIZLEK-80'),
(11, 'BIOF-INNE',
   $STEM$Gdy pomiędzy dwa roztwory o różnym stężeniu wprowadzimy błonę półprzepuszczalną, nastąpi przenikanie rozpuszczalnika z roztworu o niższym stężeniu do roztworu o wyższym stężeniu. Skutkiem tego pojawia się ciśnienie osmotyczne działające na błonę w kierunku przeciwnym do przepływu rozpuszczalnika. Ciśnienie to określa prawo van't Hoffa, które wyrażamy wzorem ($c_m$ – stężenie molowe roztworu, $R$ – stała gazowa, $T$ – temperatura roztworu):$STEM$,
   $OPTS$[{"id": "a", "text": "$\\pi=c_mRT$"}, {"id": "b", "text": "$\\pi=\\frac{c_m}{RT}$"}, {"id": "c", "text": "$\\pi=\\frac{RT}{c_m}$"}, {"id": "d", "text": "$\\pi=c_m+RT$"}]$OPTS$::jsonb,
   'a',
   $EXPL$Prawo van't Hoffa $\pi=c_mRT$ jest formalnie identyczne z równaniem stanu gazu doskonałego — cząsteczki substancji rozpuszczonej zachowują się jak gaz wypełniający objętość rozpuszczalnika. Dla elektrolitów wprowadza się **współczynnik van't Hoffa** $i$: $\pi=ic_mRT$. Ciśnienie osmotyczne to własność **koligatywna**: zależy od liczby cząstek, a nie ich rodzaju. Dla osocza wynosi ok. **7,5 atm** przy osmolalności ok. **290 mOsm/kg**.$EXPL$,
   $SUB$Osmoza$SUB$, 'BIOFIZLEK-81'),
(12, 'BIOF-INNE',
   $STEM$Potencjał błonowy (który definiuje się jako różnicę między potencjałami wewnątrz i na zewnątrz komórki) w spoczynku nosi nazwę potencjału spoczynkowego. Mechanizmy samoregulacji utrzymują potencjał spoczynkowy mięśni szkieletowych o wartościach rzędu:$STEM$,
   $OPTS$[{"id": "a", "text": "$\\mu\\mathrm{V}$"}, {"id": "b", "text": "$\\mathrm{mV}$"}, {"id": "c", "text": "$\\mathrm{nV}$"}, {"id": "d", "text": "$\\mathrm{kV}$"}]$OPTS$::jsonb,
   'b',
   $EXPL$Potencjał spoczynkowy włókna mięśnia szkieletowego wynosi ok. **-90 mV** (neuron ok. -70 mV), czyli rząd **miliwoltów**. Wynika z gradientów jonowych utrzymywanych przez **pompę Na⁺/K⁺-ATPazę** i z przewagi przepuszczalności błony dla K⁺; ilościowo opisuje go równanie **Goldmana-Hodgkina-Katza**, a dla pojedynczego jonu — równanie Nernsta. Wartości rzędu $\mu\mathrm{V}$ mają sygnały EEG mierzone z powierzchni ciała, a kilovolty w układach biologicznych nie występują.$EXPL$,
   $SUB$Elektryczne właściwości błon$SUB$, 'BIOFIZLEK-82'),
(13, 'BIOF-S3',
   $STEM$Jeżeli fala ultradźwiękowa przechodzi z ośrodka o impedancji akustycznej $Z_1$ do ośrodka o impedancji $Z_2$, to ilość energii, która ulegnie odbiciu od powierzchni granicznej pomiędzy obu ośrodkami (prostopadłej do kierunku rozchodzenia się fal) określa współczynnik odbicia $R$, równy:$STEM$,
   $OPTS$[{"id": "a", "text": "$\\left(\\frac{Z_1+Z_2}{Z_1-Z_2}\\right)^2$"}, {"id": "b", "text": "$\\frac{(Z_1-Z_2)^2}{Z_1+Z_2}$"}, {"id": "c", "text": "$\\left(\\frac{Z_1-Z_2}{Z_1+Z_2}\\right)^2$"}, {"id": "d", "text": "$\\frac{Z_1-Z_2}{Z_1+Z_2}$"}]$OPTS$::jsonb,
   'c',
   $EXPL$Dla padania prostopadłego $R=\left(\frac{Z_1-Z_2}{Z_1+Z_2}\right)^2$; **kwadrat** sprawia, że wynik nie zależy od kolejności ośrodków i mieści się w przedziale 0–1. Gdy $Z_1=Z_2$, $R=0$ i fala przechodzi bez odbicia; im większy **skok impedancji**, tym silniejsze echo. Na granicy tkanka–powietrze odbija się niemal **100%** energii, dlatego konieczny jest **żel sprzęgający**, a granice tkanek miękkich odbijają ułamki procenta.$EXPL$,
   $SUB$Odbicie fal ultradźwiękowych$SUB$, 'BIOFIZLEK-83'),
(14, 'BIOF-C3',
   $STEM$Prawo Bernoulliego wyraża zasadę zachowania energii cieczy płynącej bez tarcia. Stosować je można jedynie dla cieczy:$STEM$,
   $OPTS$[{"id": "a", "text": "nielepkich, nieściśliwych i płynących w elastycznym przewodzie"}, {"id": "b", "text": "nielepkich, nieściśliwych i płynących w sztywnym przewodzie"}, {"id": "c", "text": "lepkich, ściśliwych i płynących w sztywnym przewodzie"}, {"id": "d", "text": "lepkich, ściśliwych i płynących w elastycznym przewodzie"}]$OPTS$::jsonb,
   'b',
   $EXPL$Równanie $p+\rho gh+\frac{\rho v^2}{2}=\mathrm{const}$ wyprowadza się z zasady zachowania energii dla cieczy **doskonałej**: nielepkiej (brak strat na tarcie wewnętrzne) i nieściśliwej, płynącej ustalonym strumieniem w **sztywnym** przewodzie — elastyczne ściany magazynowałyby energię w odkształceniu. Stąd wniosek stosowany w krążeniu: w przewężeniu rośnie prędkość, więc **maleje ciśnienie** statyczne (efekt Venturiego).$EXPL$,
   $SUB$Hydrodynamika cieczy doskonałej$SUB$, 'BIOFIZLEK-84'),
(15, 'BIOF-C3',
   $STEM$Zależność między strumieniem objętości cieczy a różnicą ciśnień powodującą przepływ określa prawo Hagena-Poiseuille'a. Prawo to stosuje się zakładając, że:$STEM$,
   $OPTS$[{"id": "a", "text": "ciecz jest nieściśliwa, przepływ jest laminarny a ściany są elastyczne"}, {"id": "b", "text": "ciecz jest ściśliwa, przepływ jest laminarny a ściany są sztywne"}, {"id": "c", "text": "ciecz jest ściśliwa, przepływ jest laminarny a ściany są elastyczne"}, {"id": "d", "text": "ciecz jest nieściśliwa, przepływ jest laminarny a ściany są sztywne"}]$OPTS$::jsonb,
   'd',
   $EXPL$Prawo Hagena-Poiseuille'a: $Q=\frac{\pi r^4\Delta p}{8\eta l}$. Założenia: ciecz **nieściśliwa** i newtonowska, przepływ **laminarny** i ustalony, rura o stałym przekroju i **sztywnych** ścianach, warstwa przyścienna nieruchoma. Kluczowa jest zależność od $r^4$ — dwukrotne zwężenie naczynia zmniejsza przepływ **16-krotnie**, co tłumaczy wagę zmian średnicy tętniczek. Krew jest cieczą nienewtonowską, więc w krążeniu prawo obowiązuje tylko w przybliżeniu.$EXPL$,
   $SUB$Przepływ laminarny$SUB$, 'BIOFIZLEK-85'),
(16, 'BIOF-S3',
   $STEM$Narząd Cortiego, będący właściwym receptorem słuchu, znajduje się w uchu wewnętrznym i jest odpowiedzialny za transdukcję bodźców mechanicznych w sygnały nerwowe. Za mechanizm ten odpowiedzialna jest:$STEM$,
   $OPTS$[{"id": "a", "text": "struktura komórek rzęsatych"}, {"id": "b", "text": "błona bębenkowa"}, {"id": "c", "text": "powierzchnia okienka owalnego"}, {"id": "d", "text": "struktura kanałów półkolistych"}]$OPTS$::jsonb,
   'a',
   $EXPL$Transdukcja zachodzi w **komórkach rzęsatych** narządu Cortiego: ugięcie **stereocilii** względem błony pokrywającej otwiera mechanicznie bramkowane kanały jonowe, następuje napływ K⁺ z endolimfy, depolaryzacja i uwolnienie neuroprzekaźnika do włókien nerwu **VIII**. Błona bębenkowa i okienko owalne jedynie przenoszą i wzmacniają drgania mechaniczne (ok. **17-krotny** zysk ciśnienia), a kanały półkoliste należą do narządu **równowagi**.$EXPL$,
   $SUB$Fizjologia słuchu$SUB$, 'BIOFIZLEK-86'),
(17, 'BIOF-C2',
   $STEM$Mikroskop służy do obserwacji obiektów niewidocznych dla oka (nieuzbrojonego). Obserwowany obraz w mikroskopie jest obrazem:$STEM$,
   $OPTS$[{"id": "a", "text": "pozornym, prostym, powiększonym"}, {"id": "b", "text": "rzeczywistym, odwróconym, powiększonym"}, {"id": "c", "text": "pozornym, odwróconym, powiększonym"}, {"id": "d", "text": "rzeczywistym, prostym, powiększonym"}]$OPTS$::jsonb,
   'c',
   $EXPL$Obiektyw tworzy obraz **rzeczywisty, odwrócony i powiększony**, który powstaje wewnątrz ogniskowej okularu. Okular działa jak **lupa** i daje z niego obraz **pozorny** oraz dodatkowo powiększony, wciąż odwrócony względem preparatu. Obserwator widzi więc obraz pozorny, odwrócony i powiększony — dlatego preparat przesuwa się w kierunku przeciwnym do ruchu obrazu. Powiększenie całkowite to iloczyn powiększeń obiektywu i okularu.$EXPL$,
   $SUB$Mikroskopia optyczna$SUB$, 'BIOFIZLEK-87'),
(18, 'BIOF-C4',
   $STEM$Ruch harmoniczny można opisać równaniem ($x$ – wychylenie, $t$ – czas, $A$ – amplituda drgań, $\omega$ – częstość drgań, $\varphi$ – przesunięcie fazowe):$STEM$,
   $OPTS$[{"id": "a", "text": "$x=A\\cos(\\varphi t+\\omega)$"}, {"id": "b", "text": "$x=A\\sin^2(\\omega t+\\varphi)$"}, {"id": "c", "text": "$x=A\\cos(\\omega t^2+\\varphi)$"}, {"id": "d", "text": "$x=A\\sin(\\omega t+\\varphi)$"}]$OPTS$::jsonb,
   'd',
   $EXPL$Ruch harmoniczny prosty wynika z siły sprężystej $F=-kx$ i opisuje go $x=A\sin(\omega t+\varphi)$ (równoważnie z kosinusem, przy innej fazie). $A$ to **amplituda**, $\omega=2\pi f=\sqrt{k/m}$ — **częstość kołowa**, $\varphi$ — faza początkowa. Argument funkcji musi mieć wymiar kąta, więc czas występuje w **pierwszej potędze** i mnoży $\omega$; $\sin^2$ dawałby wyłącznie wartości nieujemne, a zamiana $\omega$ z $\varphi$ jest wymiarowo błędna.$EXPL$,
   $SUB$Drgania i sprężystość$SUB$, 'BIOFIZLEK-88'),
(19, 'BIOF-S1',
   $STEM$LET, czyli liniowy współczynnik przenoszenia energii dla promieniowania jonizującego, to:$STEM$,
   $OPTS$[{"id": "a", "text": "parametr w radiobiologii zwyczajowo wyrażany w $\\frac{\\mu\\mathrm{m}}{\\mathrm{keV}}$"}, {"id": "b", "text": "parametr, który nie zależy od rodzaju promieniowania"}, {"id": "c", "text": "miara gęstości przekazywania energii do ośrodka, która decyduje o efektach chemicznych i biologicznych"}, {"id": "d", "text": "parametr tym mniejszy, im mniej przenikliwe jest promieniowanie"}]$OPTS$::jsonb,
   'c',
   $EXPL$LET to energia przekazana ośrodkowi na **jednostkę drogi**, wyrażana w $\mathrm{keV/\mu m}$ (wariant z $\frac{\mu\mathrm{m}}{\mathrm{keV}}$ ma odwrócone jednostki). Wysokie LET — cząstki $\alpha$, protony, neutrony — oznacza **gęstą jonizację** wzdłuż toru, liczne podwójne pęknięcia DNA i wysoką skuteczność biologiczną (**RBE**), przy małej przenikliwości. Niskie LET (promieniowanie X, $\gamma$, $\beta$) daje jonizację rzadką i dużą przenikliwość, więc parametr silnie zależy od rodzaju promieniowania.$EXPL$,
   $SUB$Oddziaływanie promieniowania z materią$SUB$, 'BIOFIZLEK-89'),
(20, 'BIOF-C3',
   $STEM$Prawo ciągłości strumienia, które określa zachowanie się cieczy przy przepływach przez przewężenia lub rozszerzenia naczynia, stwierdza że:$STEM$,
   $OPTS$[{"id": "a", "text": "w połączonych równolegle naczyniach strumień objętości w danym przekroju naczynia jest jednakowy na całej długości połączonych naczyń"}, {"id": "b", "text": "w połączonych szeregowo naczyniach strumień objętości w danym przekroju naczynia jest jednakowy na całej długości połączonych naczyń"}, {"id": "c", "text": "w połączonych szeregowo naczyniach strumień objętości w danym przekroju naczynia jest zmienny na całej długości połączonych naczyń"}, {"id": "d", "text": "w połączonych równolegle naczyniach strumień objętości w danym przekroju naczynia jest zmienny na całej długości połączonych naczyń"}]$OPTS$::jsonb,
   'b',
   $EXPL$Prawo ciągłości wynika z zachowania masy cieczy nieściśliwej: $Q=Sv=\mathrm{const}$, więc w naczyniach połączonych **szeregowo** strumień objętości jest jednakowy w każdym przekroju, mimo zmian prędkości. W przewężeniu maleje pole $S$, a rośnie prędkość $v$. W krążeniu sumaryczny przekrój **kapilar** jest największy, dlatego prędkość krwi jest tam najmniejsza (rzędu **0,5 mm/s**), co umożliwia wymianę gazów i metabolitów.$EXPL$,
   $SUB$Hydrodynamika układu krążenia$SUB$, 'BIOFIZLEK-90'),
(21, 'BIOF-C4',
   $STEM$Zysk mechaniczny (inaczej przekładnia mechaniczna) dźwigni, jest to:$STEM$,
   $OPTS$[{"id": "a", "text": "iloraz długości ramienia działania (odległość od punktu przyłożenia siły do osi obrotu) do długości ramienia obciążenia (odległość od punktu przyłożenia obciążenia do osi obrotu)"}, {"id": "b", "text": "iloraz długości ramienia obciążenia do długości ramienia działania siły"}, {"id": "c", "text": "suma długości ramienia działania siły i ramienia obciążenia"}, {"id": "d", "text": "iloczyn długości ramienia działania siły i wartości siły przyłożonej do obciążenia"}]$OPTS$::jsonb,
   'a',
   $EXPL$Z warunku równowagi momentów sił $F\cdot r_s=F_o\cdot r_o$ wynika **zysk mechaniczny** $ZM=\frac{r_s}{r_o}=\frac{F_o}{F}$. Gdy $ZM>1$, do zrównoważenia obciążenia wystarcza siła od niego mniejsza. W układzie ruchu człowieka przeważają dźwignie o **ZM<1** (np. staw łokciowy — przyczep bicepsa tuż przy osi obrotu): tracimy na sile, ale zyskujemy na **prędkości i zakresie** ruchu końca kończyny, co jest korzystne biomechanicznie.$EXPL$,
   $SUB$Dźwignie kostne$SUB$, 'BIOFIZLEK-91'),
(22, 'BIOF-C3',
   $STEM$Ciecz nienewtonowska charakteryzuje się:$STEM$,
   $OPTS$[{"id": "a", "text": "nieliniową zależnością naprężenia ścinającego od szybkości ścinania przy zmiennej lepkości"}, {"id": "b", "text": "nieliniową zależnością naprężenia ścinającego od szybkości ścinania przy stałej lepkości"}, {"id": "c", "text": "liniową zależnością naprężenia ścinającego od szybkości ścinania przy zmiennej lepkości"}, {"id": "d", "text": "liniową zależnością naprężenia ścinającego od szybkości ścinania przy stałej lepkości"}]$OPTS$::jsonb,
   'a',
   $EXPL$Ciecz newtonowska spełnia $\tau=\eta\frac{dv}{dx}$: naprężenie ścinające rośnie **liniowo** z szybkością ścinania przy **stałej** lepkości (woda, osocze). W cieczy **nienewtonowskiej** zależność jest nieliniowa, a lepkość pozorna zmienia się z szybkością ścinania. **Krew** należy do cieczy rozrzedzanych ścinaniem: przy małych prędkościach erytrocyty tworzą **rulony** i lepkość rośnie, przy dużych — odkształcają się i lepkość maleje.$EXPL$,
   $SUB$Lepkość cieczy$SUB$, 'BIOFIZLEK-92'),
(23, 'BIOF-W4',
   $STEM$Skala Hounsfielda (jednostki skali Hounsfielda – HU) to ilościowa skala radiologiczna stosowana w tomografii komputerowej (CT) do określania gęstości radiologicznej tkanek i materiałów. Skala opiera się na pomiarze współczynnika osłabienia promieniowania rentgenowskiego przez różne struktury w ciele, w której -1000 jednostek HU określa gęstość radiologiczną:$STEM$,
   $OPTS$[{"id": "a", "text": "wody"}, {"id": "b", "text": "powietrza (próżni)"}, {"id": "c", "text": "kości"}, {"id": "d", "text": "tkanki tłuszczowej"}]$OPTS$::jsonb,
   'b',
   $EXPL$Skalę definiuje wzór $HU=1000\cdot\frac{\mu_t-\mu_w}{\mu_w}$, znormalizowany do dwóch punktów: **woda = 0 HU** i **powietrze = -1000 HU** (osłabianie praktycznie zerowe, jak w próżni). Tkanka tłuszczowa ma ok. **-100 HU**, tkanki miękkie 20–70 HU, krew krzepnąca ok. 80 HU, a kość zbita **ponad +1000 HU**. Dobór odpowiednio wąskiego **okna** prezentacji pozwala różnicować tkanki miękkie mimo niewielkich różnic w osłabianiu wiązki.$EXPL$,
   $SUB$Skala Hounsfielda$SUB$, 'BIOFIZLEK-93'),
(24, 'BIOF-INNE',
   $STEM$Wskaż, które z poniższych stwierdzeń najlepiej opisuje pierwszą zasadę termodynamiki:$STEM$,
   $OPTS$[{"id": "a", "text": "zmiana energii wewnętrznej układu jest równa sumie ciepła dostarczonego do układu i pracy wykonanej nad układem"}, {"id": "b", "text": "zmiana energii wewnętrznej układu jest równa różnicy między ciepłem oddanym przez układ a pracą wykonaną przez układ"}, {"id": "c", "text": "zmiana energii wewnętrznej układu zależy tylko od ilości ciepła dostarczonego do układu"}, {"id": "d", "text": "energia wewnętrzna układu nie może się zmieniać, niezależnie od procesów zachodzących w otoczeniu"}]$OPTS$::jsonb,
   'a',
   $EXPL$I zasada termodynamiki to zasada **zachowania energii**: $\Delta U=Q+W$, gdzie $Q$ to ciepło dostarczone do układu, a $W$ — praca wykonana **nad** układem (w konwencji z pracą wykonaną przez układ zapisujemy $\Delta U=Q-W$). Energia wewnętrzna jest **funkcją stanu** — jej zmiana nie zależy od drogi przemiany, podczas gdy $Q$ i $W$ są funkcjami procesu. Organizm to układ otwarty: pobiera energię chemiczną, a oddaje ciepło i pracę mechaniczną.$EXPL$,
   $SUB$Termodynamika$SUB$, 'BIOFIZLEK-94'),
(25, 'BIOF-INNE',
   $STEM$Temperatura człowieka jest ważnym parametrem pomagającym określić stan pacjenta. Temperatura skóry jest wynikiem dynamicznej równowagi pomiędzy ciepłem uwalnianym w przemianach metabolicznych i dostarczanym do powłoki skórnej a ciepłem oddawanym do otoczenia. Człowiek zanurzony w lodowatej wodzie traci energię cieplną głównie na skutek:$STEM$,
   $OPTS$[{"id": "a", "text": "promieniowania"}, {"id": "b", "text": "przewodzenia i konwekcji"}, {"id": "c", "text": "parowania"}, {"id": "d", "text": "innego mechanizmu niż wymienione powyżej"}]$OPTS$::jsonb,
   'b',
   $EXPL$W wodzie dominuje **przewodzenie** ciepła do warstwy przylegającej do skóry oraz **konwekcja** unosząca ogrzaną wodę. Przewodnictwo cieplne wody jest ok. **25 razy** większe niż powietrza, a jej pojemność cieplna ogromna, więc wychłodzenie następuje wielokrotnie szybciej niż w powietrzu o tej samej temperaturze. **Parowanie** pod wodą nie zachodzi, a **promieniowanie** (prawo Stefana-Boltzmanna), istotne w powietrzu w spoczynku, ma tu znaczenie marginalne.$EXPL$,
   $SUB$Termoregulacja$SUB$, 'BIOFIZLEK-95'),
(26, 'BIOF-INNE',
   $STEM$Pęd fotonu określamy wzorem ($h$ – stała Plancka, $\nu$ – częstotliwość promieniowania, $c$ – prędkość światła, $\lambda$ – długość fali promieniowania):$STEM$,
   $OPTS$[{"id": "a", "text": "$\\frac{h\\nu}{c}=\\frac{h}{\\lambda}$"}, {"id": "b", "text": "$\\frac{h}{c}=\\frac{\\lambda}{\\nu}$"}, {"id": "c", "text": "$\\frac{hc}{\\nu}=\\frac{h}{\\lambda}$"}, {"id": "d", "text": "$\\frac{h\\nu}{c}=\\lambda$"}]$OPTS$::jsonb,
   'a',
   $EXPL$Foton nie ma masy spoczynkowej, ale niesie pęd $p=\frac{E}{c}=\frac{h\nu}{c}=\frac{h}{\lambda}$, bo $E=h\nu$ oraz $c=\lambda\nu$. Zapis ten jest zgodny z relacją **de Broglie'a** $\lambda=h/p$ i stanowi podstawę opisu zjawiska **Comptona**, w którym foton rozprasza się na swobodnym elektronie, tracąc część energii i pędu, a także ciśnienia promieniowania. Pozostałe wyrażenia są niepoprawne **wymiarowo** — nie dają jednostki $\mathrm{kg\cdot m/s}$.$EXPL$,
   $SUB$Podstawy fizyki kwantowej$SUB$, 'BIOFIZLEK-96'),
(27, 'BIOF-S3',
   $STEM$Dźwięk można opisać za pomocą cech fizycznych, do których nie zaliczamy:$STEM$,
   $OPTS$[{"id": "a", "text": "częstotliwości dźwięku"}, {"id": "b", "text": "natężenia dźwięku"}, {"id": "c", "text": "struktury widmowej"}, {"id": "d", "text": "wysokości dźwięku"}]$OPTS$::jsonb,
   'd',
   $EXPL$Cechy **fizyczne** dźwięku to mierzalne parametry fali: **częstotliwość** (Hz), **natężenie** (W/m²) i **struktura widmowa**, czyli skład harmoniczny. **Wysokość** jest natomiast cechą **subiektywną** (psychoakustyczną) — wrażeniem odpowiadającym częstotliwości. Analogiczne pary tworzą głośność (fon) wobec natężenia oraz barwa wobec widma. Zależność wrażenia od bodźca ma charakter **logarytmiczny** i opisuje ją prawo Webera-Fechnera.$EXPL$,
   $SUB$Cechy dźwięku$SUB$, 'BIOFIZLEK-97'),
(28, 'BIOF-S1',
   $STEM$W liczniku Geigera-Müllera wykorzystuje się zjawisko zachodzące w gazie wypełniającym kondensator cylindryczny i nazywane zjawiskiem:$STEM$,
   $OPTS$[{"id": "a", "text": "jonizacji lawinowej"}, {"id": "b", "text": "termoemisji elektronów"}, {"id": "c", "text": "Comptona"}, {"id": "d", "text": "wyładowania ciągłego pomiędzy elektrodami kondensatora cylindrycznego"}]$OPTS$::jsonb,
   'a',
   $EXPL$Napięcie między elektrodami jest tak wysokie, że elektron uwolniony przez promieniowanie rozpędza się i jonizuje kolejne atomy gazu — powstaje **jonizacja lawinowa** (lawina Townsenda) dająca impuls prądowy. Amplituda impulsu **nie zależy od energii** cząstki, więc licznik zlicza akty jonizacji, ale nie mierzy energii (robi to licznik proporcjonalny lub scyntylacyjny). Domieszka **gazu gaszącego** przerywa lawinę, zapobiegając wyładowaniu ciągłemu.$EXPL$,
   $SUB$Detekcja promieniowania$SUB$, 'BIOFIZLEK-98'),
(29, 'BIOF-C2',
   $STEM$Obraz, który powstaje na siatkówce oka ludzkiego, jest:$STEM$,
   $OPTS$[{"id": "a", "text": "rzeczywisty, pomniejszony, prosty"}, {"id": "b", "text": "rzeczywisty, pomniejszony, odwrócony"}, {"id": "c", "text": "urojony, pomniejszony, prosty"}, {"id": "d", "text": "rzeczywisty, powiększony, odwrócony"}]$OPTS$::jsonb,
   'b',
   $EXPL$Układ optyczny oka działa jak soczewka **skupiająca** o zdolności ok. **60 D**, a obserwowany przedmiot leży dalej niż podwójna ogniskowa, więc na siatkówce powstaje obraz **rzeczywisty, pomniejszony i odwrócony**. Odwrócenie jest korygowane dopiero w korze wzrokowej. Obraz musi być rzeczywisty, bo powstaje na „ekranie” pobudzającym fotoreceptory; powiększenie wymagałoby przedmiotu bliższego niż $2f$, co w oku nie zachodzi.$EXPL$,
   $SUB$Optyka oka$SUB$, 'BIOFIZLEK-99'),
(30, 'BIOF-S1',
   $STEM$W którym odcinku drogi naładowanych cząstek w materii obserwuje się maksymalny stopień jonizacji (widoczny na krzywej Bragga jako maksimum)?$STEM$,
   $OPTS$[{"id": "a", "text": "na początku drogi, gdy cząstka ma najwyższą prędkość"}, {"id": "b", "text": "w połowie drogi cząstki przez ośrodek"}, {"id": "c", "text": "w końcowym odcinku drogi, tuż przed zatrzymaniem cząstki"}, {"id": "d", "text": "po całkowitym zatrzymaniu cząstki"}]$OPTS$::jsonb,
   'c',
   $EXPL$Zgodnie ze wzorem Bethego straty energii na jednostkę drogi rosną, gdy prędkość cząstki maleje ($\frac{dE}{dx}\sim\frac{1}{v^2}$), bo dłużej oddziałuje ona z elektronami ośrodka. Maksimum jonizacji — **pik Bragga** — przypada więc tuż **przed zatrzymaniem** cząstki. Zjawisko to wykorzystuje **terapia protonowa i jonowa**: dobierając energię wiązki, deponuje się dawkę w guzie, oszczędzając tkanki leżące za nim. Po zatrzymaniu cząstka nie jonizuje.$EXPL$,
   $SUB$Oddziaływanie cząstek naładowanych z materią$SUB$, 'BIOFIZLEK-100'),
(31, 'BIOF-S2',
   $STEM$Ciało doskonale czarne emituje energię w postaci fal elektromagnetycznych, dla których zgodnie z prawem Wiena długość fali, przy której obserwowane jest maksimum emisji, jest:$STEM$,
   $OPTS$[{"id": "a", "text": "wprost proporcjonalna do bezwzględnej temperatury"}, {"id": "b", "text": "wprost proporcjonalna do czwartej potęgi bezwzględnej temperatury"}, {"id": "c", "text": "odwrotnie proporcjonalna do bezwzględnej temperatury"}, {"id": "d", "text": "niezależna od bezwzględnej temperatury"}]$OPTS$::jsonb,
   'c',
   $EXPL$Prawo przesunięć Wiena: $\lambda_{max}=\frac{b}{T}$, gdzie $b\approx2{,}9\cdot10^{-3}\ \mathrm{m\cdot K}$ — maksimum emisji przesuwa się ku **krótszym** falom, gdy temperatura rośnie. Dla skóry o temperaturze ok. **300 K** wypada ono przy ok. **10 µm**, czyli w podczerwieni, co jest podstawą **termografii**. Do **czwartej potęgi** temperatury proporcjonalna jest natomiast całkowita moc emisji, zgodnie z prawem Stefana-Boltzmanna $P=\sigma ST^4$.$EXPL$,
   $SUB$Promieniowanie cieplne$SUB$, 'BIOFIZLEK-101'),
(32, 'BIOF-C2',
   $STEM$Kąt Brewstera jest kątem, przy którym światło odbite od powierzchni dielektryka jest całkowicie spolaryzowane. Spełnia on zależność $n=\operatorname{tg}(\varphi)$, gdzie $n$ jest współczynnikiem załamania dielektryka, a $\varphi$ jest kątem:$STEM$,
   $OPTS$[{"id": "a", "text": "pomiędzy kierunkami drgań pola elektrycznego i rozchodzenia się światła"}, {"id": "b", "text": "między promieniem odbitym a załamanym"}, {"id": "c", "text": "załamania światła"}, {"id": "d", "text": "padania światła na powierzchnię dielektryka"}]$OPTS$::jsonb,
   'd',
   $EXPL$Kąt Brewstera to szczególny **kąt padania**, przy którym promień odbity jest całkowicie spolaryzowany liniowo, z drganiami **prostopadłymi** do płaszczyzny padania. Spełnia $\operatorname{tg}\varphi_B=n$, a promienie odbity i załamany tworzą wtedy kąt **90°**. Dla granicy powietrze–szkło ($n=1{,}5$) wynosi ok. **56°**. Zjawisko wykorzystują okulary polaryzacyjne tłumiące odblaski od wody i szyb oraz okienka Brewstera w rezonatorach laserowych.$EXPL$,
   $SUB$Polaryzacja światła$SUB$, 'BIOFIZLEK-102'),
(33, 'BIOF-C3',
   $STEM$Model reologiczny, w którym element lepki (tłoczek z cieczą) połączony jest szeregowo z elementem sprężystym (sprężyna), nazwiemy modelem:$STEM$,
   $OPTS$[{"id": "a", "text": "Kelvina-Voighta"}, {"id": "b", "text": "Maxwella"}, {"id": "c", "text": "Hooke'a"}, {"id": "d", "text": "mięśni poprzecznie prążkowanych"}]$OPTS$::jsonb,
   'b',
   $EXPL$W modelu **Maxwella** sprężyna (prawo Hooke'a) i tłumik są połączone **szeregowo**: naprężenia w obu elementach są równe, a odkształcenia się sumują. Model odtwarza **relaksację naprężeń** przy stałym odkształceniu oraz nieodwracalne płynięcie. Połączenie **równoległe** tych samych elementów to model **Kelvina-Voighta**, opisujący **pełzanie** i opóźnioną sprężystość. Tkanki takie jak ścięgna czy kość wymagają modeli złożonych z obu członów.$EXPL$,
   $SUB$Modele reologiczne$SUB$, 'BIOFIZLEK-103'),
(34, 'BIOF-S3',
   $STEM$W której technice ultrasonograficznej jasność punktów na ekranie odpowiada sile odbitego sygnału ultradźwiękowego, natomiast położenie punktów przedstawiane jest jako funkcja czasu wzdłuż jednej wybranej linii skanowania, co umożliwia ocenę ruchu struktur w czasie?$STEM$,
   $OPTS$[{"id": "a", "text": "prezentacji D"}, {"id": "b", "text": "prezentacji M"}, {"id": "c", "text": "prezentacji A"}, {"id": "d", "text": "prezentacji B"}]$OPTS$::jsonb,
   'b',
   $EXPL$W prezentacji **M** (motion) echa z **jednej** linii skanowania są kodowane jasnością i rozwijane w funkcji **czasu**, co daje zapis ruchu struktur o bardzo dobrej rozdzielczości czasowej. Jest podstawą oceny ruchomości zastawek i kurczliwości ścian serca. **Prezentacja A** to wykres amplitudy echa w funkcji głębokości, **prezentacja B** — dwuwymiarowy przekrój w skali szarości, a „prezentacja D” w klasycznym podziale nie występuje.$EXPL$,
   $SUB$Techniki ultrasonograficzne$SUB$, 'BIOFIZLEK-104'),
(35, 'BIOF-S3',
   $STEM$Zjawisko Dopplera wykorzystywane w ultrasonograficznych metodach diagnostycznych pozwala obliczyć prędkość przepływu krwi przez naczynie krwionośne. Metoda ta polega na pomiarze:$STEM$,
   $OPTS$[{"id": "a", "text": "natężenia fali odbitej lub rozproszonej"}, {"id": "b", "text": "czasu opóźnienia powrotu fali odbitej lub rozproszonej"}, {"id": "c", "text": "zmiany częstotliwości fali odbitej lub rozproszonej względem fali padającej"}, {"id": "d", "text": "zmiany prędkości rozchodzenia się fali odbitej lub rozproszonej względem fali padającej"}]$OPTS$::jsonb,
   'c',
   $EXPL$Zjawisko Dopplera polega na **zmianie częstotliwości** fali odbitej od poruszającego się reflektora (erytrocytów) względem fali padającej: $\Delta f=\frac{2f_0v\cos\alpha}{c}$. Z przesunięcia dopplerowskiego wyznacza się wartość i kierunek prędkości przepływu. Kluczowy jest **kąt** $\alpha$ między wiązką a osią naczynia — przy $90°$ sygnał zanika. Prędkość fali w tkankach jest stała (**ok. 1540 m/s**) i nie zmienia się wskutek ruchu krwi.$EXPL$,
   $SUB$Efekt Dopplera w diagnostyce$SUB$, 'BIOFIZLEK-105'),
(36, 'BIOF-C2',
   $STEM$Znając masę molową ($M$), gęstość ($\rho$) oraz współczynnik załamania światła ($n$) możemy obliczyć refrakcję molową ($R$), którą określa wzór:$STEM$,
   $OPTS$[{"id": "a", "text": "$\\frac{n^2+1}{n^2-2}\\cdot\\frac{M}{\\rho}$"}, {"id": "b", "text": "$\\frac{n^2-1}{n^2+2}\\cdot\\frac{\\rho}{M}$"}, {"id": "c", "text": "$\\frac{n^2-2}{n^2+1}\\cdot\\frac{M}{\\rho}$"}, {"id": "d", "text": "$\\frac{n^2-1}{n^2+2}\\cdot\\frac{M}{\\rho}$"}]$OPTS$::jsonb,
   'd',
   $EXPL$Wzór **Lorentz-Lorenza**: $R=\frac{n^2-1}{n^2+2}\cdot\frac{M}{\rho}$, gdzie iloraz $M/\rho$ to **objętość molowa**. Refrakcja molowa jest miarą **polaryzowalności** cząsteczki, praktycznie niezależną od temperatury i ciśnienia, a przy tym **addytywną** względem atomów i wiązań — służy więc do identyfikacji związków i oceny czystości. Refraktometrem Abbego oznacza się też stężenia roztworów, np. białka w surowicy czy w moczu.$EXPL$,
   $SUB$Refraktometria$SUB$, 'BIOFIZLEK-106'),
(37, 'BIOF-C3',
   $STEM$Prędkość, przy której dochodzi do przejścia z przepływu laminarnego do burzliwego, nazywana jest prędkością krytyczną $v_k$ równą (gdzie: $\eta$ – lepkość cieczy; $d$ – średnica naczynia; $\rho$ – gęstość cieczy; $Re$ – krytyczna liczba Reynoldsa):$STEM$,
   $OPTS$[{"id": "a", "text": "$\\frac{Re\\,\\rho}{\\eta d}$"}, {"id": "b", "text": "$\\frac{Re\\,d}{\\eta\\rho}$"}, {"id": "c", "text": "$\\frac{Re\\,\\eta}{\\rho d^2}$"}, {"id": "d", "text": "$\\frac{Re\\,\\eta}{\\rho d}$"}]$OPTS$::jsonb,
   'd',
   $EXPL$Liczba Reynoldsa to $Re=\frac{\rho v d}{\eta}$, więc po przekształceniu $v_k=\frac{Re\,\eta}{\rho d}$. Prędkość krytyczna **rośnie** z lepkością, a **maleje** z gęstością i średnicą naczynia; dla rur przyjmuje się $Re\approx2300$. Dlatego turbulencje pojawiają się najłatwiej w naczyniach o dużej średnicy (aorta) oraz przy **niedokrwistości**, gdy lepkość krwi spada — słychać je wtedy jako **szmer** naczyniowy lub sercowy.$EXPL$,
   $SUB$Przepływ burzliwy$SUB$, 'BIOFIZLEK-107'),
(38, 'BIOF-INNE',
   $STEM$W którym stwierdzeniu zawarty jest prawdziwy sens prawa Ohma?$STEM$,
   $OPTS$[{"id": "a", "text": "napięcie prądu między końcami przewodnika jest wprost proporcjonalne do jego natężenia"}, {"id": "b", "text": "opór przewodnika jest wprost proporcjonalny do napięcia na jego końcach, a odwrotnie proporcjonalny do natężenia płynącego w nim prądu"}, {"id": "c", "text": "natężenie prądu w przewodniku jest wprost proporcjonalne do napięcia na jego końcach, a odwrotnie proporcjonalne do jego oporu elektrycznego"}, {"id": "d", "text": "opór elektryczny przewodnika to stosunek napięcia na jego końcach do natężenia płynącego prądu"}]$OPTS$::jsonb,
   'c',
   $EXPL$Prawo Ohma: $I=\frac{U}{R}$ — natężenie prądu jest **wprost proporcjonalne** do napięcia i **odwrotnie proporcjonalne** do oporu, a istotą prawa jest **stałość** ilorazu $U/I$ dla danego przewodnika. Wariant o oporze jako stosunku napięcia do natężenia podaje jedynie **definicję** oporu, prawdziwą także dla elementów nieliniowych, więc nie oddaje treści prawa. Tkanki nie są przewodnikami ohmowymi — ich **impedancja** zależy od częstotliwości prądu i pojemności błon.$EXPL$,
   $SUB$Prąd elektryczny$SUB$, 'BIOFIZLEK-108'),
(39, 'BIOF-C3',
   $STEM$Jeżeli naczyniem jest kapilara o długości $l$ i promieniu przekroju poprzecznego $r$, to opór naczyniowy ($R$) kapilary można zapisać w postaci (gdzie $\eta$ – współczynnik lepkości cieczy przepływającej):$STEM$,
   $OPTS$[{"id": "a", "text": "$R=\\frac{\\eta l}{8\\pi r^4}$"}, {"id": "b", "text": "$R=\\frac{8\\eta l}{\\pi r^4}$"}, {"id": "c", "text": "$R=\\frac{8\\eta}{\\pi r^4}$"}, {"id": "d", "text": "$R=\\frac{8\\eta l}{\\pi r}$"}]$OPTS$::jsonb,
   'b',
   $EXPL$Opór definiujemy jako $R=\frac{\Delta p}{Q}$; po podstawieniu prawa Hagena-Poiseuille'a $Q=\frac{\pi r^4\Delta p}{8\eta l}$ otrzymujemy $R=\frac{8\eta l}{\pi r^4}$. Opór rośnie z długością naczynia i lepkością krwi, ale przede wszystkim z **czwartą potęgą** odwrotności promienia — zwężenie naczynia o połowę zwiększa go **16-krotnie**. Dlatego głównym miejscem regulacji oporu obwodowego są **tętniczki**, aktywnie zmieniające średnicę.$EXPL$,
   $SUB$Opór naczyniowy$SUB$, 'BIOFIZLEK-109'),
(40, 'BIOF-S3',
   $STEM$Fale ultradźwiękowe w USG generowane i odbierane są z wykorzystaniem zjawiska piezoelektrycznego. Główną cechą prostego zjawiska piezoelektrycznego jest to, że:$STEM$,
   $OPTS$[{"id": "a", "text": "odkształcenie kryształu wymusza pojawienie się ładunków tego samego znaku na przeciwległych ściankach kryształu"}, {"id": "b", "text": "ogrzewanie kryształu powoduje pojawienie się ładunków przeciwnego znaku na przeciwległych ściankach kryształu"}, {"id": "c", "text": "odkształcenie kryształu wymusza pojawienie się ładunków przeciwnego znaku na przeciwległych ściankach kryształu"}, {"id": "d", "text": "po przyłożeniu do kryształu pola elektrycznego następuje odkształcenie kryształu"}]$OPTS$::jsonb,
   'c',
   $EXPL$Zjawisko piezoelektryczne **proste**: odkształcenie kryształu (kwarc, ceramika PZT) przesuwa ładunki w sieci, więc na przeciwległych ścianach pojawiają się ładunki **przeciwnych znaków**, czyli napięcie — na tym opiera się **odbiór** echa. Zjawisko **odwrotne** — odkształcenie po przyłożeniu pola elektrycznego — służy do **generowania** ultradźwięków, a głowica wykorzystuje oba efekty naprzemiennie. Powstawanie ładunków przy ogrzewaniu to odrębne zjawisko **piroelektryczne**.$EXPL$,
   $SUB$Wytwarzanie ultradźwięków$SUB$, 'BIOFIZLEK-110'),
(41, 'BIOF-S2',
   $STEM$Fale świetlne (VIS) i podczerwone (IR) rozchodzące się w różnych ośrodkach zaliczymy do fal:$STEM$,
   $OPTS$[{"id": "a", "text": "sprężystych i podłużnych"}, {"id": "b", "text": "sprężystych i poprzecznych"}, {"id": "c", "text": "elektromagnetycznych i podłużnych"}, {"id": "d", "text": "elektromagnetycznych i poprzecznych"}]$OPTS$::jsonb,
   'd',
   $EXPL$Światło widzialne i podczerwień to fale **elektromagnetyczne**: rozchodzące się zaburzenia pól $\vec{E}$ i $\vec{B}$, wzajemnie prostopadłych i prostopadłych do kierunku rozchodzenia się — a więc fale **poprzeczne**. Nie wymagają ośrodka i biegną w próżni z prędkością $c$. Poprzeczność umożliwia **polaryzację**, niemożliwą dla fal podłużnych. Falami sprężystymi podłużnymi są natomiast dźwięk i ultradźwięki w tkankach miękkich.$EXPL$,
   $SUB$Natura fal elektromagnetycznych$SUB$, 'BIOFIZLEK-111'),
(42, 'BIOF-W5',
   $STEM$Parametrem charakteryzującym reakcję próbki na zewnętrzne pole magnetyczne jest magnetyzacja próbki. Zewnętrzne pole magnetyczne powoduje, że dla próbki umieszczonej w tym polu wektor magnetyzacji:$STEM$,
   $OPTS$[{"id": "a", "text": "jest proporcjonalny do indukcji pola magnetycznego oraz liczby jąder w próbce"}, {"id": "b", "text": "maleje wraz ze zwiększeniem indukcji pola magnetycznego"}, {"id": "c", "text": "jest proporcjonalny do indukcji pola magnetycznego i nie zależy od liczby jąder w próbce"}, {"id": "d", "text": "jest odwrotnie proporcjonalny do liczby jąder w próbce oraz proporcjonalny do indukcji pola magnetycznego"}]$OPTS$::jsonb,
   'a',
   $EXPL$W polu $B_0$ obsadzenia rozszczepionych poziomów energetycznych różnią się zgodnie z rozkładem **Boltzmanna**, a nadmiar spinów ustawionych zgodnie z polem rośnie wraz z indukcją. Magnetyzacja jest więc **wprost proporcjonalna** do $B_0$ oraz do **liczby jąder** w próbce (prawo Curie: $M\sim\frac{B_0}{T}$). Dlatego skanery o wyższym polu dają lepszy **stosunek sygnału do szumu**, a sygnał pochodzi głównie od licznych protonów wody.$EXPL$,
   $SUB$Magnetyzacja próbki$SUB$, 'BIOFIZLEK-112'),
(43, 'BIOF-S2',
   $STEM$W medycynie szeroko wykorzystywane jest promieniowanie rentgenowskie powstające w lampie rentgenowskiej. Obwód niskiego napięcia w lampie rentgenowskiej ma na celu:$STEM$,
   $OPTS$[{"id": "a", "text": "rozpędzenie elektronów do dużej prędkości w kierunku od anody do katody"}, {"id": "b", "text": "zwiększenie emisji elektronów z powierzchni anody"}, {"id": "c", "text": "rozpędzenie elektronów do dużej prędkości w kierunku od katody do anody"}, {"id": "d", "text": "zwiększenie emisji elektronów z powierzchni katody"}]$OPTS$::jsonb,
   'd',
   $EXPL$Obwód niskiego napięcia **żarzy katodę** (włókno wolframowe), wywołując **termoemisję** elektronów. Jego prąd decyduje o liczbie emitowanych elektronów, czyli o natężeniu wiązki (**mAs**) i dawce. Za rozpędzenie elektronów od **katody do anody** odpowiada obwód **wysokiego napięcia** (dziesiątki kV), który wyznacza maksymalną energię fotonów, czyli twardość promieniowania. Na anodzie powstaje promieniowanie hamowania i charakterystyczne.$EXPL$,
   $SUB$Lampa rentgenowska$SUB$, 'BIOFIZLEK-113'),
(44, 'BIOF-W5',
   $STEM$Rozszczepienie energii jąder w zewnętrznym polu magnetycznym $B_0$ jest zjawiskiem, w którym różnica między poziomami energii jąder:$STEM$,
   $OPTS$[{"id": "a", "text": "jest proporcjonalna do $B_0$ i nosi nazwę efektu Tyndalla"}, {"id": "b", "text": "jest proporcjonalna do $B_0$ i nosi nazwę zjawiska Zeemana"}, {"id": "c", "text": "jest odwrotnie proporcjonalna do $B_0$ i nosi nazwę efektu Tyndalla"}, {"id": "d", "text": "nie zależy od $B_0$ i nosi nazwę zjawiska Zeemana"}]$OPTS$::jsonb,
   'b',
   $EXPL$W polu $B_0$ poziomy energetyczne jąder o spinie $I\neq0$ rozszczepiają się — to jądrowe zjawisko **Zeemana**. Różnica energii $\Delta E=\gamma\hbar B_0=h\nu_L$ jest **wprost proporcjonalna** do indukcji pola, a odpowiadająca jej **częstotliwość Larmora** wynosi dla protonów ok. **42,58 MHz/T**. Dlatego impuls wzbudzający leży w zakresie **radiowym**. Efekt **Tyndalla** to rozpraszanie światła w koloidach i nie ma związku z NMR.$EXPL$,
   $SUB$Rozszczepienie poziomów energetycznych$SUB$, 'BIOFIZLEK-114'),
(45, 'BIOF-W1',
   $STEM$Przyrządy pomiarowe przy dłuższym okresie stosowania mogą być przyczyną pojawienia się błędów, trudnych do wychwycenia. Błędy te, wynikające z braku kalibracji przyrządu, nazwiemy błędami:$STEM$,
   $OPTS$[{"id": "a", "text": "grubymi"}, {"id": "b", "text": "bezwzględnymi"}, {"id": "c", "text": "systematycznymi"}, {"id": "d", "text": "przypadkowymi"}]$OPTS$::jsonb,
   'c',
   $EXPL$Brak kalibracji powoduje **błąd systematyczny**: obarcza on wszystkie pomiary odchyleniem o tym samym znaku i zbliżonej wartości, więc nie ujawnia się przy powtarzaniu serii ani nie znika przy uśrednianiu — obniża **dokładność** przy zachowanej precyzji. Usuwa się go przez wzorcowanie lub wprowadzenie poprawki. Błędy **przypadkowe** mają rozkład losowy i maleją z liczbą pomiarów, a **grube** to pomyłki obserwatora, których wyniki się odrzuca.$EXPL$,
   $SUB$Rodzaje błędów pomiarowych$SUB$, 'BIOFIZLEK-115'),
(46, 'BIOF-S3',
   $STEM$Do obrazowania rozkładu tkanek miękkich oraz do badania szybkości przepływu krwi w naczyniach krwionośnych wykorzystywane są metody ultrasonograficzne. Prędkość fali ultradźwiękowej w tkankach miękkich jest:$STEM$,
   $OPTS$[{"id": "a", "text": "znacznie mniejsza niż w kościach"}, {"id": "b", "text": "znacznie mniejsza niż w powietrzu"}, {"id": "c", "text": "dużo większa niż w kościach"}, {"id": "d", "text": "taka sama jak w powietrzu"}]$OPTS$::jsonb,
   'a',
   $EXPL$Prędkość fali rośnie ze sprężystością ośrodka: w tkankach miękkich wynosi średnio **1540 m/s**, w kości zbitej ok. **3500 m/s**, a w powietrzu tylko **330 m/s**. Jest więc znacznie mniejsza niż w kościach i kilkakrotnie większa niż w powietrzu. Aparat USG przelicza czas powrotu echa na głębokość przy założeniu stałej wartości 1540 m/s, dlatego kość i gaz zniekształcają obraz, dając **artefakty** i cień akustyczny.$EXPL$,
   $SUB$Prędkość fali ultradźwiękowej$SUB$, 'BIOFIZLEK-116'),
(47, 'BIOF-W4',
   $STEM$O rozdzielczości w tomografii komputerowej decydują jednakowe, niewielkie elementy objętościowe, na które dzielona jest objętość badanej tkanki. Struktury te nazywamy:$STEM$,
   $OPTS$[{"id": "a", "text": "pikselami"}, {"id": "b", "text": "wokselami"}, {"id": "c", "text": "gradientami"}, {"id": "d", "text": "projekcjami"}]$OPTS$::jsonb,
   'b',
   $EXPL$Badana objętość jest dzielona na elementarne bryły — **woksele** (volume elements), a współczynnik osłabiania w każdym z nich odtwarza się przez **rekonstrukcję** z wielu projekcji. Woksel odwzorowany na monitorze jako element obrazu dwuwymiarowego to **piksel**. Rozmiar woksela wraz z grubością warstwy decyduje o rozdzielczości przestrzennej i o artefakcie **częściowej objętości**. Projekcje to zbiory pomiarów, a gradienty pola należą do techniki MRI.$EXPL$,
   $SUB$Rozdzielczość obrazu CT$SUB$, 'BIOFIZLEK-117'),
(48, 'BIOF-W5',
   $STEM$Wartość wektora magnetyzacji próbki w metodzie obrazowania NMR jest definiowana jako:$STEM$,
   $OPTS$[{"id": "a", "text": "wektorowy iloczyn momentów magnetycznych jąder w próbce pomnożony przez objętość próbki"}, {"id": "b", "text": "wektorowy iloczyn momentów magnetycznych jąder w próbce podzielony przez objętość próbki"}, {"id": "c", "text": "wektorowa suma momentów magnetycznych jąder w próbce podzielona przez objętość próbki"}, {"id": "d", "text": "wektorowa suma momentów magnetycznych jąder w próbce pomnożona przez objętość próbki"}]$OPTS$::jsonb,
   'c',
   $EXPL$Magnetyzacja to **suma wektorowa** momentów magnetycznych jąder zawartych w próbce **podzielona przez jej objętość**, czyli gęstość momentu magnetycznego wyrażana w $\mathrm{A/m}$. Bez pola zewnętrznego momenty są zorientowane przypadkowo i suma wynosi zero; w polu $B_0$ pojawia się niewielki nadmiar spinów zgodnych z polem i **wypadkowy wektor** wzdłuż osi $z$. To on jest odchylany impulsem RF i daje mierzalny sygnał.$EXPL$,
   $SUB$Definicja magnetyzacji$SUB$, 'BIOFIZLEK-118'),
(49, 'BIOF-S1',
   $STEM$Organizmy żywe poddawane są działaniu różnych czynników jonizujących (promieniowanie kosmiczne, izotopy promieniotwórcze w otoczeniu i inne), powodujących uszkodzenia somatyczne i genetyczne w komórkach. Przeciętna roczna dawka skuteczna promieniowania jonizującego dla człowieka od tła wynosi (Sv – siwert, Gy – grej):$STEM$,
   $OPTS$[{"id": "a", "text": "$2{,}5\\ \\mathrm{mSv}$"}, {"id": "b", "text": "$0{,}25\\ \\mathrm{Sv}$"}, {"id": "c", "text": "$2{,}5\\ \\mathrm{mGy}$"}, {"id": "d", "text": "$2{,}5\\ \\mathrm{Gy}$"}]$OPTS$::jsonb,
   'a',
   $EXPL$Średnia roczna dawka skuteczna od tła naturalnego wynosi ok. **2,4–2,5 mSv**; największy udział ma **radon**, dalej promieniowanie kosmiczne, ziemskie i izotopy w organizmie. Dawkę skuteczną wyraża się w **siwertach** — uwzględnia ona rodzaj promieniowania i wrażliwość narządów, podczas gdy **grej** to jednostka dawki pochłoniętej (energia na kilogram). Wartości rzędu **0,25 Sv** czy **2,5 Gy** odpowiadają ekspozycji wypadkowej lub radioterapii.$EXPL$,
   $SUB$Dawki i tło promieniowania$SUB$, 'BIOFIZLEK-119'),
(50, 'BIOF-C1',
   $STEM$W przypadku cząsteczek oprócz skwantowanych stanów elektronowych atomów wyróżnia się skwantowane stany oscylacyjne (drgania atomów tworzących cząsteczkę) i rotacyjne (obroty cząsteczki). Zmiana stanu oscylacyjnego cząsteczki następuje w wyniku absorpcji lub emisji promieniowania:$STEM$,
   $OPTS$[{"id": "a", "text": "widzialnego (VIS)"}, {"id": "b", "text": "ultrafioletowego w zakresie A (UVA)"}, {"id": "c", "text": "podczerwonego (IR)"}, {"id": "d", "text": "ultrafioletowego w zakresie B (UVB)"}]$OPTS$::jsonb,
   'c',
   $EXPL$Odstępy między poziomami **oscylacyjnymi** odpowiadają energiom fotonów **podczerwieni** (ok. 0,01–0,5 eV), dlatego drgania cząsteczek bada spektroskopia **IR**, dająca charakterystyczny „odcisk palca” związku. Przejścia **rotacyjne** wymagają energii jeszcze mniejszych (mikrofale), a **elektronowe** — fotonów VIS i UV. Wariant z UVB jest błędny: promieniowanie o tak dużej energii wzbudza elektrony, a nie drgania atomów w cząsteczce.$EXPL$,
   $SUB$Przejścia oscylacyjne i rotacyjne$SUB$, 'BIOFIZLEK-120'),
(51, 'BIOF-S2',
   $STEM$Warunkiem koniecznym do działania lasera jest inwersja obsadzeń, polegająca na tym, że:$STEM$,
   $OPTS$[{"id": "a", "text": "jest to proces równowagi termodynamicznej, w którym liczba cząstek na poziomach energetycznych jest zgodna z rozkładem Boltzmanna"}, {"id": "b", "text": "jest to stan, w którym liczba cząstek o niższej energii jest większa niż liczba cząstek o wyższej energii"}, {"id": "c", "text": "jest to stan, w którym więcej cząstek znajduje się na wyższym poziomie energetycznym niż na niższym, co umożliwia emisję wymuszoną"}, {"id": "d", "text": "jest to proces, w którym cząstki przechodzą spontanicznie z wyższego poziomu energetycznego na niższy, emitując foton"}]$OPTS$::jsonb,
   'c',
   $EXPL$Inwersja obsadzeń to stan **nierównowagowy**, w którym na wyższym poziomie energetycznym znajduje się **więcej** cząstek niż na niższym. Dzięki temu **emisja wymuszona** przeważa nad absorpcją i wiązka jest wzmacniana, dając światło spójne, monochromatyczne i skolimowane. W równowadze termodynamicznej rozkład **Boltzmanna** wymusza sytuację odwrotną, dlatego konieczne jest **pompowanie** układu trój- lub czteropoziomowego z poziomem **metastabilnym**.$EXPL$,
   $SUB$Zasada działania lasera$SUB$, 'BIOFIZLEK-121'),
(52, 'BIOF-C1',
   $STEM$Czas życia fosforescencji to czas, przez jaki trwa emisja światła przez substancję po jej wzbudzeniu, i wynosi w zależności od rodzaju związku:$STEM$,
   $OPTS$[{"id": "a", "text": "od milisekund do sekund, a nawet godzin"}, {"id": "b", "text": "około $10^{-8}$ sekundy"}, {"id": "c", "text": "znacznie mniej niż $10^{-8}$ sekundy"}, {"id": "d", "text": "$10^{-6}$ sekundy"}]$OPTS$::jsonb,
   'a',
   $EXPL$Fosforescencja zachodzi z metastabilnego stanu **trypletowego**, a powrót do stanu podstawowego jest **wzbroniony** regułami wyboru, więc trwa długo: od **milisekund do sekund**, a nawet godzin. **Fluorescencja** przebiega ze stanu singletowego i zanika w czasie rzędu $10^{-8}$ s. Oba zjawiska poprzedza bezpromienista utrata części energii, dlatego światło emitowane ma **dłuższą falę** niż wzbudzające — to przesunięcie Stokesa.$EXPL$,
   $SUB$Luminescencja$SUB$, 'BIOFIZLEK-122'),
(53, 'BIOF-S2',
   $STEM$Irydotomia jest zabiegiem wykonywanym z zastosowaniem lasera w:$STEM$,
   $OPTS$[{"id": "a", "text": "stomatologii"}, {"id": "b", "text": "medycynie estetycznej"}, {"id": "c", "text": "okulistyce"}, {"id": "d", "text": "urologii"}]$OPTS$::jsonb,
   'c',
   $EXPL$Irydotomia to wykonanie otworu w tęczówce (łac. *iris*) laserem **Nd:YAG**, stosowane w **okulistyce** w jaskrze z zamykającym się kątem przesączania: udrażnia przepływ cieczy wodnistej z komory tylnej do przedniej, przerywa blok źreniczny i obniża ciśnienie wewnątrzgałkowe. Inne zastosowania laserów w okulistyce to **fotokoagulacja** siatkówki laserem argonowym oraz korekcja wad wzroku metodą **LASIK** z laserem ekscymerowym.$EXPL$,
   $SUB$Zastosowania laserów w medycynie$SUB$, 'BIOFIZLEK-123'),
(54, 'BIOF-INNE',
   $STEM$Szybkość utraty ciepła z organizmu poprzez parowanie zależy m.in. od różnic:$STEM$,
   $OPTS$[{"id": "a", "text": "temperatur otaczających obiektów i skóry"}, {"id": "b", "text": "czwartych potęg ciśnień parcjalnych pary wodnej w powietrzu i przy powierzchni skóry"}, {"id": "c", "text": "ciśnień parcjalnych pary wodnej w powietrzu i przy powierzchni skóry"}, {"id": "d", "text": "czwartych potęg temperatur otaczających obiektów i skóry"}]$OPTS$::jsonb,
   'c',
   $EXPL$Parowanie potu odbiera ciepło równe **ciepłu parowania** wody (ok. **2400 kJ/kg**), a jego szybkość zależy od **różnicy ciśnień parcjalnych** pary wodnej przy powierzchni skóry i w otaczającym powietrzu oraz od ruchu powietrza. Przy dużej wilgotności różnica maleje, pot spływa bez odparowania i rośnie ryzyko przegrzania. Od różnicy **czwartych potęg temperatur** zależy natomiast wymiana ciepła przez **promieniowanie** (prawo Stefana-Boltzmanna).$EXPL$,
   $SUB$Termoregulacja$SUB$, 'BIOFIZLEK-124'),
(55, 'BIOF-C2',
   $STEM$Gdy promienie światła przechodzą z ośrodka optycznie rzadszego, czyli o mniejszym współczynniku załamania światła, do ośrodka optycznie gęstszego, czyli o większym współczynniku załamania, kąt załamania jest:$STEM$,
   $OPTS$[{"id": "a", "text": "równy kątowi padania"}, {"id": "b", "text": "większy od kąta padania"}, {"id": "c", "text": "mniejszy od kąta padania"}, {"id": "d", "text": "mniejszy bądź równy kątowi padania"}]$OPTS$::jsonb,
   'c',
   $EXPL$Prawo Snella: $n_1\sin\alpha=n_2\sin\beta$. Przy przejściu do ośrodka **optycznie gęstszego** ($n_2>n_1$) zachodzi $\sin\beta<\sin\alpha$, więc promień załamuje się **do normalnej** i kąt załamania jest mniejszy od kąta padania. Przy przejściu odwrotnym kąt rośnie i po przekroczeniu **kąta granicznego** następuje całkowite wewnętrzne odbicie, wykorzystywane w światłowodach endoskopów. Promień padający prostopadle kierunku nie zmienia.$EXPL$,
   $SUB$Załamanie światła$SUB$, 'BIOFIZLEK-125'),
(56, 'BIOF-C2',
   $STEM$O możliwości zbierania światła przez mikroskop oraz zdolności tworzenia obrazu o jak największej ilości szczegółów decyduje apertura numeryczna (NA) obiektywu, która jest zdefiniowana następująco ($\alpha$ – kąt aperturowy; $n$ – współczynnik załamania ośrodka, w którym jest zanurzona czołowa soczewka obiektywu):$STEM$,
   $OPTS$[{"id": "a", "text": "$NA=n\\cos(\\alpha)$"}, {"id": "b", "text": "$NA=n\\sin^2(\\alpha)$"}, {"id": "c", "text": "$NA=n\\cos^2(\\alpha)$"}, {"id": "d", "text": "$NA=n\\sin(\\alpha)$"}]$OPTS$::jsonb,
   'd',
   $EXPL$Apertura numeryczna: $NA=n\sin\alpha$, gdzie $\alpha$ to **połowa kąta rozwarcia** stożka promieni wpadających do obiektywu, a $n$ — współczynnik załamania ośrodka przed soczewką czołową. Ponieważ $\sin\alpha<1$, w powietrzu $NA<1$, natomiast **immersja olejowa** ($n\approx1{,}5$) podnosi ją do ok. **1,4**. Wraz z NA rośnie ilość zbieranego światła i maleje granica rozdzielczości, zgodnie ze wzorem $d=\frac{0{,}61\lambda}{NA}$.$EXPL$,
   $SUB$Mikroskopia optyczna$SUB$, 'BIOFIZLEK-126'),
(57, 'BIOF-INNE',
   $STEM$Zgodnie z mechaniką kwantową materia charakteryzuje się dualizmem korpuskularno-falowym, co oznacza, że każdej cząstce można przypisać tzw. falę de Broglie'a. Zgodnie z równaniem de Broglie'a długość fali $\lambda$ związanej z poruszającym się elektronem wynosi ($h$ – stała Plancka, $m$ – masa elektronu, $v$ – prędkość elektronu):$STEM$,
   $OPTS$[{"id": "a", "text": "$\\lambda=\\frac{h}{mv}$"}, {"id": "b", "text": "$\\lambda=\\frac{mv}{h}$"}, {"id": "c", "text": "$\\lambda=\\frac{h}{m^2v}$"}, {"id": "d", "text": "$\\lambda=\\frac{mv^2}{h}$"}]$OPTS$::jsonb,
   'a',
   $EXPL$Fala materii de Broglie'a: $\lambda=\frac{h}{p}=\frac{h}{mv}$ — długość fali jest **odwrotnie proporcjonalna** do pędu, dlatego dla ciał makroskopowych jest niemierzalnie mała. Dla elektronu rozpędzonego napięciem rzędu kilkudziesięciu kV wynosi ułamki nanometra, czyli tysiące razy mniej niż dla światła widzialnego — stąd ogromna zdolność rozdzielcza **mikroskopu elektronowego**. Falowy charakter elektronów potwierdza ich **dyfrakcja** na sieci krystalicznej.$EXPL$,
   $SUB$Podstawy fizyki kwantowej$SUB$, 'BIOFIZLEK-127'),
(58, 'BIOF-C3',
   $STEM$Prędkość wypływu $v$ cieczy doskonałej pod wpływem siły ciężkości ($g$ – przyspieszenie ziemskie) z otworu znajdującego się na głębokości $h$ pod powierzchnią swobodną cieczy opisuje równanie:$STEM$,
   $OPTS$[{"id": "a", "text": "$v=2gh$"}, {"id": "b", "text": "$v=\\sqrt{2gh}$"}, {"id": "c", "text": "$v=\\sqrt{3gh}$"}, {"id": "d", "text": "$v=4gh$"}]$OPTS$::jsonb,
   'b',
   $EXPL$Wzór **Torricellego** $v=\sqrt{2gh}$ wynika wprost z równania Bernoulliego: energia potencjalna słupa cieczy zamienia się w energię kinetyczną strugi, dokładnie tak jak przy swobodnym spadku z wysokości $h$. Prędkość zależy więc tylko od głębokości otworu, a **nie od gęstości** cieczy. Wyrażenia liniowe względem $h$ są błędne **wymiarowo**. Założenia: ciecz doskonała, otwór mały w stosunku do naczynia i stały poziom swobodny.$EXPL$,
   $SUB$Hydrodynamika cieczy doskonałej$SUB$, 'BIOFIZLEK-128'),
(59, 'BIOF-INNE',
   $STEM$Błona komórkowa wykazuje specyficzne właściwości elektryczne wynikające z jej budowy oraz obecności kanałów jonowych. W jej opisie uwzględnia się zarówno zjawisko rozdziału ładunków po obu stronach błony, jak i możliwość przepływu jonów przez wyspecjalizowane struktury białkowe. Zjawiska te mogą być analizowane przy użyciu uproszczonych modeli elektrycznych, w których stosowane są:$STEM$,
   $OPTS$[{"id": "a", "text": "tylko oporniki"}, {"id": "b", "text": "oporniki i solenoidy"}, {"id": "c", "text": "solenoidy i kondensatory"}, {"id": "d", "text": "kondensatory i oporniki"}]$OPTS$::jsonb,
   'd',
   $EXPL$Dwuwarstwa lipidowa to cienki **dielektryk** rozdzielający przewodzące roztwory elektrolitów, więc zachowuje się jak **kondensator** o pojemności ok. **1 µF/cm²**. Kanały jonowe umożliwiają przepływ ładunku i odpowiadają **opornikom** połączonym z ogniwami o napięciach równych potencjałom Nernsta. Model **RC** wyjaśnia stałą czasową błony i bierne rozprzestrzenianie się potencjału. Solenoidy, czyli indukcyjność, nie mają w błonie odpowiednika.$EXPL$,
   $SUB$Elektryczne właściwości błon$SUB$, 'BIOFIZLEK-129'),
(60, 'BIOF-W1',
   $STEM$Jednym z ważnych parametrów statystycznych, przybliżającym wartość mierzonej wielkości i obliczonym z szeregu pomiarowego, jest:$STEM$,
   $OPTS$[{"id": "a", "text": "średnia"}, {"id": "b", "text": "wariancja"}, {"id": "c", "text": "odchylenie standardowe"}, {"id": "d", "text": "błąd standardowy"}]$OPTS$::jsonb,
   'a',
   $EXPL$Najlepszym przybliżeniem wartości mierzonej wielkości jest **średnia arytmetyczna** $\bar{x}=\frac{1}{n}\sum x_i$ — minimalizuje sumę kwadratów odchyleń i przy błędach czysto przypadkowych zmierza wraz ze wzrostem $n$ do wartości rzeczywistej. Pozostałe wymienione parametry opisują **rozrzut**: wariancja i odchylenie standardowe charakteryzują pojedynczy pomiar, a **błąd standardowy** — dokładność wyznaczenia samej średniej.$EXPL$,
   $SUB$Statystyczne opracowanie pomiarów$SUB$, 'BIOFIZLEK-130'),
(61, 'BIOF-INNE',
   $STEM$Jako głównych parametrów charakteryzujących falę (elektromagnetyczną lub mechaniczną) używamy: długość, częstotliwość i prędkość fali. Z kolei energia przenoszona przez falę charakteryzowana jest przez natężenie fali. Wielkość tę definiujemy jako iloraz:$STEM$,
   $OPTS$[{"id": "a", "text": "energii fali do pola powierzchni prostopadłej do kierunku rozchodzenia się fali, przez którą fala przechodzi"}, {"id": "b", "text": "mocy fali do pola powierzchni prostopadłej do kierunku rozchodzenia się fali, przez którą fala przechodzi"}, {"id": "c", "text": "energii fali do pola powierzchni równoległej do kierunku rozchodzenia się fali, przez którą fala przechodzi"}, {"id": "d", "text": "mocy fali do pola powierzchni równoległej do kierunku rozchodzenia się fali, przez którą fala przechodzi"}]$OPTS$::jsonb,
   'b',
   $EXPL$Natężenie fali to **moc** przenoszona przez jednostkę powierzchni ustawionej **prostopadle** do kierunku rozchodzenia się fali: $I=\frac{P}{S}$, w jednostkach $\mathrm{W/m^2}$. Sama energia odniesiona do powierzchni dałaby $\mathrm{J/m^2}$, czyli inną wielkość, a przez powierzchnię równoległą fala w ogóle by nie przechodziła. Natężenie jest proporcjonalne do **kwadratu amplitudy**, a dla dźwięku jego poziom wyraża się logarytmicznie w **decybelach**.$EXPL$,
   $SUB$Parametry fal$SUB$, 'BIOFIZLEK-131'),
(62, 'BIOF-W1',
   $STEM$Po wykonaniu $n$ pomiarów mierzonej wielkości $X$ obliczamy parametry statystyczne charakteryzujące daną wielkość. Błąd standardowy, określający dokładność wyznaczenia średniej, obliczany jest z równania:$STEM$,
   $OPTS$[{"id": "a", "text": "$\\sqrt{\\frac{1}{n-1}\\sum_{i=1}^{n}(x_i-\\bar{x})^2}$"}, {"id": "b", "text": "$\\sqrt{\\frac{1}{n}\\sum_{i=1}^{n}(x_i-\\bar{x})^2}$"}, {"id": "c", "text": "$\\sqrt{\\frac{1}{n(n-1)}\\sum_{i=1}^{n}(x_i-\\bar{x})^2}$"}, {"id": "d", "text": "$\\frac{1}{n-1}\\sum_{i=1}^{n}(x_i-\\bar{x})$"}]$OPTS$::jsonb,
   'c',
   $EXPL$Błąd standardowy średniej: $S_{\bar{x}}=\sqrt{\frac{1}{n(n-1)}\sum(x_i-\bar{x})^2}=\frac{s}{\sqrt{n}}$, gdzie $s$ to **odchylenie standardowe** pojedynczego pomiaru (wzór z dzielnikiem $n-1$). Maleje z **pierwiastkiem** liczby pomiarów, więc czterokrotny wzrost $n$ poprawia dokładność zaledwie dwukrotnie. Dzielnik $n-1$ to liczba **stopni swobody**, bo jeden zużyto na wyznaczenie średniej. Suma odchyleń bez podnoszenia do kwadratu jest zawsze równa zeru.$EXPL$,
   $SUB$Statystyczne opracowanie pomiarów$SUB$, 'BIOFIZLEK-132'),
(63, 'BIOF-W1',
   $STEM$Współczynnik liniowej korelacji (współczynnik Pearsona) charakteryzuje zależność między dwiema badanymi zmiennymi. Gdy współczynnik ten jest większy od zera, to można stwierdzić, że funkcja zależności między badanymi zmiennymi jest:$STEM$,
   $OPTS$[{"id": "a", "text": "malejąca, a wartości współczynnika Pearsona mieszczą się w zakresie od -1 do 1"}, {"id": "b", "text": "rosnąca, a wartości współczynnika Pearsona mieszczą się w zakresie od 0 do 1"}, {"id": "c", "text": "malejąca, a wartości współczynnika Pearsona mieszczą się w zakresie od 0 do 1"}, {"id": "d", "text": "rosnąca, a wartości współczynnika Pearsona mieszczą się w zakresie od -1 do 1"}]$OPTS$::jsonb,
   'd',
   $EXPL$Współczynnik Pearsona przyjmuje wartości od **-1 do 1** i mierzy siłę oraz kierunek zależności **liniowej**. Znak dodatni oznacza funkcję **rosnącą** — wzrostowi jednej zmiennej towarzyszy wzrost drugiej; znak ujemny funkcję malejącą, a $r=0$ brak korelacji liniowej. Zakres od 0 do 1 dotyczy $r^2$, czyli **współczynnika determinacji**. Korelacja nie dowodzi związku **przyczynowego** ani nie wykrywa zależności nieliniowych.$EXPL$,
   $SUB$Korelacja wyników$SUB$, 'BIOFIZLEK-133'),
(64, 'BIOF-W5',
   $STEM$W tomografii NMR wykorzystywane jest silne pole magnetyczne i pole elektromagnetyczne z zakresu radiowego. Generatorem silnego pola magnetycznego w tomografii NMR mogą być:$STEM$,
   $OPTS$[{"id": "a", "text": "uzwojenia, przez które przepływa stały prąd elektryczny"}, {"id": "b", "text": "ładunki elektryczne rozmieszczone na płytkach kondensatora"}, {"id": "c", "text": "cewki indukcyjne, przez które przepuszczane są sinusoidalne prądy zmienne o częstotliwości Larmora"}, {"id": "d", "text": "ładunki magnetyczne rozmieszczone odpowiednio wokół badanego pacjenta"}]$OPTS$::jsonb,
   'a',
   $EXPL$Pole główne $B_0$ musi być **stałe w czasie** i bardzo jednorodne, dlatego wytwarzają je **uzwojenia zasilane prądem stałym** — w praktyce cewki **nadprzewodzące** chłodzone ciekłym helem, dające 1,5–3 T bez strat omowych. Cewki zasilane prądem zmiennym o **częstotliwości Larmora** pełnią inną rolę: nadają impulsy RF, a cewki gradientowe kodują położenie. Kondensator wytwarza pole elektryczne, a swobodne „ładunki magnetyczne” nie istnieją.$EXPL$,
   $SUB$Budowa tomografu$SUB$, 'BIOFIZLEK-134'),
(65, 'BIOF-INNE',
   $STEM$Zjawiskiem występującym w układach biologicznych, jak i w przyrządach wykorzystywanych do badań tych układów, jest rezonans elektryczny lub mechaniczny. W ogólnym przypadku rezonans polega na przekazie energii z jednego układu drgającego do drugiego:$STEM$,
   $OPTS$[{"id": "a", "text": "o jednakowej amplitudzie drgań dla częstotliwości wymuszającej niezależnej od struktury układu odbierającego energię"}, {"id": "b", "text": "o maksymalnej amplitudzie drgań dla częstotliwości wymuszającej określonej przez strukturę układu odbierającego energię"}, {"id": "c", "text": "o minimalnej amplitudzie drgań dla częstotliwości wymuszającej określonej przez strukturę układu przesyłającego energię"}, {"id": "d", "text": "z amplitudą drgań proporcjonalną do częstotliwości wymuszającej układu"}]$OPTS$::jsonb,
   'b',
   $EXPL$Rezonans zachodzi, gdy częstotliwość wymuszająca jest zbliżona do **częstotliwości własnej** układu **odbierającego** energię, wyznaczonej przez jego strukturę (np. $f_0=\frac{1}{2\pi}\sqrt{\frac{k}{m}}$ dla oscylatora mechanicznego). Amplituda drgań osiąga wtedy **maksimum**, ograniczone jedynie **tłumieniem**, a przekaz energii jest najefektywniejszy. Zjawisko to leży u podstaw **NMR**, obwodów strojonych oraz rezonansowych drgań narządów przy wibracjach.$EXPL$,
   $SUB$Drgania i rezonans$SUB$, 'BIOFIZLEK-135'),
(66, 'BIOF-W5',
   $STEM$Parametry opisujące czasowe zmiany magnetyzacji w metodzie obrazowania NMR po zaburzeniu wektora magnetyzacji impulsem $\pi/2$, nazywane czasami relaksacji, odpowiadają:$STEM$,
   $OPTS$[{"id": "a", "text": "$T_1$ – czas relaksacji spin-spin, odpowiadający zmianom składowej podłużnej magnetyzacji, $T_2$ – czas relaksacji spin-sieć, odpowiadający zmianom składowej poprzecznej magnetyzacji"}, {"id": "b", "text": "$T_1$ – czas relaksacji spin-sieć, odpowiadający zmianom składowej poprzecznej magnetyzacji, $T_2$ – czas relaksacji spin-spin, odpowiadający zmianom składowej podłużnej magnetyzacji"}, {"id": "c", "text": "$T_1$ – czas relaksacji spin-sieć, odpowiadający zmianom składowej podłużnej magnetyzacji, $T_2$ – czas relaksacji spin-spin, odpowiadający zmianom składowej poprzecznej magnetyzacji"}, {"id": "d", "text": "$T_1$ – czas relaksacji spin-spin, odpowiadający zmianom składowej poprzecznej magnetyzacji, $T_2$ – czas relaksacji spin-sieć, odpowiadający zmianom składowej podłużnej magnetyzacji"}]$OPTS$::jsonb,
   'c',
   $EXPL$**$T_1$** (relaksacja **spin-sieć**, podłużna) opisuje odbudowę składowej **podłużnej** $M_z$ dzięki oddawaniu energii do otoczenia. **$T_2$** (relaksacja **spin-spin**, poprzeczna) to zanik składowej **poprzecznej** $M_{xy}$ wskutek utraty spójności fazowej spinów, bez wymiany energii z siecią. Zawsze $T_2\leq T_1$: w tkankach $T_1$ ma setki milisekund, $T_2$ — dziesiątki. Dobór czasów **TR** i **TE** decyduje o obrazach T1- i T2-zależnych.$EXPL$,
   $SUB$Czasy relaksacji$SUB$, 'BIOFIZLEK-136'),
(67, 'BIOF-W4',
   $STEM$Aby otrzymać obraz wewnętrznej struktury pacjenta za pomocą tomografii komputerowej, należy brać pod uwagę ryzyko związane z potencjalnymi uszkodzeniami tkanek pacjenta. Czy w przypadku stosowania rentgenowskiej tomografii CAT (tomografia komputerowa osiowa) tkanki pacjenta poddane badaniom narażone są na potencjalne uszkodzenia?$STEM$,
   $OPTS$[{"id": "a", "text": "tak, ze względu na to, że stosowane w metodzie CAT silne pole magnetyczne jonizuje materię"}, {"id": "b", "text": "nie, ponieważ stosowane w metodzie pole elektromagnetyczne nie wnika do organizmu człowieka"}, {"id": "c", "text": "nie, ze względu na to, że w metodzie tej stosowane jest pole elektromagnetyczne z zakresu radiowego"}, {"id": "d", "text": "tak, ze względu na to, że stosowane jest pole elektromagnetyczne z zakresu jonizującego"}]$OPTS$::jsonb,
   'd',
   $EXPL$W tomografii komputerowej stosuje się promieniowanie **rentgenowskie** — falę elektromagnetyczną o energii fotonów wystarczającej do **jonizacji**, więc tkanki są narażone na uszkodzenia, głównie o charakterze **stochastycznym** (ryzyko nowotworowe). Dawka z badania CT jamy brzusznej sięga **kilku–kilkunastu mSv**, wielokrotnie przewyższając zdjęcie klatki piersiowej. Pole magnetyczne i fale radiowe, niejonizujące, wykorzystuje natomiast **MRI**.$EXPL$,
   $SUB$Bezpieczeństwo badania CT$SUB$, 'BIOFIZLEK-137'),
(68, 'BIOF-S3',
   $STEM$Jednym z ważnych parametrów w metodach ultrasonograficznych jest impedancja akustyczna. Parametr ten definiujemy jako:$STEM$,
   $OPTS$[{"id": "a", "text": "iloczyn prędkości rozchodzenia się fali ultradźwiękowej w danym ośrodku i gęstości ośrodka"}, {"id": "b", "text": "iloraz prędkości rozchodzenia się fali ultradźwiękowej w danym ośrodku i gęstości ośrodka"}, {"id": "c", "text": "sumę prędkości rozchodzenia się fali ultradźwiękowej w danym ośrodku i gęstości ośrodka"}, {"id": "d", "text": "różnicę prędkości rozchodzenia się fali ultradźwiękowej w danym ośrodku i gęstości ośrodka"}]$OPTS$::jsonb,
   'a',
   $EXPL$Impedancja akustyczna to **iloczyn** gęstości ośrodka i prędkości fali: $Z=\rho c$, wyrażany w $\mathrm{kg/(m^2\cdot s)}$, czyli w **rayl**ach. Decyduje o odbiciu na granicy ośrodków: im większy **skok $Z$**, tym silniejsze echo. Tkanki miękkie mają $Z$ zbliżoną (ok. $1{,}5\cdot10^6$), więc ich granice dają słabe echa, natomiast powietrze ma impedancję tysiące razy mniejszą, a kość kilkakrotnie większą — stąd cień akustyczny i konieczność użycia żelu.$EXPL$,
   $SUB$Impedancja akustyczna$SUB$, 'BIOFIZLEK-138'),
(69, 'BIOF-W5',
   $STEM$Po wzbudzeniu impulsem $\pi/2$ wektor magnetyzacji w metodzie obrazowania NMR powraca do początkowego ustawienia (zgodnie z wektorem pola $B$). Czas potrzebny na to, aby podłużna składowa wektora magnetyzacji wzrosła do 63% jej wartości maksymalnej, nazywamy czasem:$STEM$,
   $OPTS$[{"id": "a", "text": "relaksacji spin-spin $T_2$"}, {"id": "b", "text": "relaksacji spin-sieć $T_1$"}, {"id": "c", "text": "połowicznego zaniku $T_1$"}, {"id": "d", "text": "relaksacji spin-sieć $T_2$"}]$OPTS$::jsonb,
   'b',
   $EXPL$Odbudowa składowej **podłużnej** magnetyzacji przebiega wykładniczo: $M_z=M_0(1-e^{-t/T_1})$. Po czasie $t=T_1$ nawias osiąga wartość $1-e^{-1}\approx0{,}63$, więc **$T_1$** — czas relaksacji **spin-sieć** — to czas odbudowy do **63%** wartości maksymalnej, przy oddaniu energii do otoczenia. **$T_2$** (spin-spin) opisuje zanik składowej **poprzecznej** do 37% wartości początkowej i jest zawsze krótszy lub równy $T_1$.$EXPL$,
   $SUB$Czasy relaksacji$SUB$, 'BIOFIZLEK-139')
),
maxes AS (
  SELECT q.topic_id,
         COALESCE(
           MAX((regexp_match(q.id, '^biofiz-' || lower(substring(q.topic_id from 6)) || '-([0-9]+)$'))[1]::int),
           0
         ) AS mx
    FROM public.questions q
   WHERE q.topic_id IN ('BIOF-C1', 'BIOF-C2', 'BIOF-C3', 'BIOF-C4', 'BIOF-INNE', 'BIOF-S1', 'BIOF-S2', 'BIOF-S3', 'BIOF-W1', 'BIOF-W4', 'BIOF-W5')
   GROUP BY q.topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam, theme_label, tracks)
SELECT
  'biofiz-' || lower(substring(n.topic_id from 6)) || '-' ||
    LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_biof_lek_2026/1', 'Egzamin biofizyka LEK SUM 2026 (BIOFIZLEK e2026-1)',
  '2026', ARRAY['lekarski']::TEXT[]
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (
    SELECT topic_id, COUNT(*)::int AS cnt
      FROM public.questions
     WHERE topic_id IN ('BIOF-C1', 'BIOF-C2', 'BIOF-C3', 'BIOF-C4', 'BIOF-INNE', 'BIOF-S1', 'BIOF-S2', 'BIOF-S3', 'BIOF-W1', 'BIOF-W4', 'BIOF-W5')
       AND COALESCE(is_active, true) = true
     GROUP BY topic_id
  ) sub
 WHERE t.id = sub.topic_id;

UPDATE public.topics
   SET question_count = 0
 WHERE id = 'biofizyka-THEME-2026';
