-- ============================================================
-- BATCH: e_hist_stoma_2026/5  ·  subject_id=histologia  ·  tracks=stomatologia
-- Źródło: HISSTO e2026-1, 58 pytań A–E
-- id = HIST-NN-NNN · theme_label = 2026 (kafelek wirtualny, bez duplikatu)
-- Kafelek histologia-THEME-2026 już istnieje (tracks NULL) — nie nadpisujemy.
-- Wygenerowane przez scripts/build-hissto-e2026-1.py (nie edytować ręcznie)
-- ============================================================

WITH new_rows (seq, topic_id, qtext, opts, correct, expl, subtheme, srccode) AS (
 VALUES
(1, 'HIST-19',
   $STEM$W prawidłowym, 28-dniowym cyklu miesiączkowym owulacja następuje w:$STEM$,
   $OPTS$[{"id": "a", "text": "7. dniu cyklu"}, {"id": "b", "text": "10. dniu cyklu"}, {"id": "c", "text": "14. dniu cyklu"}, {"id": "d", "text": "21. dniu cyklu"}, {"id": "e", "text": "26. dniu cyklu"}]$OPTS$::jsonb,
   'c',
   $EXPL$**Owulacja** dzieli cykl na fazę **folikularną** (o zmiennej długości) i **lutealną** (stałą, ok. 14 dni). Wyzwala ją gwałtowny **pik LH**, poprzedzony szczytem **estradiolu** wydzielanego przez dojrzały **pęcherzyk Graafa**; do pęknięcia dochodzi ok. 36 h po piku. Powstałe **ciałko żółte** produkuje **progesteron**. Ponieważ faza lutealna jest stała, w cyklu 28-dniowym owulacja przypada na **14. dobę** — przy cyklach dłuższych wydłuża się wyłącznie faza folikularna.$EXPL$,
   $SUB$Cykl jajnikowy i miesiączkowy$SUB$, 'HISSTO-e2026-1-222'),
(2, 'HIST-04',
   $STEM$Główną funkcją połączeń ścisłych (zonula occludens) jest:$STEM$,
   $OPTS$[{"id": "a", "text": "uszczelnianie przestrzeni międzykomórkowej i tworzenie bariery dyfuzyjnej"}, {"id": "b", "text": "mechaniczne wiązanie komórek przez filamenty pośrednie"}, {"id": "c", "text": "przekazywanie jonów i drobnych cząsteczek między cytoplazmami"}, {"id": "d", "text": "przytwierdzanie komórki do blaszki podstawnej"}, {"id": "e", "text": "kotwiczenie komórki we włóknach kolagenowych blaszki właściwej"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Klaudyny** i **okludyna** zbliżają zewnętrzne blaszki błon sąsiednich komórek, zamykając szczelinę międzykomórkową. Blokuje to transport **paracelularny** i wymusza drogę **transcelularną** — stąd bariery jelitowa, krew–mózg i krew–jądro. Drugą funkcją jest utrzymanie **polaryzacji**: białka domeny szczytowej nie mieszają się z podstawno-bocznymi. Wiązanie filamentów pośrednich to cecha **desmosomów**, a kontakt z blaszką podstawną — **hemidesmosomów**.$EXPL$,
   $SUB$Połączenia międzykomórkowe$SUB$, 'HISSTO-e2026-1-223'),
(3, 'HIST-13',
   $STEM$Krypty migdałka podniebiennego i pokrywający je nabłonek charakteryzują się tym, że:$STEM$,
   $OPTS$[{"id": "a", "text": "nabłonek jest gęsto naciekany limfocytami i granulocytami"}, {"id": "b", "text": "nie zawierają żadnych elementów układu odpornościowego"}, {"id": "c", "text": "nabłonek jest silnie zrogowaciały"}, {"id": "d", "text": "są wyścielone nabłonkiem jednowarstwowym walcowatym z rąbkiem szczoteczkowym"}, {"id": "e", "text": "zawierają wyłącznie limfocyty T, bez grudek chłonnych"}]$OPTS$::jsonb,
   'a',
   $EXPL$Krypty pokrywa **nabłonek wielowarstwowy płaski nierogowaciejący**, tak gęsto naciekany **limfocytami** i **granulocytami**, że granica z tkanką limfoidalną bywa nieczytelna — stąd nazwa **nabłonek limfoepitelialny (retikularny)**. Umożliwia to bezpośredni kontakt antygenów jamy ustnej z komórkami immunokompetentnymi. W blaszce właściwej leżą **grudki chłonne z ośrodkami rozmnażania** (limfocyty B), więc odpowiedź o samych limfocytach T jest błędna.$EXPL$,
   $SUB$Migdałki$SUB$, 'HISSTO-e2026-1-224'),
(4, 'HIST-12',
   $STEM$Podstawową funkcją eozynofilów jest:$STEM$,
   $OPTS$[{"id": "a", "text": "eliminacja pasożytów wielokomórkowych i udział w reakcjach alergicznych"}, {"id": "b", "text": "fagocytoza bakterii ropotwórczych"}, {"id": "c", "text": "wydzielanie histaminy i heparyny"}, {"id": "d", "text": "produkcja przeciwciał"}, {"id": "e", "text": "prezentacja antygenu dziewiczym limfocytom T"}]$OPTS$::jsonb,
   'a',
   $EXPL$Ziarnistości kwasochłonne zawierają **MBP (główne białko zasadowe)**, **ECP** i **peroksydazę eozynofilową** — cytotoksyczne dla **helmintów**, których wielkość uniemożliwia fagocytozę. Eozynofile modulują też reakcje alergiczne, rozkładając **histaminę** (histaminaza) i **leukotrieny**. Stanowią **2–4%** leukocytów; ich wzrost widać w inwazjach pasożytniczych i atopii. Fagocytoza bakterii to domena **neutrofilów**, a histamina i heparyna — **bazofilów**.$EXPL$,
   $SUB$Granulocyty$SUB$, 'HISSTO-e2026-1-225'),
(5, 'HIST-18',
   $STEM$Hormonem wydzielanym przez warstwę kłębkowatą kory nadnerczy jest:$STEM$,
   $OPTS$[{"id": "a", "text": "aldosteron"}, {"id": "b", "text": "kortyzol"}, {"id": "c", "text": "dehydroepiandrosteron (DHEA)"}, {"id": "d", "text": "adrenalina"}, {"id": "e", "text": "kortykoliberyna (CRH)"}]$OPTS$::jsonb,
   'a',
   $EXPL$Warstwa **kłębkowata** (najbardziej zewnętrzna) produkuje **mineralokortykoidy**, głównie **aldosteron**, regulowany przez układ **RAA** i stężenie potasu; zwiększa on resorpcję sodu i wydzielanie potasu w kanaliku dalszym. Warstwa **pasmowata** wydziela **kortyzol**, **siateczkowata** — androgeny nadnerczowe (**DHEA**), a **rdzeń** — **adrenalinę**. Mnemonik: GFR = Glomerulosa/Fasciculata/Reticularis → Salt, Sugar, Sex („im głębiej, tym słodziej i przyjemniej”).$EXPL$,
   $SUB$Nadnercza$SUB$, 'HISSTO-e2026-1-226'),
(6, 'HIST-18',
   $STEM$Które stwierdzenie dotyczące kalcytoniny jest prawdziwe?$STEM$,
   $OPTS$[{"id": "a", "text": "jest głównym regulatorem gospodarki wapniowej u człowieka"}, {"id": "b", "text": "jest ważniejsza niż parathormon"}, {"id": "c", "text": "jest wydzielana przez komórki pęcherzykowe tarczycy"}, {"id": "d", "text": "nie wpływa na tkankę kostną"}, {"id": "e", "text": "ma mniejsze znaczenie niż parathormon i witamina D"}]$OPTS$::jsonb,
   'e',
   $EXPL$**Kalcytonina** powstaje w **komórkach C (przypęcherzykowych)**, wywodzących się z grzebienia nerwowego, a nie w komórkach pęcherzykowych produkujących **T3/T4**. Hamuje **osteoklasty**, obniżając kalcemię, ale u człowieka jej rola jest **marginalna** — po tyreoidektomii ani w raku rdzeniastym (skrajnie wysoka kalcytonina) gospodarka wapniowa nie ulega zaburzeniu. Głównymi regulatorami pozostają **parathormon** i **kalcytriol**.$EXPL$,
   $SUB$Tarczyca — komórki C$SUB$, 'HISSTO-e2026-1-227'),
(7, 'HIST-20',
   $STEM$Ciecz wodnista przepływa w gałce ocznej:$STEM$,
   $OPTS$[{"id": "a", "text": "z komory tylnej przez źrenicę do komory przedniej i dalej do kąta tęczówkowo-rogówkowego"}, {"id": "b", "text": "z komory przedniej przez źrenicę do komory tylnej i dalej do ciała szklistego"}, {"id": "c", "text": "z ciała szklistego przez siatkówkę do naczyniówki"}, {"id": "d", "text": "z komory przedniej bezpośrednio do naczyń siatkówki"}, {"id": "e", "text": "z rogówki przez twardówkę do przestrzeni nadnaczyniówkowej"}]$OPTS$::jsonb,
   'a',
   $EXPL$Ciecz wodnistą wytwarza **nabłonek wyrostków rzęskowych** do **komory tylnej**. Przez **źrenicę** trafia do **komory przedniej**, a odpływa w **kącie tęczówkowo-rogówkowym** przez **beleczkowanie** do **zatoki żylnej twardówki (kanał Schlemma)** i dalej do żył wodnistych. Odżywia beznaczyniowe **rogówkę** i **soczewkę** oraz utrzymuje ciśnienie wewnątrzgałkowe. Blok odpływu w kącie to mechanizm **jaskry**, a wymiana całej objętości cieczy zachodzi co ok. **90 minut**.$EXPL$,
   $SUB$Ciecz wodnista$SUB$, 'HISSTO-e2026-1-228'),
(8, 'HIST-20',
   $STEM$Uszkodzenie mięśnia strzemiączkowego powoduje:$STEM$,
   $OPTS$[{"id": "a", "text": "nadwrażliwość na dźwięki (hiperakuzję)"}, {"id": "b", "text": "całkowitą głuchotę przewodzeniową"}, {"id": "c", "text": "zaburzenie wyrównywania ciśnień w uchu środkowym"}, {"id": "d", "text": "niedrożność trąbki słuchowej"}, {"id": "e", "text": "brak jakiegokolwiek wpływu na odbiór bodźców słuchowych"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Mięsień strzemiączkowy** (unerwiony przez **nerw twarzowy**) usztywnia strzemiączko w **odruchu strzemiączkowym**, tłumiąc przenoszenie głośnych dźwięków na okienko owalne. Jego porażenie znosi to zabezpieczenie — pojawia się **hiperakuzja**, typowa dla porażenia n. VII powyżej odejścia gałązki do mięśnia. Kosteczki pozostają ruchome, więc przewodzenie jest zachowane; ciśnienie wyrównuje **trąbka słuchowa** z mięśniem napinaczem podniebienia.$EXPL$,
   $SUB$Ucho środkowe$SUB$, 'HISSTO-e2026-1-229'),
(9, 'HIST-18',
   $STEM$Komórki B (beta) wysp trzustkowych:$STEM$,
   $OPTS$[{"id": "a", "text": "wydzielają glukagon"}, {"id": "b", "text": "leżą obwodowo w wyspie"}, {"id": "c", "text": "wydzielają insulinę"}, {"id": "d", "text": "wydzielają somatostatynę"}, {"id": "e", "text": "prawidłowe A i B"}]$OPTS$::jsonb,
   'c',
   $EXPL$Komórki **B (beta)** stanowią **60–70%** wyspy, leżą **centralnie** i wydzielają **insulinę** oraz **amylinę**. Obwodowo rozmieszczone są komórki **A (alfa)** produkujące **glukagon** (ok. 20%), a między nimi komórki **D** z **somatostatyną** i komórki **PP**. Ziarnistości insuliny mają charakterystyczny **krystaliczny rdzeń z cynkiem**. Autoimmunologiczne zniszczenie komórek B leży u podłoża **cukrzycy typu 1**. Wyspy są silnie unaczynione i barwią się jaśniej niż otaczające pęcherzyki zewnątrzwydzielnicze.$EXPL$,
   $SUB$Wyspy trzustkowe$SUB$, 'HISSTO-e2026-1-230'),
(10, 'HIST-21',
   $STEM$Podczas wydzielania szkliwa ameloblasty przemieszczają się w kierunku:$STEM$,
   $OPTS$[{"id": "a", "text": "zębiny"}, {"id": "b", "text": "cementu korzeniowego"}, {"id": "c", "text": "brodawki zębowej"}, {"id": "d", "text": "nabłonka wewnętrznego narządu szkliwotwórczego"}, {"id": "e", "text": "nabłonka zewnętrznego narządu szkliwotwórczego"}]$OPTS$::jsonb,
   'e',
   $EXPL$**Ameloblasty** różnicują się z **nabłonka wewnętrznego narządu szkliwotwórczego** i rozpoczynają wydzielanie na przyszłym **połączeniu szkliwno-zębinowym**, dopiero po pojawieniu się pierwszej warstwy **predentyny**. Odkładając macierz **przed sobą**, cofają się od zębiny **na zewnątrz**, ku **nabłonkowi zewnętrznemu** — dlatego szkliwo przyrasta odśrodkowo. Odontoblasty działają odwrotnie: wędrują do wnętrza, ku **miazdze**.$EXPL$,
   $SUB$Amelogeneza$SUB$, 'HISSTO-e2026-1-231'),
(11, 'HIST-22',
   $STEM$Ogonowa część trzonu kości gnykowej powstaje z łuku gardłowego:$STEM$,
   $OPTS$[{"id": "a", "text": "I"}, {"id": "b", "text": "II"}, {"id": "c", "text": "III"}, {"id": "d", "text": "IV"}, {"id": "e", "text": "VI"}]$OPTS$::jsonb,
   'c',
   $EXPL$Chrząstka **III łuku** (nerw **IX**, m. rylcowo-gardłowy) daje **rogi większe** i **dolną (ogonową) część trzonu** kości gnykowej. Z chrząstki **Reicherta** (II łuk, nerw **VII**) powstają **rogi mniejsze**, **górna część trzonu**, wyrostek rylcowaty, więzadło rylcowo-gnykowe i **strzemiączko**. Chrząstka **Meckela** (I łuk, nerw **V3**) tworzy młoteczek i kowadełko, a łuki **IV i VI** — chrząstki krtani. Kość gnykowa ma więc **podwójne pochodzenie**: część górna z II łuku, część dolna z III.$EXPL$,
   $SUB$Łuki gardłowe$SUB$, 'HISSTO-e2026-1-232'),
(12, 'HIST-11',
   $STEM$Ostatnim elementem układu bodźcoprzewodzącego serca są:$STEM$,
   $OPTS$[{"id": "a", "text": "kardiomiocyty robocze przedsionków"}, {"id": "b", "text": "węzeł przedsionkowo-komorowy"}, {"id": "c", "text": "węzeł zatokowo-przedsionkowy"}, {"id": "d", "text": "pęczek Hisa"}, {"id": "e", "text": "włókna Purkinjego"}]$OPTS$::jsonb,
   'e',
   $EXPL$Kolejność: **węzeł zatokowo-przedsionkowy** (rozrusznik, ok. 70/min) → **węzeł przedsionkowo-komorowy** (opóźnienie AV) → **pęczek Hisa** → **odnogi** → **włókna Purkinjego**. Te ostatnie leżą podwsierdziowo, są to zmodyfikowane kardiomiocyty o dużej średnicy, ubogie w miofibryle i bogate w **glikogen**, z licznymi **koneksonami** — stąd najszybsze przewodzenie (**do 4 m/s**), zapewniające jednoczesny skurcz komór od koniuszka.$EXPL$,
   $SUB$Układ bodźcoprzewodzący serca$SUB$, 'HISSTO-e2026-1-233'),
(13, 'HIST-21',
   $STEM$Włókna skośne ozębnej zapobiegają przede wszystkim:$STEM$,
   $OPTS$[{"id": "a", "text": "wtłaczaniu zęba w zębodół"}, {"id": "b", "text": "wysuwaniu zęba z zębodołu"}, {"id": "c", "text": "obracaniu zęba wokół osi długiej"}, {"id": "d", "text": "przemieszczaniu zęba w kierunku przedsionkowo-językowym"}, {"id": "e", "text": "resorpcji brzegu wyrostka zębodołowego"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Włókna skośne** to najliczniejsza grupa (ok. 2/3 ozębnej). Biegną od **cementu** skośnie ku górze, przyczepiając się do kości **bardziej dokoronowo**. Siła żucia działająca wzdłuż osi zęba napina je, zamieniając nacisk na **rozciąganie** — ząb jest zawieszony, a nie wciskany w zębodół. Wtłaczaniu przeciwdziałają więc włókna skośne, wysuwaniu — włókna **wierzchołkowe**, a rotacji — włókna **okrężne** i **międzyzębowe**.$EXPL$,
   $SUB$Ozębna$SUB$, 'HISSTO-e2026-1-234'),
(14, 'HIST-21',
   $STEM$Wskaż zdanie FAŁSZYWE dotyczące substancji organicznej szkliwa:$STEM$,
   $OPTS$[{"id": "a", "text": "tworzy delikatną siateczkę otaczającą kryształy hydroksyapatytu"}, {"id": "b", "text": "otacza zarówno pryzmaty szkliwne, jak i substancję międzypryzmatyczną"}, {"id": "c", "text": "otacza wyłącznie pryzmaty szkliwne"}, {"id": "d", "text": "enamelina jest jej składnikiem"}, {"id": "e", "text": "w szkliwie dojrzałym stanowi zaledwie kilka procent masy"}]$OPTS$::jsonb,
   'c',
   $EXPL$Macierz organiczna tworzy **siateczkę** wokół kryształów **hydroksyapatytu** w **całym** szkliwie — obejmuje pryzmaty **i** substancję międzypryzmatyczną, więc twierdzenie o wyłącznie pryzmatach jest fałszywe. Głównymi białkami są **amelogeniny** (szkliwo niedojrzałe, ok. 90% białek) oraz **enameliny**, **ameloblastyna** i **tuftelina**. W czasie dojrzewania białka ulegają degradacji, a substancja organiczna spada do **ok. 1%**.$EXPL$,
   $SUB$Szkliwo — skład$SUB$, 'HISSTO-e2026-1-235'),
(15, 'HIST-22',
   $STEM$Wyniosłości nosowe boczne, leżące bocznie od dołków nosowych, powstają bezpośrednio z:$STEM$,
   $OPTS$[{"id": "a", "text": "plakod usznych"}, {"id": "b", "text": "mezenchymalnych wałów tkankowych otaczających dołek nosowy"}, {"id": "c", "text": "pierwszego łuku gardłowego"}, {"id": "d", "text": "cewy nerwowej"}, {"id": "e", "text": "endodermy jelita przedniego"}]$OPTS$::jsonb,
   'b',
   $EXPL$W **5. tygodniu** ektoderma wyniosłości czołowo-nosowej tworzy **plakody nosowe**, które zapadają się w **dołki nosowe**. Otaczające je **mezenchymalne wały** dzielą się na wyniosłości **przyśrodkowe** (od strony linii pośrodkowej) i **boczne** (od strony bocznej). Boczne dają **skrzydła nosa**, przyśrodkowe — **rynienkę podnosową**, przegrodę i **podniebienie pierwotne**. Plakody uszne dają pęcherzyk błędnikowy, nie nos.$EXPL$,
   $SUB$Rozwój twarzy i nosa$SUB$, 'HISSTO-e2026-1-236'),
(16, 'HIST-09',
   $STEM$Wskaż zdanie prawdziwe dotyczące astrocytów:$STEM$,
   $OPTS$[{"id": "a", "text": "astrocyty włókniste występują w istocie białej i mają długie, słabo rozgałęzione wypustki"}, {"id": "b", "text": "astrocyty włókniste występują w istocie szarej i mają krótkie wypustki"}, {"id": "c", "text": "astrocyty plazmatyczne występują w istocie białej"}, {"id": "d", "text": "astrocyty tworzą osłonkę mielinową w ośrodkowym układzie nerwowym"}, {"id": "e", "text": "astrocyty wywodzą się z monocytów krwi"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Astrocyty włókniste** leżą w **istocie białej**: mają nieliczne, **długie i słabo rozgałęzione** wypustki bogate w **GFAP**. **Astrocyty plazmatyczne** zajmują **istotę szarą** i mają liczne, **krótkie, silnie rozgałęzione** wypustki. Obie formy tworzą **stopki okołonaczyniowe** bariery krew–mózg, buforują **K+**, wychwytują **glutaminian** i tworzą bliznę glejową. Mielinę w OUN wytwarzają **oligodendrocyty**, a z monocytów pochodzi **mikroglej**.$EXPL$,
   $SUB$Glej — astrocyty$SUB$, 'HISSTO-e2026-1-237'),
(17, 'HIST-11',
   $STEM$Końcową część układu bodźcoprzewodzącego serca stanowią:$STEM$,
   $OPTS$[{"id": "a", "text": "węzeł zatokowo-przedsionkowy"}, {"id": "b", "text": "węzeł przedsionkowo-komorowy"}, {"id": "c", "text": "pęczek Hisa"}, {"id": "d", "text": "włókna Purkinjego"}, {"id": "e", "text": "kardiomiocyty robocze przedsionków"}]$OPTS$::jsonb,
   'd',
   $EXPL$**Włókna Purkinjego** to ostatnie ogniwo przed kardiomiocytami roboczymi komór. Leżą **podwsierdziowo**, są szersze od zwykłych kardiomiocytów, mają **skąpe miofibryle** zepchnięte obwodowo i obfity **glikogen**, co daje im jasny obraz w H+E. Liczne **połączenia szczelinowe** zapewniają przewodzenie do **4 m/s** — najszybsze w sercu. Dzięki temu skurcz komór zaczyna się od **koniuszka** i przebiega synchronicznie ku podstawie.$EXPL$,
   $SUB$Układ bodźcoprzewodzący serca$SUB$, 'HISSTO-e2026-1-238'),
(18, 'HIST-13',
   $STEM$Nabłonek pokrywający migdałek podniebienny:$STEM$,
   $OPTS$[{"id": "a", "text": "jest silnie rogowaciejący"}, {"id": "b", "text": "jest gęsto naciekany limfocytami i granulocytami"}, {"id": "c", "text": "zawiera liczne komórki Panetha"}, {"id": "d", "text": "zawiera liczne komórki Kulczyckiego (enteroendokrynne)"}, {"id": "e", "text": "jest nabłonkiem jednowarstwowym walcowatym"}]$OPTS$::jsonb,
   'b',
   $EXPL$Migdałek podniebienny pokrywa **nabłonek wielowarstwowy płaski nierogowaciejący**, wpuklający się w **krypty**. Jest on masowo naciekany **limfocytami** i **granulocytami**, tworząc **nabłonek limfoepitelialny**, w którym granice komórek nabłonkowych stają się nieostre. Ułatwia to próbkowanie antygenów. Komórki **Panetha** i **Kulczyckiego** są elementami nabłonka **jelitowego**, nie migdałka; rogowacenie występuje w dziąśle i podniebieniu twardym.$EXPL$,
   $SUB$Migdałek podniebienny$SUB$, 'HISSTO-e2026-1-239'),
(19, 'HIST-04',
   $STEM$Najbardziej apikalnie w kompleksie połączeń międzykomórkowych nabłonka leżą:$STEM$,
   $OPTS$[{"id": "a", "text": "desmosomy"}, {"id": "b", "text": "hemidesmosomy"}, {"id": "c", "text": "połączenia szczelinowe"}, {"id": "d", "text": "połączenia ścisłe"}, {"id": "e", "text": "prawidłowe A i B"}]$OPTS$::jsonb,
   'd',
   $EXPL$Kolejność od szczytu komórki: **zonula occludens** (połączenie ścisłe) → **zonula adherens** (obwódka przylegania, filamenty **aktynowe**) → **macula adherens** (desmosom, filamenty **pośrednie**). Poniżej rozproszone są **połączenia szczelinowe**, a przy biegunie podstawnym **hemidesmosomy** łączące komórkę z **blaszką podstawną**. Apikalna lokalizacja połączeń ścisłych warunkuje ich rolę w uszczelnianiu i utrzymaniu **polaryzacji** nabłonka.$EXPL$,
   $SUB$Kompleks połączeniowy$SUB$, 'HISSTO-e2026-1-240'),
(20, 'HIST-11',
   $STEM$Włókna sprężyste w błonie środkowej aorty tworzą:$STEM$,
   $OPTS$[{"id": "a", "text": "blaszki kolagenowe"}, {"id": "b", "text": "blaszki sprężyste (okienkowate)"}, {"id": "c", "text": "kanaliki międzykomórkowe"}, {"id": "d", "text": "prążki mięśniowe"}, {"id": "e", "text": "siatkę retikulinową"}]$OPTS$::jsonb,
   'b',
   $EXPL$W aorcie elastyna układa się w **koncentryczne blaszki sprężyste okienkowate** — u człowieka jest ich **40–70**, a między nimi leżą **miocyty gładkie** produkujące elastynę i kolagen. Otwory (okienka) umożliwiają dyfuzję substancji odżywczych. Blaszki rozciągają się w **skurczu** komór i sprężynują w **rozkurczu**, przekształcając przepływ pulsacyjny w ciągły — to **efekt Windkessel**. Ich degradacja sprzyja powstawaniu **tętniaka aorty**.$EXPL$,
   $SUB$Tętnice typu sprężystego$SUB$, 'HISSTO-e2026-1-241'),
(21, 'HIST-21',
   $STEM$Cechą charakterystyczną brodawek nitkowatych języka jest:$STEM$,
   $OPTS$[{"id": "a", "text": "obecność licznych kubków smakowych"}, {"id": "b", "text": "całkowity brak unerwienia"}, {"id": "c", "text": "gruby, silnie rogowaciejący nabłonek"}, {"id": "d", "text": "otoczenie wałem i bruzdą okalającą"}, {"id": "e", "text": "obecność gruczołów surowiczych von Ebnera u podstawy"}]$OPTS$::jsonb,
   'c',
   $EXPL$**Brodawki nitkowate** są najliczniejsze i pokrywają całą powierzchnię grzbietową języka do bruzdy granicznej. Jako jedyne **nie zawierają kubków smakowych** — pełnią funkcję **mechaniczną** (tarcie pokarmu, czucie dotyku) i mają **gruby nabłonek rogowaciejący**, nadający językowi szarawy odcień. Wał i bruzda okalająca cechują brodawki **okolone**, przy których leżą gruczoły **von Ebnera**. Unerwienie czuciowe zachowane (n. V3).$EXPL$,
   $SUB$Brodawki języka$SUB$, 'HISSTO-e2026-1-242'),
(22, 'HIST-20',
   $STEM$W tarczce powieki znajdują się gruczoły:$STEM$,
   $OPTS$[{"id": "a", "text": "Meiboma"}, {"id": "b", "text": "Molla"}, {"id": "c", "text": "Zeissa"}, {"id": "d", "text": "Krausego"}, {"id": "e", "text": "Wolfringa"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Gruczoły tarczkowe (Meiboma)** to duże gruczoły **łojowe** typu holokrynowego, wbudowane w płytkę tarczki i uchodzące na wolnym brzegu powieki. Ich wydzielina tworzy **warstwę lipidową filmu łzowego**, hamując parowanie łez. Zatkanie przewodu daje **gradówkę**. Gruczoły **Zeissa** (łojowe rzęs) i **Molla** (apokrynowe potowe) leżą przy mieszkach rzęs — ich zapalenie to **jęczmień**; **Krausego** i **Wolfringa** to dodatkowe gruczoły łzowe.$EXPL$,
   $SUB$Powieka$SUB$, 'HISSTO-e2026-1-243'),
(23, 'HIST-11',
   $STEM$Rozszerzanie się ściany aorty i dużych tętnic podczas skurczu komór jest możliwe dzięki:$STEM$,
   $OPTS$[{"id": "a", "text": "licznym blaszkom sprężystym w błonie środkowej"}, {"id": "b", "text": "zanikowi błony środkowej"}, {"id": "c", "text": "skurczowi miocytów gładkich błony środkowej"}, {"id": "d", "text": "spadkowi ciśnienia w świetle naczynia"}, {"id": "e", "text": "grubej, kolagenowej przydance"}]$OPTS$::jsonb,
   'a',
   $EXPL$Wzrost ciśnienia w **skurczu** rozciąga **blaszki sprężyste** błony środkowej, magazynując energię; w **rozkurczu** ich sprężysty odrzut utrzymuje ciśnienie i ciągły przepływ obwodowy — **efekt Windkessel (powietrzni)**. Za odkształcalność odpowiada więc **elastyna**, a nie skurcz miocytów, który przeciwnie — zwęża naczynie. **Kolagen** przydanki pełni funkcję ograniczającą, chroniąc ścianę przed nadmiernym rozciągnięciem i pęknięciem.$EXPL$,
   $SUB$Mechanika ściany tętnic$SUB$, 'HISSTO-e2026-1-244'),
(24, 'HIST-21',
   $STEM$Świeżo wydzielone szkliwo pierwotne (niedojrzałe) zawiera około:$STEM$,
   $OPTS$[{"id": "a", "text": "10% substancji nieorganicznej"}, {"id": "b", "text": "30% substancji nieorganicznej"}, {"id": "c", "text": "50% substancji nieorganicznej"}, {"id": "d", "text": "70% substancji nieorganicznej"}, {"id": "e", "text": "96% substancji nieorganicznej"}]$OPTS$::jsonb,
   'b',
   $EXPL$Macierz wydzielana przez ameloblasty jest częściowo zmineralizowana już na starcie — zawiera **ok. 30%** substancji nieorganicznej, resztę stanowią **woda** i białka (głównie **amelogeniny**). Dopiero w fazie **dojrzewania** ameloblasty resorbują wodę i białka, a kryształy **hydroksyapatytu** rosną, aż mineralizacja osiąga **ok. 96%** masy — najwyższą w organizmie. Dlatego szkliwo dojrzałe jest **bezkomórkowe** i niezdolne do regeneracji.$EXPL$,
   $SUB$Mineralizacja szkliwa$SUB$, 'HISSTO-e2026-1-245'),
(25, 'HIST-21',
   $STEM$W trakcie amelogenezy ameloblasty migrują w kierunku:$STEM$,
   $OPTS$[{"id": "a", "text": "zębiny"}, {"id": "b", "text": "nabłonka wewnętrznego narządu szkliwotwórczego"}, {"id": "c", "text": "nabłonka zewnętrznego narządu szkliwotwórczego"}, {"id": "d", "text": "cementu korzeniowego"}, {"id": "e", "text": "miazgi zęba"}]$OPTS$::jsonb,
   'c',
   $EXPL$Ameloblast odkłada macierz **przed sobą** przez **wyrostek Tomesa**, więc oddala się od nowo powstałego szkliwa. Ponieważ start następuje na **granicy szkliwno-zębinowej**, ruch odbywa się **odśrodkowo** — od zębiny ku **nabłonkowi zewnętrznemu narządu szkliwotwórczego**. Odontoblasty wędrują lustrzanie, ku **miazdze**, zostawiając za sobą **wypustki Tomesa** w kanalikach. Rozejście obu populacji wyznacza **połączenie szkliwno-zębinowe**.$EXPL$,
   $SUB$Amelogeneza$SUB$, 'HISSTO-e2026-1-246'),
(26, 'HIST-15',
   $STEM$Wskaż zdanie FAŁSZYWE dotyczące pneumocytów typu I:$STEM$,
   $OPTS$[{"id": "a", "text": "stanowią około 40% komórek nabłonka pęcherzyków płucnych"}, {"id": "b", "text": "są płaskie i mają bardzo cienką cytoplazmę"}, {"id": "c", "text": "umożliwiają dyfuzję gazów przez barierę krew-powietrze"}, {"id": "d", "text": "zawierają ciałka blaszkowate magazynujące surfaktant"}, {"id": "e", "text": "wchodzą w skład ściany pęcherzyków płucnych"}]$OPTS$::jsonb,
   'd',
   $EXPL$**Ciałka blaszkowate** z **surfaktantem** są cechą **pneumocytów typu II** (komórek ziarnistych), które stanowią ok. 60% liczby komórek, lecz pokrywają zaledwie kilka procent powierzchni i pełnią rolę komórek macierzystych nabłonka. **Pneumocyty typu I** to ok. **40%** komórek, ale wyściełają **95%** powierzchni: skrajnie spłaszczone, o cytoplazmie grubości ok. **0,2 µm**, tworzą wraz ze śródbłonkiem i wspólną błoną podstawną **barierę krew-powietrze**.$EXPL$,
   $SUB$Nabłonek pęcherzyków płucnych$SUB$, 'HISSTO-e2026-1-247'),
(27, 'HIST-18',
   $STEM$Wskaż zdanie prawdziwe dotyczące kalcytoniny:$STEM$,
   $OPTS$[{"id": "a", "text": "jest głównym hormonem regulującym gospodarkę wapniową człowieka"}, {"id": "b", "text": "jest ważniejsza niż parathormon"}, {"id": "c", "text": "ma mniejsze znaczenie niż witamina D i parathormon"}, {"id": "d", "text": "jest wytwarzana przez komórki pęcherzykowe tarczycy"}, {"id": "e", "text": "nasila resorpcję kości przez osteoklasty"}]$OPTS$::jsonb,
   'c',
   $EXPL$Kalcytonina z **komórek C** hamuje **osteoklasty** (a nie je pobudza) i obniża kalcemię, ale u człowieka jest hormonem **pomocniczym**. Dowodem jest brak zaburzeń wapniowych zarówno po **tyreoidektomii**, jak i w **raku rdzeniastym tarczycy** z ekstremalnie wysokim jej stężeniem — służy tam wyłącznie jako **marker**. Oś regulacyjną tworzą **PTH** (mobilizacja wapnia z kości i resorpcja nerkowa) oraz **kalcytriol** (wchłanianie jelitowe).$EXPL$,
   $SUB$Gospodarka wapniowo-fosforanowa$SUB$, 'HISSTO-e2026-1-248'),
(28, 'HIST-20',
   $STEM$Zewnętrzna warstwa nabłonka pokrywającego wyrostki rzęskowe:$STEM$,
   $OPTS$[{"id": "a", "text": "jest silnie pigmentowana i stanowi przedłużenie nabłonka barwnikowego siatkówki"}, {"id": "b", "text": "nie ma żadnego związku z wytwarzaniem cieczy wodnistej"}, {"id": "c", "text": "tworzy zatokę żylną twardówki"}, {"id": "d", "text": "przechodzi we włókna nerwowe siatkówki"}, {"id": "e", "text": "jest nabłonkiem wielowarstwowym płaskim rogowaciejącym"}]$OPTS$::jsonb,
   'a',
   $EXPL$Wyrostki rzęskowe pokrywa **dwuwarstwowy nabłonek** — pozostałość **kielicha ocznego**. Warstwa **zewnętrzna (przylegająca do zrębu)** jest silnie **barwnikowa** i kontynuuje **nabłonek barwnikowy siatkówki**; warstwa **wewnętrzna**, zwrócona do komory tylnej, jest **bezbarwnikowa** i odpowiada za czynne wydzielanie **cieczy wodnistej** (pompa Na+/K+, **anhydraza węglanowa** — cel farmakologiczny w jaskrze). Obie warstwy stykają się biegunami szczytowymi.$EXPL$,
   $SUB$Ciało rzęskowe$SUB$, 'HISSTO-e2026-1-249'),
(29, 'HIST-15',
   $STEM$Wskaż zdanie FAŁSZYWE dotyczące makrofagów płucnych:$STEM$,
   $OPTS$[{"id": "a", "text": "pochodzą z komórek prekursorowych szpiku kostnego"}, {"id": "b", "text": "różnicują się z pneumocytów typu II"}, {"id": "c", "text": "występują w przegrodach międzypęcherzykowych"}, {"id": "d", "text": "występują na powierzchni nabłonka oddechowego"}, {"id": "e", "text": "w przewlekłym zastoju żylnym gromadzą hemosyderynę"}]$OPTS$::jsonb,
   'b',
   $EXPL$Makrofagi pęcherzykowe („komórki pyłowe”) wywodzą się z **monocytów** krwi i prekursorów **szpikowych**, należąc do **układu fagocytów jednojądrzastych** — nie powstają z nabłonka. **Pneumocyty II** są komórkami macierzystymi wyłącznie dla **pneumocytów I**. Makrofagi wędrują po powierzchni nabłonka i w **przegrodach międzypęcherzykowych**; w zastoju żylnym pochłaniają erytrocyty i gromadzą **hemosyderynę** — to **komórki wad sercowych**.$EXPL$,
   $SUB$Makrofagi pęcherzykowe$SUB$, 'HISSTO-e2026-1-250'),
(30, 'HIST-21',
   $STEM$Unerwienie zębiny pochodzi z:$STEM$,
   $OPTS$[{"id": "a", "text": "splotu pododontoblastycznego Raschkowa w miazdze"}, {"id": "b", "text": "ozębnej, przez otwór wierzchołkowy do cementu"}, {"id": "c", "text": "naczyń krwionośnych brodawki zębowej"}, {"id": "d", "text": "resztek nabłonkowych Malasseza"}, {"id": "e", "text": "zębina jest tkanką całkowicie nieunerwioną"}]$OPTS$::jsonb,
   'a',
   $EXPL$Włókna czuciowe **nerwu trójdzielnego** wnikają przez otwór wierzchołkowy i tworzą tuż pod warstwą odontoblastów **splot Raschkowa (pododontoblastyczny)**. Odchodzące od niego bezmielinowe zakończenia wnikają do **kanalików zębinowych** wyłącznie w **zębinie przymiazgowej** (wewnętrzna 1/3). Ból ze stref głębszych tłumaczy **teoria hydrodynamiczna Brannstroma** — ruch płynu w kanalikach drażni te zakończenia (nadwrażliwość szyjek).$EXPL$,
   $SUB$Unerwienie zębiny i miazgi$SUB$, 'HISSTO-e2026-1-251'),
(31, 'HIST-21',
   $STEM$Powierzchnia nosowa podniebienia miękkiego pokryta jest nabłonkiem:$STEM$,
   $OPTS$[{"id": "a", "text": "jednowarstwowym płaskim"}, {"id": "b", "text": "wielowarstwowym sześciennym"}, {"id": "c", "text": "wielorzędowym walcowatym migawkowym"}, {"id": "d", "text": "wielowarstwowym płaskim rogowaciejącym"}, {"id": "e", "text": "przejściowym"}]$OPTS$::jsonb,
   'c',
   $EXPL$Podniebienie miękkie ma **dwie różne powierzchnie**. Od strony jamy ustnej pokrywa je **nabłonek wielowarstwowy płaski nierogowaciejący**, odporny na urazy mechaniczne żucia. Powierzchnia **nosowa** należy do dróg oddechowych, więc wyściela ją **nabłonek oddechowy** — wielorzędowy walcowaty **migawkowy z komórkami kubkowymi**, oczyszczający powietrze dzięki transportowi śluzowo-rzęskowemu. W okolicy brzegu wolnego następuje strefa przejściowa.$EXPL$,
   $SUB$Podniebienie miękkie$SUB$, 'HISSTO-e2026-1-252'),
(32, 'HIST-05',
   $STEM$Głównymi komórkami tkanki łącznej włóknistej są:$STEM$,
   $OPTS$[{"id": "a", "text": "fibroblasty"}, {"id": "b", "text": "makrofagi"}, {"id": "c", "text": "mastocyty"}, {"id": "d", "text": "plazmocyty"}, {"id": "e", "text": "adipocyty"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Fibroblast** to komórka **stała** i dominująca ilościowo — syntetyzuje **kolagen**, **elastynę**, **glikozaminoglikany** i **glikoproteiny**, czyli całą macierz zewnątrzkomórkową. Ma wrzecionowaty kształt, jasne jądro z wyraźnym jąderkiem i obfitą **szorstką siateczkę śródplazmatyczną**. Forma spoczynkowa to **fibrocyt**. Makrofagi, mastocyty i plazmocyty należą do komórek **napływowych** (obrona), a adipocyty dominują dopiero w tkance **tłuszczowej**.$EXPL$,
   $SUB$Komórki tkanki łącznej$SUB$, 'HISSTO-e2026-1-253'),
(33, 'HIST-20',
   $STEM$Kosteczki słuchowe i okostna jamy bębenkowej pokryte są nabłonkiem:$STEM$,
   $OPTS$[{"id": "a", "text": "jednowarstwowym płaskim"}, {"id": "b", "text": "wielowarstwowym sześciennym"}, {"id": "c", "text": "wielorzędowym walcowatym urzęsionym"}, {"id": "d", "text": "wielowarstwowym płaskim rogowaciejącym"}, {"id": "e", "text": "przejściowym"}]$OPTS$::jsonb,
   'a',
   $EXPL$Jamę bębenkową wyściela błona śluzowa z **nabłonkiem jednowarstwowym płaskim** — cienka warstwa minimalizuje masę i **bezwładność** układu przewodzącego drgania, co jest kluczowe dla ruchomości kosteczek. W okolicy ujścia **trąbki słuchowej** nabłonek przechodzi stopniowo w **wielorzędowy walcowaty migawkowy** (kontynuacja nabłonka nosogardła), umożliwiający oczyszczanie i wentylację ucha środkowego.$EXPL$,
   $SUB$Jama bębenkowa$SUB$, 'HISSTO-e2026-1-254'),
(34, 'HIST-21',
   $STEM$Zrąb podniebienia miękkiego zbudowany jest głównie z:$STEM$,
   $OPTS$[{"id": "a", "text": "tkanki tłuszczowej"}, {"id": "b", "text": "tkanki mięśniowej poprzecznie prążkowanej"}, {"id": "c", "text": "chrząstki szklistej"}, {"id": "d", "text": "chrząstki sprężystej"}, {"id": "e", "text": "kości gąbczastej"}]$OPTS$::jsonb,
   'b',
   $EXPL$W przeciwieństwie do podniebienia twardego, opartego na **kości**, podniebienie miękkie jest ruchomym fałdem zbudowanym z **mięśni poprzecznie prążkowanych** (dźwigacz i napinacz podniebienia miękkiego, podniebienno-gardłowy, podniebienno-językowy, języczka) osadzonych na **rozcięgnie podniebiennym**. Umożliwia to **zamykanie cieśni gardłowo-nosowej** przy połykaniu i mowie. Niewydolność tego mechanizmu daje **nosowanie otwarte**.$EXPL$,
   $SUB$Podniebienie miękkie$SUB$, 'HISSTO-e2026-1-255'),
(35, 'HIST-02',
   $STEM$Cząsteczki cholesterolu w dwuwarstwie lipidowej błony komórkowej ułożone są:$STEM$,
   $OPTS$[{"id": "a", "text": "równolegle do cząsteczek fosfolipidów, prostopadle do powierzchni błony"}, {"id": "b", "text": "prostopadle do łańcuchów kwasów tłuszczowych fosfolipidów"}, {"id": "c", "text": "wyłącznie po zewnętrznej stronie błony, w obrębie glikokaliksu"}, {"id": "d", "text": "jako osobna, trzecia warstwa pod dwuwarstwą lipidową"}, {"id": "e", "text": "swobodnie w cytozolu, bez kontaktu z błoną"}]$OPTS$::jsonb,
   'a',
   $EXPL$Cholesterol jest **amfipatyczny**: grupa **-OH** kontaktuje się z polarnymi główkami fosfolipidów, a sztywny układ **pierścieni sterolowych** z łańcuchem węglowodorowym wsuwa się między **kwasy tłuszczowe** — czyli **równolegle** do cząsteczek fosfolipidów i **prostopadle** do płaszczyzny błony. Działa jak **bufor płynności**: w temperaturze ciała usztywnia błonę, a w niskiej zapobiega krystalizacji. Jest też składnikiem **tratw lipidowych**.$EXPL$,
   $SUB$Błona komórkowa$SUB$, 'HISSTO-e2026-1-256'),
(36, 'HIST-09',
   $STEM$Podstawowym substratem energetycznym neuronów mózgu jest:$STEM$,
   $OPTS$[{"id": "a", "text": "sfingozyna"}, {"id": "b", "text": "glukoza"}, {"id": "c", "text": "glikolipidy"}, {"id": "d", "text": "fosfolipidy"}, {"id": "e", "text": "glicerol"}]$OPTS$::jsonb,
   'b',
   $EXPL$Neurony pokrywają zapotrzebowanie energetyczne niemal wyłącznie z **glukozy**, transportowanej przez **GLUT3** (wysokie powinowactwo) niezależnie od **insuliny**. Mózg zużywa ok. **20%** tlenu i glukozy organizmu, mimo że stanowi 2% masy, a rezerwy **glikogenu** ma tylko w astrocytach — stąd błyskawiczna utrata przytomności w **hipoglikemii**. Dopiero po kilku dniach głodzenia paliwem zapasowym stają się **ciała ketonowe**. Kwasy tłuszczowe nie przechodzą efektywnie bariery krew-mózg.$EXPL$,
   $SUB$Metabolizm neuronu$SUB$, 'HISSTO-e2026-1-257'),
(37, 'HIST-21',
   $STEM$Wskaż zdanie FAŁSZYWE dotyczące fosforyn zębinowych:$STEM$,
   $OPTS$[{"id": "a", "text": "wiążą jony wapnia"}, {"id": "b", "text": "wpływają na strukturę kryształów hydroksyapatytu"}, {"id": "c", "text": "należą do niekolagenowych białek zębiny"}, {"id": "d", "text": "wchodzą w skład cząsteczki kolagenu"}, {"id": "e", "text": "ich niedobór prowadzi do wad rozwojowych tkanek zęba"}]$OPTS$::jsonb,
   'd',
   $EXPL$**Fosforyna zębinowa (DPP)** to najobficiej występujące **niekolagenowe** białko zębiny, powstające z prekursora **DSPP**. Jest silnie **kwaśna** (mnóstwo reszt asparaginianowych i **fosfoseryny**), dzięki czemu wiąże **Ca2+** i przyłącza się do włókien kolagenowych, sterując **nukleacją** i wzrostem kryształów **hydroksyapatytu**. Nie jest jednak elementem cząsteczki kolagenu — działa obok niej. Mutacje **DSPP** dają **dentinogenesis imperfecta**.$EXPL$,
   $SUB$Białka niekolagenowe zębiny$SUB$, 'HISSTO-e2026-1-258'),
(38, 'HIST-21',
   $STEM$Ścisłe połączenie zęba z dziąsłem nosi nazwę:$STEM$,
   $OPTS$[{"id": "a", "text": "przyczepu nabłonkowego (nabłonek łączący)"}, {"id": "b", "text": "rowka dziąsłowego"}, {"id": "c", "text": "więzadła okrężnego"}, {"id": "d", "text": "przyczepu cementowego"}, {"id": "e", "text": "blaszki zbitej zębodołu"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Nabłonek łączący** przylega do szkliwa za pomocą **hemidesmosomów** i wewnętrznej **blaszki podstawnej**, tworząc **przyczep nabłonkowy** — biologiczne uszczelnienie oddzielające tkanki przyzębia od jamy ustnej. Jest niezrogowaciały, wysoce przepuszczalny (droga migracji **granulocytów** i płynu dziąsłowego) i szybko się odnawia. **Rowek dziąsłowy** to szczelina nad nim (fizjologicznie do **0,5-2 mm**); jego pogłębienie tworzy **kieszonkę** w periodontitis.$EXPL$,
   $SUB$Przyzębie - dziąsło$SUB$, 'HISSTO-e2026-1-259'),
(39, 'HIST-04',
   $STEM$Blaszka siateczkowata (lamina reticularis) błony podstawnej zawiera przede wszystkim:$STEM$,
   $OPTS$[{"id": "a", "text": "agrekan"}, {"id": "b", "text": "fibronektynę i kolagen typu III"}, {"id": "c", "text": "elastynę"}, {"id": "d", "text": "prawidłowe A i C"}, {"id": "e", "text": "prawidłowe A, B i C"}]$OPTS$::jsonb,
   'b',
   $EXPL$**Lamina reticularis** to najgłębsza warstwa błony podstawnej, wytwarzana przez **fibroblasty** tkanki łącznej (nie przez nabłonek). Budują ją **włókna siateczkowe** z **kolagenu typu III** oraz **fibronektyna**, spajające blaszkę podstawną z podłożem; kotwiczą je fibryle **kolagenu VII**. Powyżej leży **lamina densa** z **kolagenem IV**, **lamininą**, **entaktyną** i **perlekanem**. **Agrekan** jest typowy dla chrząstki, a elastyny w błonie podstawnej brak.$EXPL$,
   $SUB$Błona podstawna$SUB$, 'HISSTO-e2026-1-260'),
(40, 'HIST-05',
   $STEM$Największym i najobficiej występującym glikozaminoglikanem w organizmie człowieka jest:$STEM$,
   $OPTS$[{"id": "a", "text": "siarczan chondroityny"}, {"id": "b", "text": "siarczan heparanu"}, {"id": "c", "text": "hialuronian (kwas hialuronowy)"}, {"id": "d", "text": "siarczan dermatanu"}, {"id": "e", "text": "siarczan keratanu"}]$OPTS$::jsonb,
   'c',
   $EXPL$**Hialuronian** to jedyny GAG **niesiarczanowany**, niezwiązany kowalencyjnie z białkiem rdzeniowym i syntetyzowany nie w aparacie Golgiego, lecz przez **syntazy w błonie komórkowej**. Osiąga masę **milionów daltonów** i długość kilku mikrometrów. Silnie wiąże wodę, tworząc uwodniony żel odporny na ucisk; stanowi rusztowanie dla agregatów **agrekanu** w chrząstce. Obficie występuje w mazi stawowej, ciele szklistym i skórze właściwej.$EXPL$,
   $SUB$Glikozaminoglikany$SUB$, 'HISSTO-e2026-1-261'),
(41, 'HIST-13',
   $STEM$Podstawową funkcją limfocytów cytotoksycznych (Tc, CD8+) jest:$STEM$,
   $OPTS$[{"id": "a", "text": "niszczenie komórek zakażonych wirusami i komórek nowotworowych"}, {"id": "b", "text": "wytwarzanie przeciwciał"}, {"id": "c", "text": "prezentacja antygenu limfocytom pomocniczym"}, {"id": "d", "text": "fagocytoza bakterii zewnątrzkomórkowych"}, {"id": "e", "text": "wydzielanie histaminy i heparyny"}]$OPTS$::jsonb,
   'a',
   $EXPL$Limfocyty **Tc (CD8+)** rozpoznają antygen prezentowany w **MHC klasy I**, obecnym na **wszystkich** komórkach jądrzastych — dlatego wykrywają zakażenie wirusowe i transformację nowotworową. Zabijają dwiema drogami: uwalniając **perforyny** (tworzą pory) i **granzymy** uruchamiające **kaspazy**, oraz przez **FasL**. Obie ścieżki kończą się **apoptozą**. Przeciwciała produkują **plazmocyty**, a pomoc immunologiczną świadczą limfocyty **Th (CD4+)**.$EXPL$,
   $SUB$Limfocyty T$SUB$, 'HISSTO-e2026-1-262'),
(42, 'HIST-21',
   $STEM$Głównym składnikiem szkieletu (zrębu) podniebienia miękkiego jest:$STEM$,
   $OPTS$[{"id": "a", "text": "rozcięgno podniebienne - tkanka łączna włóknista zbita"}, {"id": "b", "text": "chrząstka szklista"}, {"id": "c", "text": "chrząstka sprężysta"}, {"id": "d", "text": "kość gąbczasta"}, {"id": "e", "text": "tkanka tłuszczowa"}]$OPTS$::jsonb,
   'a',
   $EXPL$Podstawę podniebienia miękkiego stanowi **rozcięgno podniebienne** — płytka **tkanki łącznej włóknistej zbitej** o utkaniu regularnym, będąca ścięgnem **mięśnia napinacza podniebienia miękkiego**, przyczepiona do tylnego brzegu podniebienia twardego. Do niej przyczepiają się pozostałe mięśnie podniebienia. Chrząstka i kość tu nie występują — dzięki temu podniebienie miękkie jest **ruchome** i może odgradzać część nosową gardła.$EXPL$,
   $SUB$Podniebienie miękkie$SUB$, 'HISSTO-e2026-1-263'),
(43, 'HIST-22',
   $STEM$Błędna fuzja wyniosłości nosowych przyśrodkowych prowadzi do:$STEM$,
   $OPTS$[{"id": "a", "text": "atrezji przełyku"}, {"id": "b", "text": "rozszczepu podniebienia wtórnego"}, {"id": "c", "text": "rozszczepu wargi"}, {"id": "d", "text": "braku języka"}, {"id": "e", "text": "przetoki tchawiczo-przełykowej"}]$OPTS$::jsonb,
   'c',
   $EXPL$Wyniosłości nosowe **przyśrodkowe** zlewają się ze sobą i z wyniosłościami **szczękowymi**, tworząc **segment międzyszczękowy**: rynienkę podnosową, przedszczękę z czterema siekaczami i **podniebienie pierwotne**. Zaburzenie tej fuzji daje **rozszczep wargi**, często z rozszczepem wyrostka zębodołowego. Rozszczep podniebienia **wtórnego** wynika z niezrośnięcia **płytek podniebiennych** wyniosłości szczękowych - to odrębny mechanizm i inny okres krytyczny.$EXPL$,
   $SUB$Wady rozwojowe twarzy$SUB$, 'HISSTO-e2026-1-264'),
(44, 'HIST-14',
   $STEM$Koncepcja gronka wątrobowego przedstawia:$STEM$,
   $OPTS$[{"id": "a", "text": "różnice w metabolizmie i zaopatrzeniu hepatocytów w tlen"}, {"id": "b", "text": "drogę odpływu żółci do przewodu żółciowego wspólnego"}, {"id": "c", "text": "unerwienie autonomiczne wątroby"}, {"id": "d", "text": "przebieg naczyń chłonnych wątroby"}, {"id": "e", "text": "rozmieszczenie komórek Browicza-Kupffera"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Gronko (acinus) Rappaporta** to romb między dwiema żyłami centralnymi, którego osią jest **triada wrotna**. Dzieli miąższ na **strefy 1-3** wg odległości od dopływu krwi. **Strefa 1** (okołowrotna) jest najlepiej utlenowana - dominuje tu **glukoneogeneza**, **beta-oksydacja** i synteza mocznika, i tu pierwsze uszkadza **wirusowe zapalenie**. **Strefa 3** (okołocentralna), uboga w tlen, prowadzi **glikolizę** i detoksykację (**cytochrom P450**) - jest najwrażliwsza na **niedokrwienie** i toksyny.$EXPL$,
   $SUB$Wątroba - jednostki czynnościowe$SUB$, 'HISSTO-e2026-1-265'),
(45, 'HIST-21',
   $STEM$W kierunku jakiej struktury przemieszczają się ameloblasty podczas wydzielania szkliwa?$STEM$,
   $OPTS$[{"id": "a", "text": "brodawki zębowej"}, {"id": "b", "text": "zębiny"}, {"id": "c", "text": "nabłonka zewnętrznego narządu szkliwotwórczego"}, {"id": "d", "text": "nabłonka wewnętrznego narządu szkliwotwórczego"}, {"id": "e", "text": "cementu korzeniowego"}]$OPTS$::jsonb,
   'c',
   $EXPL$Wydzielanie zaczyna się na **granicy szkliwno-zębinowej**, więc każda kolejna warstwa macierzy odsuwa ameloblast **na zewnątrz** - w stronę **nabłonka zewnętrznego narządu szkliwotwórczego**. Ślad tego ruchu widać jako **pryzmaty szkliwne** o przebiegu prostopadłym do powierzchni zębiny oraz **linie przyrostowe Retziusa**. Po zakończeniu amelogenezy ameloblasty tworzą **nabłonek zredukowany szkliwa**, z którego powstaje pierwotny **przyczep nabłonkowy**.$EXPL$,
   $SUB$Amelogeneza$SUB$, 'HISSTO-e2026-1-266'),
(46, 'HIST-05',
   $STEM$W tkance łącznej zbitej o utkaniu regularnym włókna kolagenowe są ułożone:$STEM$,
   $OPTS$[{"id": "a", "text": "losowo"}, {"id": "b", "text": "promieniście"}, {"id": "c", "text": "równolegle"}, {"id": "d", "text": "spiralnie"}, {"id": "e", "text": "w luźną siateczkę"}]$OPTS$::jsonb,
   'c',
   $EXPL$W utkaniu **regularnym** grube pęczki **kolagenu typu I** biegną **równolegle**, zgodnie z kierunkiem działania siły - daje to ogromną wytrzymałość na rozciąganie w **jednej osi**. Między pęczkami leżą spłaszczone **fibrocyty (komórki ścięgnowe)** w charakterystycznych szeregach. Tak zbudowane są **ścięgna**, **więzadła** i **rozcięgna**. Utkanie **nieregularne** (skóra właściwa, torebki narządów) ma pęczki splecione wielokierunkowo - odporność na siły z każdej strony.$EXPL$,
   $SUB$Tkanka łączna zbita$SUB$, 'HISSTO-e2026-1-267'),
(47, 'HIST-21',
   $STEM$Wypustki odontoblastów biegnące w kanalikach zębinowych to:$STEM$,
   $OPTS$[{"id": "a", "text": "włókna Tomesa"}, {"id": "b", "text": "włókna Korffa"}, {"id": "c", "text": "włókna Sharpeya"}, {"id": "d", "text": "włókna siateczkowe"}, {"id": "e", "text": "włókna von Ebnera"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Wypustki (włókna) Tomesa** to przedłużenia cytoplazmy odontoblastów wypełniające **kanaliki zębinowe** na całej grubości zębiny. Ciała komórek pozostają na obwodzie **miazgi**, dlatego zębina jest tkanką **żywą**, zdolną do odkładania zębiny **wtórnej** i **reparacyjnej**. Ruch płynu wokół wypustek odpowiada za ból wg teorii **hydrodynamicznej**. Włókna **Korffa** to kolagen zębiny płaszczowej, a **Sharpeya** - włókna kotwiczące ozębną w cemencie i kości.$EXPL$,
   $SUB$Zębina - odontoblasty$SUB$, 'HISSTO-e2026-1-268'),
(48, 'HIST-05',
   $STEM$Najliczniejszymi komórkami tkanki łącznej właściwej są:$STEM$,
   $OPTS$[{"id": "a", "text": "fibroblasty"}, {"id": "b", "text": "adipocyty"}, {"id": "c", "text": "makrofagi"}, {"id": "d", "text": "mastocyty"}, {"id": "e", "text": "plazmocyty"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Fibroblasty** to komórki **osiadłe**, wywodzące się z **mezenchymy**, stanowiące większość populacji komórkowej. Produkują wszystkie elementy macierzy: **kolagen**, **elastynę**, **glikozaminoglikany**, **proteoglikany** i **glikoproteiny adhezyjne**, a przez wydzielanie **kolagenaz** także ją przebudowują - kluczowe w **gojeniu ran**. Pozostałe wymienione komórki (makrofagi, mastocyty, plazmocyty) są **napływowe** i pojawiają się liczniej dopiero w stanie zapalnym.$EXPL$,
   $SUB$Komórki tkanki łącznej właściwej$SUB$, 'HISSTO-e2026-1-269'),
(49, 'HIST-08',
   $STEM$Białkiem niekolagenowym odpowiadającym za mineralizację kości jest:$STEM$,
   $OPTS$[{"id": "a", "text": "osteokalcyna"}, {"id": "b", "text": "elastyna"}, {"id": "c", "text": "fibronektyna"}, {"id": "d", "text": "prawidłowe A i B"}, {"id": "e", "text": "prawidłowe A, B i C"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Osteokalcyna (BGP)** jest najobficiej występującym niekolagenowym białkiem kości, wydzielanym przez **osteoblasty**. Zawiera reszty **kwasu gamma-karboksyglutaminowego** powstające przy udziale **witaminy K**, które wiążą **Ca2+** i **hydroksyapatyt**, regulując mineralizację. Jej stężenie w surowicy służy jako **marker obrotu kostnego**. **Elastyna** w kości nie występuje, a **fibronektyna** to białko adhezyjne bez roli mineralizacyjnej.$EXPL$,
   $SUB$Macierz kostna$SUB$, 'HISSTO-e2026-1-270'),
(50, 'HIST-13',
   $STEM$Główną funkcją krypt migdałkowych jest:$STEM$,
   $OPTS$[{"id": "a", "text": "produkcja limfocytów T"}, {"id": "b", "text": "synteza RANKL"}, {"id": "c", "text": "magazynowanie limfy"}, {"id": "d", "text": "zwiększenie powierzchni kontaktu antygenów z tkanką limfoidalną"}, {"id": "e", "text": "produkcja śluzu"}]$OPTS$::jsonb,
   'd',
   $EXPL$**Krypty** to głębokie wpuklenia nabłonka (w migdałku podniebiennym ok. **10-20**), które wielokrotnie zwiększają powierzchnię czynną narządu. Zatrzymany w nich materiał antygenowy z pokarmu i powietrza przenika przez **nabłonek limfoepitelialny** do **grudek chłonnych**, inicjując odpowiedź swoistą i produkcję **IgA**. Migdałki są narządami **obwodowymi** - limfocyty T dojrzewają w **grasicy**. Zaleganie złuszczonego nabłonka w kryptach daje **czopy migdałkowe**.$EXPL$,
   $SUB$Migdałki$SUB$, 'HISSTO-e2026-1-271'),
(51, 'HIST-12',
   $STEM$Wskaż zdanie prawdziwe dotyczące bazofilów:$STEM$,
   $OPTS$[{"id": "a", "text": "zawierają ziarnistości z histaminą i heparyną"}, {"id": "b", "text": "nie mają ziarnistości"}, {"id": "c", "text": "są najliczniejszymi granulocytami krwi"}, {"id": "d", "text": "nie uczestniczą w reakcjach nadwrażliwości typu I"}, {"id": "e", "text": "stanowią około 20% krążących leukocytów"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Bazofile** to najrzadsze leukocyty - poniżej **1%** wszystkich krwinek białych (najliczniejsze są **neutrofile**, 60-70%). Ich duże, ciemnofioletowe ziarnistości **metachromatyczne** przesłaniają dwupłatowe jądro i zawierają **histaminę**, **heparynę** oraz czynniki chemotaktyczne. Na powierzchni mają receptory **FcepsilonRI** dla **IgE**: związanie alergenu wyzwala degranulację, czyli reakcję **nadwrażliwości typu I**. Ich odpowiednikiem tkankowym są **mastocyty**.$EXPL$,
   $SUB$Granulocyty zasadochłonne$SUB$, 'HISSTO-e2026-1-272'),
(52, 'HIST-14',
   $STEM$Wskaż zdanie prawdziwe o inhibitorze trypsyny obecnym w ziarnistościach komórek zewnątrzwydzielniczych trzustki:$STEM$,
   $OPTS$[{"id": "a", "text": "zapobiega przedwczesnej aktywacji trypsyny wewnątrz trzustki"}, {"id": "b", "text": "jest aktywowany przez enterokinazę dwunastnicy"}, {"id": "c", "text": "aktywuje chymotrypsynogen"}, {"id": "d", "text": "odpowiada za wydzielanie jonów HCO3- przez komórki przewodzików"}, {"id": "e", "text": "rozkłada trypsynę w świetle dwunastnicy"}]$OPTS$::jsonb,
   'a',
   $EXPL$Enzymy trzustkowe są magazynowane w **ziarnistościach zymogenowych** jako nieczynne **proenzymy**. Razem z nimi pakowany jest **inhibitor trypsyny (PSTI/SPINK1)**, który natychmiast blokuje śladowe ilości samoistnie powstałej **trypsyny** - to zabezpieczenie przed **autotrawieniem** narządu. Fizjologiczna aktywacja zachodzi dopiero w dwunastnicy: **enterokinaza** tnie trypsynogen, a powstała trypsyna aktywuje pozostałe zymogeny. Załamanie tej ochrony to mechanizm **ostrego zapalenia trzustki**.$EXPL$,
   $SUB$Trzustka zewnątrzwydzielnicza$SUB$, 'HISSTO-e2026-1-273'),
(53, 'HIST-18',
   $STEM$Hormonem przysadki wpływającym na wydzielanie hormonów tarczycy jest:$STEM$,
   $OPTS$[{"id": "a", "text": "TSH (tyreotropina)"}, {"id": "b", "text": "FSH (folikulotropina)"}, {"id": "c", "text": "ACTH (kortykotropina)"}, {"id": "d", "text": "LH (lutropina)"}, {"id": "e", "text": "GH (somatotropina)"}]$OPTS$::jsonb,
   'a',
   $EXPL$**TSH** powstaje w **tyreotropach** części gruczołowej przysadki (komórki **zasadochłonne**), pod kontrolą podwzgórzowej **TRH**. Pobudza komórki pęcherzykowe do wychwytu jodu, syntezy **tyreoglobuliny** i endocytozy koloidu, zwiększając uwalnianie **T3/T4**; te zwrotnie hamują przysadkę - klasyczne **ujemne sprzężenie zwrotne osi HPT**. Przewlekła stymulacja TSH powoduje **przerost pęcherzyków** i wole. **FSH** i **LH** działają na gonady, **ACTH** na korę nadnerczy.$EXPL$,
   $SUB$Przysadka - część gruczołowa$SUB$, 'HISSTO-e2026-1-274'),
(54, 'HIST-14',
   $STEM$Koncepcja gronka wątrobowego (acinus) opisuje:$STEM$,
   $OPTS$[{"id": "a", "text": "strefy miąższu różniące się zaopatrzeniem w tlen i profilem metabolicznym"}, {"id": "b", "text": "klasyczny zrazik sześciokątny z żyłą centralną w osi"}, {"id": "c", "text": "budowę dróg żółciowych zewnątrzwątrobowych"}, {"id": "d", "text": "rozmieszczenie komórek Ito magazynujących witaminę A"}, {"id": "e", "text": "przebieg naczyń chłonnych przestrzeni Dissego"}]$OPTS$::jsonb,
   'a',
   $EXPL$**Gronko Rappaporta** ujmuje miąższ od strony **ukrwienia**, a nie odpływu żółci: osią jest **triada wrotna**, a wierzchołkami dwie **żyły centralne**. Wyróżnia **strefy 1-3** o malejącej prężności tlenu i odmiennym profilu enzymatycznym. Model tłumaczy typowe wzorce uszkodzeń: martwicę **okołocentralną (strefa 3)** w niedokrwieniu i zatruciu **paracetamolem** oraz zmiany **okołowrotne (strefa 1)** w wirusowym zapaleniu. Zrazik klasyczny opisuje natomiast odpływ krwi do żyły centralnej.$EXPL$,
   $SUB$Wątroba - strefy czynnościowe$SUB$, 'HISSTO-e2026-1-275'),
(55, 'HIST-02',
   $STEM$Glikolipidy błony komórkowej komórek zwierzęcych zbudowane są z:$STEM$,
   $OPTS$[{"id": "a", "text": "ceramidu (sfingozyna + kwas tłuszczowy) połączonego z resztami cukrowymi"}, {"id": "b", "text": "glicerolu, dwóch kwasów tłuszczowych i reszty fosforanowej"}, {"id": "c", "text": "czterech pierścieni sterolowych z grupą hydroksylową"}, {"id": "d", "text": "łańcucha polipeptydowego z przyłączonym kwasem tłuszczowym"}, {"id": "e", "text": "wyłącznie reszt cukrowych połączonych wiązaniami glikozydowymi"}]$OPTS$::jsonb,
   'a',
   $EXPL$Glikolipidy zwierzęce to **glikosfingolipidy**: część hydrofobową stanowi **ceramid** (**sfingozyna** + kwas tłuszczowy), a hydrofilową - łańcuch cukrowy. Przy jednej reszcie cukru powstaje **cerebrozyd**, przy oligosacharydzie z **kwasem sialowym** - **gangliozyd**. Występują wyłącznie w **zewnętrznej** warstwie błony, współtworząc **glikokaliks**, oznaczenia grup krwi i receptory. Glicerol z resztą fosforanową to **fosfolipid**, a pierścienie sterolowe - **cholesterol**.$EXPL$,
   $SUB$Lipidy błonowe$SUB$, 'HISSTO-e2026-1-276'),
(56, 'HIST-21',
   $STEM$Brodawki nitkowate języka charakteryzują się:$STEM$,
   $OPTS$[{"id": "a", "text": "silnym zrogowaceniem nabłonka"}, {"id": "b", "text": "obecnością licznych kubków smakowych"}, {"id": "c", "text": "czerwonym zabarwieniem wynikającym z prześwitywania naczyń"}, {"id": "d", "text": "obecnością wału i bruzdy okalającej"}, {"id": "e", "text": "obecnością gruczołów surowiczych u podstawy"}]$OPTS$::jsonb,
   'a',
   $EXPL$Brodawki nitkowate mają stożkowaty kształt i **gruby nabłonek rogowaciejący**, skierowany szczytami ku tyłowi - działają jak szczotka ułatwiająca przesuwanie pokarmu i odbiór bodźców **dotykowych**. Brak w nich **kubków smakowych**. Ich białoszara barwa kontrastuje z **czerwonymi** brodawkami **grzybowatymi**, w których prześwitują naczynia. Nadmierne rogowacenie i przerost dają obraz **języka włochatego**; zanik - **wygładzenie języka** w niedokrwistościach.$EXPL$,
   $SUB$Brodawki języka$SUB$, 'HISSTO-e2026-1-277'),
(57, 'HIST-21',
   $STEM$Brodawki grzybowate języka:$STEM$,
   $OPTS$[{"id": "a", "text": "leżą pojedynczo na grzbiecie i brzegach języka, głównie na koniuszku, i zawierają kubki smakowe"}, {"id": "b", "text": "są całkowicie pozbawione kubków smakowych"}, {"id": "c", "text": "są otoczone wałem i głęboką bruzdą okalającą"}, {"id": "d", "text": "są pokryte grubym, silnie zrogowaciałym nabłonkiem"}, {"id": "e", "text": "są najliczniejszymi brodawkami języka"}]$OPTS$::jsonb,
   'a',
   $EXPL$Brodawki grzybowate mają kształt **grzybka** o wąskiej podstawie i szerokim szczycie; leżą **pojedynczo** wśród brodawek nitkowatych, najgęściej na **koniuszku** i brzegach języka. Cienki, **nierogowaciejący** nabłonek i obfite unaczynienie blaszki właściwej nadają im **czerwoną** barwę widoczną gołym okiem. Na powierzchni górnej mają nieliczne **kubki smakowe**. Wał i bruzda okalająca cechują brodawki **okolone** (7-12 sztuk przed bruzdą graniczną).$EXPL$,
   $SUB$Brodawki języka$SUB$, 'HISSTO-e2026-1-278'),
(58, 'HIST-21',
   $STEM$Bladoróżowe zabarwienie dziąsła przyczepionego wynika z:$STEM$,
   $OPTS$[{"id": "a", "text": "rogowacenia nabłonka i zbitej blaszki właściwej bez powierzchownych splotów naczyniowych"}, {"id": "b", "text": "obecności licznych melanocytów"}, {"id": "c", "text": "gęstej sieci naczyń włosowatych tuż pod nabłonkiem"}, {"id": "d", "text": "braku blaszki właściwej"}, {"id": "e", "text": "obecności obfitej tłuszczowej tkanki podśluzowej"}]$OPTS$::jsonb,
   'a',
   $EXPL$Dziąsło przyczepione należy do błony śluzowej **żującej**: pokrywa je **nabłonek wielowarstwowy płaski rogowaciejący** lub parakeratotyczny, a blaszka właściwa jest **zbita**, bogata w kolagen i zrośnięta z okostną wyrostka zębodołowego (**mucoperiosteum**) - bez warstwy podśluzowej i bez powierzchownych splotów naczyniowych. Zrogowaciała warstwa rozprasza światło, dając barwę bladoróżową. Sąsiednia **śluzówka wyścielająca** jest cienka, nierogowaciejąca i wyraźnie **czerwona**.$EXPL$,
   $SUB$Błona śluzowa dziąsła$SUB$, 'HISSTO-e2026-1-279')
),
maxes AS (
  SELECT topic_id,
         COALESCE(MAX((regexp_match(id, topic_id || '-([0-9]+)$'))[1]::int), 0) AS mx
    FROM public.questions WHERE topic_id IN ('HIST-02', 'HIST-04', 'HIST-05', 'HIST-08', 'HIST-09', 'HIST-11', 'HIST-12', 'HIST-13', 'HIST-14', 'HIST-15', 'HIST-18', 'HIST-19', 'HIST-20', 'HIST-21', 'HIST-22') GROUP BY topic_id
)
INSERT INTO public.questions
  (id, topic_id, text, options, correct_option_id, explanation,
   subtheme_label, source_code, batch_label, source_exam, theme_label, tracks)
SELECT
  n.topic_id || '-' || LPAD((COALESCE(m.mx,0) + ROW_NUMBER() OVER (PARTITION BY n.topic_id ORDER BY n.seq))::text, 3, '0'),
  n.topic_id, n.qtext, n.opts, n.correct, n.expl,
  n.subtheme, n.srccode, 'e_hist_stoma_2026/5', 'Egzamin histologia STOMA SUM 2026 (HISSTO e2026-1)',
  '2026', ARRAY['stomatologia']::TEXT[]
FROM new_rows n LEFT JOIN maxes m ON m.topic_id = n.topic_id;

UPDATE public.topics t SET question_count = sub.cnt
  FROM (
    SELECT topic_id, COUNT(*)::int AS cnt
      FROM public.questions
     WHERE topic_id IN ('HIST-02', 'HIST-04', 'HIST-05', 'HIST-08', 'HIST-09', 'HIST-11', 'HIST-12', 'HIST-13', 'HIST-14', 'HIST-15', 'HIST-18', 'HIST-19', 'HIST-20', 'HIST-21', 'HIST-22')
       AND COALESCE(is_active, true) = true
     GROUP BY topic_id
  ) sub
 WHERE t.id = sub.topic_id;

UPDATE public.topics
   SET question_count = 0
 WHERE id = 'histologia-THEME-2026';
